<?php session_start(); ?>
<!DOCTYPE html>

<head>
    <?php include '../header.php'; ?>
    <link rel="stylesheet" type="text/css" href="../../style.css">
    <title>
        Bits and Pieces
    </title>
</head>

<body>
    <h1 id="top">Bits and Pieces</h1>
    <ul>
        <li><a href="#1">Shadimon and Hunger</a></li>
    </ul>
    <hr/>
    <h2>Shadimon and Hunger</h2>
    <p>Shadimon finds Hunger in the relative quiet near the tables of food. “I’m not sure what I was expecting, but I don’t think this is it,” he says to the fire elf. “Do you have a moment? I need advice again, and I’d rather have it out in person.” </p>
    <p>The Hunger leans back against a nearby table. “Certainly. I take it my advice helped?” </p>
    <p>“I hope it does, because the political situation has caught a downdraft these past couple seasons. Now I’m at the point of preventing riots <i>before</i> I can even start any real form of government.” He sighs, adjusting the infant he’s still carrying, “So the advice I need is on how to handle multiple conflicting political factions, none of whom are technically <i>wrong</i>, without the entire thing exploding.” </p>
    <p>"Aha." Hunger coughs. "<i>Politics.</i> I wasn't expecting you to have to worry about that before your government actually forms, but I suppose that isn't terribly surprising, given the fun we've all been having of late." He glances over at Lucinia, still hiding behind Fury. "Be forewarned, my advice on this isn't and cannot be perfect -- not only is there no certain way to handle competing groups with equivalent fairness and impartiality, but we haven't been perfectly successful either.</p>
    <p>"What I can tell you is that the strongest method I know of for handling competing interests is this: set them against each other." He gestures to Barry, who is currently lounging by a snack table, munching on River Elf canapes. "Leafstorm and his Phoenix Imperialis is something of a success story there. By allowing both they and their competitors, the Ashen, the space to argue over the course of the nation while we in the Triumvirate instead work to enact policy, we both gave them the chance to grow into a more stable and useful organization, and allowed their better ideas the chance to grow to fruition. And also ignored their stupider ones.</p>
    <p>"The opposite of this would be the Ashen." Hunger sighs. "On the one hand, they are now stable, and provide a beneficial service. On the other, they were pretty much being run by the Wolf Elves up until last season." </p>
    <p>Shadimon has been listening intently with the particular look of someone taking detailed mental notes, but all his feathers slick down at that last statement. “That bad? How did that happen?” </p>
    <p>“The ultimate problem with centralized leadership -- a single point of failure. In this case… I’m afraid our friend ‘Faustus’ cornered Tsun in the ruins outside of Surt three years ago, and managed to con her into accepting a geas effect ‘in the name of helping Surt’. Which, given that she was able to report this to us, is probably still better than just flat out killing her would have been -- but not by a lot, and I may be a biased source on that. Terror and I are planning on having a full discussion on it with senior leadership here, somewhat later, in as secure an area as possible. In summary, however… one of the two groups we have dedicated to maintaining our internal security had been compromised for three years, as a direct result of the political interests of its leadership being manipulated by foreign interests. And I’m even more convinced that this ‘Faustus’ is our late, great, and overweight Muspelhami governor.” </p>
    <p>Shadimon’s stare goes distant for a moment as he runs through the organizations in Asavardi. “Mother’s breath, they’ve been going after you. We...anticipated that they might turn to us, if they haven’t already, once they get wind that we’re having trouble. We’ve been working on countermeasures, which I’ll also bring up in that secure meeting.” He shakes out his tense shoulders, “Right...let me...give you a bit more detail about <i>our</i> situation, and you tell me if letting them go at each other seems wise.”</p>
    <p>He drums his fingers on the blanket for a moment, and ends up with one finger caught in a tiny fist. “So...we have a very loud faction that fully supports an organized government. But they’ve also used phrases like ‘drag people along kicking and screaming’ and ‘for their own good’. That largely consists of recent immigrants who’ve been hiding out in human lands, and have gotten a bit more...abrasive than average.</p>
    <p>“The other major group wants no organization at all. You may not know our history really, but we’ve never had anything more than small, scattered villages, most of which didn’t even have their own central leader, let alone any kind of broader organization. The main system of organized government we’ve seen is...the Empire. To these people, any kind of central organization or power is inherently corrupting, and they’re already calling <i>me</i> a tyrant for what little we’ve done-” </p>
    <p>A strained chuckling sound echoes from behind Hunger’s mask. It takes Shadimon a second to realize that Hunger is trying not to laugh. </p>
    <p>“Thanks,” Shadimon says dryly. “But what part of this specifically are you laughing at?” </p>
    <p>Hunger covers his mouth, shaking. “My apologies,” he gasps. “I’m just… they called you a <i>tyrant?</i> ...I’m so proud.” </p>
    <p>Shadimon throws up his free hand, “Yes they did, while lobbing a rotten tomato at me, in the middle of a speech, if you must know.” </p>
    <p>The Hunger laughs. “<i>And</i> a rotten tomato! Oh, this is <i>excellent!</i> You must really be getting their attention!” </p>
    <p>Shadimon opens his mouth, but an odd gurgling noise interrupts him. He glances down, and the baby is also giggling, waving his chubby fists. “Really? You too? And after you’ve been all of <i>no</i> help to me.” He sighs, “I’m glad at least that you don’t seem to think this is as much of a disaster as it felt to me.” His ears go down as his wings tuck against his back, “I’m not...used to being publically disliked. And yelled at.” </p>
    <p>“Just wait until they accuse you of being a werewolf,” Hunger says flatly. “...I’m smiling, in case the mask doesn’t make that clear. And I’m not mocking you for your reaction. No one enjoys public disapproval, myself usually included. The public can be as needy, whiny, and unaware of itself as a baby -- no offense meant, tiny elf-child -- and their tendency to act out can result in some very painful consequences. But the point is they’re acting out. You have their <i>attention</i> -- which is far, far better than the alternative. In most cases, the anarchists of any society that had previously not had much of a government to speak of will ignore anyone trying to set up a real government. But they’re not ignoring you. They’re angry at you, trying to influence you, and maybe even a little scared of you. And that’s <i>good.</i></p>
    <p>“The person who throws tomatoes at you is one of the people you want to talk to, because they’re a solid indicator that at least some part of their group is energized. They’ve got opinions they want to express; values they want registered. Even to the point of risking public disapproval and violence themselves. And that means congrats to them, because now <i>they’re part of it.</i> </p>
    <p>“So based on your description, there are a couple of different methods available to you. You’ve got two groups with opposite goals, neither of which is particularly trustworthy -- one keeps using language that screams ‘murder the opposition’, while the other employs fruit-violence in situations they don’t like.</p>
    <p>“They both have to live in the same society, however, and that means they have to put up with each other whether they like it or not. </p>
    <p>“One of your options -- which is honestly the one I generally prefer -- is ‘assumed impartiality’. Inform both sides that you want their opinion, but they’ll have to meet in the middle, or neither side will be happy with the result. Your anarchists don’t like the idea of a real government? Let them know there’s an entire other chunk of society that wants to, and that the best thing for both of them would be to come to an agreement. If you’re okay with playing the villain, tell them they need to form a coalition or you’ll ignore both of them; that way they’ll have to try to play moderate with each other in order to ‘keep you in check’. If not, find the members of them you like that are most agreeable, and start talking to them -- first separately, and then together. Make them try to find common ground. They’ll never agree with each other one hundred percent, but that’s on them, and that’s where the competition will come in. The point is to make it clear that you’ll only listen if they’re talking, rather than tomato-ing.” </p>
    <p>“I do at least have an in with...they’re calling themselves Cynics. After one of the anarchists chucked the tomato, someone <i>else</i> whipped around and decked them in the face. That one was willing to be...apprehended? And we talked. I’ve been trying to talk to people, but it’s...a <i>lot</i> more people than I expected. I <i>do</i> want to hear from them. I can’t do anything until I know what they want beyond ‘our way or nothing’. How do you even arrange something like that? I was absolutely mobbed any time I went out in public this entire last season.” </p>
    <p>The Hunger pauses. “This is where delegation, and having the Terror around, is particularly useful, but in your case… probably one of the best methods would be to aim for blunt bureaucracy. They don’t want a government? Well, tough, you can’t talk to everyone at once and expect to get anything done. Tell them they need to choose some representatives -- elves they think best argue for and support their interests -- so you can invite those elves to a close-quarters meeting, to really hash it out. Get a scribe to take notes of the whole thing, and then slap those notes somewhere public so that the Cynics know their reps are accountable for what they say. And if those reps missed something? Tell them to try to go to the other reps first -- you’re busy.” </p>
    <p>Shadimon looks thoughtful, “That...is a good idea. Ridiculously, the <i>Anarchists</i> are more organized, of the two groups. They might already have actual leadership. I’m lacking in armored enforcers, but blunt intimidation wouldn’t help the ‘tyrant’ impression anyway.” He sighs, “Thank you. I don’t know yet if it’ll work, but it’s much more than I had originally. I also have some ideas to undercut both groups and try to boost a more moderate middle ground, but I need information that I just don’t have. But truly, thank you.” </p>
    <p>The fire elf nods. “Happy to help. It sounds like you’re getting along pretty well, at the very least. They’re paying attention to you.” He pauses. “And watch the leadership of both sides. Especially with the Wolf Elves around.” </p>
    <p>Shadimon smiles a little, “You’ll like our countermeasures, I think.”</p>
    <p class="center"><a href="#top">-FIN-</a></p>
    <hr/>



    <?php
    include "../footer.php";
    include '../../settarget.php';
    settarget("Blade",null,null,11);
    echo getarrows("../../Events/06_0.php#jump","10_Open Athlon I.php");
    #setlast("Bonus/4_Bits and Pieces.php");
    ?>
</body>