<?php session_start(); ?>
<!DOCTYPE html>

<head>
    <?php include '../header.php'; ?>
    <link rel="stylesheet" type="text/css" href="../../style.css">
    <title>
        Open Athlon I
    </title>
</head>

<body>
    <h1>Open Athlon I</h1>
    <p>The Athlon!  By longstanding tradition, held every twenty years, it is an event where all Crag, regardless of origin, bloodline, or specialty, may come together to demonstrate their prowess through numerous competitions and trials.  The only Crag who may not participate are the Named, those Crag whose actions and accomplishments have marked them as the physical embodiment of one of the great virtues of their people.  This is because the Athlon is meant to demonstrate the capabilities of the common Crag;  It is a celebration, not of individual achievement, but rather a demonstration to all of how far the Crag have progressed along their Path, an inspirational event to remind all who observe of what the Crag can hope to achieve in the quest for Perfection.  Although, of course, those who excel at the trials cannot but help to gain the attention of those who observe them....</p>
    <p>Taking place across several days, the Trials of the Athlon are broken up into three general categories;</p>
    <ul>
        <li><i>The Athlon of Body</i>, which concerns itself with feats of strength, agility, endurance, and other qualities of the Physical form.  Judgement of these is fairly simple, based on highest numbers, fastest(or longest) times, or on who is left standing when all is said and done.</li>
        <li><i>The Athlon of Mind</i>, which concerns itself with matters of learnedness, philosophy, deftness, honed skill, and other qualities of a learned intellect.  Judgement of these may be obvious in some cases, but in many others requires adjudication by elected panels of Named, typically chosen from the Bakshish and the Onagi.</li>
        <li><i>The Athlon of Spirit</i>, the most esoteric and unpredictable of the three, which concerns itself with displays of creativity, innovation, expression, and other qualities of an enlightened soul.  Judgement of these almost always requires adjudication, given their sometimes nebulous qualities, performed by elected panels of Named, typically chosen from the Elpahka and the Aggro.</li>
    </ul>
    <p id="top">Being the first Athlon to occur since the Extermination, this event was already guaranteed to be one of some uncertainty… however, further confusing matters is that now, the trials have been opened to Elves of all description.  What this could mean for this ancient celebration, none can say…</p>
    <ul>
        <li>
            <a href="#Body">Athlon of Body</a>
            <ul>
                <li><a href="#Athletics">Athletics</a></li>
                <li><a href="#Acrobatics">Acrobatics</a></li>
                <li><a href="#Fortitude">Fortitude</a></li>
                <li><a href="#Perception">Perception</a></li>
                <li><a href="#Pankration">Pankration</a></li>
                <li><a href="#Top Bird">Top Bird</a></li>
            </ul>
        </li>
        <li>
            <a href="#Mind">Athlon of Mind</a>
            <ul>
                <li><a href="#Adroitness">Adroitness</a></li>
                <li><a href="#Artifice">Artifice</a></li>
                <li><a href="#Knowledge">Knowledge</a></li>
                <li><a href="#Fieldcraft">Fieldcraft</a></li>
                <li><a href="#Markselfship">Markselfship</a></li>
            </ul>
        </li>
        <li>
            <a href="#Spirit">Athlon of Spirit</a>
            <ul>
                <li><a href="#Deception">Deception</a></li>
                <li><a href="#Artistry">Artistry</a></li>
                <li><a href="#Performance">Performance</a></li>
                <li><a href="#Insight">Insight</a></li>
                <li><a href="#Intimidation">Intimidation</a></li>
            </ul>
        </li>
        <li><a href="#End">Athlon's End</a></li>
    </ul>
    <hr/>
    <h2 id="Body">Athlon of Body</h2>
    <h3 id="Athletics">Athletics</h3>
    <p>Outside of the decorative walls of Eparchy’s Dejima district, an area has been cordoned off for those Crag wishing to demonstrate various feats of Strength.  In one corner, a bulging Crag hefts a bar weighted with rounded stones above her head, impressing various onlookers, while in another a stout Crag makes a running start, before leaping as far as he can.  What many are eager to see today, however, is the 10 league race; set on a wide track that encircles the entirety of Eparchy, there are few trials which better demonstrate a mastery of one’s physical form. </p>
    <p>Envoyer’s residents take to the Athletics events with great enthusiasm.  Their unassumingly pudgy appearances even give them a slight edge in competitions of strength, as they are consistently underestimated.</p>
    <p>Off to one side, a fierce but diminutive competition is taking place. Trischal and Shrike have found a small table, and are squaring off. Their solemn handshake quickly turns into arm-wrestling. Time and time again, the smaller dark elf pins Shrike’s arm down, until Shrike is laughing too hard to even put up a fight (Trischal: str 21; Shrike: str 10). </p>
    <p>The wolf elves make a determined showing. Every single one of Vesnia's band competes. With their status as conditioned soldiers and their natural swiftness, they make a strong showing. Vesnia herself is the standout. She makes a solid launch off the line and makes an extremely good showing, keeping a steady pace that is extremely rapid thanks to a wolf elf's speed. </p>
    <p>Noticing the Wolf Elf lineup intent on taking the field, the Terror marches onto the race track, fully armored and ready to demonstrate that the elves of Surt will not sit back and give any victories over without a fight. Rocketing from the start barely microseconds after the “go” signal, Terror dashes down the track like a bronzed, burning locomotive (a ruminant mammal related to deer, common to the northern stretches of the continent; the name comes from Draconic for “moves” and “crazy”). </p>
    <p>But refusing to be outdone by an armored gasbag, Vesnia charges onto the field, taking the lead back from Terror in an aggressive half-league run that still leaves her with plenty of oomph left for the finish.</p>
    <p>Some enterprising idjits among the river elves dump Dhakamari’s name into the lists for the endurance race.  Seeing as they’re missing out on the Flood Run this year, they get the idea that they should get to see their best hero participate in an endurance race on foot.  It would certainly be an exciting change of course!</p>
    <p>Dhakamari tries, he really does, but foot races are just not his thing. He has to give up on that pretty quickly and just takes to the air. He at least stays fairly low to the ground and follows the track. Which, actually, is a hell of a lot harder. Welp.</p>
    <p>Dhak’s exhausting low-angle flap gives him the lead for almost two leagues, but the punishing maneuvers required to maintain pace drag at him. As the third lap approaches, he hears a lupine howl. Vesnia pulls past him on his left.</p>
    <p>Scant seconds later, he’s hit by a rush of air that nearly tosses him to the dirt. He scrambles in midair, orienting himself to take the drift, and spots the source -- Terror, running like a juggernaut, still on Vesnia’s tail.</p>
    <p>The leagues close. Despite Dhak’s best efforts, he finds himself lapped. He pulls himself forward, wing stretching, reaching his second to last lap right as Vesnia, then Terror, reach their last. He’s still ahead of the rest of the competition, and the distance is only growing, but Dhak knows it’ll be an effort to even make that final league.</p>
    <p>Vesnia hits her final three-quarters of a league, Terror still behind her. Her final half. Her final third.</p>
    <p>There is a terrible mechanical sound behind her. </p>
    <p>The Terror surges forward, driving past her and towards the finish line on a jet of ash and rage, a blur of speed at a pace twice what Terror had been pulling before. Vesnia tries to copy her, muscles aching, pushing for a final sprint. </p>
    <p>It's not enough.</p>
    <p>The Terror barrels through the finish line less than a minute in front of Vesnia. The armored elf stops just past it, wheezing to herself, ash cloud fading out behind her. She turns to watch as Vesnia finishes her final stretch and takes a few coughing steps off the side of the track. Seemingly coming to a decision, the Terror walks straight over to the coughing Wolf Elf, and extends her hand. The panting wolf elf stares at her for a long moment, but accepts the handshake. </p>
    <p>The Crag reaction to the footrace is largely appreciative: among the crowd, there are even Bakshish who comment on Terror’s ability to manipulate the arcanic matrix without even breaking stride.  While there are some grumbles from other competitors in the race, they seem to be in a minority.</p>
    <p>The outcome is clear: Terror, having also made significant gains in other feats of strength, is the overall victor in the event.  Vesnia’s performance is also recognized, and, with some astonished surprise, so is Trischal: Though not a significant placer in the footrace, the sheer number of other feats of strengths successfully completed or excelled is more than enough to place her in a solid third.</p>
    <p><b>Winners:</b> Terror, Vesnia, Trischal</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Acrobatics">Acrobatics</h3>
    <p>One of the few events to take place inside a structure, this repurposed warehouse has been filled with all manner of unusual equipment, meant to facilitate a demonstration of gymnastic capability.  In the center, two Crag struggle to climb a nearly-sheer surface, finding thin grabs and handholds where they can, while in one corner a placid Crag walks daintily along a thin rope, and in another, a narrow-framed Crag twists and twirls upon a suspended bar, contorting himself into an unusual shape as he propels himself to the next bar in line.  </p>
    <p>River elves most likely should not be competing in Acrobatics challenges.  They do anyway.  But someone has to come in last place, and at least they’re having fun.</p>
    <p>Shrike has claimed herself a decently sized piece of floor, and is working through the complex and acrobatic forms of <a href="https://www.youtube.com/watch?v=UN0bAa_ko4I">winged elf martial art</a>. Knowledgeable observers will note the distinct blade elf influence in her movements, but blade elves don’t tend to do flips on a whim.</p>
    <p>No one has ever seen what a cryptid elf is physically capable of before. When Skulk enters the acrobatics contest, they learn. Skulk is able to move in ways that other elves literally can’t. She moves with a level of grace and speed that is both unearthly and disturbing. (Shrike pauses to watch appreciatively.)</p>
    <p>Shyrendora takes a minor interest in the suspended line of rope.  Getting up there is fine.  Her balance starts out fine.  She shoots herself in the foot by trying to do a flip and seemingly aggravates some kind of injury.  She settles for some wobbly walking after that and then goes back to watching Skulk the others. </p>
    <p>At the end of the Event, the adjudicators are forced to compare notes;  Several of them expressed concern that what they witnessed from the cryptid competitor may have actually been some form of illusion, but after great deliberation, they are forced to concede they can find no evidence of foul play.  Between this display, and that from the other Lowlander competitors, many of the Crag competing dropped out entirely just so they could better gawp at the goings-on.  Because of this, few are left to challenge the outcomes.</p>
    <p><b>Winners:</b> Skulk, Shrike, Shyrendora</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Fortitude">Fortitude</h3>
    <p>While many of the events have been set up one day, and taken down the next, in one corner of the Plaza, a somewhat unnerving set of trials has been going on since the Athlon began.  Crag, with fiercely determined expressions, have plunged appendages, limbs, and even heads into cauldrons of boiling water, or into stone barrels filled with freshly harvested mountain ice.  Numerous Crag stand on duty for this Trial, prepared to offer soothing balms, ointments, or even magical healing at the conclusion of these short lived tests, but the reason for the prolonged presence of this event lies in one of the corners of the Plaza.  There, a small handful of Crag stand attentive.  They have been doing so for two and a half days so far. </p>
    <p>A miscellaneous river elf manages to win a breath-holding contest against other elves who were having their heads held underwater.  Said river elf then proceeds to be absolutely trounced at all of the other trials.</p>
    <p>Breaker wanders into the event with a mostly empty bottle of tequila in hand. It’s unclear whether or not she knows this is actually a formal competition. She wanders from station to station, taking an inadvisable amount of punishment from various tests set up by the crag, including most impressively plunging both her arms completely in a vat of boiling water without so much as a flinch.</p>
    <p>While her pain threshold serves her well, her attentiveness does not. The crag seem to favor steadfastness and resolve in most tests, and Breaker seems to lose interest easily and does not stick out some of the tests as long as might be possible for her. She also just kind of laughs at the idea of standing at attention for days.</p>
    <p>The dark elves seem to have conflicting interests relating to this event.  Trischal thinks it would be hilarious and fun to have Shy enter.  Shy really does not want to enter.  In the end, Trischal corners her and “convinces” her to enter the event.  Shyrendora plays it cool for the most part, at least getting to the part where she puts her arm in the boiling water while her friend watches like a hawk.  The second Trischal is distracted by a needy Fuzzy, however, Shyrendora rips her arm from the water and poofs as fast as she physically can.  Apparently the thought of being stared at for what was meant to be days was not high on her list of things that she considers to be fun.  Trischal grumbles about “spoil sports” for a while after that.</p>
    <p>Ultimately, the showing for this Event is predominantly among the Crag;  While few refute Breaker’s performance as impressive, her refusal to participate in all aspects, along with the general disinterest with which she approaches those she engages with, causes her performance to be evaluated below where it could be had she shown it the regard it deserved.  It is for this reason alone that she only places in Third Tier; even without the standing trial, her performances in other endeavors could have easily earned her second.   To that end, Second and First tier are awarded to two Crag of considerable endurance; Gabbro, who performed greatest in various tests of pain, takes Second, while First goes to Slater, who was able to remain awake for the entirety of the Athlon.</p>
    <p><b>Winners:</b> Slater, Gabbro, Breaker</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Perception">Perception</h3>
    <p>Every day, as the first light of morning alights upon Eparchy, a short event is held; over night, hundreds of small beads, made of everything from brilliant topaz’s to little more than pebbles of chert, have been secreted about the gardens and decorations of the Dejima district, many of them requiring the keenest of eyes to spot.  While there are many Crag that undertake this trial with the same solemn intensity as other events, it is also clear that many approach it as an entertaining diversion. </p>
    <p>Dust wanders through the gardens, cheerfully looking for shiny (or not shiny) beads. (Perception 40)</p>
    <p>After a little while, Baijani joins him, burdened with the twins. She’s on grandmother duty while the actual parents are elsewhere showing off. A walk through a lovely garden looking for shiny things seems their speed. (Perception: 22)</p>
    <p>Ehra seems to enjoy admiring the architecture of the Dejima district. He spends quite a bit of time simply wandering the district and contemplating the mind that may have conceived its subtle order and hidden grandeur. While doing so, he finds a good deal of baubles. (Perception 34).</p>
    <p>The adjudication for this event is simple and painless; more stones is more points.  By the end of the Athlon, Dust’s affinity for bits and bobs has resulted in a small pile of them being tallied to his name, gaining first tier while Ehra has only a slightly smaller pile, gaining second.  As for Baijani, her slightly more sedate rate of stone-spotting had put her neck and neck with a number of other Crag, most of whom seemed to be of similar age; evidently, this was a popular Event for those who wished to show the abilities of the body, without overmuch strain.  In the end, the deciding bauble was not technically found by Baijani, but by a curious little one who almost managed to get it into their mouth; however, Baijani’s instincts granted her a slobber-free stone, and also the third tier.</p>
    <p><b>Winners: Dust, Ehra, Baijani</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Pankration">Pankration</h3>
    <p>Held within the central Pagoda, a simple circle is drawn in chalk; into this line, two crag at a time enter, and then pummel the everliving crag out of each other until one submits, or until there is only one still standing.  Thankfully, in most cases, the rounds end by either submission or by ringout; only a handful of matches have required a total K.O.  For those that have, however, the majority of them have been delivered so far by a single Crag of considerable breadth.  So far, she has made a habit of merely lifting less massive opponents and tossing them out of the ring; in other matches, she has caught more recalcitrant opponents in an implacable sleeper hold, maintaining it no matter how many blows her opponent delivers.  Now, there are few who remain who are willing to challenge her. </p>
    <p>The miscellaneous river elves make an excellent showing in the Pankration event.  On account of their longstanding tradition of wrasslin’, they finally found an event at which they are not at a severe disadvantage.  Their higher than average strength does them well in these matters.  Their rather average constitutions do not hinder them.  </p>
    <p>The Rivers win about as many bouts as they lose, but it seems even they cannot best the current champion… until one River Elf of some noticeable brawn steps into the ring. As the two square off, the match endures for a long time, with the River elf regularly breaking the Crag’s attempted locks and holds.  Finally, the Crag manages to slip behind, taking advantage of the River’s slower speed, and seizes a powerful sleeper clench that the River cannot dislodge.  Indeed, rather than trying to, the River elf does something unexpected… and hoists the Crag up onto his back with a powerful lunge.  His opponent’s footing lost, he dashes to the left, and collapses onto his side in a graceless flop… which just so happens to leave him inside the ring, and his opponent outside of it.  The Crag crowd are <i>impressed.</i> </p>
    <p>When a Wolf Elf enters the Pankration ring, the previously victorious River Elf does not even permit their exchange to last past the first contact.  He immediately lifts his enemy off his feet and slams his face into the ground with an efficiency that suggests having practiced quite a lot for the challenge of facing enemies with skin that deflects mere steel.  It is clear that were this a slightly more humid environment, the wolf elf would summarily be drowned.  As it is, he is merely temporarily asphyxiated. </p>
    <p>Trischal seems far too excited as she enters the whole of her 5’4” self into this competition.  It is mildly humorous and then a little disconcerting as she proves herself to be a decent opponent.</p>
    <p>If not for her performance within the event of Athletics, many Crag would have underestimated Trischal as an opponent.  However, although they approach her with the due respect that should be given an opponent, few can match her strength… and low center of gravity.  Nigh unmovable, several opponents are practically tripped out of the ring, and several others hurled bodily.  </p>
    <p>By event’s end, it is clear who the ultimate victor is… however, even though the event comes to an end, the sparring continues well past it, as Crag of many shapes and sizes eagerly come to grips with the smaller, but densely muscled River elves.  The often evenly matched nature of the event seems a pleasant exception to the events which have been swept by those of unmatchable skill. Still, accolades are given as they are earned; Trischal claims the first Tier, while the River elf known as Torrenticola claims second.  In third is the prior favored Crag, Marble, who takes her outplacement in stride.</p>
    <p><b>Winners:</b> Trischal, Torrenticola, Marble</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Top Bird">Top Bird</h3>
    <p>Thanks to popular demand by the Fury, the Crag assemble a “Flying Race” competition, to allow flight-capable attendees an opportunity to compete with each other in speed, agility, and maneuverability. The competition consists of a series of hoops, set into the ground at various heights above an open field, and spanning a length of around two leagues. Participants are given a time limit and asked to lap the entire course three times, passing through as many of the hoops as possible, with the winner being determined by how many hoops are successfully passed through, how much time is left over, and judgement calls from a small number of experts as to the “grace and efficiency” of the participant’s maneuvers. </p>
    <p>While the official name of this particular competition is “Aeronautics”, some participants and observers have taken to referring to it as the “Flying Competition”, or “Top Bird.”</p>
    <p>As with all other competitions, a random civilian of Envoyer is attempting to compete in this event by running the course and leaping through any of the hoops that are close enough to the ground.</p>
    <p>Next out of the gates is Vita Grassforest, aka ‘the Smoke’, running on a standard fly spell. Clocking at a whopping three geesepower, Vita’s speed advantage over the majority of local flyers is lessened substantially the short several-minute timer attached to standard magical flight. Despite her great speed, Vita only manages to score 12 hoops before being forced to complete her laps and land in the Designated Landing Zone. Any slower, or that landing any worse, and she would have been disqualified; as it stands, she exits the field with fanfair and a concussion. </p>
    <p>Shadimon takes his turn at the start, scanning the ranks of hoops. Unlike Vita, he takes himself up high, circles around, and plummets down toward the course. His years of practice with the narrow, twisting canyons around Asavardi stand him in good stead, as he weaves through the hoops. He was doing very well until he decided to be fancy and one of his wings clips a hoop, rattling it but not knocking it down. He’s laughing and shaking his head as he lands, “Showboating, of course.”</p>
    <p>Steve takes off on shadowy wings, taking his time before flying off course after a bird. He is disqualified, but seems cheerful about his failure.</p>
    <p>The whole crowd turns at once to take a gander as Fury darts forward at a glorious three-point-oh goosepower, zooming like a maniac through not one, not two, but ten hoops in a matter of scant seconds. Seconds which turn out to be just enough time for the judges to notice that she's setting fire to every hoop she passes through!</p>
    <p>The judges at the sidelines immediately cry fowl, ordering Fury disqualified for 'destruction of competition equipment'. Fury, hearing the whistle and the sudden shift in the crowd, turns back for a hasty landing at the edge of the yard. Unfortunately for her, “turning” and “landing” aren’t always things that go well together; the sudden shift in circular motion takes her to the ground with a hard plop, and she is forced to spend the next several seconds burning her ankle back together. She tromphs off soon afterward, in slightly dampened spirits but still eager to cheer for the next contestant. </p>
    <p>Dhakamari, the last official contender, stares at the flaming hoops, shrugs, and launches himself into the air. Like Shadimon, he takes a moment to gain height before plunging down. He whips through the burning hoops, trailing cinders as he goes. He completes his loops without missing a single one, though the final one has nearly burned through and collapsed as he clears it. He quietly lands and checks his feathers for soot marks. </p>
    <p>And the crowd. Goes. Wi-- honestly pretty sedate, but very appreciative. Clapping and solemn chanting abound as Dhakamari is marched to the podium, and presented with the sacred symbol of Top Bird -- the “high five”, an ancient and traditional gesture of power and altitude. He is also presented with a mighty cragoose feather, as a token of Dhak’s might and profound ‘birdliness’. </p>
    <p><b>Winner:</b> Dhakamari</p>
    <p><a href="#Top">Return to Top</a></p>
    <h2 id="Mind">Athlon of Mind</h2>
    <h3 id="Adroitness">Adroitness</h3>
    <p>At first glance, this Event might be mistaken for one of the Athlon of Spirit; dozens of Crag demonstrate remarkable displays of legerdemain, prestidigitation, and general sleight of hand.  From disappearing tiles to appearing fowl to brazen displays of jugglery, one could easily imagine such displays at any faire… if not for the deathly serious expression on the parts of the sweating performers, who are performing to their utmost capability. </p>
    <p>Crassus the Fire Elf, hunched-over and determined, demonstrates surprisingly adroit stagecraft when he somehow manages to cause the feathers of several contestants’ fowls to spontaneously reappear in a burning cloud raining over the audience’s heads. At least one fowl was never recovered. At least one audience member points out that he really just switched out the birds and tore a feather pillow open, but the effect was still impressive. (Sleight of Hand: 17)</p>
    <p>There are some fumbling attempts by River Elves to compete at the Adroitness challenge.  All are terrible embarrassments.  Fortunately, they are good sports and have a lot of fun cheering on the much better acts.  Webbed hands just aren’t great for being incredibly delicate, but make a great clapping sound.  Nobody bothers to point out that it’s not a hindrance when they’re eating with chopsticks.</p>
    <p>Fuzzy demonstrates one of his best tricks learned.  He lays on an item and it disappears!  The large badger then proceeds to not move and rumbles at anyone brave enough to get close to him.  Those beady eyes dare them to try.</p>
    <p>Throughout the competition, competitors seem to be plagued with small bouts of misfortune. Nothing serious. A few misplaced tiles here and there, a coin that stubbornly refuses to reappear, some missing jugglers items, even a few missing bits of pocket detritus. Every now and then someone gets a feeling like there's a hole in their pocket or feels a strange brush of air, but no one ever proves there's a perpetrator. Near the close of the event it becomes abundantly clear that there is. On a central table one morning, every single item that went missing is found neatly stacked in a pile topped with a sign that reads "SKULK WAS HERE." (sleight of hand 22)</p>
    <p>Of note, nothing ever goes missing from Fuzzy's care… or his general vicinity. </p>
    <p>While the feats of dexterity and skill on display are varied indeed, Skulk’s ultimate display becomes one of particular interest… and not precisely pleasant interest.  Having located the source of their ails, the Adjudicators are forced to admit that Skulk’s display is one of impressive adroitness… but the poor sport it demonstrated in actively harming the performances of other contestants is cause for concern.  As such, her standing is severely penalized.</p>
    <p>Because of this, it is the unusual fire elf Crassus who carries victory in this event; while the Crag have seen many varied displays of sleight of hand, the introduction of fire into the mix is an altogether intriguing one, impressing many of the Bakshish adjudicators.  Following him is a Crag of considerable legerdemain and craftiness by the name of Gustaf… in particular, he managed to keep his tiles from being pilfered, allowing him to perform unabated.  Lastly, it is Skulk who begrudgingly falls into the third tier… while some would have placed her lower, other adjudicators were concerned with what backlash might befall them if they did. That was probably wise.</p>
    <p><b>Winners:</b> Crassus, Gustaf, Skulk</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Artifice">Artifice</h3>
    <p>Curiously sedate compared to the other events, the conceit of this event is quite simple; adjudicated by Named Onagi, participants are tasked with creating a particular item- a tool, a piece of masonry, some unit of furniture- and then appraised on how quickly, and how accurately, they provide said item.  However, one part of this event is somewhat eye-catching;  Crag of significant training who attempt to utilize their will to contort simple blocks of stone into ever more complex shapes.  While many of the results are blocky and indistinct, others are of surprising detail. </p>
    <p>Miscellaneous River Elves aren’t able to complete the willed stone, but they do manage to assemble several chairs, build a deck for one of the guest houses, and provide a collection of well-crafted shingles.</p>
    <p>One of them does make an attempt at the willed stone crafting.  He sits in front of the block for a day and a half, just staring right at it.  At the end of that competition he swears that there is now a divot in the spot he was staring at.  There is not.</p>
    <p>In the end, while there are some expected results, there is a surprising upset in this event;  Performing with highest marks in all fields, a Crag by the name of Gneiss is granted the First Tier, as expected.  However, while not capable of utilizing will, the quick and efficient construction and craftselfship of the River Elf competitors raises a number of eyebrows.  Indeed, while their particular methods are not as cut, dry, and rote as most Crag, they nonetheless manage to construct their pieces with surprising speed and without the anticipated errors that such speed would typically be expected to result in.</p>
    <p>In the end, both Second and Third tiers are awarded to two particularly prolific River Elves, known as Anaxyrus and Sechellophryne respectively.  Their cumulative addition of an entirely new lodging to Eparchy, themed in River elf style, was considered more than sufficient evidence of the River’s skill in the field of Artifice.</p>
    <p><b>Winners:</b> Gneiss, Anaxyrus, Sechellophryne</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Knowledge">Knowledge</h3>
    <p>Not all events are intended to be of equal size or duration, and nowhere is that more obvious than in the event of Knowledge.  Attracting scholars of every study and field, of every shape and size, the event has gone on for days, with trials of trivia encompassing any and every conceivable subject.  Delivered by wizened Bakshish Named, these questions intensify in esotericism and specificity until only one competitor remains… and, curiously, in a large number of cases, this remainder has been a tired looking scholar with Dark Blue hair. </p>
    <p>On the sidelines, Litoria and Smilisca watch the competition and make commentary to each other in Sylvan. They are a little bit perturbed when they notice Ink sitting next to them. Apparently also content to not compete, Ink joins their commentary in Sylvan.</p>
    <p>Apparently, things get a little bit heated between him and Smilisca. Words are exchanged.  The judges are unimpressed.  To keep things civil, they’re both entered into the competition.  The competition is fierce.</p>
    <p>Dust watches for a bit and joins in, clearly more for his own amusement than for competitiveness.  Hunger also joins the fray.  Rasputin also wanders in and seems to do what he does best: ramble.</p>
    <p>Baijani joins Litoria to watch. And heckle. It’s very entertaining, and the twins probably pick up a few Sylvan words.</p>
    <p>Forced to try to defend the field against paragons of mental superiority, Drivel gives his utmost to represent the Crag at their own event.  As the day wears on, however, he appears to be physically drained by the endless barrage of questions.  </p>
    <p>Not only is the competition fierce… it is <i>long</i>.  As elimination is largely based on questions answered improperly, the adjudicators run out of pre-prepared queries and are forced to make several up on the spot.  It is likely that the Crag- bias introduced in these questions near the end are to blame for Drivel’s significant performance in the final stretch; yet, as the event draws to a close, Drivel becomes more and more worn, while Smilisca is only getting warmed up.  As the Adjudicators begin taking longer to devise questions than the remaining participants take to answer them, they begin discussing the possibility of a tie… a possibility which The First, who was observing the event with growing consternation, strenuously objects to, going so far as to argue that, should there even be a <i>consideration</i> of such, then a tiebreaker should be issued based on the basis of <i>correct pronunciation</i>.  After considering The First’s sage advice, the adjudicators <i>firmly</i> declare the occurrence of a Tie, self-pleased smugness writ large on their faces. The First is apoplectic. </p>
    <p><b>Winners:</b> Smilisca/Drivel, Dust, Ink/Rasputin, The Judges</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Fieldcraft">Fieldcraft</h3>
    <p>The name of this event is somewhat misleading; while fieldcrafts encompass a broad number of skills, several of which are trialed out in the wild stones half a day’s march from Eparchy, the premier event focuses on one’s talents for camouflage and concealment… and, on their capability to track in spite of these.  In this untamed, rough field of mountainside, Crag are tasked with hunting… and being the hunted.  Overseen by watchful Aggro Stalkers to ensure that none become <i>too</i> unfound, this game of seeking-the-hidden lasts until the quarry is caught… at which time, the roles are reversed.</p>
    <p>Allophryne has decided, very early on, that he has done enough field work to qualify for the fieldwork event.  When Bryti sees that he’s entered the competition she crosses herself right off that list.  He makes a decent showing while hiding, partly by peppering his tracks with cayenne to fool the noses of anyone trying to track him by scent.  He then finds a nice pond and hangs out at the bottom of it until someone decides to dredge him up.  He then does a significantly less great job of things on the find side of the event, managing to tag a few elves.  If Allophryne has trouble finding the wolf elves, he uses his Detect Shapechangers ability to better pick them out.</p>
    <p>Pebble eagerly signs up for this event as well. </p>
    <p>She focuses on finding others first, hiding as an afterthought. Mountains aren't really her usual terrain, but she manages to find something vaguely familiar to hide.</p>
    <p>The wolf elves (and Vesnia in particular) attack this problem with aggressive tactics. They have been living in this kind of difficult terrain for years now, and are experts at avoiding detection in it. They are also experts at hunting and tracking. With their keen senses of smell, they are able to track down several unlucky competitors… until they hit Allophryne’s cayenne pepper traps. They must complete the rest of the competition with their traditional senses only.</p>
    <p>Consistent and dedicated, if not necessarily skilled, Vita takes advantage of her long experience in the field and supernatural spellslinging to… get found out pretty rapidly, and catch a sum total of Pebble (and that’s a maybe). But as her bumbling and antics make clear, she was clearly having fun regardless.</p>
    <p>Litoria can’t let the wolf elves win.  That would be a great tragedy.  She picks a similar strategy to the former Crocodilian and finds somewhere damp to hide.  Unaware of the cayenne being deployed, she makes use of <i>Pass without Trace</i>.  And then when following tracks handily locates any elves and provides a very bad day for anyone who might be using traditional Lycan tactics.</p>
    <p>Trischal shrugs and decides to give this hide and seek a whirl against all of these surface elves.  As she is not underground, hiding becomes an exciting conundrum but she does her best to make it work while wearing all black in a very… not… dark setting.  Tracking down other elves, however, is where she thrives as she uses all clues at her disposal to find some of the others.</p>
    <p>Shyrendora enters separately from Trischal (obviously), and promptly vanishes with little to no fanfare.  Her tracking isn’t great but through her ridiculous dark elf hearing, she manages to find a few competitors.</p>
    <p>This event starts off fairly typical.</p>
    <p>Most of the competitors are younger crag scouts called Stalkers. Though most of them are pretty new, a few of them are very experienced in mountain environments. There are also a good number of river elves. Though many of them are also experienced, it is in completely different environments. This leads to some awkward crowding on the few bodies of water in the game area in the first couple days.</p>
    <p>Pebble has a strong early showing, gleefully tagging quite a few unsuspecting crag, Vita, and even a wolf elf. However, the environment is against her. She is not used to mountainous terrain, much less the altitude. The tighter corners and vertical environments catch her off guard, and she is spotted a few times from above or below.</p>
    <p>Vita is a bit more familiar with the terrain and makes a fairly robust showing, but does not tag as many opponents as Pebble does. Unfortunately, her spellwork is useless against wolf elves and doesn't make her any harder to track.</p>
    <p>Both of them are out of the competition by around late day two, as is most of the competition. With only a handful of crag, the wolves, the rivers, and the dark elves left, the competition suddenly gets much more fierce. With many of the competitors able to evade even the judges, tactics get ruthless.</p>
    <p>The wolf elves have numerous early successes, tagging many of the unwary Crag competitors. However, things take a swiftly sour turn for them - or rather, spicy.</p>
    <p>Allophryne holds back until the field narrows. Once he has a more open field, he begins deploying his cayenne traps. They are carefully deployed to negate the scent advantage of the wolf elves. Even if there's not traps everywhere, the fact that there <i>might</i> be will slow them down. Other than that, Allophryne plays it safe. He only makes a few tags (though he does tag a wolf elf at one point,) but he is able to last the duration of the event. He spends most of his time trying to trip up the wolf elves. He does get tagged by Trischal while setting a trap and by Litoria when he thought he was safe underwater, but perhaps most importantly to him he is never tagged by a wolf elf.</p>
    <p>Trischal has one of the most exciting runs. After several embarrassing tags early on, she swiftly realizes she has brought the wrong camouflage for this terrain. Those moments include, at one point, swiftly transitioning between "throwing rocks at a pond because I'm pretty sure there is a river elf in there" to "being dragged into the pond by my ankle because Litoria is definitely in there." After these early setbacks, she swiftly switches tactics, remaining hidden as much as possible during the day and seeking other competitors at night. She manages to turn the momentum, tagging numerous other skilled competitors (except Shy and Litoria so far) and entering the last few days as one of the most favored to win.</p>
    <p>Shyrendora maybe wasn't sure what she was signing up for. Despite this, she makes an excellent showing early on. She is able to tag a notable amount of competitors (including Trischal) while staying completely concealed. As the field narrows, she remains completely undetected. She also starts slowly becoming unable to find anyone else. Man, this competition is sure going on a long time. (Survival: 14) Near the end of day 6, Shyrendora has run out of supplies and gets frustrated. She ends up marching back to the starting point to declare she's dropping out, only to find that she has been listed as missing for two days and the <i>judges</i> have been out looking for her.  Oops.</p>
    <p>Litoria, meanwhile, is having <i>fun.</i> She’s able to coast through the first few days tagging a few here and there, but it’s when the field narrows that she really cuts loose. She becomes an unholy terror on the wolf elves. While she does tag a few of the other major competitors, she saves most of her time for that particular group. Most importantly, she manages to avoid getting tagged at all for the majority of the event. It is only on day 7 that she is finally tagged.</p>
    <p>Trischal manages to sneak up on Litoria while she’s holding Vesnia’s head underwater in a stream. Trischal politely reminds Litoria that this particular wolf elf is kinda sorta maybe on our side-ish, so don’t drown her please. More importantly, Litoria was the last competitor remaining to be tagged, so that marks the end of the event. Litoria releases Vesnia. Y’know, in her own time.</p>
    <p>While Trischal had the most tags total and Shy has the unique honor of never being tagged at all, Litoria still has a hefty number of tags on her belt and more importantly spent the longest time without being tagged. That is more than enough to declare the event a win for her. </p>
    <p>The Crag, especially the Stalker population, are in awe.  It becomes swiftly apparent that rumors of ‘The Litoria’ have already begun making their way around the Aggro population; with this latest display, the rumors are proven to be completely founded, and perhaps even understated.  Not far behind, however, Trischal’s sheer number of successful hunts has helped make up for her earlier lacklustre performance, comfortably placing her in a secondary position.  While Vesnia and her wolf elves looked to be a clear runner for the 3rd place early on, Allophryne’s sabotage… for which there was not <i>technically</i> a prohibition in the books yet… causes them to lag behind, allowing him to move into that position.  At least, that’s what everyone assumed, until Shyrendora reemerges from the mountainside.  Although never technically disqualified(and the fact that an MIA is not a disqualification is <i>another</i> area where the books will need to be amended), the winners of the event have already been announced.  Quick to shift the possible blame to another, the Bakshish adjudicators for the event propose that, perhaps, Shyrendora and Allophryne could share third standing… a decision that is largely up to Allophryne.</p>
    <p>And Allophryne’s still just thrilled to have gotten the better of the wolf elves.  He’s totally happy to share any accolades granted.</p>
    <p><b>Winners:</b> The Litoria, Trischal, Shyrendora/Allophryne</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Markselfship">Markselfship</h3>
    <p>Exactly what it says on the tin.  The tin sign, that is, placed next to a rudimentary roped off area that overlooks a sharp drop away from Eparchy and into the lowlands.  Against this scenic backdrop, numerous targets with colored rings have been placed, with obvious purpose; to whomever places their payload swiftest, strongest, and with greatest accuracy, goes the accolades.  Across the broad expanse, Crag of all shapes and sizes wield bows of same, hurling stone-tipped arrows into the straw targets with all the precision they can muster. </p>
    <p>Pebble is reasonably certain that she can't win, but gives it a try anyway. </p>
    <p>Dhakamari takes a place in the line with the longbow most winged elf rangers favor. </p>
    <p>Web-handed fumble-fingered random river elves make a whole mess of their targets.  Their clumsiness with their bows makes everyone else look really good in comparison.  Are these people even actual elves?  You had never known elves to be so bad at archery before.</p>
    <p>Cassius, too, decides to enter into the ranged competition, bringing a Blade Elf longbow and a determined expression. Much to the audience's surprise, he manages through sheer luck to spear several rings. </p>
    <p>It is during the darker hours of the event that a dark elf finally joins.  Quiet as can be, Shyrendora wanders over to the area and observes for a while.  After a few calculations and a decision finally made on those calculations, she wanders away.  It doesn’t take too long for her to return with a winged-elf longbow in hand.  She tests the string’s draw a few times before turning to the targets.  She fires arrows from the bow with terrifying accuracy and speed.</p>
    <p>Shadimon decides to show the more unique way winged elves use their ranged weapons. With some ground-level assistance, he clears some space. Once there’s a safe approach, he circles the area, testing the wind, and plunges down toward the targets, a javelin in hand. He hurls the javelin right as he hits the line the others were shooting from, pulling up sharply, and it slams into - and through - the target.</p>
    <p>While the Onagi adjudicators on scene admit that this is an extremely impressive performance, they regretfully must inform Shadimon that they cannot properly score his target as it has sailed off the mountainside and is currently tumbling into the Lowlands.  Of course, they invite him to demonstrate his precision with a replacement target, provided he assures them they will be able to recover this one. </p>
    <p>Shadimon is distinctly sheepish about this, and offers to see if he can find and retrieve the missing target. Barring that, he makes another successful run, this time directed at a target well away from the actual ledge. </p>
    <p>By the end of the Event, the tallied numbers present a clear result: Shyrendora has placed the most accurate shots, and has done so with greatest speed.  While force is a factor in the events, it is largely only utilized as a tiebreaker; as such, while Shadimon’s employment of unusual methods of Markselfship is decidedly impressive, it is not enough to outpace Shyrendora’s sheer skill.  Finally, let it never be said that fortune does not favor the bold; by some curious quirk,  the final spot goes to the Fire Elf, Cassius.</p>
    <p><b>Winners:</b> Shyrendora, Shadimon, Cassius</p>
    <p><a href="#Top">Return to Top</a></p>
    <h2 id="Spirit">Athlon of Spirit</h2>
    <h3 id="Deception">Deception</h3>
    <p>A curious sight, this event;  not so much for what is actually happening, but for how many spectators have come to witness the display.  Within the Central plaza, two Crag stand face to face, eyeing eachother, scanning for any tell.  And so their match begins, a struggle of wits; each participant must make three statements, one of them a falsehood.  The first to pass five falsehoods past the other is granted victory.  Named Elpahka stand at attention, to ensure there is no attempt to falsify falsehoods. </p>
    <p>It is… kind of silly.</p>
    <p>This is the first event where Dust seems genuinely competitive.</p>
    <p>If he starts with a crag opponent, he will stare unblinkingly at them with coppery eyes and state,</p>
    <p>"Lock does not sleep peacefully, because of me. <br/>
    My kids walk on four legs, instead of two. <br/>
    I'm reading your mind right now." <br/></p>
    <p>He grins broadly.</p>
    <p>While Dust's cheerful attitude and good sportsmanship make him a crowd favorite, this is a competition that requires bald faced lying. This is not Dust's usual mode of operation, but he is still extremely skilled at it. More importantly, even when <i>not</i> using <i>Detect Thoughts,</i> Dust is a master of reading his opponents and proves nigh impossible to lie to. </p>
    <p>It may also come down to Dust's more unique abilities.</p>
    <p>But not to be outdone, Barrabus Leafstorm takes the field, coming out hard with a rhyme of truths so stretched the audience could make a rope out of them (or a noose to hang him with).</p>
    <p>“Drank a wolf’s corpse-mead <br/>
    Fought my double one fall eve <br/>
    Ghetto-born I still can’t leave”</p>
    <p>Bryti also enters the field. She is armed with the senses of a refined hunter, and surprising to many can lie extremely well despite how rarely she does so. Most important, though, is a stare that seems like it could melt stone. She is perhaps taking this too seriously.  Knowing the competition, she has hit herself with an <i>Enshroud Thoughts</i> beforehand.</p>
    <p>“You cannot lie to me.”</br>
    “I can smell your fear.”<br/>
    “I do not need to lie to win.”</p>
    <p>She might be stretching the rules a little.</p>
    <p>This is going to be a close one. Barrabus rolled the highest Bluff and his haiku is quite stylish, but both Bryti and Dust beat him on sense motive. Further, they tied.</p>
    <p>Bryti's browbeating tactics are effective, but Dust's more diplomatic approach may give him an edge if there is an arbitration.</p>
    <p>Speaking of, while Dust is able to pierce Bryti's magic defenses against his psychic abilities, he's unable to touch Bryti's mind and he is unable to evade her gaze.</p>
    <p>Barrabus and Dust quickly turn out to be crowd favorites. Barrabus is clearly the best at wordplay they have seen in a very long time, and his strategy of making every set of statements a haiku is extremely popular. A few common crag enter the event knowing they'll lose, just to hear one. His matches usually take a while, as he slowly racks up lies detected as his opponents try to tackle his inscrutable wordplay.</p>
    <p>Similarly, Dust's sly jokes and evasive candor also gain a lot of interest. He's not the best liar here, but by mixing polite charm into his wordplay, he's able to keep the opposition off guard long enough for him to figure out their lies before they can figure out his. A few higher level matches are won by the sheer fact that he figures out five lies before they can. It's an unconventional tactic that catches a lot of people's interest.</p>
    <p>Bryti, on the other hand, is clearly the heel of the event. The judges are reluctant to arbitrate her matches, and several competitors quit outright rather than stand under her withering gaze. Worse yet, her lies aren't even all that good. She relies on making opponents too rattled to call her out and on her own ability to sniff out a lie like it was prey. Her tactics are clearly against the spirit of the event, but the judges appear unwilling to challenge her on it.</p>
    <p>The semifinal bout between Barry and Dust is by far the highlight of the event. They both play to the crowd, hamming up the wordplay and playing off each other's strengths in turn. They even stretch it out a little, bringing it to the maximum number of rounds. In the end, Dust goes to the final round on an extremely narrow 5/4 win with Dust detecting the last lie just a heartbeat faster than Barry.</p>
    <p>The final bout between Dust and Bryti is not as pleasant. It feels less like a game and more like a confrontation. Bryti doubles down on the intensity, cracking even Dust's unflappable calm. Dust, however, is not to be beaten easily. The match is a close one as the two each rapidly disassemble the others' lie, but even Dust feels like Bryti's gaze sees right through him, and that she is <i>unimpressed.</i></p>
    <p>It comes down to the last extremely tense round. Dust pulls out his best, but Brtyi counters with something unexpected. She makes three extremely personal and extremely confrontational statements at Dust:</p>
    <p>"You betrayed my confidence in you."<br/>
    "I will not trust you again."<br/>
    "I will never forgive you."<br/></p>
    <p>These statements cut deep. Dust is caught off guard, unsure how to reply to such a personal attack. Before he can, Bryti swiftly declares which one of Dust's statements is a lie, cinching an extremely close and extremely begrudged victory.</p>
    <p>A few seconds later, Dust parses which statement is a lie. It's the third one. </p>
    <p>Though the Crag response to much of the exchange is bitter, there is pause given in this final exchange; In this event, to strive for victory by exposing one's wounds is considered a sign of one’s dedication to the trial as it is intended.  Still, a great deal of ill-will remains, but the outcome is clear; Bryti carries the event, and the accolades to follow.  However, they are more than willing to award the second tier to Dust, whose performance throughout the event was quite clearly in keeping with the finest traditions;  and, of course, it comes to no surprise that the crowd-pleaser, Barrabus, is granted the position of Third Tier.</p>
    <p><b>Winners:</b> Bryti, Dust, Barrabus</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Artistry">Artistry</h3>
    <p>A twin event to that of Artifice, the trials of Artistry take much the same form, but with the ultimate intent not resting with efficiency or stability, but with expression and evocation.  In spite of this goal, however, much of what is on display is, so far, very practical and realist, depictions of landscapes, or still carvings, or animals in motion.  It’s all very… rudimentary.</p>
    <p>Shadimon, after obtaining a small stack of paper, sits quietly and starts assembling a small menagerie of animals. There is a selection of horses in a variety of poses, some birds, a flower, and even a winged elf. (Craft: 18) </p>
    <p>Cassius, the ugly, hunch-backed Fire Elf driver who should probably not be confused with that dead Wolf Elf guy, cackles to himself as he composes a complicated and gorgeous house of cards… which catches fire and burns into nothingness just as he places the final parchment piece. (Craft: 7) This does not stop his laughing, however. </p>
    <p>Smilisca would have entered the Artistry event, but then noticed Ink competing and didn’t feel up to it anymore.</p>
    <p>Ink enters relatively late, and not alone. He has apparently been having long discussions with Shyrendora and Rasputin. Several people begin to take interest when Shyrendora and Ink enter the pavillion for Artistry late one evening. When word gets out that Ink is setting up his tattooing tools, several more people take interest.</p>
    <p>Though Ink works in the dark, he allows just enough light for judges to see what he’s doing. What he is doing is breathtaking. Ink works with purely traditional tapping tools and moves with incredibly deft strokes, allowing a design to slowly take shape on Shyrendora’s forearm.</p>
    <p>It is a striking geometric design. Everything about the design flows from a layered diamond shape, a central form with both heavy dark edges and lighter more complex lines. Coming from that are sharp patterns that flow both towards her hand and support the central symbol. The lines that support the diamond suggest both action and strength, as well as community. In one sense, they resemble hands supporting the central symbol. If looked at another way, they could form pillars of strength. If taken another, they could form a blade that flows from the central symbol towards her hand. It is a symbol of strength and decisive action, but also one of community and support. It is a sign of darkness, but also one of hope. It is a tattoo to mark Shyrendora’s full acceptance as Domawit. (Craft Tattoo: 49)</p>
    <p>At the end of the tattooing session, Shyrendora can be seen gently touching Ink’s hand with her own while murmuring something to him in an odd form of what might be Elven.  Rasputin just stands off to the side with his hands clasped over his chest like an overly proud parent, which he is in all technicality.</p>
    <p>It is a very unusual showing, by Crag consideration, to place an art upon the flesh, but the Elpahka adjudicators of the event silence any qualms.  The sheer aesthetics, the message embedded within, the <i>evocation</i> of the work stands as moving as any temple frieze.  And, while novelty does not hinder Ink’s entrance, it actually assists Shadimon; the concept of papercraft seems to be one completely unheard of to the Crag, who most typically utilize vellum and fabrics for their non-stone writing.  However, Cassius’ performance art piece, while technically an art, belonged under performance, not artistry.  As such, the third slot goes to an up and coming Onagi by the name of Deedee, who seems to have an unusually keen eye for aesthetics, for a Crag. </p>
    <p><b>Winners:</b> Ink, Shadimon, Deedee</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Performance">Performance</h3>
    <p>In stark contrast to the silent contemplation of the previous event, few events are as boisterous and clamorous as that of Performance.  Largely dominated by Aggro warriors making displays of their use of instrument or voice, special care must be taken to physically separate many participants to opposite sides of the Dejima district’s walls… not for fear of physical confrontation, but to ensure that opposing harmonies do not resonate destructively with each other.  Still, for any looking for a truly energetic show of variety, they could do little better than to attend Performance.</p>
    <p>Intent on engaging as a bard should, Barrabus Leafstorm, Phoenix Lord, conducts a series of complicated southwestern melodies on a gorgeous guitar -- melodies that are somewhat drowned out by the Aggro performance surrounding him. Eventually, he gives up on that particular antic, and switches to singing in harmony with the Aggro... which is still mostly drowned out by the Aggro. </p>
    <p>Smilisca tries to convince Terje to join the Performance event, but the blade elf declines to share his marching chants with the Crag.  When teased that he’s too shy, he deflects with PDA.  Smilisca does not attempt to convince Terje to sing in public again.</p>
    <p>Rasputin the Echoes of Many wanders into this area in a way that one could almost call obliviousness, humming softly to himself.  He stands around for a while, ears turning to and fro before he finally opens his mouth and begins to sing in harmony with the Aggro.  Anyone in the area around him will note the odd way that the ground seems to rumble with his voice as he spins a musical tale of a Dagger, a Dragon, and, surprisingly, a Werewolf.</p>
    <p>After seeing Rasputin's performance, Terje is a little more competitive. He puts on a good showing with blade elf marching cadences. He's good at making his voice heard and the steady rhythm of the chants fits with crag sensibilities, but his performance is rather simple and straightforward compared to some of the others. </p>
    <p>He immediately asks Rasputin about that song once he's done though…</p>
    <p>In the last day of the Athlon, an extremely disheveled looking Vesnia shows for a performance. She stands on a pedestal and launches into a stirring series of speeches extolling the virtues of strict martial discipline and asceticism. While the content of her speeches are a little fascist in nature, none can doubt her passion and speechcraft, and a few crag find her concepts interesting. Still, her words are delivered with blunt brutalism and little of the artistry of other competitors.</p>
    <p>The performance area is rather too loud even for infants used to boisterous winged elf noise. So after finding a willing babysitter (Ehra), Baijani wanders in and joins the harmonies. Where Rasputin’s voice rumbles, her soars. Her clear alto breaks apart into the multipart harmonies and layers of sound typical of winged elf singing.</p>
    <p>While many are present to witness the events that took place once Rasputin, The Echoes of Many, took to the stage, few are prepared to explain exactly how they unfolded.  Though at one point merely one voice among many aspiring to compete, as his performance continued, he did more than merely perform in harmony… indeed, he became it.  Many surrounding Aggro, hearing the piece, abandoned their own melodies, instead improvising ones to accompany and compliment his, swept up in the pure expression of Art.  The piece, as it was performed that night, may never be precisely repeated, but perhaps a song that aspires to it will be conducted in tribute.</p>
    <p>Meanwhile, on the other side of the wall, Baijani’s performance in multiple harmonies seems to attract a great amount of attention; indeed, it seems that this performance is quite akin to one of the Crag’s own traditional singing methods, and hearing it from the throat of a Lowlander is an altogether entrancing experience.</p>
    <p>Speaking of entrancing, while Vesnia’s passionate oratory may not find much root in the ears of Lowlanders, it speaks deeply to many of the same virtues espoused by the Crag… and, in particular, the Aggro adjudicators for the event.  As she speaks, she finds appreciative stamps and thuds of hammerheads punctuating her words.</p>
    <p>The ultimate victor is clear: Rasputin, The Echoes of Many, carries the event.  For second and third place, however, there is some fierce contention between the adjudicators; those who favor Baijani’s soaring harmonies, and those who favor Vesnia’s inspiring rhetoric.  Ultimately, the decision may have run afoul of some degree of resentment… it is decided that Baijani is to take the second tier, while Vesnia is left with but the third.</p>
    <p><b>Winners:</b> The Echoes of Many, Baijani, Vesnia</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Insight">Insight</h3>
    <p>Though there are a number of contenders, it is difficult to find an event with less actually happening than in the event of Insight.  Held within one of the Gardens of Eparchy, it seems to mostly feature Crag who will move to the center of the assembly, sit, meditate (or just nap, it’s hard to tell), and then, after some amount of time, spout some kind of ‘Wisdom’.  While some of them actually do sound somewhat profound, others… well, just listen to this.</p>
    <p>“Look for meaning in the small things, find drive, and you will be happy.”</p>
    <p>Yeah.  There’s a lot like that. </p>
    <p>Steve is having <i>so much fun.</i> "Fates interwoven like threads in a tapestry. Tangle too much, you get cut out of the future." He smiles beatifically.</p>
    <p>Even Crassius deigns to get in on the wisdom-dispatching business, busting out the true lore of the ancients: “Before the bad reputation, comes the circus.”</p>
    <p>Rasputin gives everyone an unnaturally wide grin as he delivers his nugget of wisdom from obvious centuries of life and toil: “In life, is best to take nothing for granite."</p>
    <p>When Grandmaster Ehra Indrek takes a place in the garden, it gets a lot of attention. Unlike most of the non-Crag competitors, he seems to take this seriously. He spends time looking at the garden itself. He contemplates its structure and form, as well as the architecture around him and the faces of the crag who watch him.</p>
    <p>"Pride is the gift of Calestros, but unbridled pride begets only blinding shame. Perfect pride requires perfect humility."</p>
    <p>It is a quiet event, without much of the bustle and swagger of the others.  Once all the contenders have had an opportunity to impart their wisdom, the Elpahka adjudicators retire to a separate area to consult and reflect.  Upon their return, the results are as any could have expected, with one upset.   Ehra’s insight into the root of suffering for all is clearly worthy of First Tier, while Rasputin’s reflection upon the uncertainty of the present resonates with Crag in recent times.  However, while Crassius’ Wisdom was moving, it was also moving at the last Athlon; he should have known better than to quote oft-known wisdom, as ingenuity is part of the judgement.  Therefore,  It is Steve who receives the Third Tier.  </p>
    <p><b>Winners:</p> Ehra, Rasputin, Steve</p>
    <p><a href="#Top">Return to Top</a></p>
    <h3 id="Intimidation">Intimidation</h3>
    <p>It seems that each of the Athlons must have some element dedicated to a martial skill; for the Athlon of Spirit, that is evidently gauged by screaming.  Outside of the boundaries of Eparchy, a ring, even smaller than that for Pankration, is drawn in chalk.  Standing within the boundaries, the opponents are scant inches apart, and from there, the trial begins; who can make the other flinch first.  Named Elpahka adjudicate, searching for signs of jolting, or for contact; it seems that although feints and jabs are allowed, any actual contact results in a disqualification for the feinter, making it a risky proposition.  Sometimes the contests are solemn, intense bouts, each looking for their opponent’s guard to drop; other times, the contests get extremely loud as both do their best to jar the other.  But in the end, only one elf can leave the circle victorious.</p>
    <p>Dust watches for a while, before deciding to enter. He stands motionless, making eerie unbroken eye contact with his opponent.</p>
    <p>Shadimon is...an unexpected competitor. However, his surprising wingspan and ability to go minutes at a time without blinking is actually fairly successful. Until he and Dust end up locked in a staring contest. Which ends abruptly when Terror strides in, triggering the winged elf reflex known as ‘popcorning’. Shadimon shoots straight up, which startles Dust into stepping back, and thus taking both of them out of the line of fire.</p>
    <p>A master of the same school of motionless intimidation as Dust, Terror seemingly looms over the whole of the arena, punctuating her existentially foreboding presence with the groans and screeches of long-dead thunderstorms.</p>
    <p>It seems there has been a challenge to the boisterous and loud methods of intimidation favored by the crag. Bryti enters the competition completely unflinching. Rather than fake a strike or yell, she seems to rely on what everyone knows she is, despite the fact that she is in elf form. Several crag flee the ring outright, more than one is disqualified for attempting to actually strike her in a panic. Bryti continues with simple statements of fact and unflinching resolve that can shake an elf to their core.</p>
    <p>Except for one.</p>
    <p>…</p>
    <p>Early in the match, Litoria and Bryti both enter the ring. The both fold their arms and glare menacingly at each other. There is a tense moment. The Elpahka are sweating. They are afraid it might come to blows.</p>
    <p>Until both of them burst into a giggle fit.</p>
    <p>While this may slightly hurt their appearance, Litoria decides to continue in the competition anyway.  She is not a very loud person.  She just sits and polishes the silversheen on her viciously barbed spear, giving a practiced stink-eye. </p>
    <p>Dust and Shadimon both make surprisingly strong showings in the event. Litoria even makes it into the final few. The more subtle and personal methods of intimidation used by these elves makes much of the posturing, yelling, and feinting look like schoolyard antics. All of them get quite far.</p>
    <p>We know who the real two choices were always going to be, though.</p>
    <p>Bryti and Terror face off. By this point, both of them have sent several competitors literally fleeing the arena. This event has gathered quite a bit of attention, and the crowd is bigger than most… at a safe distance. After a few harsh lessons learned, there are three judges just in case one of them gets cold feet.</p>
    <p>It starts off calm, more like a staring contest. Those who speak of the event later will describe the pair seeming to physically grow in size. There are reports of droning, roaring noises, of glowing eyes and sparks, of smoke and cinders. It takes a considerable amount of time, and a considerable amount of the audience hide under their benches.</p>
    <p>It stops when one of the judges calls a flinch to Bryti. He claims to have seen her blink. The other two judges didn’t see it. It sparks a brief but heated debate on the definition of a “flinch” and on how many judges need to agree. Bryti interrupts the discussion. She concedes the loss. She admits the flinch. To quote her:</p>
    <p>“I saw her wrath and pain. It is greater than mine.”</p>
    <p>Terror is the winner, and that much is obvious.   Equally obvious is that second tier is awarded to the menacing suit of armor which houses a furious spirit.  But, there is a curious development; while First and Second were hotly contested, there were no contenders for third among the Crag.  Indeed, while many faced against Terror, and many more against Bryti… after all, there is some nobility in at least being willing to face such threats… once word begins circulating that one of the contenders is The Litoria, competition begins to dry up fast.  By the final day, while Terror and Bryti must contend with each other, Litoria finds that she has no more challengers to face; Third is hers by default.</p>
    <p><b>Winners:</b> Terror, Bryti, The Litoria</p>
    <p><a href="#Top">Return to Top</a></p>
    <h2 id="End">Athlon's End</h2>
    <p>While the events of the Athlon gained their fair number of intrigued and fascinated Crag, at the Athlons conclusion, it becomes evident to all involved just how poorly their people fared against their opponents from the Lowlands.  While individual sentiment did not seem overly hostile at the time, when coalesced together, there is a sudden outrage;  After all, in nearly every category, a Crag competitor did not place in the top three tiers!  Once this is realized, further objections materialize, especially as many of the winners are formally introduced… many of them are Named!  While not Bloodnames they are familiar with, surely this evidence of their importance and capabilities should have meant that they would refrain from competing, as the Crag Named do!</p>
    <p>It is Jahnni who steps forth to help soothe the bruised egos of the Crag people.  While it is clear that the Lowlanders have brought the brightest, strongest, and wisest of their people, making an impossible challenge for those Crag who competed, there was a vital service behind it; after all, the Crag people are well aware of the capabilities of their own Named, the greatest of the Crag, but who would be able to appreciate the capabilities of Lowlanders but by seeing what the greatest of their number was capable of?  Those who competed should not be discouraged by the results; rather they should commend themselves for having the resolve to face off against elves of such overwhelming ability, and reflect on the achievements they scored in spite of such incredible adversity.  Also, about the whole Named thing, it- look, it doesn’t mean what you think.  Its- its complicated.  Just trust me on this one.  You don’t even want to know.</p>
    <p>While not entirely capable of dismissing ill will, the Crag populace accepts this explanation for this Athlon’s events, and so the awarding of accolades can continue as planned.</p>
    <p>For all who ranked in the highest tiers in the Athlon, tokens which commemorate their performance are awarded.  Made of a thick circle of various types of stone, they resemble a coin or token, although at Crag proportions they might as well be a medal to some; their perfectly smooth surfaces carry no markings, polished until they shine.  However, the manner in which these Accolades is awarded is surprisingly, and a bit disappointingly,  methodical; one by one, contestants of a particular tier of a particular Athlon are called into the Pagoda at the center of the Plaza, have their name announced, and have their accolade presented by one of the Adjudicators.  There is a reason for this lack of pomp and circumstance, and it is an unfortunately sad one;  It is explained that, by longstanding tradition, they who hold an Athlon Accolade are expected to return to the next Athlon; not necessarily to compete, but to pass on the award to whomever may next be found deserving of it.  When doing so, they are invited to make statements regarding their evaluation of the winner’s performance, to better familiarize all with what was done to earn it. Sadly, the Crag have precious few Accolades which may be passed for this Athlon; many were lost in the Extermination, and even for those that have been kept or recovered, almost none of their original owners still live to award them.  However, for all of those which have gone missing, new Accolades have been sculpted, in hopes that in future events, this tradition may be carried on once more, to give the event all the Gravitas it deserves.</p>
    <p>Those who excelled in the Athlon of Body are rewarded with Accolades tinted red;  </p>
    <p>Trischal, Shyrendora, Breaker, Baijani, and Marble are granted an Accolade made entirely of cloudy Carnelian.</p>
    <p>Vesnia, Shrike, Gabbro, Ehra, and Torrenticola are granted an Accolade made of Carnelian, with a large Spinel set in the center.</p>
    <p>Terror, Skulk, Slater , Dust, and Trischal are granted an Accolade made of Carnelian, with a brilliant Ruby set in the center.  Immediately after receiving her Accolade, Slater passes out.</p>
    <p>As the Event of Top Bird is a new one, the Accolade granted is Awarded by Lowlander traditions… which, apparently, involve a large feather.  There is mention that perhaps this event will be integrated into a future Athlon.</p>
    <p>Those who excelled in the Athlon of Mind are rewarded with Accolades tinted Green:</p>
    <p>Skulk, Sechellophryne, and Cassius are granted an Accolade made entirely of lustrous Jade;  To account for the ties which were shared between Ink and Rasputin, and Shyrendora and Allophyne, Onagi are called out to will the Accolades into two stones of equal size; in the future, they may be joined once more.</p>
    <p>Gustaf, Anaxyrus, Dust, Trischal, and Shadimon are granted an Accolade made of Jade encircling a verdant Peridot.</p>
    <p>Crassus, Gneiss, Litoria, and Shyrendora are granted an Accolade made of Jade, with a translucent Emerald set in the center.  To account for the tie between Smilisca and Drivel, the Layer of the Path, Slabal, is called forth to will the accolade apart.  After a great deal of concentration, she is able to separate the Accolade into two identical accolades of equal size, proportion, and design.  </p>
    <p>It is also at this point that some great deal of confusion emerges about what, precisely, is the relation between Crassus, Crassius, and Cassius, who all appear to be the same person.  Suspicious muttering abounds.</p>
    <p>Those who excelled in the Athlon of Spirit are rewarded with Accolades tinted Blue:</p>
    <p>Barrabus, Deedee, Vesnia, Steve, and Litoria are granted an Accolade made entirely of speckled Lapis Lazuli.</p>
    <p>Dust, Shadimon, Baijani, Rasputin and Bryti are granted an Accolade made of Lapis with a dark Iolite set in the center.</p>
    <p>Bryti, Ink, Rasputin, Ehra, and Terror are granted an Accolade made of Lapis around a gleaming Sapphire.</p>
    <p>With the accolades awarded, the simple ceremony is concluded, and the Crag populace are invited to retire to the communal halls, where celebratory meals, rich in nutrition, have been prepared.  The Lowlander winners are asked to stay behind for a quick chat, however.</p>
    <p>During this discussion, it is politely but firmly recommended that, when they participate in future Athlons, it would be in the best interests of the Intention of the Athlon if they were to prepare and send their <i>people</i>, not their <i>leaders</i>.  They will reiterate that no transgression has occurred, just a misunderstanding, and hope that all awardees will be available to be present to pass on their Accolade in the future, as that lends considerably more pomp and circumstance to the proceedings.</p>
    <p>With this, all are released to their own recognizance.</p>
    
    <p class="center"><a href="#top">-FIN-</a></p>
    <hr/>



    <?php
    include "../footer.php";
    include '../../settarget.php';
    settarget("Blade",null,null,11);
    echo getarrows("9_Bits and Pieces.php","../../Events/06_0.php#jump");
    #setlast("Bonus/11_Open Athlon I.php");
    ?>
</body>