<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../header.php'; ?>
    <link rel="stylesheet" type="text/css" href="../style.css">
    <title>
        The Troublesome Duo (Trio?)
    </title>
</head>

<body>
<h1>The Troublesome Duo (Trio?)</h1>
<p>Tsun strode down the palace steps, and then out the main doors to the open Agora square. She glanced at the line of bonfires set out front, and then turned and walked along the edge of the Palace, towards a pair of dancers warming up with handstands on the far corner of the palace grounds. </p>
<p>One of the two glanced up. He gave a quick kick to his partner, and rolled back to a standing position. </p>
<p>Tsun ran a thin line across her forehead with one finger, along the line of ash traced beneath her hair. </p>
<p>The dancer replied with a similar salute. His comrade stood, and did the same.</p>
<p>“What news?” Tsun said.</p>
<p>“Little, Ashwalker,” the first dancer replied. “The Smoke Jaguars came, and were rebuffed by the Ashcast, as you expected. The rest are quiet. Even the Shattered Mirror is quiet tonight. Its… tense. As if the city is waiting on something.”</p>
<p>“It is,” Tsun said quietly. She turned back towards the palace doors.</p>
<p>“If I may…” the dancer said. Tsun glanced back.</p>
<p>The dancer swallowed. “...What is it waiting on?”</p>
<p>Tsun shook her head, and walked back to the doorway. </p>
<p>The doors sigh open once more, and a lone figure glides through them, surprisingly graceful for its size.  Great curls of green hair rest over watchful eyes, which scan back and forth, taking in their surroundings.  Finally, Embebi lays eyes on Tsun, her quarry.   A small, wry smile works its way onto her face.  Satisfied that none have moved to restrain her or assault her, she steps through the door, quietly closing it behind her with her good hand.</p>
<p>“Hail and prevail, Ristar.  Looks like they haven’t managed to kill you yet, quineg?”</p>
<p>"No," Tsun sighed. She leaned back against the palace wall. "But crippled me, almost. Hunger and Terror have dispersed my forces, while Fury's weakened our determination by pushing sects like this," she gestured to the Firedancers lining up by the nearby bonfires, "to the fore. They even had me near-exiled, for a season. ...My battle at Alfyr has almost inflicted more harm than help." </p>
<p>Embebi raises an eyebrow, leaning against the same wall.  She seems to mull over Tsun’s woes.  “Bitch of it, that.  The Past, you can see for miles.  The Future, inches.  Shame we never get to fight in the past.”  She makes a soft, amused <i>hmm</i>.  “Still, they let you draw breath.  Says they either respect you enough, or entirely little, and either’s a position of advancement, sibkin, with sharp eye and a dose of fortune.”</p>
<p>"But how to use that..." Tsun said. "This should have been a perfect opportunity -- the Terror herself is south, fighting a nameless war for elves too wasted to pick up blades themselves. Hunger and Fury brought in a band of our betraying kin to 'guard' us; that alone should have been enough to make unseating Hunger easy. Yet I have too few loyalists to organize a coup, and if I went after him myself... it would only fit the adjective they've already given me. 'Petulant.' </p>
<p>"What would you do?" </p>
<p>Embebi squints, then clicks her tongue twice.  “First Hell, sibkin, you’re asking me for wisdom?  You’re looking for handholds when scaling shale.  Doesn’t sound like a fight you have, it sounds like a plot.  Wrong bloodline, there.  Still…” she rubs her mouth and chin for a moment, in thought.  A few seconds later, she pipes back up.  “Aight, here’s a choice: you want the truthful response, or the helpful wisdom?”  While her grasp on modern elven seems to have little improved, at least she’s less hesitant about speaking in it.</p>
<p>"Helpful wisdom," Tsun said. "I can find truth. ...But don’t force yourself. " </p>
<p>“Ack, wisdom.  Like I said, wrong bloodline, and from what I’ve seen of you, Ashwalker- and names like that help hint-  you’re more Aggro than Elpahka.” She frowns.  “...Which means nothing to you.  See, out of my elevation, me.  My point is this; you ‘n yourn, you’re Warriors.  You know what it is to fight, what it is to die, and you know the rights and wrongs that those two ain’t bad things.  But those you aggress… Well, I don’t know them wholesome.  Just the one.  And him, I got a deep feel for.  That Hunger.  He isn’t a warrior.  At best… he’s a soldier.  At best.  But unless your plan is to slit him lengthways… and I figure it isn’t, since he’s still in one piece… you can’t fight water like him by thinking like fire like you.  Third Hell, you can tell I can’t either.  I don’t even have the fitting words to describe it.  So my advice?  Find someone who does.”  </p>
<p>She huffs.  She can tell her ‘wisdom’ isn’t really helpful, at least not yet.  She makes one more try.  “It’s akin to this, sibkin.  You know yourself, and you know you know rightsome, and wrongsome, and that rightsome should matter more.  Thats good to have.  It’s a solid foundation.  An unwavering stance.  But stances need weapons in hand to cut.  And you’ve tried yours, and they don’t seem to do the job.  Solid Stone won’t cut.  So, you need a new weapon, one that’s like your foe, one that cuts them.  You need silver.”  She frowns.  She can tell her words still aren’t really wise, more just obvious, but they’re the best ones she has.</p>
<p>"...You've hit it," Tsun said. "I'm not made for all of this politics, like he is. I need silver, but what's the silver for bureaucrats?"</p>
<p>She sank to the paving tiles. "Wolf-devils, this was so much easier during the war. We were all warriors then, and they were our champions. The Terror, the hammer that struck fear in beasts. The Fury, the heat that drove us. The Hunger, the lure that forced the wolf armies to the field when they would have cowered in their forts. There was no talk of allying close with those who left us to burn; no waging war for a bunch of distant, drug-addled cowards with no 'aggros' of their own. </p>
<p>"I thought all we wanted was to be separate, so we wouldn't have to drag the dullest and bluntest of our cousins with us. When did that change? ...Its like this peace is an infection that creeps in and turns us, slowly, from noble elf to timid beast. ...Is there a wolfsbane cure for this? ...I once thought it was me." </p>
<p>Embebi’s face is lined with confusion, although this is an indistinct term.  For some, confusion is alloyed with fear; for others, it is closely twinned with anger.  For Embebi, her confusion is melded with excitement, an eager curiosity.  She crouches down, closer to Tsun, but still looming… she doesn’t really have any other option. “If I lived twenty generations, I don’t think I’d ever fully digest all the ways you lowlanders are.  Ancestors Inspire, sibkin, you say things I can’t even picture the shape of.  But at least, one thing here I have knowledge on.  I’ll tell you now, as any Aggro could; to follow your story, the ‘wolfsbane’ to Peace is Time.  It may not seem so in the moment, but that’s that foggy future for you.”  </p>
<p>She looks to the murky skies of Surt, focusing on a point beyond the clouds.  When she speaks, her words seem practiced, recited, as if from rote.  “Right now, all you can see is that past, and it is clear and present.  The blood, the expense, the suffering.  To you youths- uh, Lowlanders, you may think that the past you see is evidence enough that no one could ever want that.  In the moment, you feel exhausted, and seek to avoid conflict if at all possible.  The Ancestors, however, saw the right of it.  However harsh, however cruel the last conflict was, it will seem dull and distant when fresh trauma rises.   Fresh insult, fresh pain, fresh hunger.  In this moment, you cannot imagine how Raw it will feel.  It is an endlessly proven cycle.  Conflict, exhaustion, peace, argument, conflict.  It is why the Aggro is.  For so many, it is easy to forget, to want to forget, that argument will come after peace.  In the moment, they feel only the peace, how it is, and cannot see why it would not be so forever. But the next argument will always come.  And, in Time, that argument will come to conflict.  We Aggro do not forget, will not forget, that conflict is coming.  It is our duty, our Responsibility, to endure it, to enact it.  And when it passes, our duty remains, for we must be prepared for the next.”</p>
<p>She looks back down to Tsun.  “So, if all you wish is to see Peace end, all you must carry is patience.  That is a wisdom so ancient, it existed before there were even words to voice it.  But there is more core to your desires, quiaff? Not war solely to end a poison peace, but for…?” She lets the question trail off. </p>
<p>Tsun hesitated. "...Survival. Months ago, I would have said 'unity', or 'independence', but now the more I see of peace, the less certain I am that we can survive it. What happens if the Blade Elves never leave? Do we just integrate back in, as if they'd never left us for dead? Drop all the rules we built for ourselves, until millennia from now, we're just Blade Elves again, kowtowing to a man that literally once served our enemies, with no passion or self-determination or <i>anything</i> the fire granted us?"</p>
<p>She glanced up at Embebi. "I must be boring you with this. The Crag, at least, seem to have themselves put together." </p>
<p>Embebi scoffs, but it is playful, not judgemental.  “If you read boredom on me, sibkin, then the clouds here are bad for your eyes.  Crag are together, yes.  Crag know the way, Crag have a plan, Crag know the rules, how to play the game.  And then in the Lowlands?  The rules are different.  The game is changed.  Fourth Hell, you don’t even use the same tools of chance!  Whoever heard of triangular dice?”  She looks off in the distance.  Seeing the walls of Surt encroach around her, a degree of nervousness creeps onto her face, but it can’t manage to extinguish the playful smile.  “Your people, your cultures, your very land misbehaves.  It is chaotic, insensible, ineffable.  Every descent is a new fever dream, every conversation heard or action seen a contradiction.  This very moment, you are telling me that your warriors have gone to engage a foe, and another’s warriors have come to protect your people, and in spite of all my seeing and hearing I cannot begin to understand how that happened.  Even in a most logical case scenario, it seems there’s a bizarrely added step, but what is madness to me must be another day to you!” She looks back to Tsun.  Focusing in helps her nervousness, as her grin becomes stronger once more.  “Your Lowlands is many things, more than I have the words for.  But ‘boring’ does not even reside within the same temple as it.”</p>
<p>Tsun nearly smiled. " 'Confusing' is probably a better term. It certainly covers how I feel."</p>
<p>She levered herself back into a standing position. "The Terror led our finest troops south, because the enemy there rides horses... and there are few warriors as equipped to handle charging enemies as ours. These Blades Elves are clearly not so equipped; my assumption is that the 'Grandmaster' pleaded with the Terror to lend our warriors to help the Dreamdust, and offered his best "guard duty soldiers" to hold the more-defensible Surt in exchange. Unnecessarily complicated, but I doubt these Blade Elves would hold as well against mounted opponents as the Charred Eagles would." </p>
<p>Embebi’s expression shifts slightly.  “Wait… you had mentioned the enemy earlier.  I hadn’t really considered… who is this enemy?”</p>
<p>"The ones attacking the drug-addled elves down south? 'Coyote elves' or some such. Some lost tribe or another, no doubt." </p>
<p>“Coyote,” Embebi deadpans.  “What in the second hell is a ‘Coyote’?” </p>
<p>"A small wild dog. Mischevious and annoying, and known for eating small livestock. Either they behave similarly, or its a derogatory description, not unlike the 'wolf elves' boogeyman that the Hunger has been talking about." </p>
<p>Embebi tenses for a moment.  Staring into the distance, she touches her slung arm for a moment, before snapping to. Her voice is somewhat distant. “So.  Even with the <span class="animal">Animals</span> gone, there are Lowlanders who have not yet had their fill of conflict.  The wisdom of the Ancestors rings true once more.  Would be that more heeded this simple truth.  So,” she says, recovering somewhat, “what is it that you stand to gain from these… Dreamdust?  Have I gotten that right?  Which subtype are those?” </p>
<p>"The taller desert-dwellers. You might have seen them associating with a small reptilian person of some kind. As to what we have to gain from them... I don't know. Politics, probably." </p>
<p>Embebi’s face turns sour.  “Oh, fiends’ tender caress.  That word is like an epithet all its own variety to my ears. It’s vague, it’s treacherous, and worst of all, it’s <i>lazy</i>.  Come on, Ristar, you can do better than that.  Dig deep.  Think through.  If you were your enemy… I mean your local enemy, not your enemy-enemy… why would you want to help that lot?  What does it give you?” Embebi gestured with her free hand, a meaningless little hand twirl.</p>
<p>"Well, it isn't logistical," Tsun said. "They only export drugs. It's too far away for a strategic advantage, though it would fit Hunger well to want to clear a potential enemy before they can actually threaten us. Other than taking the horses for ourselves..." Tsun blinked. "You're not suggesting this action is for mere "goodwill", are you?" </p>
<p>Now Embebi holds up her hand in a supplicating gesture.  “Neg, I’m not suggesting anything.  I’m not the Lowlander here, sibkin, I was just looking for more thought than ‘some reason, supposes’.  Gotta show you did some footwork for your debrief, quiaff?”  She taps on the wall, thinking.  “That said… you said you Fires and them Swords.  You were once alike, quiaff?  But not any more, quineg? Lines diverged, full separation?  You definitely don’t have matching pheno.  Which came first?”</p>
<p>"Blade." Tsun sighed. "I was barely two decades old when Muspelham burned. Without the Conflagration, ...I suppose I would still be one of them." She frowned. "It is fortunate I don't remember much of that time... but to answer your question, the Blade Elves came first; everyone in this city was a Blade Elf the day before the Conflagration, and a Fire Elf after." </p>
<p>Embebi is quiet for a moment.  Her face seems somewhat somber, but her tone remains playful. Ish.  “Conflagration.  Sounds like either something pretty spiritual… or something pretty painful.  Knowing the luck of all us elfkin, probably both, quiaff?”</p>
<p>Tsun smirked. "Definitely. The city, and most of the people in it, burned to ash. Those that survived it were... like this." She waved her hands, and a strong orange glow rose within her, traveling up her arm until her fingertips glowed like torchlight. "The last memory I have of my life as a Blade Elf was the heat burning through me, smothering me, charring my bones. The next memory... is of the Terror throwing off the log that was crushing me, and hauling me out of a burning inn." </p>
<p>Embebi says nothing in response.  Instead, she just solemnly extends a fist towards Tsun.</p>
<p>Tsun stared at Embebi's hand for a second, and then, cautiously, bumped her fist against it. </p>
<p>“Solidarity, sibkin.” Embebi retracts the fist, letting it hang by her side as she then leans her good shoulder against the wall.  “But, point I was thinking- and I’m in uncharted ravines here, so iunno,” she says, somehow mashing it into one syllable, “but it also looks to me like it could be a Rite of Claimance, quiaff?”</p>
<p>"I don't follow." </p>
<p>Embebi closes her eyes and taps her forehead.  “Ack, ack, different rules, different game.  Well, how did you go about claiming your Bloodname?  Or… Or do you even have one?  Name like “Ashwalker” sounds more a Title than Bloodname, but it’s two and three quarter bitches to get a Title without one. Leastways ourways.”</p>
<p>" 'Ashen' was a nickname the wolf-devils gave us in the field." Tsun paused. "...It sounds more derogatory in their language. But 'Ashwalker' was a name we took back from that -- for those of us who stood back up, after Muspelham, and were able to walk out and stand against them while still dusted with the ash of our families. ...It's not really a title, so much as a moniker; I earned it in the battles close to the war's end." </p>
<p>“Title, moniker, what have you.  It’s a descriptor you get, fits you well, says I, but I’m asking about Bloodnames.  Although… maybe you don’t have them?  Titles do seem more common.  Fury, Terror, Ashwalker, Hunger… I think Leafstorm?  Kind of out of place, that one.” She clicks her tongue thoughtfully.</p>
<p>"Leafstorm is his original name," Tsun said. "...Probably. We don't have bloodnames, if I understand your meaning, though the Terror and the Fury would probably be the closest." </p>
<p>“Ack.  Okay.  Short version.  Bloodnames, you earn.  Usually, from someone else, who’s already got it.  A lot of Aggro get theirs through Rite of Claimance… essentially, you prove to them that you have more claim to the name than they do.  Usually by outdoing them in Virtue.”  She makes the hand-leveling gesture.  “It can vary some, but it’s a very big deal.  Wrap around three minutes ago, I thought it looked that way, your Enemy’s actions?  Name like Blade, they must think themselves fighters.  Not so, says yours! This foe, you cannot defeat?  I shall defeat it! And so, Claimance of the Martial Virtue to you, the Fire. No real name here… Unless I guess you would be Fire, holder of the Martial Bloodname of Sword. Hnheh! Such names you have down here.”  Her chortle is mild, but sincere.</p>
<p>"Interesting..." Tsun said. "I doubt that's what the Terror had planned, but the idea has merit."</p>
<p>She glanced upward, at the patio where the party was being held. "And in a way, they are doing the work for us; having their own soldiers cower in homes -- theirs and ours, no less -- while our soldiers clear the threat from the field. Perhaps there is merit to "reclaiming our heritage," in a somewhat literal sense." </p>
<p>Embebi makes a half shrug.  “As I said, uncharted ravines.  See some details, draw conclusions.  It’s what Stalkers do.  Sometimes, we get the gifted time to refine.  Mostimes, gotta go on first glance.  Decisions in seconds, not hours, days, not years.  It’s what Stalkers do.  It’s what all Aggro do.”  This last part is said with noticeably less cheerfulness. </p>
<p>"...Tell me about Stalkers. And Aggro in general, if you may. I assume you serve your people in a martial role, correct?" </p>
<p>Embebi picks back up.  “That’s the simple truth!  Aggro are the guardians of the Crag.  Whatever foe threatens, whatever peril ills, we take pains to take pains before any others will! Hehhn.   Our Responsibility is, as I’ve said, to prepare for those troublesome times, to be ready when they come… and to know when those times are, which is one of the hardest parts.  Stalkers, like me?  We are the distant sight of the Aggro, the unseen presence, the singular, sharpest killing intent.  We see, and are not seen.  At least, in the best situ. Doesn’t always go that way. You get some, you get got by some.”  Embebi shrugs. “And what’s the Responsibility of an Ashwalker?  Seems it should do something interesting, to earn such an evocative title.”</p>
<p>"To embrace the flame, and fight for what it means to be a Fire Elf; to have survived Muspelham when your brothers and sisters abandoned you to burn, and to prove yourself stronger than what was lost in the ashes. To stand ready, when your brothers and sisters are weak or injured, so as to buy time for them to rise up and join you. And to never stop fighting for your people -- including those that can't or won't, even when they should. To be an Ashwalker is to walk out of the ashes of the world you love, and still stand ready to fight for it." </p>
<p>AHEM</p>
<p>“ ‘Can’t or <i>won’t’</i>...” Embebi looks out to the streets of Surt.  She exhales softly.  “...Among the Crag, I am… a bit of an odd soul, when it comes to the Lowlands.  There’s something about this place, about it’s kin, that isn’t repellant, or maddening, or aggravating… although, that might be as I am in part all those things myself. Hmmhmm.” She stares at a random citizen, engaged in their normal business, very pointedly not gawking at the freakishly tall grey elf nearby.  “...But for all that this place fascinates me, there is a part that is all those things.  That I just can’t seem to wrap my headbone fully upon.”  She looks back to Tsun.  “And it’s just how… <i>Irresponsible</i>, you Lowlanders are.”</p>
<p>“<i>Scandalous</i>,” a raspy voice somewhere nearby rattles with a laugh, “Careful where you put that headbone.” </p>
<p>Skulk is casually walking along the edge of a nearby rooftop garden, one hand in a pocket, the other hand occasionally plucking something out of the greenery. </p>
<p>Taken off guard, Embebi moves suddenly.  Instinct kicks in, and she reaches for her kuthe- </p>
<p>“HrraaAAGH GREAT RUNNY GOOSE SQUIRTS”</p>
<p>-on the wrong side.  With the wrong arm. She clenches her teeth, making a soft ‘hnnng’ noise as she eyes her “quarry”.</p>
<p>Skulk just shrugs and continues walking, “Oops?” </p>
<p>Tsun bent her knees, and put one foot against the wall behind her. “Cryptic elf number two," she said. "Curious. ...Why are you plucking at that line of poison sumac?"</p>
<p>Skulk’s hand snaps into the bushes again, she peers at something between her fingers, then flicks it at Tsun. Tsun sidestepped smoothly away from Skulk's projectile (a small red spider), allowing the spider to arc onto the nearby wall, before promptly smushing it with a backhand. "You functional, Embebi?" she asked, keeping her eyes on the Cryptic above. </p>
<p>“Clear as quartz,” she says, standing straight once more.  Whatever pain assailed her seems to have passed. “Not used to getting dropped on, though it’s more familiar by the day.”  She peers up at Skulk, her eyes narrowing… not angry, but just intense.  “...I remember seeing this one.  Never caught a name.  Either one. Either way.”</p>
<p>“Skulk,” she responds casually as she snatches another spider out of the garden. This time, she flicks it in her mouth with a crunch. </p>
<p>“Skulk elves, quiaff?  Appropriate name.  Seems a popular timespender from all I’ve seen.” Embebi recovers some of her coy grin.</p>
<p>The Cryptid elf snorts through crunching bug legs, “<i>I’m</i> Skulk. Otherelves call us Cryptids.” </p>
<p>Embebi actually looks slightly embarrassed about that one.  “...Ack.” </p>
<p>“An unusually communicative one, as well,” Tsun said. “The Hunger’s party no longer suit you?”</p>
<p>Skulk casually steps off the side of the rooftop, catches the ledge, and drops herself down to the street with barely as much sound as a cat blinking. She looks the other two elves over for a moment before shrugging, “Room full of idiots.” </p>
<p>Tsun nodded. “Accurate.” She relaxed, letting her leg drop off the wall. “So… if you’re going to join us out here, then join our conversation. What would you say is the ‘responsibility’ of a Cryptid elf?”</p>
<p>“Easy,” she tilts her head at her, “Never answer questions like that.” </p>
<p>Embebi’s gaze slackens a bit, as that confusiosity gets the better of her.  “Ack, then mayhappen a different line of inquiry.”  She points her good hand at Skulk, and then up to the rooftop where she, appropriately, skulked.  “How in the Inth Hell do you <i>do</i> that?”</p>
<p>She looks back up at the rooftop and shrugs, “Jumped?” (note - it’s only a one story building.)</p>
<p>Tsun nodded. “Not especially difficult; I could probably make that leap. Which fits. Cryptid ‘abilities’ may be more shadow than substance, anyway.”</p>
<p>Skulk makes a grating chuckle, "That's the idea, dustbin." </p>
<p>“Then I can sum your people up as ‘shadowy figures who feign powerful abilities for attention’?”</p>
<p>"You can say that," she grins with black teeth, "Yeah. It fits my brother." </p>
<p>“...To be honest, you brother is rather upfront -- not with his abilities in entirety, but with his motivations.” Tsun smiled. “I’m afraid your preference for sneaking around behind him has made you the far more talked-about subject.”</p>
<p>"Talk is talk," she shrugs, "Didn't mean to interrupt. Keep talking about overthrowing the government, or whatever." </p>
<p>“ ‘The government’ is already aware of how I feel about them,” Tsun said. “And at this point, it's more of a ‘cultural exchange’. Feel free to chime in.”</p>
<p>"Wow," Skulk actually sounds taken aback, "They just let you wander around muttering about a coup?" </p>
<p>“They make their plans to stop me, and I make my plans to stop them. Thusfar, I’m still here.”</p>
<p>"And they haven't just killed you yet?" </p>
<p>“...You haven’t just killed your brother yet. Same general reasoning, perhaps?”</p>
<p>Skulk lens down and peers at Tsun curiously, "You're kind of an idiot, aren't you?"</p>
<p>Without waiting for a response, she turns to Embebi, "What about you? Plan coups for funsies too?" </p>
<p>Embebi looks back and forth between Tsun and Skulk.  “...Neg.  In full truth, I’m not even fully sure of the meaning.  Kinda sure, sure.  Fully, I think some of the… finer grit is lost.”</p>
<p>Skulk tilts her head back at Tsun, "All you, dustbin."</p>
<p>“What Skulk is referring to,” Tsun said,” is the replacement of an existing governing body with a new one without the original governing body’s… consent. And isn’t entirely accurate to my goals, but I wouldn’t judge her harshly for her misconception. I’m not yet convinced the Cryptids have a government.” </p>
<p>Embebi snaps her fingers.  She points at Tsun.  “Attend! That is a perfect example of what I meant!  ‘Government’.  I got a loose feelsome for it, when scoping Lowlanders during the Ex… During the ‘War’.  You’ve got this idea, that you have to have someone to tell you what to do, when to do, how to do.  That’s all good, in principle; in practice, it seems like you use it as an excuse to be Irresponsible.”</p>
<p>Tsun cocked her head at Embebi. “That’s twice you’ve described we ‘Lowlanders’ as that. Irresponsible. The way you say it implies there’s more to it than… well, then our term would normally mean. What does ‘irresponsible’ mean to the Crag?” </p>
<p>Embebi furrows her brows, rubbing her forehead for a moment.  “...It’s… there is… okay, aarep- I mean, example.  During the war, I’d use to…” she looks over to Skulk, “...skulk, myself.  Watching Lowlanders.  How they talked.  What they talked about.  Here and there, I’d see it.  An elf, bedecked in metal, wielding metal, maintaining metal… and then, in his voice, the passion he would hold for making <i>pastries</i>.  Or binding books.  Or, at least somewhat sensibly, hammering metal.  I thought it was madness, desperation, at first.  But as the relief was hewn, the whole picture was clear.  You have these ‘governments’, who tell you what to do, what not to do… because <i>none of you know what to do.</i>”  </p>
<p>She slaps her chest… then winces, a little.  “I am Aggro.  I know what it is to be Aggro.  I have known what, how, and when to be since my tutimes in sibclade.  Every time light rise, I know how to end that day <i>successful</i>.  But what I’ve seen is… you don’t have that.  Oftentimes, it sounds like you don’t <i>want</i> that.  That knowledge, that surety… that Responsibility.  That’s what I mean.  Your soldiers are bakers, your bakers are scholars, your scholars are laborers.  How does that happen?  How can you function that way?”</p>
<p>Skulk has turned completely away from Tsun and is giving Embebi her full attention. As she speaks, Skulk tilts her head one way, then another. Once the Crag is finished speaking, she speaks in a curious voice, "All that Responsibility… Why? What is it for?" </p>
<p>Embebi looks uncertain.  She looks at the flagstones beneath her, feeling them with her feet.  Her mouth curls this way and that.  Finally, she looks back up (<i>well</i> up, quite novel) at Skulk.  “I… what kind of question is that?  It is for the Crag.  It is for us all.  It is so…” she looks over to Tsun.  “...so we all survive.”</p>
<p>Skulk jerks her thumb back up at the rooftop she was just on, "Those plants are surviving. Spiders and bugs, too. Everything is surviving. What are you <i>doing</i>?" </p>
<p>Embebi looks more uncertain… and then, a cocksure expression climbs onto her face… and then fades away again.  She looks down at her broken arm.  Then, back up to Skulk.  “I have learned, and it was a harsh lesson, to not try and turn that question around.  It is razor honed on both ends.  So, all I can answer is this: Everything that is necessary.  And not a grain less.”  She speaks the words, but there is little fire beneath them.</p>
<p>Tsun studied Embebi’s face for a moment. “I suppose the difference is one of planning. It sounds as if your people have a plan for everyone involved; every baker, every scholar, every warrior accounted for. Is that the case?” </p>
<p>“We know who we are.  We all know what is expected of us. We are not thrust into this world, blindly grasping for meaning. We are all born to a purpose.  Not all may fulfill that purpose… but that is where wisdom prevails.  Where purpose is found.  And all in all, what we find is this; we all have a Responsibility we must tend to.  And we all must believe in each other Crag to tend to their Responsibility.  And through our joint efforts, through the abilities of all the Bloodlines, the Crag Walk the Pa-” She stops short.  A frustrated look is evident upon her face.</p>
<p>"That sounds…" Skulk isn't looking directly at Embebi and there is a note of perplexity in her voice, "... dull."</p>
<p>“And there is your answer, to some extent,” Tsun said. “The rest of us,” she gave Skulk a sideways look, “<i>are</i> grasping for meaning. Sometimes we find it, sometimes we do not. And sometimes… that meaning requires one to stand up to their hero-- their leaders. Even if it's risky. Even if it costs you something.” </p>
<p>Skulk blinks and turns to Tsun, "Are you… trying to get me to plot against my brother?" </p>
<p>Tsun… giggled. “Honestly, no. I was only trying to get you talking earlier. That was entirely my own issues. ...Why? Are you planning on plotting against your own brother?”</p>
<p>"Nope," is her only answer. </p>
<p>Tsun nodded. “That would be a heavy burden, anyway.” </p>
<p>Skulk makes a snorting noise.</p>
<p>Embebi makes a sour face.  “Eugh, plot plot plot.  The word is beginning to lose all meaning, I hear it so frequently now.  It’s not even the first meaning I’d associate with it, either.  I have far more stomach for plots than plots.”   She then makes a different face altogether.  “Ugh, to speak of stomachs.  I should have grabbed something while I could.  Might have been able to get another potato.”  She… pronounces the word wrong.  Entirely wrong.</p>
<p>“There are vendors all along the main street tonight,” Tsun said. “I don’t know if they’d have potatoes, but they might have something to your interest. If you wish, I can find some of the better ones.” </p>
<p>Embebi actually comes short of guffawing at Tsun’s mispronunciation of ‘Potato’.  She’s quick to collect herself.  “Lead the way, sibkin.  I have heard the other bloodlines complain, but I have yet to meet a Lowlander meal that could fell an Aggro.”</p>
<p>Tsun turned to Skulk. “You may come as well, if you wish.” </p>
<p>Skulk's response is silence, because she is no longer present.</p>
<p class="center">-FIN-</p>

<?php
include "../footer.php";
include '../../settarget.php';
settarget("Blade",null,null,1);
echo getarrows("../../Events/03_0.php#jump","../../Events/03_0.php#jump");
#setlast("Bonus/1_The Troublesome Duo.php");
?>
</body>