<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../header.php'; ?>
    <link rel="stylesheet" type="text/css" href="../../style.css">
    <title>
        A Plan Comes Together
    </title>
</head>

<body>
<h1>A Plan Comes Together</h1>
<p>Crater Lake glimmers in the light, it’s surface relatively undisturbed save for the wind and an occasional boney fish nose poking out to say hello as you pass.  The farther one travels to get to the small town not far away, the less… lively everything seems in comparison to the river mouth that led into the Lake.</p>
<p>The refugees you pass are plenty lively, make no mistake of that.  There isn’t much in the way of animals (or even bugs) around, almost like nothing else living had been here for a long while before the dark elves showed up.  One refugee is currently starring in fascinated confusion at the wiggling skeletal fish they have attached to their finger.</p>
<p>Moving in-wards, closer to the Caldera and further from the Lake, you see smatterings of old huts and other such small buildings.  Some look to be in the process of being torn down while others still stand untouched; it is obvious that not much attention has been paid to this part of the settlement save for what was needed to help the refugee camp.  The Hilt’Inn stands in much better condition where it is built into the side of the Caldera.  It towers over the small huts like a proud monument of what this place could have been before whatever tragedy befell it.</p>
<p>Upon entering, you are greeted by a spacious entrance with seating and hearths spread around to accommodate the mingling guests.  A central chandelier made of quartz and other crystals hangs to help spread multicolored lights within the area.</p>
<p>A dark elf materializes from a small crowd and beckons for all to follow them to a set of doors off to the side.</p>
<hr/>
<p>Shyrendora sits at a desk near the end of the large ‘meeting’ room she had picked out for this maybe two minutes after yelling at a piece of enchanted metal.  Her head rests between her hands as her fingers press to her temples.  There are papers scattered on the top of the desk, but it is unclear if she is actually looking at them or not.</p>
<p>Trischal stands to Shyrendora’s right side, arms tightly crossed over her chest and a dark frown upon her face.  Fuzzy looms to Shyrendora’s left in a manner that looks like the badger is keeping the other elf from leaving the desk.</p>
<p>Silence stretches between them like an old argument.</p>
<p>The river elves have parked their flotilla along the shore and have been generally miffed about the whole undead fish issue.  Apparently even the mollusks are not precisely living, and finding empty clam shells behaving as though they were alive is most disconcerting for someone looking for a snack.</p>
<p>The river elven military is looking significantly worse for the wear.  Many of their number sport bandages and fading bruises.  They lurk as wary guardsmen in the lake, avoiding the hot summer sun by not often clearing the surface of the water.</p>
<p>All four of their top leadership assemble in the designated meeting place, and are a little bit on the early side for this one. Smilisca sits with Litoria, and the cousins carefully observe a map together.  Eina patiently waits for others to arrive, while Staurois carefully reads through pages in a tiny notebook.</p>
<p>Terje is sitting next to Smilisca, having arrived a few days earlier. With the rest of the blade elf leadership busy this turn, Terje was the only one available. Of course, he travelled to the Hilt’Inn as soon as possible to represent the blade elves at this critical meeting. Not just to get a few extra days of vacation time in a spa with his boyfriend. Definitely not.</p>
<p>Baijani and Dhakamari come in, pausing at the door to chat with their guide. They actually arrived earlier, and had found someone willing to give them a tour. They take seats near the end of the table, and Baijani nods to Staurois, “Good to see you again. How are Ny and Natator?” </p>
<p>“Them’s doin’ well, them is.  Near six months done passed like they were four weeks or somethin, weh?”  Staurois gives Baijani a very wide grin.  “They’re playin in one of them kiddy pools.”</p>
<p>“We’ll have to look at that later. Even we can handle shallow water without rive elf help.” She bumps Dhakamari on the shoulder; everyone had heard about his brief vacation with the flotilla.</p>
<p>"Ah, good, you're all here," the Hunger said, stepping smartly into the room. He ambled over to the edge of the table, grabbed a scroll from the satchel at his side, and unrolled it onto the table in front of him. "Shall we get started? I'm somewhat pressed for time."</p>
<p>Shyrendora finally glances up at the so far gathered elves.  She raises a brow at Hunger, “Do we have a current plan or are we starting from scratch?  I only have vague details that I could wring out of Greg before he decided to pass out for a few days.” </p>
<p>The Dreamdust elves arrive, a bit late.  Dust, Steve, Pebble, and an unfamiliar elf in the enveloping hooded outfit that Dreamdust elves wear during sandstorms make their way into the room.  Dust nods to the other elves, and Pebble waves enthusiastically.  “Sorry we’re late,” Dust says.  “You all know Steve and Pebble, but you don’t know Shift yet.  Hope you don’t mind the hood, but he’s been spying for us, and the fewer folks who know his identity, the better.  He’ll let us know if there’s relevant intel that might not have come up yet.”</p>
<p>"Si, uh-" Shift clears his throat suddenly and starts speaking very carefully, "Uh, sorry. That accent is uh, sticky. I've been around Coldwater some and can answer questions, but I'll be keeping quiet mostly." </p>
<p>Baijani squints at Shift and catches Dust’s eye, very clearly asking a question. </p>
<p>Dust offers a small smile and quirks his eyebrows reassuringly. </p>
<p>She watches Shift for another moment, then turns back to Hunger, “There were nebulous plans made at the potluck, but nothing terribly solid. Hunger? I assume you have ideas?</p>
<p>“Weh,” Litoria agrees, “I weren’t there, so I’d be real interested ta hear what yall done thunk up.”</p>
<p>Before Hunger is able to answer, the room is greeted to a surprising sight. Both Ink and Skulk, instead of just appearing somewhere, actually walk into the room. With astonishing normalcy, they take seats at the table quietly.</p>
<p>Skulk folds her arms and generally glowers at the room before muttering “No promises.” </p>
<p>Shift leans over to Dust and speaks in a low whisper, “<small>Fuck me, they’re real!?</small>”</p>
<p>Dust muffles a snort.  “<small>Yep.  Allies, be nice.</small>” Pebble waves cheerfully at Ink. Ink waves back with an expression that’s probably supposed to be a smile. Pebble’s grin, if anything, gets broader when noting his attempt.</p>
<p>The Hunger blinked. "Ah, there we go. <i>Now</i> we're all here." </p>
<p>He swept his eyes across the room. "Quick review, ladies and gentlemen. Coyote Elves: formerly cavalry units fighting the Lycans, now vicious bandits. Stop me if I say anything inaccurate, Shift." The Hunger glanced over at the Dreamdust Elf.</p>
<p>Shift just makes a vague shrugging gesture, “Hobgoblins too.” </p>
<p>Baijani nods, “Very, very good cavalry. <i>We</i> couldn’t keep up with them. The one we spoke to, woman named Breaker, seemed to at least go by her word. Don’t know anything about the other one.” </p>
<p>“Ah, yes, the Hobgoblins,” the Hunger said. “We’ll get back to them. Next -- Shadimon: currently captured by said Coyote Elves, and being stored in their town of Coldwater. Third -- ‘Coyote’, their ‘bandit king’, who has demanded continuous tribute, a town, and control over a vast swath of territory in exchange for Shadimon’s life. Rather outrageous, honestly.</p>
<p>“This meeting,” he continued. “Is to go over plans for two operations, to act as response initiatives to the current situation. First, we’ll talk about Operation Birdcage.”</p>
<p>Baijani snorts at the name.</p>
<p>“Thanks to intel provided by the Dreamdust Elves, we now know the following information about Coyote Elf society. Like us, they are another branch of former slaves and Lycan subjects, who managed to fight their way out of captivity through, in this case, their extensive cavalry operations. Their current leadership was selected in response to their previous leadership ostensibly selling out to the Hobgoblin Satrapies to the south, whom they had to fight off in order to avoid being enslaved by them. Their current leader, Coyote, is a former bandit who allied with them in their war of independence; their secondary leader, Breaker, is the one we’re more familiar with, and is both effectively in charge of the cavalry, and the daughter of the sheriff who ‘betrayed them to the Hobgoblins’. </p>
<p>“We also have fairly detailed information into their mannerisms, cultural practices, and general behavior, as well as a cover origin -- their “Northern farms” are apparently considered to be full of hillbillies, and thus good cover for inserted operatives -- and a general idea of the exterior fortifications and interior prison positions within the city.</p>
<p>“My proposal for Operation Birdcage is operative insertion. We send in a small, carefully chosen team of operatives, using the exterior lake access as a potential entrance point. There is a difficult to scale wall there, but there are also docks; operatives could enter via spider climbing potions, or just from the docks themselves. Once there, the team will infiltrate, attempt to gain access to Shadimon, and retrieve him for transport out of Coldwater -- preferably via the docks again.</p>
<p>“In order to distract the Coyote Elven forces, and remove a good portion of the cavalry in the area, my people have been preparing a simultaneous operation -- Operation Friendly Fire. We’ll go into that one momentarily. For now… the floor. Comments? Options? Go.” </p>
<p>Dhakamari pulls a roll of paper out of his bag and slides it down the table, “This is the map and report on Coldwater from the scout who accompanied Shadimon. We have the general layout, with what we could tell about different sections of the city. And it is a real city. Secondly, we believe Shadimon is being held in the fort itself. We have the landmark of a large garden, and the bricks we could see in the image Ink showed us at the potluck. Those seem to match.” He glances at Baijani, “Also information from Anasatri, that wherever Shadimon is, it’s down many stairs and passes some kind of running water.” </p>
<p>“Shift?”  Dust gestured at the map.  “Thoughts?”</p>
<p>Shift turns the map towards him and looks over it. Once again, he speaks very deliberately.</p>
<p>“Coyote’s, uh, mansion,” he points at the garden, “Is around this. Old Lycan… thing. Uh, main gates into the fort here, here, and here,” he points to the four sides of the large square building, “Always lots of guards on the fort, few more on the outside wall. Town guards only, on the docks and in the streets. Lots of m- uh, stuff built under the fort. Don’t know where running water would be.” </p>
<p>“Sneaking in operatives,” Baijani says. “But from what we saw of these Coyotes, they’re more or less of a physical ‘type’.” She gestures around the table at the wide array of elven morphologies, “We are definitely not that type.”</p>
<p>“Nah,” Shift shrugs, “You’re lookin’ mostly at Cazadores… who are soldiers. Normal people can be different, not just built.” </p>
<p>The Hunger nodded. “And any differences remaining can be filled in with magic or clever costuming. My understanding is that Leafstorm has been practicing a fairly believable model; is that the case, Shift?”</p>
<p>“Looks good to me,” He makes another gesture with his hands, then slowly places them flat on the table having apparently thought better of it. </p>
<p>“Excellent,” the Hunger said. “Leafstorm has ‘volunteered’ to act as our operative. Who else can we depend upon for this task?” </p>
<p>Baijani shakes her head, “None of us, I’m afraid. We can send our rangers to support the other operation and to keep an eye on the Coyotes, but infiltration isn’t our strong point.” She lifts her wings, “Nor entirely feasible.”</p>
<p>Litoria looks around at the other three river elves, mentally checking off boxes.</p>
<p>“Non, I can’t make the trip neither.  Too many injured to leave right away.”  She looks at the Oarmaster.  “An he’s busy with the babe.  Leaves a couple a options.  I’m hearin’ that the lake is yer choice for point of entry, weh?”</p>
<p>The Hunger nodded. “It is likely to be the least secure entrance and exit. That’s not exactly guaranteed, but I’m estimating that Coyote is more likely to expect physical assault on the city -- or at least will have an easier time spotting approaches from the plains.”</p>
<p>“Weh.”  Litoria nods sharply.  “I ken give you either of these two.”  She gestures at Eina and Smilisca.</p>
<p>“And probably a couple Eyes,” Staurois adds, as though anyone else would know what he’s referring to.</p>
<p>“We can offer a couple of Dreamdust elves, for both communication and… entering locked places.  Dave is minding Riverhaven right now, but she volunteered, as have a few others.”  </p>
<p>“Excellent,” the Hunger said. “You’ll have to group up with Leafstorm at Riverhaven before the operation commences; training and preparation will take place there. The Terror will be maintaining the Charred Eagles’ vigil near there for the remainder of the season, so the area should be secure until this operation can commence. </p>
<p>“We need to aim the operation for one month before the end of the season; that’s when Operation Friendly Fire is set to commence. We’ll have until then to get our operatives trained, get our deployment vessels ready and into position -- I’m assuming we’ll have your assistance there, Litoria -- and transport our operatives to the site. Once Friendly Fire commences, the Coyote Elf forces in the immediate should be suitably distracted to provide the operatives some cover. In addition, should the operatives take too long to exit Birdcage, Friendly Fire can be used to provide them additional, emergency cover at the time of its final activation.</p>
<p>“This likely means our operatives will only have a few weeks to infiltrate the city. Not a lot of time to truly maintain cover, but that <i>should</i> hopefully be enough time to find Shadimon, recover him, and exit.”</p>
<p>Ink opens his mouth. Skulk shoots him a warning look.</p>
<p>“... Emergency extraction,” Ink returns her look, “Last resort, only.”</p>
<p>Skulk stares for a moment, then gives a quiet nod.</p>
<p>Shyrendora casually stares down at the map from where she is suddenly standing next to Shift, as if she has been there the whole time.  “I can offer my skills to this operation.  I am fairly well fit for going unseen, thus can be of use for scouting the best path to Shadimon.”</p>
<p>Shift jumps at Shyrendora's sudden appearance and muffles a "<smaller>Mierda!</smaller>" </p>
<p>He quickly clears his throat and nods in agreement.</p>
<p>Trischal’s head whips to look at the very vacant desk next to her.  Her face does some exciting musculature exercises before settling onto an expression that could be described as paper thin patience. “With all due respect,” it sounds like she is hissing through clenched teeth as she turns her head back to face everyone, “they don’t need your personal help with this operation.  It sounds like they have plenty of able volunteers.”</p>
<p>“We discussed this.  I am going, Trischal.”  Shyrendora states plainly as she continues to look over the map.</p>
<p>The slight twitch that Trischal gains under her right eye speaks volumes of her thoughts on the matter.</p>
<p>Skulk has leaned forward in her chair. Her eyes are locked on Shyrendora, tracking her movements carefully. When Shyrendora pulls her Cryptid-like trick, Skulk makes a grating sound that might be a chuckle.</p>
<p>Terje looks at the map and frowns, "Sounds like the team is going to be gone for at least two months including travel time, even if everything goes right. It isn't a good idea for me to be gone from the Fort that long, not with a couple hundred winged and dreamdust elves stress testing the academy. Still," he looks to Smilisca, "If you think you need me I'm there."</p>
<p>Terje lowers his voice so only Smilisca and those nearby can hear, "I don't want to leave you like that again, cher." </p>
<p>Baijani drums her fingers on the table, “This is sounding good, but I do have to point out something.” She points around the table, “Shyrendora, Eina, Smilisca, Dave. The best we have, yes, but for a reason. If this goes to hell on a downdraft, we potentially lose more important people. Not that I’m objecting to sending the best people we have to get my lost one back, but the risk has to be made plain.”</p>
<p>“Thems that are goin’ will foh shore make steps to have th’ leas’ risk th’ ken.”  Staurois answers quietly.  “Which means that thems that ain’t goin’ need to not know what they’re about, non.”</p>
<p>"Agreed, Staurois," the Hunger said. "But that may have to wait until the operatives in question join Leafstorm at the Riverhaven staging point. There are two other operations we need to discuss here -- Friendly Fire and War Bonds. Friendly Fire is mostly ready to go, and is almost entirely our operation; I just want to brief you before it happens, so you can let the assigned Birdcage operatives know what to expect."</p>
<p>Litoria and Staurois nod.  Eina and Smilisca share a vaguely panicked look.</p>
<p>Baijani puts her chin in her hand, “I’ve got to say I’m intrigued by these operation names you’re coming up with, Hunger. Do tell.” </p>
<p>"Operation Friendly Fire is designed to distract Coyote and his supporting forces," the Hunger said. "Through open Feathernet communication, we've managed to convey to Coyote that we are 'willing'," he waved fingerquotes in the air, "to meet his demands for tribute. This tribute will consist of an artfully designed statue, filled with expensive oils and alcohols. I've offered to deliver it to Riverhaven; this should keep Coyote's attention focused on there, and should also draw some of his forces out to receive it.</p>
<p>"Once the tribute arrives within Coldwater, the other items within the statue will trigger -- alchemist's fire, a mix of highly flammable materials, and several expensive fire elemental gems. With some luck, the statue will have been brought into the fortress before detonation. While the fire will not be sufficient to destroy the fort, it will be enough to superheat the interior in a matter of minutes, preventing proper usage for weeks and incinerating a good portion of any material they can't run out with. If they're using the fortress as I believe they are, this should prevent them from resupplying their troops for quite some time.</p>
<p>"If Birdcage operatives are still in the city by that point, I'm quite certain that the fire will be enough of a distraction that they can escape in the result. But I recommend not being in the fortress at the time." </p>
<p>Baijani stares in a combination of awe and horror, “Goddess <i>bless</i> it, Hunger. You don’t fuck around, do you.”</p>
<p>Shift stares at Hunger, "You're… putting a giant bomb in the middle of the city, and hoping it goes off in the fort?" </p>
<p>"For their sake, it had better," the Hunger said. "But the statue is more of a very hot fire than an explosive, and there will likely be time for evacuation and spreading prevention should it go off outside. And if I've deduced Coyote's personality properly, the design and accessible contents of the statue should make him much more likely to want to store it in his own properties, or with his chosen officers at a celebratory banquet. But I would appreciate any suggestions you have to make that more likely; the goal here is not to cause civilian casualties, but to disrupt their armed forces, and inform Coyote that blackmail will not be tolerated."</p>
<p>Shift makes several gestures with his hands before speaking very carefully, "That's gonna be a dice roll. Coyote is not an easy mark. He's gonna have people check it out before he just drops it in his backyard." </p>
<p>"That is what I thought," the Hunger said. "My hope is that the design of the statue and the carefully hidden mechanical nature of the trap should allow it to avoid detection, and make it more likely that the statue will be moved into a prominent location within the fort. We've had a chance to look at Coyote Elf horses at this point, and we've had some of our best sculptors and woodworkers model it to match. The mechanism itself is also hidden, and set to trigger only after a certain number of bottles have been removed from the design, but can trigger automatically if the statue is physically disrupted. Worst case scenario, the statue blows early in-transit or at the dropoff site, and the Coyote cavalry spends significant time panicking over a very large fire, and are themselves disrupted for at least a season."</p>
<p>"You may think you're some devious minded motherfucker," Shift's accent slips with fear in his voice, "but you aren't half the monster Coyote is. Play your cards close."</p>
<p>Baijani is watching him, her face unreadable. “Killing Coyote himself isn’t the point of this, I think. It would be a nice bonus, but the odds are unlikely. Based on the things you’ve said, it seems clear to me that rescuing Shadimon is the only chance we have of ever seeing him alive again. I doubt this man you describe as a monster intends on releasing him regardless of ‘tribute’.” She glances around the table, “Much as I dislike the risk of civilian casualties, we have to show this man that we will not fold to his demands. This will almost certainly be met with retribution, especially for those of us living in the area, and we must be prepared for that. Hunger, you said you had a third operation in mind. Let’s hear that one so we have everything on the table.” </p>
<p>Shift doesn't reply and avoids facing Baijani.</p>
<p>The mask covering the Hunger's face seemed to smile at this point. "Yes, let's. And to be clear, Friendly Fire is just a distraction compared to this one; frankly, even if it fails, but Shadimon is rescued, I will call it a success. Our real coup-de-grace is Operation War Bonds.</p>
<p>"Operation War Bonds starts with gaining contact with the Hobgoblin Satrapies to the South; that's somewhat out of range for my people, so we will most likely need assistance from the Dreamdust Elves and River Elves with this.</p>
<p>"Our intel informs us that the Satrapies kidnapped a number of Coyote civilians from Coldwater before they were eventually driven off. We'll need to purchase at least five of these civilians -- preferably including the former sheriff of Coldwater, whom, if my estimation is correct, is at least in bondage, if not for sale. This will be a testbed for the actual goal of War Bonds: purchasing all of them. </p>
<p>"The resources we need to purchase five hundred enslaved civilians will take a few seasons to gather, and for security reasons I won't be revealing <i>how</i> or <i>where</i> we'll be getting these resources from. Once the purchase is complete, the civilians will be invited to stay at a secure location with enough resources to provide them proper treatment, food, and living space, as guests. I'll recommend Surt for that. At that point, we will send Breaker and Coyote a demand of our own; cease all raids and stay out of our combined territories for two years, and all willing recovered civilians will be released to Coldwater at the one-year mark. With allowances for visitation from Coldwater citizens who want to confirm the safety and status of their friends and family members during that period." </p>
<p>“The sheriff is dead,” Baijani says flatly. “We found his body, marked with an office badge, in a burnt-out village south of Asavardi. Along with about three hundred other people.”</p>
<p>Shift turns towards her so hard he nearly falls out of his chair, "<i>What!?</i>" </p>
<p>Shyrendora steadies Shift with a gentle hand as she watches him from the corner of her eye.  Her hand does not linger and goes back to her side once she is sure he is not about to fall over.</p>
<p>"...Well, damn," the Hunger said. "I don't suppose you used <i>Speak with Dead</i> on him so we could confirm the current 'story' on his disappearance. ...I suppose we could instead use those resources for a resurrection, but even that seems somewhat... anticlimactic. ...The total number of missing civilians was five hundred, not three hundred. Correct, Shift?" </p>
<p>Baijani looks back at Shift, “Yes. I don’t remember the name on it, but it was a small copper star with ‘Coldwater Sheriff’. Name started with a G.”</p>
<p>"Gabe," Shift says, "Sheriff Gabe Cazares. Madre diosa… I mean… fuck. The… fuck, I don't know. I'm trying to figure out what that even means." </p>
<p>Baijani sighs, “Son, at this point I think everyone has figured out that you’re a former Coyote elf. You can drop the act. No one’s going to hurt you with Dust and Pebble there to vouch for you.” She reaches over to pull the larger map toward her. “Here’s Asavardi, and here’s where we found the village. Up here, further up the river, was the remains of a palisade. The village had been burned, everyone was dead, and there were hoofprints everywhere.” She slants her eyes over at Shift, “Sound familiar?”</p>
<p>"No," he states in a shaking voice, "And I sure as shit ain't worried about <i>you</i>. I got a family in Coldwater. If Coyote finds out about me, they're fucking <i>dead</i>. No one can say a word about me, si? <i>Please</i>." He looks around the room desperately.</p>
<p>“Fortunate none of us know your original name or your face.” Baijani pushes the map back towards Hunger. “Plan might still have merit as a back-up, but drawing the Hobgoblin’s attention to us is also potentially dangerous.”</p>
<p>"If…" Shift's voice stabilizes a bit, "If it was Coyote, there's nothing left. He always hated Gabe. If he was gonna take Gabe out… he wouldn't leave anyone alive. If they didn't die in the town, they didn't make it far." </p>
<p>Dhakamari lifts his hand, “Hunger, you said this sheriff was the father of the other leader, Breaker, yes? Does <i>she</i> know about this? If not…”</p>
<p>Shift leans over and puts his hands on his head, "I… no, she can't know. She wouldn't go along with that, no matter what Coyote told her. He fucking gave us proof. Spy reports, the stolen documents, the… how the… fucking bastard."</p>
<p>Dhakamari looks excited, “We have that badge! If you can somehow show it to her…”</p>
<p>Baijani goes pale under her dark skin, “No...we don’t...Shadi took it with him…”</p>
<p>“<span class="tooltip">Pourquoi?<span class="tooltiptext">Why?</span></span>” Litoria asks, eyebrow raised.  “What possessed him ta take en irreplaceable item with him on that flight?  Damn <span class="tooltip">couyon<span class="tooltiptext">Idiot, testicle</span></span>.”</p>
<p>“I don’t know, but he certainly wasn’t intending to get shot down and make it relevant. <i>Hopefully</i> it isn’t relevant.”</p>
<p>"If the pollo had it on him when he got shot down, then Coyote has it now and none of us are ever gonna see it," he looks at Hunger, "Look pendejo, I don't know if you got any fucking family but this ain't no small thing. When Breaker found out her dad went traitor she went nuts. You gotta understand, Coyote gave us <i>proof</i>. I don't know how he faked it but he did. You think you… fuck, if Breaker thinks you're fucking with her about that, if she thinks you're telling <i>any</i> kind of lie about her dad, she'll lose her fucking mind. No tradeoff, no nothing, she'll never listen to another clever word you have to say."</p>
<p>“<span class="tooltip">Quoi?<span class="tooltiptext">What?</span></span>”  Staurois asks, “What proof was that, weh?”</p>
<p>"People who had been loyal to him saying they'd escaped and telling us what happened, reports from our spies and scouts, stolen documents from the Hobbs, fuck me there was a letter signed by a Hobb Satrap thanking Gabe for the sale. He must have had moles everywhere, been planning that for years…" Shift trails off.</p>
<p>“<i>Her name</i>,” Baijani mutters. She shoots another questioning glance at Dust, and gets another nod. “You weren’t exaggerating. Well, leaving <i>that</i> aside for the moment...Is there anything else we here need to do to put this in motion?” </p>
<p>The Hunger shook his head. “Not unless we want to add new optional objectives, and see if Leafstorm can hit Coyote’s office before he leaves. I’ve been preparing a fourth potential operation… but to be honest, I did not particularly want to have to use that one if we could avoid it, so I’ll table that discussion for now.”</p>
<p>Shyrendora gives Hunger a look.  “No offense to your Leafstorm, but I would prefer to be the one to hit Coyote’s office if we are to add more objectives to this.”  </p>
<p>He nodded. “Reasonable. If you get the opportunity, take it; just don’t take on too much risk to do so. ...Or really, we should be looking at his mansion, rather than his office; a person like him is unlikely to store anything incriminating in an obvious spot, but <i>might</i> have a trophy room within easy reach.”</p>
<p>She stares for a moment but nods in turn.  “I have no intention to take any unnecessary risks, of that I can promise.”  Her gaze shifts to a very livid looking Trischal.  “Shadimon is my main concern.  If we can gain more from this than just his release, that will be bonuses brought by very good opportunities.” </p>
<p>Trischal snorts, “<span class="tooltip"><small>Žiadny zámer, môj zadok…</small><span class="tooltiptext">No intention my ass...</span></span>”</p>
<p class="center">-FIN-</p>

<?php
include "../footer.php";
include '../../settarget.php';
settarget("Blade",null,null,2);
#echo getarrows("../../Events/03_0.php#jump","../../Events/03_0.php#jump");
echo goback();
?>
</body>