<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../header.php'; ?>
    <link rel="stylesheet" type="text/css" href="../../style.css">
    <title>
        Operation Birdcage
    </title>
</head>

<body>
<h1>Operation Birdcage</h1>
<h2>DAY 1</h2>
<p>The underwater approach to Coldwater goes smoothly, more or less. The team has to practice walking with their canoe over their heads, but Coldwater is a big lake and they have time to practice. They set out in the early morning, flipping the canoe and heading out on the gravelly lake bed. For Eina and the two Eyes, it’s a pretty leisurely pace. The water in the lake is cool, pure, and clear - so clear, in fact, that it might be a problem. There’s a solid thirty to forty feet of clear visibility. They will have to move carefully when they approach the docks.</p>
<p>For Barry, Shyrendora, and Dave, however, it is a harrowing journey. They have only the narrow space and limited air of the underside of the canoe. The only thing that they can see outside of that is the lake bed and the occasional river elf popping in to give them an update. All that they can do is tread carefully and trust the river elves. After a little over an hour, the air is stale and they are beginning to feel a bit light headed. Thankfully, Eina pops in to tell them they are getting close.</p>
<p>As they near the Coldwater docks, the river elves watch the hulls of small fishing boats cut through the water above them. They watch the occasional net or line hit the water near them. There is certainly activity in the area. <a href="https://en.wikipedia.org/wiki/Rulyrana">Rulyrana</a>, the subdued and quiet river elf whom most of you have just met, goes first. She has the best observation and stealth skills in water. </p>
<p>She scouts out a spot in the forest of wooden dock pylons that has shade and cover. Even with the clear water, the boat will be difficult to spot. The team comes to a halt. Rulyrana swims up to the surface carefully, hugging the rocky lakebed as it ramps up towards the surface near the docks. She slowly pokes her head above water to see what is happening.</p>
<p>The docks have a low hum of activity. Most of the fishing boats are still out, but a handful have come back early with full hulls. A few teams of fishermen are removing their cargo and taking it through the docks towards a covered market square a few hundred feet away. There, merchants are already setting up their stalls and even beginning to haggle for fish.</p>
<p>As Shift said, there are guards. They are dressed  in the same ponchos and wide brimmed hats as the Cazadores, but marked with blue bandanas instead of red. They carry similar polearms as well as clubs. Currently, the guards are mostly focusing on the market and the fishermen as they unload, but there are a few patrolling the empty dock sections. Crates,  unused fishing gear, and docked or beached boats do provide cover. It’s possible to slip past, if you time it right. Rulyrana quietly slips back and makes her report to the rest of the team huddled under the canoe. </p>
<p>“Coming from an empty docked boat is too obvious,” Barrabus said. “Rulyrana should get the name of a boat that just docked. We’ll pop out by the crates, grab a few, and say we’re from that boat if asked.” </p>
<p>The Right Eye nods, and ducks back out of the boat to find a likely ship.  She takes a few quick peeks above the water to read names on hulls. A nearby boat that has recently docked and been emptied is called the "<span class="tooltip">Oro Cubo<span class="tooltiptext">Gold Bucket</span></span>." She submerges and quickly relays the information.</p>
<p>“<i>Oro Cubo</i>,” Barrabus said to himself, memorizing the name. He pointed at a set of boxes in a quieter area of the docks, not too far from the main thoroughfare, but not so close as to be visible. Then he turned to the rest of the crew. “Any objections, lords and ladies? ...Then away we go.”</p>
<p>The crew hauled themselves onto the docks, casually avoiding a guard relieving himself off the side of the dock. They dashed over to a nearby alleyway, grabbing a box or two as they went. As soon as they were in cover, Barry began blasting the water and lake muck from each spy, and Barrabus set to work with his disguised kit. </p>
<p>Barrabus' disguises were simple but effective, relying on minor changes and careful emphasis to transform the crew's more exotic traits to fit closer to Coyote 'standard'. Within minutes, the entire crew had been transformed. </p>
<p>Barrabus waved a pile of black foam through his hair and mustache, and then tapped a finger against his hat. His clothes shimmered, replacing his yellow doublet with a stark white shirt and brown duster; the hat itself paled and stretched into a white stetson. "Brilliant," he said. "We should split up here. Reduce our chances of being noticed." </p>
<p>“Weh,” the Left Eye agrees.  “Leave separately, avoid being seen as a group.”</p>
<p>Shyrendora nods her agreement, eyes watching the exit of the alleyway. While there are people in the street headed to and from the market, none of them are particularly watching the alley. The two groups are able to head their separate ways and are soon able to disappear into the growing afternoon crowd around the docks and market.</p>
<h3>Barrabus and Teratohyla</h3>
<p>Barrabus is inevitably drawn towards the closest drinking hole like a moth to flame. To gather information, of course. <a href="https://en.wikipedia.org/wiki/Teratohyla">Teratohyla</a> tails him some distance behind, blending in well with the crowd. It is not a particularly long distance to the <span class="tooltip">Gran Pesca<span class="tooltiptext">Big Catch</span></span>. It’s just on the other side of the open market, which is just starting to get warmed up for the day. Set on a corner with open archways leading inside, the cantina is currently sparsely attended but it is open. A heavyset Coyote bartender with a beard eyes him curiously as he enters, but otherwise says nothing. Teratohyla finds a table to look unobtrusive at. </p>
<p>Barrabus strolled up to the bartender, with his fiddle case overtly displayed on his back. "How much for a whiskey, barkeep?" he said.</p>
<p>The barkeep furrows his fuzzy eyebrows at Barrabus, “Whiskey’s run out. We got watered down tequila, moonshine, and some of that goat milk mierda they took from the elves. You want whiskey, head to the Yegua. They still got some.” </p>
<p>"Ah, watered down tequila," Barrabus said. "Quality."</p>
<p>He blinked, forcing himself to think like Alejandro. "I'll take it," Alejandro said. He glanced pointedly to the corners of the room. "And I don't suppose you have an… opening?" He gave the bartender a nervous smile.</p>
<p>The bartender gives Alejandro’s instrument case a highly suspicious look as he slides a shot of tequila to him.</p>
<p>“Pay first,” he grunts, “Because if you suck I throw you out, si?” </p>
<p>"...How much did you say this was?"</p>
<p>“Nickel,” he grunts again. </p>
<p>Alejandro grunted, and pulled ten mangled coppers from a shriveled coinpurse. "If it sucks, can I throw you out?" he muttered. He grabbed the glass and gave it a tentative sip. "Any place you want me to sit? Or can I just claim a corner and get started?"</p>
<p>The tequila is only a bit watered down, and that’s probably for the best as it was apparently pretty strong to start with. The bartender gives him an annoyed look before shrugging, “Knock yourself out, cabron.”</p>
<p>Alejandro sets up at a table out of the way, but still close to the doors. He tunes up his fiddle and begins to play. He takes it easy, going with tunes he knows are common just about everywhere and just a little bit of improvisation. After an hour or two, the cantina gets more crowded as merchants close down their stalls and fishermen have sold the last of their stock.</p>
<p>While he’s not awash in adoring fans or anything, Alejandro’s playing does seem to attract a few people into the cantina and get a few listeners. A little longer than that, and there are six shiny new nickels stacked on the table next to him. A modest performance for one of his grand talent, but best not to draw the adoring crowds he’s used to just quite yet. As Alejandro finishes a set, there is light applause from a few scattered places in the room. </p>
<p>Alejandro got up, and stumbled back over to barkeep. "You haven't thrown me out, yet."</p>
<p>The bartender shrugs, “You haven’t scared anyone off yet, so <span class="tooltip">estamos bien<span class="tooltiptext">we're good</span></span>. Even pulled one or two more.”</p>
<p>He pours another tequila shot, this one not watered down, and passes it to Alejandro, “This one on the house.” </p>
<p>Alejandro picked up the glass, and gave the barkeep a quick salute with it. "Thank you kindly," he said. "I'm going to take a break, and pick back up in a few. Who around here has the best card game?"</p>
<p>The bartender shrugs, “Go for the fishermen if you wanna get some cash, go for the merchants if you wanna have a fun game and lose those nickels you got. Up to you.”</p>
<p>The bartender turns to serve other customers. Alejandro proceeds to move into the crowd and start to rub shoulders a bit. Acting the northerner rube quite well, he manages to squeeze a little local info out of the crowd. On his questions about a “priest,” he gets some laughs. There are no priests left in Coldwater. Only “Brother” Matías, a novice that Coyote lets stay around for his healing skills. As far as the best card games and all the loot, all of that is in the fort itself. Coyote always keeps the best goods for him and his soldiers. If you want in on the best card games and to find the best stuff, you’ll have to find an in with them. </p>
<p>Teratohyla has thus far avoided being noticed by anyone. He’s bought a few drinks and has mostly been keeping an eye on “Alejandro.” As Alejandro moves about the crowd talking to people. Teratohyla notes that a few people give sly glances at Alejandro when they think he’s not looking. The bartender, in particular, seems to be keeping an eye on him.</p>
<p>Alejandro steps up for another set, and this time gives it a bit more of his traditional gusto. It’s a performance far above what one would expect at a local watering hole, and it seems to draw people in from the streets. The cantina gets surprisingly crowded soon, and Alejandro gets a few more coins. After his card games though, he’s only up a few coins. Still, the crowd seems to be enjoying his performance. As he’s winding down a set, the bartender waves him over. </p>
<p>Alejandro stumbled over to him, emphasizing his tiredness; performances like that should take a lot out of him. "Think I need to take off, and look for some lodging. Unless you have…?"</p>
<p>He shakes his head, “We don’t do rooms, the only inn here is down the street. Not what I was going to ask you, si? You are new in town, right?” </p>
<p>Alejandro nodded. "Needed some money, thought I might come into town for once. Better than home, anyway, right?"</p>
<p>The bartender nods, “Ah, si. Well, I can let you play casually like that sometimes yeah, but if you want an actual job playing you need to talk to Anjele. He’s got all the best music gigs, si? If you want, you could probably find him up at <span class="tooltip">Roja Yegua<span class="tooltiptext">Red Mare</span></span> in a few hours. I’d talk to him before I went fiddling that thing around too much, comprende? You can tell him Ed sent you.” </p>
<p>Alejandro's brow furrowed. "Gigs are a bit locked down then, eh? ...Well, can't be too choosy. Where's the Roja Yegua?"</p>
<p>“Up near the main gate of the fort,” he notes, “Big red building, you can’t miss it. Can’t miss Anjele either. You’ll know him when you hear him.” </p>
<p>"And you said there was an inn down the street? I'll want to get some sleep before I leave if Anjele is not too keen on me."</p>
<p>The bartender shrugs again, “Suit yourself,” he then returns to his other customers.</p>
<p>Seeing "Alejandro" is getting ready to make his exit, Terry quietly deposits a few coins for his drink and heads out. He slips through the crowd unnoticed and waits patiently outside for his charge to show up.</p>
<p>Alejandro nodded to Ed the barkeep. He took another sip of the tequila, and strolled out, keeping a leisurely strut that Terry could easily match and still have room to maneuver. Once he was out of eyeshot of the cantina, he changed direction and headed towards the Roja Yegua.</p>
<p>As he moves closer to the center of town, he notices the buildings become sturdier brick. There are more guards around. As it is late in the evening, there are also more torches and lamps lighting the streets. There are still pedestrians, so he and Terry are not out of place.</p>
<p>The Roja Yegua is a noticeable red brick building with a mural of a horse on the side. As he approaches, Alejandro gets a whiff of some kind of smoke or incense. The intensely scented substance seems to cling to the air, along with music he does not recognize. From Shift's description, he recognizes it as the peculiar type of guitar that the Coyotes favor. It is at once somber and energetic, and whoever is playing is <a href="https://youtu.be/8EcIxJmKCQQ">very, <i>very</i> good.</a> (Total Perform Result = 34)</p>
<p>Terry signals Alejandro to wait. Terry is a bit more unobtrusive, and decides to enter first. Terry presses through the swinging wooden door and into the crowd of off duty guards.</p>
<p>The cantina is crowded, with nearly all the tables full of off-duty guards drinking, playing cards, or rolling dice games. More than half the patrons are smoking something, either in pipes or wrapped in brown paper. The pungent scent clings to Terry's sensitive skin, but otherwise doesn't bother him. </p>
<p>Terry notices the source of the music as a sharp-dressed man in the back corner sporting a beautifully engraved guitar and a sharp smile. Unfortunately, the source of the music also seems to notice him, even from all the way across the crowded room. The musician meets Terry’s eyes briefly and his smile gets slightly sharper. Terry quickly puts a few more patrons between him and the musician. He finds an out of the way spot at the bar, puts down a couple coins for a drink, and waits. He has been noticed, and a few of the patrons are keeping an eye on him. He acts like he hasn’t noticed and keeps up the image of an unobservant tourist.</p>
<p>The bartender is a thin, older looking Coyote. He puts a cheap drink in front of Terry and looks him over before asking, “Out of towner, si?”</p>
<p>Terry gives a noncommittal shrug.  “Si, ami.  Firs’ time.”</p>
<p>The bartender looks Terry over for a few moments, then chuckles, “Word of advice? Sit and enjoy your drink, don’t listen too close to conversations, and don’t talk to anyone who don’t talk to you first.”</p>
<p>Terry sips his drink slowly.  He gestures with the cup toward the musician and asks, “<span class="tooltip">Qui?<span class="tooltiptext">Who?</span></span>”</p>
<p>The bartender’s eyes flick towards the musician, then back to Terry, “And don’t ask stupid questions.” Appearing annoyed, the bartender steps away from Terry leaving him to his drink in peace. The musician’s attention has already gone away from Terry entirely, and only one or two people are watching him.</p>
<p>Alejandro strolled into the cantina, shoulders up and fiddle case at his side. He scanned the room, and then deliberately tried to catch the musician's eye, before dropping into the nearest free seat at the bar. He waved to the bartender. "Whiskey?"</p>
<p>The bartender looks Alejandro over, his eyes focusing on the fiddle case momentarily. He puts down a shot glass of what appears to be decent quality whiskey before grunting, “Nickel.” </p>
<p>Alejandro pulled a nickel from the Gran Pesca from a shriveled coin purse, and set it neatly on the table. “Gracias,” he said. He gave the glass of whiskey a careful -- and overtly grateful -- sniff.</p>
<p>As Alejandro enjoys the music, he notices something. A subtle energy in the air that makes his ears twitch. The music is enhanced by magic, clearly that of an experienced bard. It’s woven so subtly into the sound that Alejandro can’t quite figure out how, but it’s there. The musician has also noticed Alejandro’s presence and is quietly watching him. The whisky smells smooth and strong. </p>
<p>Alejandro swiveled in his seat, turning to watch the performance -- and the performer.</p>
<p>As he watches the performance, he notices someone walking towards him. A rough looking Coyote of towering height, with a jagged facial scar and shaved head. He wears a set of Lycan heavy cavalry armor and has a hobgoblin heavy falchion strapped to his back. The man steps up to Alejandro and folds his arms.</p>
<p>“Coyote wants to talk to you,” he speaks in a low voice and tilts his head towards the musician. </p>
<p>Alejandro gave the hombre an uncertain smile. “Lead the way.”</p>
<p>The bodyguard glances at the machete at Alejandro’s side and growls, “No weapons.”</p>
<p>Alejandro happily hands over the tool. The bodyguard gives hims a quick pat down and finds nothing. After that, the bodyguard leads Alejandro over towards Coyote. The man keeps quietly playing and his sharp smile does not change. There is a visible gap in the crowd around the table. The bodyguard motions for Alejandro to sit across from Coyote, then leans against the wall and watches him with a scowl.</p>
<p>Coyote nods his head towards Alejandro, “<span class="tooltip">Me disculpo,<span class="tooltiptext">I apologize</span></span>” he speaks in a pleasant voice, “Hector’s very serious about his job. No need to be nervous, si?” </p>
<p>“I admit, it's not him I’m nervous of,” Alejandro said. “First day in the city, and I’m already meeting the mayor. Either my fortunes have gone very up, or very very down.”</p>
<p>Coyote laughs. It’s a pleasant sound with no soul.</p>
<p>“Ah si, that’s up to you,” he smiles and nods towards the fiddle case, “You know how to play that?” </p>
<p>"I'm a good hand at it," Alejandro said. "Good enough to know I'm talking to an expert. I can play <a href="https://youtu.be/O2RxfyXUuPI">Para Mi Para Mi Novia</a> from memory, and a few old classics like <a href="https://youtu.be/OOwTlkuTBhs?t=52">Mudriver Traveler</a>. And if you’ve got a tune in mind, I can try my hand at it."</p>
<p>Coyote nods, “You lead, then.” </p>
<p>Alejandro slipped his fiddle from his case, gave Coyote a second to ready himself, and launched into Dueling Fiddles (the classic bard v bard song every experienced hand knows). He kept to the simple and straightforward techniques, hiding nerves under a solid, rigid performance.</p>
<p>Coyote blew him away. Perfect solos, absolute timing, smooth as silk style... Alejandro was a novice -- nay, a child -- compared to him.</p>
<p>When he finished, and the applause died down, Alejandro turned back to Coyote and gave him an apologetic smile. "Another?" he said. "I won't waste the opportunity with nerves this time."</p>
<p>“Ah, si,” Coyote pours him a shot of the high quality whisky on the table, “Relax a bit, loosen up those fingers. I got a reputation I know, but I’m not gonna cut your balls off for playing something I don’t like. Why don’t you sit a spell and tell me about yourself? Not too many people around who’ve got a bard’s gift.” </p>
<p>"Learned it from my father when he was still around," Alejandro said. "He didn't give me a lot, but he gave me that. Came into town hoping to make some cash and do some drinking -- preferably at the same time, but I'll take what I can get. I've got some... unwanted responsibilities back where I came from... and I'll admit, I'm hoping staying here a while will let me avoid them, and keep my skin intact."</p>
<p>“I see,” Coyote leans back and his smile gets slightly sharper, “So what’s your name?” </p>
<p>“Alejandro Murrieta.”</p>
<p>“Well, Alejandro, you can call me Anjele,” Coyote gives him a sideways look, “Always avoiding responsibilities, then, si? That sounds familiar. Perhaps you can avoid those here. Why don’t you play a little more, Alejandro?”</p>
<p>Alejandro nods and pulls up his fiddle again. He closes his eyes and tries not to think about the deadly sociopath sitting across from him. He imagines a crowd of adoring fans, the rush of success and pride at a performance well done. He launches into a vigorous and lively tune, improvised with his personality and all the charisma he can throw into it. It’s a performance that could put a fire into any icy heart, something truly full of all his passion and energy. He loses track of time a bit, and when he finally reaches the end of his song he realizes there are whistles and whoops of approval from the audience. Coyote is giving him the same sharp smile, but waits for the crowd to die down a bit before speaking.</p>
<p>“<i>Much</i> better,” he compliments, “That’s what I was expecting from you. Ah, now I get it. You’ve got some serious natural talent and energy, si? Some real magic to you. Maybe more than me. You’ve got a serious problem though.”</p>
<p>Coyote pauses and his smile fades, “You got that problem with dodging responsibility. Talent is easy. Lots of people have talent. Greatness? That takes will and I’m not sure you have that. Whatever responsibilities you’re dodging back home, that’s not all. I can tell by your hands, si?”</p>
<p>He gestures at Alejandro’s fingertips, “Your calluses are fresh. You only practice when you feel like you really need to, otherwise they’d be old and worn in. Which of course means you’ve been practicing a lot lately. Hoping to impress me maybe? Looking for an audition?”</p>
<p>He waves a hand at those rhetorical questions, “I don’t care. I also don’t care why you lied to me about your name, si? You can be Alejandro if you want. You want to learn from me, impress me? You’ve got to have will. Bouncing through life with the wind, doing whatever’s easiest, that won’t get you anywhere. You’ll just end up fading away. You’ll never reach any real greatness with that attitude you’ve got now. Just as soon as you grab it, it’ll slip away. Just like your skills tonight, si? You want me to teach you to play, you’ve got to learn to apply yourself even when it’s not fun. If you want to make anything of yourself, you need to stop slipping away and learn when to fucking make a stand and be something. So what do you say, ‘Alejandro,’ you want to bounce along forever or fucking be somebody?” </p>
<p>Alejandro swallowed his nerves. “I want to be somebody,” he said.</p>
<p>Coyote’s smile returns, sharp as a knife, “We all do, but only some people got the will to make it happen. You think you have that, come up to the fort tomorrow night and I’ll think about giving you a lesson. Si?” </p>
<p>Alejandro nodded. “Gracias,” he said. “...I think I’ll take a break, and enjoy your barkeep’s whiskey for a bit.” </p>
<p>Coyote returns his nod. Given leave, Alejandro stands and Hector hands him back his machete with a stare. He shuffled quietly down to the bar, looking and feeling somewhat drained.</p>
<p>As Alejandro moves through the crowd towards the bar, Coyote begins playing again just as skilled as before. Briefly, Alejandro feels a tingle of magic energy on the back of his neck as he realizes Coyote’s putting some bardic magic in the song again. Unwilling to find out what that’s about, Alejandro focuses his mind on the bar and moves away. As he reaches the bar, the slight hum of energy fades. Coyote’s skilled music fills the bar.</p>
<p>By this point, Terry is almost completely unnoticed at the other end of the bar. Nearly every patron in the place was dead focused on Alejandro’s quiet conversation with Coyote. As Alejandro returns to the bar, a few people keep their eyes on him but Terry is almost completely forgotten in his little corner.</p>
<p>With the voices around Terry a little looser, he notices a few coins change hands at a nearby table. He listens carefully without changing his relaxed posture. Apparently, these guards were taking bets on whether or not Coyote was going to order Hector to take the uppity bard’s head off.</p>
<p>The odds were not in Alejandro’s favor.</p>
<hr/>
<h3>Shyrendora and Dave</h3>
<p>As Shyrendora and Dave make their way towards the church, it becomes increasingly apparent that Coldwater used to have a much higher population than it currently does. While the docks and market district are bustling, activity gets lower the further you get from there. There are plenty of artisans plying their trade in the mid city, but as you hit the residential district it gets sparse. The houses are covered in brightly colored plaster, but it is cracking or falling off on many homes. Plenty of houses are apparently abandoned, even boarded up entirely. There are people in the streets, but not many.</p>
<p>The church still stands in front of a small square. It’s a modestly large brick building decorated with small stone gargoyles, and in relatively good repair. A long since dried out fountain sits in front of a pair of heavy wooden doors. There are no guards outside, but the doors do not appear to be locked. </p>
<p>(Going into shorthand, details and purple prose will be added later.  Inside the church are only a handful of people quietly doing their own thing, and a lone novice up at the front quietly praying in front of an odd pairing of religious symbols of Almada and Celestros. It is perfectly acceptable to go up to him and talk)</p>
<p>Shyrendora is trying to stick to the role of “moody teen”; staying quiet, close to Dave, and basically keeping an eye on the other few people in the church. It’s quiet, and everyone seems to be mostly keeping to themselves. Perhaps praying for lost loved ones, or maybe just looking for somewhere quiet to sit. The “priest” is alone.</p>
<p>Dave strides over to the priest, casting concerned glances at her ‘teen’.  “Hola,” she greets.  “Are you the healer here?”</p>
<p>The “priest” looks up at the pair and stands with a weak smile, “Er, si, such as it is.” </p>
<p>“Mi hija is… not well.  Is there somewhere we can speak privately?”</p>
<p>“Of course!” he waves you back, “Uh, though, you should know. I’m not a priest, I am only a novice. All the rest of the clergy is gone. I have precious little magic that could help, and not a lot of medicine. I promise that I will do everything I can though, si? Here, let me take you to a room and we’ll take a look at her.”</p>
<p>(He will lead you to a simple priest’s room in the back of the church.) </p>
<p>“Some healing skill is better than none,” Dave says with a wry smile.  “I appreciate your concern.”  She follows him into the room and subtly locks the door behind her.  She steps forward.  “I fear we’ve brought you here under false pretenses.”</p>
<p>“Idon’thaveanymoney” he raises his hands and steps back, “Please, I’m a pacifist. All I have are my healing supplies and I will <i>give</i> those to you if you need them. People have already taken anything of value from the church. I won’t stop you but please don’t take anything I could use to help people.”</p>
<p>Dave raises her hands and starts trying to interrupt to calm him down, shooting a startled and concerned glance at Shyrendora.  “Shh, it’s okay, we’re not trying to rob you.  We need information, that’s all.  We’re not going to hurt you unless you try to shiv one of us.”</p>
<p>Shyrendora raises her eyebrows before shooting Dave a flat look.  “She speaks truth.  We mean no harm to you… or theft, just looking to help a friend.”</p>
<p>“Umh,” He keeps his hands raised and his eyes dart between the two, “Pues, then why am I getting the feeling that I’d rather you just steal from me?”</p>
<p>“Because our friend is in a very bad place right now.”  Shyrendora responds quietly.</p>
<p>He looks <i>very</i> concerned, “... Que?” </p>
<p>Dave shoots a glance at Shyrendora, visibly debates with herself, and sighs.  “About this high,” she gestures, “White hair, big fuckin’ wings.  We’re told you’re the only healer, and we know he was hurt.  So if someone patched him up...”  She lifts an eyebrow.</p>
<p>“Oh, Madre,” He sits down and puts his hands on his face, “Can we go back to the mugging? That is probably safer for me.”</p>
<p>“Probably.”  Shyrendora offers unhelpfully. </p>
<p>“We’re willing to bring you with us and give you sanctuary, or safe passage.” Dave offers.  “Alternately, you can tell us what you know about where he’s kept, and pretend very hard that we were never here afterwards.”</p>
<p>He takes several deep breaths, “You’re his friends?”</p>
<p>Shyrendora kneels down near the poor novice and pushes her hood back to show her very not-coyote like ears.  “We are.  And we would like to get him out, without causing too much trouble for anyone involved.”</p>
<p>“Yeah, well, the empty cell is gonna cause trouble, pretty big tip off si?” he sighs and leans back looking at the two elves, “My names Matías. I helped patch him up, si, and I know where he is. I want to help you. I really do. But you gotta understand a couple things. One, not many people know where he is. He vanishes, Coyote’s gonna come down here and grill me and you’ll guess how long I’ll last against that. Two… I’m not leaving. I’m the <i>only</i> healer left in this city. There’s still lots of innocent people here, and it don’t take a genius to know war is coming. Innocent people get hurt in wars, and <i>someone</i> has to be here for them. Even if it’s just a novice.” He looks between them, with a very worried look on his face. </p>
<p>Dave shrugs.  “We can try to make it look like you were roughed up a little.  Will being the only healer not be any protection?”</p>
<p>He rubs his head, “Maybe a bit? And he don’t care too much if you get roughed up. A snitch is a snitch, to him. Though… maybe? I can never guess what he’s gonna do, and he hates my guts.” He winces. </p>
<p>Dave tilts her head, considering.  “We read minds.  Not sure how much he knows about that, but we can taunt him with that in his dreams once we’re safely away.”</p>
<p>Matias stops rubbing his head, “In… his dreams? Uh… okay. Maybe if you piss him off enough he won’t go digging too hard to figure out who told him where Shadimon is. One of you might be able to fool him, but if he comes down here and rakes me over the coals I’ll snap like a twig.” </p>
<p>“Are there any guards you dislike?  We can hint we got it from them.”</p>
<p>He glances at Dave, blushing slightly, “Luis beats up his girlfriend. Tell him it was Luis.” </p>
<p>Dave nods.  “We can do that.  So what can you tell us?  How’s Shadimon doing?”</p>
<p>Matias takes a deep breath, “He’s healing well, but he’s not doing so well being confined. I’ve patched up his injuries and go check on him as much as Coyote lets me. His injuries are healing, but he’s… I dunno, losing weight. Getting a bit stir crazy. I convinced Coyote to let me bring him paper for the little animals he makes, and to let him step outside sometimes, but uh,” He looks at Dave sheepishly, “Coyote made me clip his wings. I… I’m sorry.” </p>
<p>Dave froze.  “Clipped, or pinioned?”  Her voice was arctic.</p>
<p>Shyrendora is no longer near Matias, instead standing by a wall looking for all the world like she wants to lash out at something.  She remains silent.</p>
<p>Matias speaks very quietly, “Uh, Shadimon told me how to do it. The uh, temporary one.” </p>
<p>Dave let out a long breath.  “Okay.  That’s… okay.”  She visibly tamps down her distress.  “Where’s he being kept?”</p>
<p>“In the Fort,” Matias starts breathing again, “In a cell the old Lycan Skati had for hiding prisoners he didn’t want anyone to find. It’s hidden in the storage and utility tunnels under the fort, but there’s a secret entrance. It’s uh, in Coyote’s garden though. Near the fountain. I can draw you a map?”</p>
<p>Shyrendora’s ears visibly perk though she stares at the wall in contemplation.  “A map would be appreciated.  Do you know how far those tunnels travel, by chance?”</p>
<p>“I’m not sure the exact distance. It’s a couple hundred stairs, but they’re deliberately confusing with switchbacks and things like that. Might be traps, I’m not sure. Or other entrances. The Skati was loco, si? That’s the only one I know about, but I’ll write down what I got.</p>
<p>She gives a half-hearted smile, “Sounds familiar.  We appreciate whatever you can give.”  She pauses before looking Matias in the eye, “I am going to assume this Coyote is prepared for knives in his back?”</p>
<p>Matias breathes out through his nose and rubs his neck, “You wouldn’t be the first to try. He’ll have Hector with him, and between the two of ‘em it’s real hard to get the drop. I don’t know much about fighting or magic, but I’ve seen it go real bad for people who try…” </p>
<p>Shyrendora nods and looks away again.  “Unsurprising, but thank you for the insight.”</p>
<p>(Matias grabs some writing tools and makes a quick map)</p>
<p>“Just promise me Coyote won’t find out I did this, si?” </p>
<p>Dave offers a thin smile.  “I can swear he won’t from us, and that we won’t communicate this to anyone.  I wish I could promise more than that.  But our offer stands; if you ever need a place to hide, come to the Dreamdust elves.”</p>
<p>“I’ll… remember that. Now, please leave before anyone gets suspicious.”</p>
<p>(Dave and Shyrendora - hooded once more - shuffle out into the dangerous wilds of town) (d)</p>
<hr/>
<h3>Eina and Rulyrana</h3>
<p>Parked in the dark underneath the docks, the getaway crew passes time.  They take turns napping, eat a meal, try to make guesses at what might be on the boats above them, and play cards with their waxed waterproof deck.</p>
<p>When the sun goes down and the water fades into inky blackness, Eina and Rulyrana stealthily refresh the air trapped in the canoe.  <span class="redacted">[Stealth 36]</span> Then the Right Eye moves out alone.  She prowls slowly toward the fort, seeking to locate any inlet to its plumbing.  She does not need to see, and relies on her water sense to find her way through the cool dark of the lake.</p>
<p>The two river elves manage to easily put fresh air in the canoe. There are patrolling guards, but it’s not too difficult to time their motion for when there is a gap. Once they’ve managed that, Rulyrana taps Eina on the shoulder and goes to look for anything interesting at the fort’s foundations.</p>
<p>The water gets murky and foul as she enters the runoff from the fort. Rulyrana is of course no stranger to this kind of thing and navigates by her keen sense of the flow of water around her. There are numerous currents coming off of the fort. Rulyrana inspects them each carefully, but they all turn out to be drains far too small for an elf to slip through.</p>
<p>She moves carefully, taking her time to examine the wide foundation carefully. After a few hours of carefully moving along the sealed brick, she feels a rush of current moving inwards. Moving through the gravelly lakebed, she finds an inlet a few feet wide. It would be wide enough for an elf to fit through, but it is covered by an iron grate that is set into the bricks. </p>
<p>Rulyrana inspects the grate carefully, looking for any way to open it or weaknesses in its construction.  She does not yet try to open it. It’s set in the brick well, just enough to let water in but not anything bigger than a small fish. The iron grate has clearly been there for some time, however, and the flowing water has weakened it. It might be possible to cut through with a tool or break it loose, but it would take some time. The exhaustion of having dragged a few non-swimmers across the lake and spending hours searching might make that difficult at the moment. </p>
<p>Making the best of it, the Eye returns and brings this information back to Eina.  And the Cleric sits in contemplation for a long minute.</p>
<p>“Mais, do you think I could make it over there without being noticed?”  Eina asks, at long last.</p>
<p>“Weh, we could get you there if we went at night, but the water’s too clear - you’d be noticed foh shore in the daytime.  That tin suit they shoved you in ain’t gon’ make hiding easy.”  Rulyrana’s hoarse voice is almost a whisper.</p>
<p>Eina inspects her “borrowed” mithril breastplate.  Its original Lycan owner’s family crest has been mostly buffed off and the copper wash over it has tarnished to a nice shade of green, but is still significantly reflective.  She hardly wears it, so it still shines like new.  No, it won’t be easy for her to hide.</p>
<p>“I think I ken break my way in,” Rulyrana continues, her damaged voice still quiet, “Mais la, I don’t know how to hide that I done it.”  The two discuss their options in the murky depths, waiting for the appointed time to contact the rest of the team via Sending.</p>
<h2>DAY 2</h2>
<h3>Eina and Rulyrana</h3>
<p>Sending:<br/>
	“Found a hole in the wall.  Can explore.  Will keep the boat ready.”</p>
<p>Eina casts one more spell before heading to sleep - <i>Lay of the Land</i>.  With the information she learns, she can help Rulyrana have an accurate map of this part of the lake.</p>
<p>After getting a good night’s rest, Eina and Rulyrana spend the day waiting for better lighting conditions to begin the mission into the mystery tunnel. Once evening begins to fall and the docks above them start to quiet down, the conditions are right.</p>
<p>They share a hug for good luck, and then Rulyrana stealths away. <span class="redacted">[stealth 28]</span>  She returns to the gate and then works on getting it open.  <span class="redacted">[Disable Device take 20]</span> After about 10 minutes of careful and quiet work she is able to cut through some of the bars and make an entrance large enough to swim through. She's able to replace it with barely a noticeable difference. As she proceeds down the tunnel, she finds herself fighting a strong current leading down the tunnel <span class="redacted">(Swim 22)</span></p>
<p>The current is strong, but river elves are stronger. Rulyrana is able to safely navigate the tunnel. After a few minutes of traveling in pitch darkness, she comes to an open area and a large water wheel. Near as she can tell, it's some kind of cistern. The water wheel is powered by a strong cold current, probably diverted from the river itself. This appears to be some sort of water storage area in the lower levels of the fort. She can see the surface of the water about 10 feet above her. </p>
<p>Rulyrana seeks a shadowed location in the cistern to peek above the water’s surface.  She avoids anywhere that there is bright light. She surfaces in what appears to be some kind of storage room stacked with crates. She can hear guards talking and sees light somewhere nearby on the other side of a stack of crates. She hears water gently rushing upwards in the wall behind her. Apparently, the force of the current is pumping water upwards somewhere.</p>
<p>Unfortunately, Rulyrana doesn’t know enough about plumbing to understand much of what that could mean.The top level of the water is contained by a low wall, with the cistern being mostly below the floor. It is easy for her to quietly exit the water and drop a couple feet to the floor. She creeps along behind the crates to listen to the guards.</p>
<p>The room is stacked with rows of crates, apparently containing basic supplies and food. They provide long shadows and lots of cover in the dimly lit storage room. As she peeks around the edge of a stack, she sees the guards.</p>
<p>The group of about four guards appears to be playing cards by candle light. They have dragged a crate into an open area near the exit and are using it as a table. They are about ten feet from a door that is mostly ajar. Their weapons sit on the floor beside them.  Rulyrana lets herself drip dry for a few minutes, wringing extra water out of her clothes.</p>
<p><a href="https://www.youtube.com/watch?v=XAYhNHhxN0A">Cue the theme music.</a>  She slowly makes her way through the room, creeping behind the crates, sticking to the shadows from the one lonely candle.  And she attempts to slip behind the card players through the mostly ajar door.</p>
<p>"What the fuck, hombre, that's the third ace in two hands!" One of the guards barks just as she leaves cover. She manages to suppress a yelp and quietly slips through the door as an argument breaks out. She finds herself standing in a hallway with a spiral stairwell leading up on her left. With no other direction to go in, she starts ghosting her way up the stairs, trying not to let the remaining drips give her away.</p>
<p>She comes to a confusing system of dark tunnels, twisting through the area below the fort. She goes right, staying along the wall, but after a few minutes comes to a dead end. Some of these hallways seem barely used at all. She doubles back to the stairwell, carefully avoiding patrols. She avoids getting lost, but after some time has passed she has made little progress. Stopping to think, she hears the rush of flowing water somewhere above her and remembers the report that Shadimon heard a similar sound somewhere near his cell.</p>
<p>Rulyrana follows her epiphany, and the sound, and attempts to find the cell. She searches the wall more carefully near where she hears the water. After a few minutes of carefully running her fingers along the brick wall, she finds a narrow seam. She searches the nearby wall and finds a mechanism built into a loose brick. A quick press pops the secret door open, leading to a narrow staircase that heads upwards.</p>
<p>She carefully sneaks up the staircase keeping an eye out for traps. As she approaches the top of the staircase, she sees what appears to be the back of another concealed door. The sound of running water has gotten louder. She presses her ear to the door carefully and hears… singing?</p>
<p>Meanwhile, back underneath the docks, Eina is “resting her eyes” a little.</p>
<p>Rulyrana checks the door over for traps right quick <span class="redacted">[27]</span>, then quietly <span class="redacted">[28]</span> lets herself in, or out, whichever this counts as.</p>
<hr/>
<h3>Barrabus and Teratohyla</h3>
<p>Sending:<hr/>
	"Access to Fort achieved; Alejandro has been invited by Coyote for music lessons tomorrow. Can keep his attention while Shadimon extracted, and follow-up support if Yote is alerted." -- Barrabus Leafstorm</p>
<p>Alejandro strolled to the fort, his fiddle on his back and a cocky smile on his face. He stopped at the edge of the fort, in an alleyway nearby, and gave the entranceway a quick once-over, before checking his surroundings for suspicious looking individuals and/or potential muggers. Then he glanced at the shadows on the street.</p>
<p>Timing was critical for this part of the operation; for the plan to work, Alejandro had to not only arrive at exactly the right time to keep Coyote busy <i>(Barry mentally buried the reasons <b>for</b> keeping Coyote busy, just in case of mind-reading spells)</i>, but with enough time to keep his spells at maximum potency. He had waited at the inn until right before the evening’s seventh bell for that exact purpose. Now, he merely had to look like he was pumping himself up. He added a bit of nervousness to his smile, and then pulled out his fiddle to make sure it was still in tune.</p>
<p>And once he was certain no one was paying that much attention, he cast <i>Cultural Adaptation</i>, followed by <i>Prestidigitation</i>, then followed by <i>Innocence</i>.</p>
<p>He cleaned a bit of rosin dust off of his fiddle with a quick wave of <i>Prestidigitation</i>, and then gave the shadows another glance. Showtime. He has managed to evade the guards' notice when casting his prep spells, but as he approaches the raised portcullis to the fort interior he is stopped. There are three guards posted at the gate.</p>
<p>"No weapons," one of them grunts. </p>
<p>Alejandro reached to his belt, and detached the sheathed “el cheapo” machete he had purchased for this exact purpose previously; the real one was hidden inside his fiddle case. He handed the guard the cheap knockoff, and gave him a nervous smile. “Do you mind if we hurry? ...I’ll admit to a bit of nerves.”</p>
<p>The guard rolls his eyes and grunts. He does a quick pat down and takes the machete, but doesn't check the rest of Alejandro's equipment. He waves the bard forward once he's done.</p>
<p>While that’s going on, Teratohyla, Dave, and Shyrendora casually wander in by pretending to be staff on shift change, just part of a crowd.  Minding their own business, while Barry’s getting searched.</p>
<p>As Alejandro babbles nervously at the guards, the others are able to easily slip in with a passing group of kitchen staff. The guards apparently don't even bother looking over the group as they pay attention to the clearly on edge bard.</p>
<p>The group makes it through the gates. A guard leads Alejandro up a set of stairs towards the garden. The garden is a wide area with a large number of exotic plants and some wide pathways decorated with tile. The stealthier members are able to slip away behind the cover of some plants off to the side, near where the secret entrance is. The activation switch, however, is on the fountain itself. Someone will have to go trip it, and the door is not silent.</p>
<p>Alejandro is led to the other side of the garden. Coyote's guitar music can be heard throughout the garden, but he sounds like he is just warming up and fiddling with a few experimental tunes. Once again Barrabus can feel the tingle of magic, but can't quite place what it is.</p>
<p>Coyote is sitting at a garden table playing his guitar and smoking a pipe. His bodyguard stands behind him, arms folded. A second guitar sits leaning against another chair. Coyote sees Alejandro and quietly points his head at the chair.</p>
<p>Teratohyla accepts a dustpan from one of the cleaning staff and starts fitting in where he can overhear the music lesson. Terry sees the bodyguard give him a glance, but his nerves hold out. After a few tense moments of acting casual, the bodyguard's attention turns back to Alejandro. </p>
<p>Alejandro nodded. He walked over to the offered seat, and set his fiddle case carefully on the ground to his left, before sitting down and taking up the guitar. He gave each string a quick tuning, just in case, and then turned back to Coyote.</p>
<p>The guitar is in tune and quite high quality (mastercraft instrument.) Coyote nods at it as Alejandro experiments, though he does not stop playing. </p>
<p>"Ah, that's what I want to hear," Coyote speaks, "I can teach you quite a bit about the guitar, but first let's see where you are. Show me what you can do with that." </p>
<p>Alejandro started with a low, somber solo -- not one that was particularly technically impressive, but a quiet, sonorous melody that served as a good warmup. The song meshed well with the quality of the guitar and the acoustics of the brickwork, but even with the garden echoing with the song’s deep notes, Alejandro’s nervousness was still somewhat visible. </p>
<p>He tried to push the tension from his muscles. Still, something was bothering him, and he knew it. And just as the last few notes rumbled out of his guitar, as his eyes fell on Terry at the far side of the garden, Alej-- <i>Barry</i> finally realized what it was. </p>
<p>"Bueno," Coyote nods, "Much better. I can tell you're a fiddler at heart, though. You need to loosen up your fingers, si? Especially your little finger. Build up some strength in it. It's like you're not using it at all. Here, watch my hands and see if you can move your fingers like this."</p>
<p>Coyote strums and begins to play a moderately complex chord. </p>
<p>Alejandro followed along, carefully mimicking Coyote's finger movements. It was a slow process, and he was obviously inexperienced with his fourth finger, but he managed to follow the chord with moderate skill.</p>
<p>His eyes stayed on Coyote's fingers. <i>Just a little longer.</i> The tension in his shoulders was growing.</p>
<p>"Relax amigo," Coyote's voice is oddly comforting as he plays, "We're just here to play guitar, si? You're not in any danger. I don't care that you've got an illusion up or what your real name is. I'm your friend now, si? You can trust me." </p>
<p><i>Ah, of course,</i> Alejandro thought, his mind numbing as the charm washed over him. <i>You’re my friend.</i> He felt the tension ease off of his shoulders.</p>
<p>But those weren’t Alejandro’s shoulders; they were Barry’s.</p>
<p>Not Barrabus Leafstorm, the ever-ready, always skilled adventurer who faced death everyday (and twice again in the newspapers). Barry, the street urchin. Barry, the musician for a monster. Barry, the Fire Elf bard who’d kicked, scrabbled, and scraped his way past a thousand would-be and should-have-been deaths, and was here once again, risking his own life to save someone else just because he had been asked to.</p>
<p>He wondered briefly how he’d gotten himself into this mess.</p>
<p>“You’re right,” Barry said mildly, keeping the smile Alejandro had left behind. “Let me try it again.”</p>
<p>Coyote squints at Barry, then suddenly shrugs with a slightly impressed smile, "Pues, guess you're really not some northern cabron. Smooth. Guess that means we get to do things the fun way."</p>
<p>Coyote's music drops in tone and becomes more ominous. Barry feels something cold move along his skin. A shadow moves up from his collar and presses at the edge of his eyes with a sharp pain.</p>
<p>Coyote smiles coldly, "Now tell me who you are or I'll peel your fucking skin off." </p>
<hr/>
<h3>Shyrendora and Dave</h3>
<p>Sending:<br/>
	“Have a rough map of tunnels under the Fort.  Secret entrance is in Yote’s garden.  If you meet a guard named Luis, fuck him up.”  -- Shyrendora</p>
<p>The pair watches Terry get into position and Barry go off to meet with Coyote. They manage to locate the secret door and get eyes on the fountain. After a few moments, they hear the two bards playing guitar. It's not extremely loud, but the guards seem to be interested and watching. It's something of a distraction.</p>
<p>Shyrendora gives Dave a small ‘be ready’ gesture before settling herself.</p>
<p>Slowly she breathes in before her body dissipates into a thin, creeping black mist.  The mist moves, low to the ground, and slips through the cracks of the secret entrance.  Once through, she stays in that form to take quick stock of what she sees on the other side.</p>
<p>Luckily, there do not appear to be any guards on the other side of the door. In the murky vision of her mist form, she can see the activation lever for the door and a set of doors heading downwards dimly illuminated by oil lamps.</p>
<p>After a minute passes, Shyrendora solidifies herself and creeps closer to the lever, keeping an eye out for any traps that may have to be dealt with before hand. Carefully examining the door, she finds a trigger built into the frame that will activate if the door is opened without holding the switch down. She’s not sure what it activates, but knowing that it's there makes it easy to avoid as it is on the floor right next to the switch.</p>
<p>She eyes it, and positions herself with a hand on the door.  She pulls the lever and braces as she attempts to open the door just enough for someone to slip through. Shyrendora leans into the door and tries to carefully move it open slowly. However, it seems that someone needed to oil the hinges. There is a slight squeaking noise as it opens. Not incredibly loud, but noticeable. She winces and waits. She can still hear the sound of Coyote and Barrabus playing. No one seems to have noticed. She props the door open just enough for Dave to get through.</p>
<p>Once Dave is through, Shyrendora makes a face and attempts to close the door with less hinge squeaking before releasing the lever back to the position it started in. She manages to close the door with only a small click of the mechanism locking. So far so good. </p>
<p>Dave takes point, heading slowly down the stairwell, checking carefully for traps as she goes. Sure enough, about halfway down the stairwell there is a step with a small suspicious gap around it. It appears to be some kind of trigger mechanism. </p>
<p>She points it out to Shyrendora, waiting for acknowledgement before moving on. Shyrendora looks at the step before giving a small nod and gesture for them to continue. </p>
<p>Dave makes a mental note of which stair the trap is on and continues down the stairs, keeping an eye out for more.  While Dave keeps an eye out for traps, Shyrendora is going to keep ears peeled for signs of other life. As they quietly near the bottom of the stairs, Shyrendora does indeed hear signs of life.</p>
<p>There is a heavy wooden door at the bottom of the stairwell. Matias’ map indicates that this should be the door to Shadimon’s cell. From the other side of the door, both Dave and Shyrendora can clearly hear singing. </p>
<p>Dave gets out a tiny vial of oil and applies it to the hinges, then gets out picks and starts on the lock, as quietly as possible. The lock is cleverly designed and resists her attempts momentarily. Moving slowly to prevent too much noise, she takes her time. She holds her breath and moves carefully. She feels the tension of the lock release under her fingers with barely a sound. It is unlocked. </p>
<p>Dave lets out a careful breath and puts her picks away, meeting Shyrendora’s gaze with a nod.  She mimes opening the door slowly, pointing at Shyrendora and to an imaginary figure on one side, then to herself and an imaginary figure on the other side.  Dave lifts her eyebrows inquiringly.</p>
<p>Shyrendora flicks an ear, pauses and makes a face, before simply nodding.  She gently cracks the door to peer through. This door, thankfully, is well maintained and opens quietly. Shyrendora spots two guards standing along the back wall, looking ahead where Shadimon’s cell should be. They have not noticed her.</p>
<p>She flicks her ears at Dave before making a gesture for them to move in.</p>
<p>Dave nods, aiming her blowpipe and waiting for Shyrendora to move. As they peer into the room they hear the scrape of another door opening. Further down the corridor past the guards, they see a slight gap open in one of the walls. They see the rounded ear of a river elf as Rulyrana peers out through the gap. She appears to have not noticed them.</p>
<p>Shyrendora slips into the corridor to sneak up behind the guard to the left. Shadimon is sitting in the cell, quietly fiddling with a small piece of paper and singing to himself. Neither of the guards notice Shyrendora as she enters, and Shadimon appears to be fixated on his paper folding. He seems worse for the wear, clearly having lost weight with dark circles under his eyes. </p>
<p>Moving with careful precision, Shyrendora takes her position behind the guard and raises the hilt of her dagger. She hears the slight hiss of Dave’s dart whip past her and she brings the hilt sharply to the side of the guard’s temple.</p>
<p>“Mierda, ow!” the guard barks, claps a hand to his head, then stumbles to the ground. The second guard hits the ground like a sack of potatoes and is already snoring. It is fairly obvious that the guard Shyrendora hit is faking. Dave quickly fires off another dart, but it skips off the wall as she tries not to hit Shy. Shyrendora, for her part, simply shugs, kneels, and whacks him on the other temple. His legs flail for a moment and he appears to be actually unconscious this time. </p>
<p>Dave sighs, shakes her head, and starts rifling through their pockets. She takes everything but is looking for a key. One of them does in fact have a key, and a few nickels. Score!</p>
<p>Shyrendora arches an eyebrow at Dave’s curious behavior before looking back to Rulyrana and motioning for her to join them.</p>
<p>Shadimon is on his feet, a half-folded piece of paper in one hand, staring. “...Shyren? Dave?? What...how…?” </p>
<p>Dave wiggles her fingers in a little wave as she comes over with the key, checking for traps just to be safe.  “Sneakily.  We’re your rescue party.  Can you walk?”  She unlocks the door.  </p>
<p>Rulyrana joins the group hesitantly.</p>
<p>Shadimon grimaces, “Not fast, maybe, but yes. Can’t...fly, at the moment.” </p>
<p>Dave nods.  “We planned for that.”  She gets the door open and slips in to work on unlocking the chains.</p>
<p>Shyrendora motions to the guards, “Rulyrana, can you help me drag these two into the cell?”</p>
<p>The nigh mute river elf complies with the request.</p>
<p>Dave gets the chains undone, and locks them onto the former guards.  She nods to Rulyrana.  “You got in, can we get out that way?”</p>
<p>Rulyrana shrugs.  “Potions?”</p>
<p>Dave rummages through her bag and produces the assortment of potions.  “I’m not a swimmer, but if you can manage with the ant haul?” </p>
<p>Shadimon is rubbing his chafed wrists and grimaces, “I’m useless in the water. Unless someone can tow me, we’d be here all day. Night. Whatever the fuck it is.” Hilariously, he appears to have picked up a touch of the Coyote accent.</p>
<p>“We planned for all the contingencies we could think of,” Dave says as soothingly as she can.  “Don’t worry.” </p>
<p>Shadimon raises a wry eyebrow at Dave, “Worry has been my state of being for however long I’ve been here.” He glances at the door, “But as quickly as we can go...Who else is here besides you three?”</p>
<p>Shyrendora speaks up from where she is hovering by the door, “Leafstorm, Eina, and Teratohyla.  Eina is back at our entry point and Leafstorm is dancing with death as a distraction for us to get to you.  Teratohyla is watching Leafstorm.” </p>
<p>Dave considers.  “Rulyrana, you get Shadimon out through there.  We’ll go back up top.  I’ll see if I can jam at least one of the locks, to confuse things further.  We’ll go back out through the garden and see if Barry needs backup.” </p>
<p>Rulyrana nods quietly.  "There are guards."</p>
<p>"Hmm. The invisibility potion ought to be enough to get you past?" Dave looked over the guards again. "Shadimon, do you know if either of these guys is Luis?  And have you picked up anything we need to know?" </p>
<p>“What? The one you shot. Why do…” He pauses for a moment and decides he doesn’t want to know. “Alright, yes. On your way out, if you happen to encounter Coyote - trust me you’ll know him if you see him - run.”</p>
<p>Dave grins, pulling out a few GP and hiding them in various places in Luis' clothing and boots. She also takes a moment to jot a note. Rescue, dusk, leave door unlocked. Here's payment for your help.</p>
<p>"Bit late on the warning about Coyote, Barry is getting a music lesson." She's much more blase about the danger than she should be. "Anything else?" </p>
<p>Shadimon’s jaw drops, “What? Fucking hells!” He scrubs his hands against his face, “Alright. Just...Goddess get him out of there. And,” he cuts his eyes to Shyrendora, “this isn’t the time for an assassination attempt. There are other things moving, and me disappearing will give those a solid push. Just...leave it alone for now.” </p>
<p>Dave shrugged. "Won't go out of my way, but if it happens, I'm not going to lose sleep." </p>
<p>“It’s not you I’m worried about,” Shadimon mutters. “Shyren. I <i>know</i> you, because I’m the same way. Don’t go trading your life for mine. <i>Please.</i> Don’t put that on me.” </p>
<hr/>
<h3>Shadimon and Rulyrana </h3>
<p>Rulyrana puts a webbed hand on Shadimon's shoulder. "This way," she says in a rough whisper, and begins to lead him back through the maze of tunnels.</p>
<p>Shadimon tucks his wings in tight, keeping close to her, especially as the light fades.  They stealthily <span class="redacted">[18, 24]</span> head through the dim passages back to the cistern.</p>
<p>They make it to the door of the cistern room. They can hear the card game continuing and the door is still ajar. </p>
<p>Shadimon pitches his voice low, “Sneak past? Make a run for it? Distract them?”</p>
<p>Rulyrana mimes a tiptoe motion with her fingers.  She got past them before, she’s sure they can do it again.  And so far, Shadimon’s not been a hindrance toward that. <span class="redacted">[31 stealth, 31 swim]</span></p>
<p>Apparently the guards didn't hear the commotion upstairs. The two elves are easily able to slip past them. Shadimon and Rulyrana take their potions at the mouth of the cistern.</p>
<p>Unable to stomach the idea of swimming through cramped dark tunnels, Shadimon simply closes his eyes, folds his wings, and pretends to be elsewhere. Rulyrana is able to pull his emaciated frame through the tunnel with relative ease, even with the strong current.</p>
<p>They make it out of the fort to open water. Rulyrana is even able to replace the grate, with no one the wiser. </p>
<hr/>
<h3>Barrabus and Teratohyla</h3>
<p>"Now tell me who you are or I'll peel your fucking skin off."</p>
<p>The sharp ribbons of cold shadow dig into Barrabus' skin. They seem to be waiting and eager for him to lie. Coyote simply smiles. </p>
<p>Barry smiled right back.</p>
<p>His fingers strummed a few notes on the guitar strings. He waved his other hand in front of himself, wicking the disguise from his face and hair with Prestidigitation, and then sighed a thick puff of smoke. And then, he began to play his least favorite song in the world.</p>
<p id="i">The Ballad of Barrabus Leafstorm.</p>
<p>He had it memorized, from having heard it so many times -- even played it more than a few -- but somehow, this time, it was alive. It grew in his heart, gradually at first, but came pouring out after the first refrain as a torrent of white-hot musical energy.</p>
<p>This was what had been missing from Alejandro's performances. This was what was missing from the 'Barrabus Leafstorm' in the ballad. This was real.</p>
<p>By the time he finished, he was standing, and light as strong as torchlight poured from his skin.</p>
<p>The cold ribbons of shadow peel away from his skin and evaporate as the last chord fades. Coyote's smile has also evaporated. He gives his bodyguard a sideways look and makes the universal 'what the fuck is this?' hand gesture at Barrabus. The bodyguard scowls and places a hand on the hilt of his Falchion, watching Barrabus carefully.</p>
<p>"Barrabus. <i>Fucking.</i> Leafstorm. You." Coyote turns back to Barrabus incredulously, leaning forward with his hands resting on top of his guitar, "Pues, I gotta congratulate you. I was thoroughly convinced you were actually a talentless hack." </p>
<p>"Those aren't mutually exclusive," Barrabus said, "but I'll take the complement all the same. And your advice; I clearly was out of practice."</p>
<p>"Clearly," Coyote repeats, "So, Barrabus Fucking Leafstorm, what the hell are you doing in my house?" </p>
<p>"I came here to rock your world. And your city. Normal bard things, really."</p>
<p>Coyote gives him a bewildered look, "What?" He shakes his head, apparently having been put off balance for once, "No, you can't <i>possibly</i> be that stupid."</p>
<p>Teratohyla is impressed, a bit terrified, but impressed.</p>
<p>"Try me," Barry muttered to himself. He scanned the garden, getting a quick headcount of the guards. "All right, real talk, Coyote. You gave me some pretty great advice yesterday, and I'd like to return the favor while I still have the chance."</p>
<p>Coyote frowns, but waves his palm in a 'please continue' gesture. His bodyguard steps forward to within arm's reach but otherwise does not make any aggressive actions. </p>
<p>"You are the most bored man I have ever met," Barrabus said. "You're warlord of an entire city -- ruling it with an iron fist even -- yet you're giving guitar lessons to strangers in bars. You're Owlexander the Great, resting on your laurels, swearing there are no more worlds to conquer. The most you've done in years has been sending raiders next door to steal <i>your neighbors' milk</i>. You're <i>bored.</i></p>
<p>"Come up with new schemes. Duel some enemies. Seduce your archnemesis' boyfriend or girlfriend or kid or whomever. Do something <i>exciting.</i> You can't let responsibility trap you in a position of its choosing; there are no hells worse, and if you're not careful, you'll never be able to leave." </p>
<p>Coyote leans forward a little more, leaning his chin on his hands, "Huh," he chuckles slightly, "<span class="tooltip">Si, claro.<span class="tooltiptext">Yeah, sure.</span></span> Maybe I'm getting a little complacent. Though I don't think you really understand what I'm doing here. Lemme show you, si?"</p>
<p>Without taking his eyes off Barrabus, Coyote calmly states "Hector." The bodyguard steps forward, reaching for Barrabus.</p>
<p>When Coyote says "Hector," Teratohyla sends his dart to the body guard's back. As Hector steps forward the dart connects with his neck, burying the tip deep. He snarls and staggers, placing his hand on it and whipping back to look where that came from. In his startled response, he momentarily turns away from Barrabus. Coyote hasn't taken his eyes off him. </p>
<p>Barrabus smiled. "Looks like my chaperone is here, ‘Yote; we'll have to hold that for the next date." He breathed out a cloud of grey smoke, and waved his hands through it; it smeared and smudged like wax on glass. As Barry gathered his magic to Vanish, Coyote made an annoyed grunt. He snapped a few syllables and threw a cold ball of energy at Barry. It hit Barry's magic like a cold towel, ruining the spell.</p>
<p>"Or maybe not, si?" Coyote smirked. </p>
<p>Barrabus shrugged. "I don't mind if you watch." Still out of reach, he snagged his fiddle case and tumbled through the garden, keeping the guitar tucked close to his chest.</p>
<p>Coyote stands and begins playing his guitar. Barrabus feels the familiar tingle of bardic magic rush past him, towards all the guards waiting off to the sides of the garden.</p>
<p>"Block the exits!" He yells, "And somebody kill that <span class="tooltip">pendejo<span class="tooltiptext">stupid</span></span> in the bushes!"</p>
<p>On cue, Teratohyla pivots and takes off running for the lake. The plapping of river elf feet is the last sign of him before he dives off the ledge and into the lake. </p>
<img src="../Images/03_1_Summer_plapplapplap.png">
<p>Hector snarls and draws his falchion as he rushes Barrabus. There's a hum of magic energy as he swings the heavy blade at Barrabus. </p>
<p>Barrabus stepped sideways, letting Hector's swing pass right by his arm, and then rolled away from him, and continued his dash towards the lake. He stopped at the edge of the wall, overlooking the long drop into the lake, and then turned back around to face Coyote, his heels half-over the edge of the drop. "Well, gentlemen and ladies, it has been a pleasure, but I'm afraid it is time for me to leave, prize in hand." He patted the guitar gently. "You've been a wonderful audience, and an excellent security force. Goodbye!"</p>
<p>And with that, Barrabus launched himself backwards off the wall, tucking the guitar and fiddlecase to his chest as he went.</p>
<p>Coyote rushes forward with magic swirling around his instrument, but Barrabus leaps before he can get a spell off. Coyote jogs up to the ledge then slows. He arrives just in time to see Barrabus splash into the water below.</p>
<p>Coyote strums a simple chord and tips his hat with a smirk, "Well played."</p>
<p>Shyrendora and Dave arrived moments ago. They peek around the door just in time to see Barrabus' exit, but they are still unnoticed.</p>
<p>"Get some boats out there!" Coyote yells, "Search the fort, they might not have been alone! And somebody check on the fucking pollo!"</p>
<hr/>
<h3>Shyrendora and Dave</h3>
<p>Having just witnessed the end of the battle of the bards, they’re still standing at the secret door, and have not yet been noticed by anyone.</p>
<img src="../Images/03_1_Summer_Sneakysneaks.gif">
<p>(Dave and Shy, both being hilariously sneaky, decide to just slip away instead of trying to push their luck further. They are able to escape without being detected, leaving all agents accounted for and mission complete.)</p>
<p class="center">-FIN-</p>

<?php
include "../footer.php";
include '../../settarget.php';
settarget("Blade",null,null,4);
echo getarrows("../../Events/03_0.php#jump","../../Events/03_0.php#jump");
echo goback();
?>
</body>