<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../../header.php'; ?>
<link rel="stylesheet" type="text/css" href="../style.css">
<body>

<h2>Fall, Year 1</h2>
<div style="overflow-x:hidden;">
    <table>
        <tr>
            <th>Stress</th>
            <td>Economic 2/4</td>
            <td>Morale 2/6</td>
            <td>Property 0/4</td>
            <td>Military 0/5</td>
        </tr>
        <tr>
            <th>Fate Points</th>
            <td>3/3 refresh</td>
            <td>0 bonus</td>
        </tr>
    </table>
</div>
<div style="overflow-x:hidden;">
    <p id="cline">ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc</p>
</div>
<p>A warm wind whips over the mountainside. It carries with it echoes of an unpleasant memory. Ash stings the nostrils, forcing memories of fire and carnage, of death and blood and rubble.  You could have gone the rest of your life... however little left there may be of it... without ever experiencing that rancid smell again, and been all the happier for it.</p>
<p>But the gods do not write history to be happy.</p>
<p>You are <b>Esteemed Ledret Blakenova</b>, and you are dying.</p>
<p>Not quickly, mind you.  After all, everyone... or, at least, most everyone... is dying little by little each day.  For you, however, it is a slightly more imminent consideration.</p>
<p>You are Five hundred and Sixty Six years old as of last month, and that officially means you are too old for this poppycock.  It also means you are old enough to still use words like "poppycock". Before you lies a fallow field, once lush and filled with delicious Cliff Rye. Though it is not yet the harvest season, before too long you had anticipated once again being able to enjoy the hearty delights of a fine rye mash, seasoned with salt and just a pinch of aluminum for bite.  However, your dreams of future repast are sorely endangered by the conflagration that is before you.</p>
<br/>
<p>The whole field, near the entirety of this carefully cultivated plateau, is ablaze, carrying sickly scented memories into the air.  This is not the first field you have seen burning like this;  from what you are presently hearing, it may not be the last.  You have tried with all your considerable mental prowess to understand why this keeps happening.  Perhaps this time, it will stick properly.</p>
<p id="Esteemed">"Young one, perhaps you could explain to me, once more, why this continues to happen.  As I recall, I was to be consulted before such drastic measures were to be taken again.  I know I may be old, but I do not easily forget something of such import to our wellbeing.  Already, you have burned a full fourth of this years Cliff Rye. Were you not the one telling me that we could ill afford any further loss?"</p>
<p>To your pride, your voice is one of the few things about you that is still strong, still potent.  It never wavers, never stutters.  It has been your greatest weapon.  Well, apart from Precious Miigra.  You take a moment to scratch behind her ear.  She nuzzles into your palm, affectionately.</p>
<p>Your attention wavered.  You look back to the young man, your eye drawn to the curve of his brow, the dilation of his eyes.  He is angry.  He is always angry.  He is just-barely-not-shouting at you again, speaking to you of blights and disease as if you were a foundling merely ten years old.  He is attempting to remain just barely over the line of propriety when speaking to you.  He is failing.</p>
<p>What was his name again?  Oh yes.  It was...</p>
<hr/>
<p>You are <b>Bakshish Renyan Elematich</b>, First Among Scholars, Seeker of Forgotten Truths, Mender of Fallen Tomes, and you are about to lose your fucking mind.  </p>
<p>You guess you don't have enough on your plate! Nevermind that your project to collate the remaining available traits within the Samra has been put on hold for weeks now, never mind that you haven't looked at the rubbings recovered from the Eastern Commune in months, and never mind that you are <i>right this fucking minute</i> trying to do whatever is necessary to safeguard the last of an ancient, irreplaceable foodstuff, no! No! The single most important godsdammned task you apparently need to address right fucking now is explaining for the <br>THIRD<br>THROAT-SLITTING<br>TIME<br>why this particular blight is far, FAR more virulent than any this ancient fossil has seen before, and why her repeated insistence that you merely have the "Drusus purify the fields" <i>isn't going to fucking work</i>!  Not the least of which reasons being, as your own investigations have discovered, that the Drusus bloodline may not have sufficient potency to even continue to the Next Generation!  And that's if you fucking get to the Next Generation! Which you probably won't, because all the Cliff Rye is gonna die, and the seed vaults are empty, and the last living specimens currently consist of about twenty fields spread across the mountainside, and if, IF, this has finally done it and you've finally contained the spread of this insidious disease, you're probably still going to go hungry this winter, and <i>that is currently the best case scenario</i>.</p>
<p>You raise your hands to your temples, rubbing the left ones sunwise, and the right ones counter-sunwise.  As you do, you peek between your squinted eyes at the Esteemed.  Oh, good, she's frowning again.  Sure, disapprove more, you wrinkled old prune.  No matter what, you're gonna keep her from killing everyone else, even if it means killing her.</p>
<p>You take a deep breath, eyeing that ox of hers warily.</p>
<p id="First">"You see, Esteemed, the simple fact of the matter is that we really cannot, and I insist that this is a <i>Cannot</i>, not a Should not or a Might not or even a Probably Will not, we <i>Cannot</i> take any risks with what remains of this strain.  When we planted this years crop, we used every last ounce of the seed vault, hoping to capitalize on the mild winter we were in.  <b>Yes</b>, that was my idea as well, and in my defense, I was <i>completely correct</i> about how bountiful that weather made the harvest.  But no one, and I mean not a single entity here, could have predicted a Blight like this.  We have no records of a Blight like this.  We have no records of a Blight."</p>
<p>You pause for effect.  Rather than responding, the Esteemed just continues to <i>Look</i> at you in that way that she <i>Looks</i> at people.  In spite of yourself, you are somewhat unnerved.</p>
<p>After several more minutes of playing the staring game, you finally relent, closing your eyes and giving a small groan.  Let the crone have her petty victories, maybe it will make this next part easier.</p>
<p id="First">"Please, Esteemed.  No one wanted this.  No one, myself included, wanted it to come to this.  But now, after this catastrophe, the evidence is clear. <br/>Isolation is simply not an option any longer.<br/>We cannot fix this by ourselves.<br/>I <i>need </i>you to understand this.<br/>Please Esteemed.  Please.  For me.  For our people.  For the Path We Hope To Tread Once More.  If we do not do this, if we ignore this disaster, we will all die as surely as if the <span class="animal">Animals </span>had completed their task in the first place. "</p>
<p>That's it.  That's all you can say.  Any further would be begging.  You know for a fact that that won't work.  The only person who can save you, the only person who can save ALL of you, is sitting on an ox, probably thinking about food instead of listening to your impassioned request.  She has to convince herself.</p>
<p>Oh no.  There it is.  That look.  The wrinkle to the brow.  The furrow of the nose.  That's it.  You'll have to kill her.  You'll-</p>
<p id="Esteemed">"Very well.  I understand.  It is not what our Ancestors proscribed, but at this stage we are travelled so far from The Path that we are walking blind.  The fact that you have any glimmer of a solution means that you, at least, must have one eye remaining to you. "</p>
<p>-wha?</p>
<hr>
<p>You are the <b>Esteemed</b>, and gods preserve you all, but the child is right.  You were an imbecile to ever doubt it.  Given the revelations of the War, you wish that this would stop being such a surprise to you.</p>
<p id="Esteemed">"I cannot deny your logic.  You have thought this through.  You have weighed your options.  You may be young, but you are firm in your knowledge.  I had hoped that some new factum would arise, a new part of your equation, which would allow us to find another way... but if you are so certain, then let it be done. "</p>
<p>You lick your lips, and hope it appears dignified.  The ash is drying you.  You are so dry.  You may never be able to cry again.</p>
<p id="First">"Th- Thank you, Esteemed.  Of course I'll... "</p>
<p id="Esteemed">"You will do nothing more but what you must, for now.  Your first task is to contain this blaze.  Ensure that it can cause no harm.  Then, you will see to your other tasks.  This evening, when I am taking brew, you will make yourself present, bringing all your knowledge.  The Echo will be there as well. You will tell him everything he needs to know. "</p>
<p>You give Miigraa a small nudge, and she responds instantly, rising and turning in one smooth motion.  Behind you, you can hear the child begin to stutter and bluster.  No, it will do his pride no good to be denied an opportunity to execute his own directives, but you will not make yet one more foolish mistake.  Fie on his immaturity, he is one of the best and brightest that yet remain.  He must remain here.  Without his knowledge... you literally don't know what you would do if unfamiliar trouble arose.</p>
<p>A warm wind whips over the mountainside.  It carries a promise of death. A Path broken.  The End of Eschaton.</p>
<div style="overflow-x:hidden;">
    <p id="cline">ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc</p>
</div>
<ul>
    <li><b>Name:</b> Eschaton</li>
    <li><b>Description:</b> A grand commune, once reduced to rubble, but now tentatively being given new life at the hands of those who remain.  Nestled in the mountaintops, it gazes over the curve of The World; the Eye of the Mountain.</li>
    <li><b>Size: </b>Village</li>
    <li><b>Territory Aspects: </b>
        <ul>
            <li><i>Mountainous</i>: Eschaton is located on (not in) the Mountains</li>
        </ul>
    </li>
    <li><b>Settlement Aspects:</b>
        <ul>
            <li><i>Ruined Monastery: </i>The social and spiritual heart of the Crag Elves, Eschaton played host to numerous buildings from which decisions were made and progress was tallied.  Though work has begun to restore these vital centers, devastation is still the norm.</i></li>
            <li>Empty Slot</li>
        </ul>
    <li><b>Temporary Aspects:</b></li>
    <li><b>Garrison:</b> Currently full with the Memories of Shattered Hearth</li>
</ul>
<h3>Event: The Blight</h3>
<p><b>Duration: </b>Ongoing</p>
<p>A mysterious and ferocious blight has struck your ancient mountain crops. The same meticulous generations long cultivation that made them hardy and nutritious has also apparently made them quite vulnerable to this tragedy. Worse, it has so far resisted all attempts to contain it, both practical and magical.</p>
<p>The blight to your crops has been slowly eating away at your people's ability to function for some time. They have been failing to address it correctly for years, and as a result are losing vital resources. By this point, a lack of decision making has allowed this situation to reach a point where it is an existential threat to your people. If something isn't done, the crag elves will starve in less than a year.</p>
<p>This event causes one point of damage a turn to both the <b>Economy and Morale</b> tracks. Neither of these tracks can recover normally during this event. Worse, you have already suffered <b>two points of stress</b> to each track. Unless something is done, a collapse will happen by the end of Winter.</p>
<h2>Skill Usage</h2>
<div style="overflow-x:hidden;">
    <p id="cline">ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc</p>
</div>
<p>A mild wind whips over the mountainside.  It carries a variety of smells; there is that undercurrent of ash that has been there since this afternoon, but that's not really what you're interested in right now.  All around you, you can smell far more enticing scents; baking bread, grilling leeks, searing crageese; all in all, a panoply of enticing delights.  True, there's a bit less of it than you'd expect, but everyone's been having to tighten their belts a bit as of late, but that's just how it goes sometimes; it's been a rough couple seasons cropwise, as you understand, but that luck has got to turn around at some point; that's just how gambling works!  </p>
<p>Thankfully, you and yours have not had to go hungry; everyone appreciates how important it is to keep the Aggro fed and fit, especially after the unfortunate ruckus with the <span class="animal">Animals. </span> Speaking of which, you kind of hope that the reason you were summoned was because more of those mongrels were spotted... it's been far too long since you got to stretch your copious legs!</p>
<p>You are <b>Saltik Bergenich</b>, also known by your incredibly impressive, and deserved, monniker, Echo of Blood.  You take a moment to once again appreciate how great that name is; It's just got such a poetic ring to it!  It evokes the image of a boulder, tumbling down the mountainside, it's passage marked by its echoes... That boulder is you, and instead of echoes, it's blood!  In fact, you like it so much that you prefer it when people just call you "The Echo ".  It sounds <i>super cool</i>.</p>
<p>You approach your destination, a Andesite Pagoda aesthetically positioned on a tall outcropping of stone, giving it just enough elevation to see over the nearby rooftops and get a splendid view of Eschaton from all directions.  As you climb the steps, two or three at a time, you take a moment to make sure you strike an imposing figure before you crest the top; you shoulder your Stonebreaker with casual ease and place your other hand on your hip, generating a good swagger.  That should do the trick! </p>
<p>Ah, there we are! The Esteemed Elpahka, and her funny little ox. And also... Oh.  Him.  Hmph.  You had thought this call might be fun.  Probably not with The First here.  He's always got such a buzzard in his breakfast.  Even now, you can see him Sneering at you, the way he Sneers at people.  His partially   shaved head, his thin eyebrows, his sharp nose, his pointed chin, his underdeveloped muscles (which that overly-fancy robe of his does little to conceal)... everything about him just shouts sharp, sharp, boney, sharp.  His features, his tongue, his attitude... a thoroughly unpleasant person.  But oh well.  May as well power through.  You point your smile at the Esteemed, and perform a small bow.</p>
<p id="Echo">"Esteemed, I have come as requested! I thank you for inviting me to your brew table.  How can I be of service to you? Have we more enemies to dispatch? "</p>
<hr>
<p>You are once again The <b>First</b>, and you probably shouldn't be grinding your teeth like that.  Still, it's hard not to when this self-important walking pillar is around.   Ancestors, there's so much you hate about him; even the way he <i>looks</i> sets you off.  That ridiculously high brow ridge and big, bushy eyebrows that make the top of his head look practically flat... an effect that is not helped by his dumb <i>haircut</i>, having shaved the entire top of his head but leaving his side hair grow down to past shoulder length, looking for all the world like dark green vines hanging from the sides of a plateau.  Then there's his flat nose, his big eyes, that big mouth of his that <i>always</i> looks like he's about to laugh at you, that obscenely jutting chin... and to top it all of, he's so swollen with grotesque musculature that he doesn't actually <i>have</i> a neck; instead, it looks like he's got a hill that his head rests on top of. Yes, yes, you've got a lot of muscles, we all noticed! How couldn't we, when you wear armor a size too small just to make sure you can show it off, you troglodyte!?  Too bad you also decided to fill your head with them too, otherwise maybe you could tie your footwraps properly and not wear those disgusting, vulgar boots everywhere you go!</p>
<p>Oh, dammit, you've missed whatever conversation they were having entirely.  Well, little lost, it was probably nothing more than pointless pleasantry and ritual obeisance.  The Esteemed just loves her ritual obeisance. </p>
<p>While the two of them are sunk deep in their niceties, you prepare yourself for the coming trial with a little bit of legerdemain.  Working quickly, you sneak a swig of your Scholar's Little Helper, one of a number of reverse-engineered tinctures from the odd assortment of concoctions brought back from the lowlands.  You close your eyes, feeling the miraculous fluid ease your headache, calm your nerves, and stopper the spigot of hatred you have for bumbling oafs and senile cretins.  You even find it in yourself to smile, even if it is only politely. </p>
<p id="Esteemed">"...in any case, I believe it would be best if you were to hear the fundamentals of this endeavor from the one who so espoused it's need.  First Scholar, if you would, please inform The Echo of what it is you hope to achieve by travelling beyond the boundaries of Eschaton? "</p>
<p id="First">"Of course, Esteemed.  While the benefits are potentially multitudinous... "</p>
<p>Wait, no, blank stares.  Try again.</p>
<p id="First">"...pardon me.  While there are many benefits I hope to achieve, the most immediate are to address our current agricultural problem.  The simple fact of the matter is that, in spite of all the research done so far, the origin of the Blight and how it continues to plague our most essential crops is unknown.  We have exhausted nearly all avenues of research, apart from those of a more... Esoteric leaning.  There are some promising avenues there, however; it is possible that we have been misidentifying a Natural blight for one which has an Occult origin..  Indeed, since we cannot find any natural explanation, we must now focus our efforts on... "</p>
<p id="Esteemed">"We trust you to guide the associated capabilities of all the Bakshish, First Scholar.  You need not justify your actions in that regard.  If, instead, you could focus on this Expedition? "</p>
<p>dontgrindyourteethdontgrindyourteethdontgrindyourteethdontgrindyourteeth</p>
<p id="First">"Yes.  Very well.  To specifics.  Echo! It was the decision of the Esteemed, <small>at my recommendation,</small> that you should collect a force of Aggro whom are most skilled in scouting and natural lore, and go on an expedition to nearby terrains, both in the nearby ranges where our people once flourished, as well as in the Lowlands, where only you and yours have significant experience in treading.  The reason for this expedition is twofold.  First, and I will put this simply as possible, we must try to find new farmland for our crops.  One of our theories is that the blight may be bound locationally, either in the soil, or to Eschaton itself.  We can test this, and hopefully to our immediate benefit, by finding new outcroppings and plateaus with the ideal conditions for growing these crops.  We may even be fortunate to find other native flora capable of growing in mountainous conditions, which we could begin to cultivate.</p>
<p id="First">As for the Lowlands, well, that is a proposition which is both riskier, and may be more rewarding.  You yourself attested to the fact that the Lowlands were often congested with vegetation, a true embarrassment of greenery.  My hope is that by travelling there, you may be able to find readily available sources of food which we could exploit, even temporarily, to feed our people until this issue can be resolved. "</p>
<p>The buffoon nods, his sickening neck muscles bulging with each bob. </p>
<p id="Echo">"Sounds good! There were a lot of veggies and critters down there, some of them were even quite delicious. "</p>
<p>You shudder internally.  You still cannot believe that this oaf manages to put his tunic on the right way each morning, much less was capable of achieving such great deeds as to be <i>Named</i>.  That said, if you're being totally honest with yourself(something that has an annoying tendency to crop up when you're otherwise enjoying your focusing tonics), there must be more to him than the obvious, well, <i>nothing</i>, given the Esteemed's faith in his abilities.  Look at her, so insufferably calm in the face of this calamity.  What does she know that you don't?  What wisdom is she graced with that eludes you?  How can she possibly know that Echo is the appropriate choice for this?</p>
<hr>
<p>You are the <b>Esteemed</b>, and you fervently hope that by the grace of all the Ancestors, you are making the appropriate choice.  The dreadful calculus behind it is simple; Of all of the bloodlines who still survive in Eschaton, the Aggro contribute the least in times of peace; putting them to work elsewhere kills two crows with a single stone, displacing their nutritional needs to forage on the road, and putting them to what is hopefully good use.  You do not know if The First truly understands the difficulty of his suggested course of action;  Even with <i>The Tome</i>, your people's knowledge of Lowland herbology and hunting was sorely limited.  </p>
<p>...Lowland hunting.  Hrm.</p>
<p>The precepts set within <i>The Tome</i> levied strict restrictions on the practice of hunting in the communes; recognition of the fragile nature of fauna at this level, and how easily this natural resource could be depleted.  But if what The First says is true... if the long isolation of your people is truly over... then is it not time to also reconsider other old wisdoms?  The game, foul, and even fish that reside in the climes around Eschaton would make for a considerable supplemental source of food; not a permanent solution, no, but perhaps enough to stave off disaster.</p>
<p>Very well.  You have decided it.  Thus, it will be so.  You interrupt whatever parley is occurring without a second thought.  It cannot be as important as this decision.</p>
<p id="Esteemed">"Thank you, First Scholar.  Echo, you now know what it is you must do.  Gather your most keeneyed scouts, your most nimble trailblazers.  You will go forth from Eschaton, and find a solution to our ills.<br>You may go.  Return when you have achieved your task. "</p>
<p>The enormous Aggro rises from his resting place, then rises some more.  It always shocks you to see how enormous he is.  Even for a people dedicated to the path of Physical Perfection, he is a paragon, a small taste of what you and all your forebears have strived to create.  He leaves your table, the solid stone quaking beneath his footsteps.</p>
<p>And now, for the other one.</p>
<p id="Esteemed">And as for you, First. "</p>
<p>You level your gaze at him.  He seems unusually composed.  Perhaps he is finally learning to master himself.</p>
<p id="Esteemed">"You may go as well.  You will continue your studies into the nature of this Blight.  Before you do so, however, locate The Layer.  Tell her I wish to give her an assignment as well.  I will see her at her earliest convenience. "</p>
<p>No, perhaps not.  There is the petulant curl to his lips.  It is unfortunate that one so clever must also be so young.  </p>
<p id="First">"Of course, Esteemed.  As you wish.  I wish you good health and fortune on the enormous volume of tasks plaguing you. "</p>
<p>He rises from his spot as well, his soft feet barely making a sound on the floor. </p>
<p>Your brew has gone cold.  Excellent.  You prefer it that way.</p>
<hr>
<p>The sun dips low, receding into the horizon.  The clouds parted enough for you to watch it descend.  Soon, the only light in Eschaton will be by the ancient lanterns, long ago lit by powerful magics, still guttering heatless flame to this day.  That art, at least, has not been lost to you. <i>Yet</i>, you think.</p>
<p>The flagstones leading up to the Esteemed's pagoda flow beneath your feet.  With every step, you can feel their strength.  They were among the first things repaired when Eschaton was reclaimed.  Every Crag knows the importance of a well kept path.</p>
<p>You are <b>Slabal Nanockova</b>, simple craftself, architect, and, evidently, <i>The Layer of The Path</i>.  You still don't really understand why.  Not that you question your work, obviously.  You've proven to yourself many times now that you can confidently state that your work is of pretty adequate quality.  Of course, there's always room for improvement.  But it does it's job well, others seem to be happy with it.  No, it's more that being named such apparently comes with a lot of extra baggage that you really haven't quite gotten a handle on yet.   Like all the management.   The other Onagi coming to you for orders.  Or asking you to verify their work.  Or wanting you to "sign off " on things.  Or the delegation.  You can confidently state that you have no idea how to delegate.  If something needs to be done, you'd prefer to do it.</p>
<p>Oh well.  It's another skill to master.  It might be harder than the other skills, but you have plenty of time to work on it.  Good things come to those who tread the path.</p>
<p>The steps up to the Esteemed's pagoda are a far cry from the paths you walked upon.  The stone is sensitive.  Groaning.  Every time you come here, you have to resist the urge to begin working on it.  That happened the first time.  She told you later that it wasn't as important as other things.  She was correct, of course.  She is the Esteemed. You get the feeling that she was embarrassed for you.  It wasn't necessary, but you can appreciate the gesture, on a logical level.</p>
<p>Ah, speaking of.  She's still on that Ox of hers.  Her eyes are closed.  If she were a crageese, or a rockhawk, you'd think her asleep. She isn't. You still think it would be a little safer if you could give her some kind of saddle to use.  She refuses.  Oh well.  She is the Esteemed.  But after all your talks, it has become easier to think of her as Ledret.  You're glad for that.  It seems to make her happy when you call her by her birth name.  You get the feeling that sometimes she feels lonely.  You can understand that.</p>
<p id="Slabal">"I'm here, Ledret.  I know I have made you wait.  I hope you don't feel annoyed by that. "</p>
<p>It's true.  Everything you've ever said is true.  You understand why others don't, sometimes. You're glad that you've manage to avoid being put in that position.  <i>So far</i>, you think.</p>
<p>The esteemed cracks an eye.  You can tell she's having difficulty seeing you.  Her cataracts are growing back.  She'll probably heal them when they get in the way too much.   At least she has borne most of the other elements of aging with some grace.  Her hair is thin and white, but tied up in a topknot like it is, it's difficult to tell.  Her face, hands, feet, and presumably more are wrinkled, but it is an even, aesthetic wrinkle.  It reminds you of dried dates.  The copper bangles on her wrists and ankles show how much muscle she has lost, however.  They dangle loosely.  Sometimes, she struggles to lift them.</p>
<p>Her lips part as she speaks.  They are dry, chapped.  They reveal a mouth devoid of teeth.  No one knows how to regrow teeth anymore.</p>
<p id="Esteemed">"Thank you for coming, Slabal.  I know how your duties keep you. I am not annoyed.  Instead, I am afraid I must add to them. "</p>
<p>She gestures to one of the pillows.  You actually prefer standing, but still sit anyway.  It's polite.</p>
<p id="Esteemed">"I am afraid that what I have been hoping to avoid, has instead come to pass.  Too many straws, and now the ox's back will bear no more. " </p>
<p>You watch as she pats her ox.  You don't know if the ox appreciates it.</p>
<p id="Esteemed">"I have tried for so long to keep to the Path that our ancestors tread;  even without the guidance of <i>The Tome</i>, there are so many traditions I still wished to honor.  But... the gods have not favored tradition.  Indeed, they seem set on disrupting it.  "</p>
<p>Her gaze drifts down, staring at the center of her table.  Her breathing is steady. You wonder for a moment if she wants you to speak now.  You're not sure what to say, however.  You don't really understand much about 'the gods', per se.  She seems to like to blame them when things go awry.  She seems to imply they are challenging her, testing your people with trials and woes.  You don't really agree with that.  The cause of your people's woes seems pretty obvious to you.  The <span class="animal">Animals. </span>Maybe you should point that out.  Before you can, however, she speaks again.</p>
<p id="Esteemed">"The First has made it clear.  If we try to recover using only what was left to us by our ancestors, we are doomed.  We may be doomed, regardless, for his path to recovery requires us to break with tradition.   We must travel forth from the mountains.  We must further expose ourselves to The World, in search of a solution to this Blight, and to other shortfalls.  I have conceded to this.  However, a thought struck me.  One which may help ease our people's suffering.  For untold generations, we have carefully monitored our consumption of fowl and game found in the wilds around our home.  It was as our Ancestors decreed, to ensure that this vital supplement would not be lost to misuse.  But if we are to find succor further from home anyway, then may we not exploit this careful preservation to alleviate the hunger that stalks Eschaton? "</p>
<p>You nod your head.  You're familiar with that hunger.  To be honest, you knew of it before The Blight struck.  You have a tendency to get... focused.  Sometimes you forget basic things.  You understand if others find it more concerning.  </p>
<p id="Esteemed">"Therefore, I have a task for you and the Onagi.  I trust you to pass my orders to them.  We need more hunting tools. Bows, spears, fish hooks, nets.  Created in sufficient supply, the Samra will be able to forage and hunt freely; Though only a few of  bloodlines are skilled in the hunt, I believe the others will adapt, as the Onagi have, to changing situations.  After all, a failed hunt for one merely leaves a successful hunt for another. "</p>
<p>You stop nodding.  You're not sure about that logic.  You can't come up with a specific counter to it just yet, but it seems a bit... optimistic.  On the other hand, you also can't come up with a reason it would hurt to try.  The raw materials needed are fairly abundant; pretty much just sticks and stones.  Some onagi might balk at such simple work, but most would understand the logic.  Those that would balk, though... you feel some tension in your gut.  They would complain.  Question.  Confront.  Not really something you are looking forward to.</p>
<p>Your gaze sweeps over Eschaton at night, illuminated by those ancient lanterns.  Over the temples, the gardens, the granaries, the archives... so many years of work rebuilding what was lost.  And yet, so many of them still lay empty, unused, untended; beautiful, but meaningless, neglected, already decaying from disuse.  Few of the prideful onagi considered that an issue.  They would be needed someday.  If they decayed, then they could be rebuilt yet again.  The same temple could rise and fall a hundred times, and still be as beautiful the hundred-and-first.</p>
<p>...But <i>why</i> is it beautiful?  Why now, with so few to enjoy it?  The ancestors needed its beauty, a reminder of their inheritance, a reminder of their goal.  But now... now you need something else.  Something other than beauty.  Beauty will not fill a belly. </p><p>...You have an idea.  It's Unorthodox.  Untested.  Unproven.  But it will give the prideful, skilled onagi a challenge.  One which should keep them contented.  One which may even help the current concerns.  And the word of the Esteemed would go a long way to motivating them, without the need for any further cajoling.</p>
<p id="Slabal">"I will see to your orders immediately, Ledret.  It is Unorthodox, but these are different times.  We will need Unorthodox ideas.  And, if you will tolerate it, I believe I have another... "</p>
<p>A mild wind whips over the mountainside. It carries a promise of Survival. Of Adaptation.  Of a Newly Laid Path.</p>
<div style="overflow-x:hidden;">
    <p id="cline">ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc</p>
</div>
<p><b>Economic</b>: It has become clear that we can no longer rely on agriculture until we discover the root of this disease.  A temporary measure may be achievable by exploiting the fish, fowl, and game present on and around the mountain; to do so, the tools of such craft will need to be made in surplus.</p>
<p>Attempting to utilize the <b>Infrastructure(Investment)</b> skill to grant Eschaton the <b>Sticks and Stones</b> aspect, representing a build up of knives, spears, slings, fishhooks, shortbows, and other implements of hunting.</p>
<p>Dice used: 2 Ability, 1 Proficiency.  Result(ROLL0001093): 2 advantage, 0 successes, 1 triumphs</p>
<p><b>Political</b>: <i>Though our years of work in the Ruins of Eschaton have allowed us to recover many of the beautiful parks and pagodas enjoyed by our ancestors, our numbers are so few that many of these structures lie unused.  They must be put to better purpose; one cannot eat beauty.</i></p>
<p>Attempting to utilize the <b>Recovery(Taxation)</b> skill to move two points of stress from the Economic Track to the Property Track, with no attempt to remove one, representing converting numerous public works into victory gardens.  As this is vital to buy time, all resources are provided, spending a fate point to Invoke the aspect <b><i>Our Legacy is Set in Stone</i></b>, as this plan involves using the buildings of our ancestors in our time of need.  This Invocation is to add a Proficiency die.</p>
<p>Dice used: 1 Ability, 2 Proficiency. Result(ROLL0001094): 1 advantage, 3 successes, 0 triumphs</p>
<p><b>Military: </b><i>Ultimately, the real solution for these ills is most likely to come from outside, either from readily-available forage and game found in the lowlands, or in new mountainsides free from the blight.  For now, Echo is hedging his bets on the lowlands; those swamps always seemed to be packed with vegetation and critters.</i></p>
<p>Attempting to utilize the <b>Reconnaissance(Pathfinders)</b> Skill in a single territory to the SE of Eschaton, marked with an empty yellow circle.</p>
<p>Dice used: 1 Ability.  Result(ROLL0001095): 1 advantage, 1 successes, 0 triumphs</p>
<p><b>Mental:</b>The Blight has been present for many years, resisting all conventional attempts to truly eradicate it.  Perhaps it is not merely a normal disease...</p>
<p>Attempting to utilize the <b>Mysticism(Research)</b> Skill to investigate the potential origins of The Blight as something other than a normal disease; perhaps it is a curse, a haunt, a monster, or something else entirely?</p>
<p>Dice used: 2 Ability.  Result(ROLL0001096):3 advantage, 0 successes, 0 triumphs</p>
<h3>End of Turn </h3>
<hr>
<h2>Fall, Year 1 Results</h2>
<p><b>Economic- </b>To their credit, the crag elves are <i>very</i> enthusiastic. Just... maybe not in the most productive way this time. They attack their assignment of acquiring hunting implements with great gusto, and throw themselves into the task. However, they end up doing what they always do. They read the texts they have always read, and do what they always done. You end up with only a few spears, slings, and fishooks but a great deal of bows. In fact, the same bows you <i>always</i> get. Big, heavy, powerful warbows. Which are completely inadequate for hunting game, unless someone finds a caribou.</p>
<p>While you did fail to create the <i>sticks and stones</i> attributes, you now have enough warbows lying around to accessorize a unit with +2 strength bonus composite longbows. They're quite nice warbows, but you're still hungry.</p>
<p><b>Political</b>- Mercifully, the crag elves seem to have much more of a cultural understanding for small scale farming than for hunting. At first, there is a great outcry at turning some of the larger pavilions and amphitheaters into gardens, but the rumbling of empty bellies quickly drowns them out. It's a difficult job, and even more difficult to keep the blight out. In a stroke of either genius or luck, the distributed nature of the victory gardens actually provides some resistance against the blight. If a crop catches the blight, it only immediately spreads to a small portion of the produce.</p>
<p>The victory gardens won't be enough to feed your people long term, but they do work. The food they produce is enough to keep many off the ragged edge of starvation, and indeed preserve some of the rare ancestral grains from the blight. It has bought you time, if nothing else. You have enough supplies to last the winter at least, and the will of the crag elves should last through the season as well.</p>
<p><i>You have successfully moved 2 points of stress to the property track, however the event is still ongoing and your economy and morale tracks are still taking stress.</i></p> 
<p><b>Military- </b>Leading the crag elves is turning out to be quite frustrating. The pathfinders return, exactly on schedule and in good order. They present you with a map that is... completely inadequate. It's not... <i>wrong</i>, it just doesn't have what you need to actually understand what is in an area. They apparently noted gross terrain features, general information about the area, and things that they encountered along the way but as far as the quality of the soil? Amount of irrigation? Suitability for farming? Exact, carefully measured mapping? Not so much.</p> 
<p>Well... at least no one got hurt.</p> 
<p><b>Mental-</b> Your wisest elves mediate, consult the few remaining texts, chant their mantras, use what little incense they have remaining, and attempt to discern the nature of this cursed blight. Unfortunately, little illumination greets them. Their meditations on the nature of this tragedy simply leave them... hungry. It would almost feel better if they detected the touch of some foul magic, or the presence of some interloping outsider. At least that would mean there's a purpose to it. Alas, nothing - one way or another. Still, the sheer act of spending time in mediation and carefully considering the nature of the blight was not wasted time. Your wisest elves have spent weeks doing nothing but consider the nature of the blight itself, and perhaps how they can withstand it. Your next mental action, whatever it is, will receive a <b>bonus die</b>.</p> 
<h3>Event: The Blight</h3>
<p><b>Status: Ongoing</b></p>  
<p>It has been a frustrating season for the crag elves. Crops continue to fail. Food stores continue to get lower. The crag elves, however, are not an easily defeated people. They withstand, for now. Their bodies are strong, their dedication to their ways is resolute. At the very least, the victory garden project is a success and has staved off the bitter end just a little while longer. The blight itself, however, continues to not care...</p> 
<p>You continue to suffer the effects of the blight, and take one stress to both economy and morale.</p>

<h3 id="jump">Roleplay Event 01.2: <a href="../Bonus/0_A Seeker to Eschaton.php" alt="linked here because unreadable gibberish above.">A Seeker to Eschaton</a></h3>

    <?php
    include '../../settarget.php'; 
    settarget("Crag",3,0,0);
    include '../footer.php';
    echo getarrows("01_1_Crag.php","01_3_Crag.php");
    setlast("Year/01_2_Crag.php");
    ?>
</body>
