<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../../header.php'; ?>
    <link rel="stylesheet" type="text/css" href="../style.css">
    <title>Spring, year 1</title>
</head>
<body>
    <h2>Spring, Year 1</h2>
    <table width="100%">
        <tr>
            <th>Stress</th>
            <td>Economic 2/4</td>
            <td>Morale 4/6</td>
            <td>Property 1/4</td>
            <td>Military 0/5</td>
        </tr>
        <tr>
            <th>Fate Points</th>
            <td>1/3 refresh</td>
            <td>0 bonus</td>
        </tr>
    </table>
    <div style="overflow-x:hidden;">
        <p id="cline">ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc</p>
    </div>
    <p>A wet wind blows over the mountainside.  It feels sticky, cloying.  Although to your memory it has never bothered you before, now, it prompts you to actually latch the shutters in your rectory.  Small comforts. </p>
    <p>You wish you could blame the clammy wind on your trembling.  You wish you could blame it on your diet, which is currently going through nutrition backlash.  You even wish you could blame it on infirmity.  At least the last of these would only impact you. </p>
    <p id="Sivens">To find the Truth, start with a block of common knowledge, and then will away all the optimism.  Then chip away all the hope.  Then file away all the faith.  What is left is Truth, raw, sharp, painful. </p>
    <p>The words of Instructor Sivens echo in your head.  Good old Sivens.  What a callous turd.  Still, his curmudgeonly adage rings true this time.  You let out a shaky breath.  You stare at the riot you call a desk. </p>
    <p>The numbers, the maps, the tables all stare back, cruelly.  Your quest for fertile ground was pointless.  You glance over to the recovered parchment, it's cryptic message.  Even if you had found what you needed there, how could you exploit it knowing that death swifter than any hunger may stalk the territory?  Granted, if you had found fertile ground there, you'd probably risk it, but... for the promise of minerals to a starving people?  A hard sell indeed. </p>
    <p>You look at your other calculations.  The picture they paint is a grim one, and one with very few choices... none of them both dependable and palatable.  Some of them are neither. And all of them are your responsibility to propose.  If only there was a way to divine which would at least let the Crag survive. </p>
    <p>Here's another wish; you wish you weren't <b>The First</b> right now.   </p>
    <p>So, for a little while at least, you won't be. </p>
    <hr>
    <p>You are <b>The Layer</b>, and if you were anyone else, you'd probably be pretty excited right now.  Instead, you're just sort of faintly satisfied. </p>
    <p>You gaze down into the first of the quartzhouses, seeing tall, healthy stalks of cliff rye... possibly for the first time in years.  Though not the season for it, the controlled nature of the quartzhouses allowed you to go ahead and plant the valuable staple, as well as several other precious heirloom crops of the First Generation.  You had hoped that, like the Temple Gardens, these crops would eventually help to ease the food woes a bit, but the Elpahka's orders are clear; these crops are to be allowed to go to seed, to help restore the nearly depleted seed reserves.  You aren't sure about that logic.  What would be the point of seed reserves if there are no living souls to plant them?  </p>
    <p>Oh well.  There's probably a good reason.  At least, you sort of expect there should be.  You'd think it odd that Ledret would support that ruling otherwise.   </p>
    <p>You look over at her.  She hasn't touched her brew.  Indeed, from what you've heard, she hasn't been taking much of anything.  For the last several weeks, she's been subsisting entirely off of enchanted berries; one a day.  You understand many of the Elpahka and Bakshish and even some of your own Onagi have been resorting to such, trading magical power for survival.  While that's a fair trade for now, you know that it cannot be relied on indefinitely; even with all their magics put together, they could not feed even a tenth of Eschaton's population, and even then, few know what the consequences of living off such magical sustenance would be in the long term.  Still, they are doing what they can to make more available for others.  It is admirable, you suppose.  However, it is not doing the Esteemed any favors.  Every day she seems sallower, weaker.  You don't know how to repair that. </p>
    <p>She opens her mouth.  She tries to speak, but the first words come out dry, cracked.  She coughs. </p><p>You're surprised at how much that small weakness impacts you. </p>
    <p id="Esteemed">"Slabal.  The others will arrive soon.  Whatever may be said or heard once they do, I want you to know that of all I have called on to advise me, you have continually shown the greatest wisdom, the keenest ingenuity.  I value your opinion, your advice. So, have you thought on my question?" </p>
    <p>Ah.  That.  You got distracted.  This view of Eschaton is distracting.  Every time you look out, you see more work to be done.   </p>
    <p id="Slabal">"No, Ledret, I did not.  I was distracted by worldly matters.  However, I'm afraid I am ill suited to answer the question.  The past is as it is.  To consider a single change to it is to unravel cause, and effect, and thus render all other assumptions moot.  All I can tell you is this; if at any point I had thought of better choices, better ways, I would have told you, suggested them.  I do not think you would have been so proudful as to reject them out of hand.  I cannot claim to always follow your wisdom.  But I can confidently state that that is because you are better suited to wisdom than I." </p>
    <p>She doesn't react.  You hope that your response is helpful.  All you know is that it's the truth.  Unfortunately, the truth is not always helpful. </p>
    <p>The pagoda is silent once more.  It is quiet enough that you don't hear, but feel, the heavy tread of boots ascending.  Then you can hear the tortured click of that stone that you still need to repair.  Either that's all the Elpahka together, or... </p>
    <hr>
    <p>You ascend the stairs, two steps at a time, like usual.  However, there is no pep in your step today.  Too much as of late has conspired to ruin your mood. </p>
    <p>You are <b>Echo</b>.  Without any hesitation, you have thrown yourself into the fangs and maws of the <span class="animal">Animals</span>, and spilled so much of your <i>own</i> blood that their foul taint had no chance of taking root.  With nary a moment's thought, you have barrelled into creatures one and a half times your size, with the only consideration being how it would taste once you triumphed over it.  You cannot count the number of times that you have been threatened with death, dismemberment, infirmity, and pain, and faced it all without fear. </p>
    <p>Unfortunately for your mood, as you approach the pagoda, your gut is wrenched with trepidation. </p>
    <p>It is not additional danger you fear.  No, what you fear is that, for the first time in your longish life, you are forced to consider that the Esteemed, who is about to decide your fate, and the fate of all Crag, may not actually be all that wise. </p>
    <p>There had always been hints of it, in retrospect; how she dithered on The Blight, how she tolerated The First's casual disrespect; you shudder, remembering his sharp, acerbic tongue during your recent journey. You are immensely thankful that your Stalker, Embebi, handled most of the back-and-forth on that far-too-long expedition, but even then you found yourself all too often at the wrong end of one of his tantrums. But all that paled in comparison to what you have learned; the moment that opened your eyes was the report from a small number of Euclast who encountered an Outsider on patrol. </p>
    <p>She parlayed with them.  Bargained with them.  Let her decisions be <i>rejected </i>by them.  </p>
    <p>And, in the end, she <i>trusted a lowlander</i> and <i>let them go back to their lowlands</i>. </p>
    <p>You were never devout in your study of <i>The Tome</i>, but as one of the Aggro, you knew good and well that you and the Euclast' descent into the Lowlands was one of raw necessity, and one which was constantly fraught with the peril of discovery.  You and yours had to be constantly on guard, from both others and yourselves, lest you accidentally let slip where your homeland lay.  It was better to die than to loose your tongue, for already once discovery had led to the greatest tragedy ever recorded... the LAST tragedy ever recorded in <i>The Tome</i>. </p>
    <p>And, in a single day, in a single <i>hour</i>, she overturned that ruling, and made all you and your sacrifices pointless. </p>
    <p>That is not an act of Wisdom.  It is not even an act of Madness.  It is an act of Foolish Carelessness.   </p>
    <p>The kind typical of the Infirm. </p>
    <p>You are not looking forward to this meeting.  You dread what you may have to do if your suspicions are confirmed. </p>
    <hr>
    <p>You are not looking forward to this meeting.  You dread what you may have to say if your suspicions are confirmed. </p>
    <p>Echo arrived.  Many, but not all, of the other Elpahka have arrived.  There were some whose duties were too precious to relieve, even for something as important as this. A smaller number of Bakshsish, the Heads of their Studies, were here as well.  Echo was also here, as well as the standard Pagoda Guards, to represent the Aggro's wisdom on the matter.  Of course, Slabal was here, as you had summoned her to arrive early.  You are glad you did.  Her confidence, her assertion that you deserve the title of <b>Esteemed</b> was critical for what was about to occur.  Now, you were only waiting on... </p>
    <p>Ah, there he is.  The sight is frustrating.  While you never approved of his cocksure attitude, seeing this hangdog posture is little better.  He's discarded his pretenses of martial pomp... save, strangely, for the kuthe at his side.  Still, even that concession does little to distract from his forlorn demeanor.  You fear you know what that entails. </p>
    <p>Still, even if the conclusion is foregone, the traditions must be upheld.  Though this is a tumultuous time, there is no cause to discard everything that makes you Crag.  You take a sip of your brew. It is cold. </p>
    <p id="Esteemed">"Wise ones, Hearts, Minds, Souls and Bodies of the Crag.  We are gathered in this trying time to hear, know, and seek Wise directions.  The Path is unclear.  The way ahead is clouded.  Through confluence, let us find The Path once more.  </p>
    <p id="Esteemed">Renyan, holder of the Keen Bloodname of Elemat, First Among Scholars.  Your knowledge is proven, your logic peerless.  Enlighten us with your findings." </p>
    <p>...You will grant the youth this; he is learning to master himself.  Gone is his sagging posture.  He is now truly The First Among Scholars. </p>
    <p id="First">"Esteemed Elpahka, and all assembled Wisdom... I bring Dire Tidings." </p>
    <p>Bold.  It is highly unusual to begin with such a baneful introduction.  You hope to the gods that it is an exaggeration.  </p>
    <p id="First">"Many of you will know, by now, of our findings of the last season.  The First Generation did not choose the location of Eschaton on a whim.  I had hoped to find more evidence of the mountain loam that we enjoy upon our slopes and plateaus.  So far... there is no such sign. </p>
    <p id="First">Worse tidings come from the fruits of my Associate's labors.  The Heads of many Studies have toiled night and day to discover the truth of the Blight, to uncover its weakness.  They have succeeded.  And they have found that it's weakness... is our demise. </p>
    <p id="First">The Blight lives in the soil.  It spreads itself keenly and eagerly, infecting any plant it touches.  The smallest clod, the tiniest strip of filth, is sufficient to carry the Blight to another doomed field.  Worst of all, while any plant lives in that soil, the Blight will continue to live.  Seedling, Shoot, or Stalk, it does not judge; it will take its toll, and live on.  In truth, our efforts to counteract our losses, harvesting earlier, planting soon after, constantly attempting to make up for the shortages of the last harvest, only exacerbated it's growth.  By now, the Blight may exist in all but our most carefully cultivated plots.  If it were not for the actions of the Onagi, inspired by Slabal, holder of the Inspired Bloodname of Nanock, The Layer of the Path, there may have been no uninfected crops remaining at all." </p>
    <p>...Odd, that.  It was not uncommon to recognize the accomplishments of others, but he named none of his Associates before naming Slabal.  You wonder why.  Still, this seems a good time to interject. </p>
    <p id="Esteemed">"A Dire Tiding indeed, First Among Scholars.  Tell me, with all that you have learned and seen, have the Bakshish devised a solution to this Blight?" </p>
    <p>He nods to you.  There is no trace of his arrogance now.  You can see the sorrow set upon him. </p>
    <p id="First">"The Blight has now taken a dreadful toll, and one that is impossible to ignore.  What I share with the Wisdom now, I ask that you keep in full confidence, for it's widespread knowledge could be a telling blow to the heart of our people.  <br/>
    Our agriculture... has utterly failed.  Our seed reserves are all but gone.  Even if we were to plant every last grain, even if all of it could be spared the Blight, we would not be able to feed our people.  Worse than that, to even attempt another harvest would only hasten our demise. </p>
    <p id="First">With all that we have discovered, we find that there is only one possible solution to the Blight. </p>
    <p id="First">We must immediately harvest or destroy all of the current crop of Snow Lentils.  We must render the soil devoid of plant life.  Indeed, we must poison it so no weed, no fungus, no plant at all may take root.  And we must leave our fields so poisoned for a full season. </p>
    <p id="First">Perhaps two." </p>
    <p>To say you are shocked is an understatement.  The gasps echoing in your Pagoda reveal how terrible this is.  Perhaps in the times before the Extermination, it would have been possible to let the fields lay fallow an entire season without trouble.  Perhaps even as soon as few years ago, it would have been possible to do so and still conceivably survive.  But now, already taxed to the brink?  It is a death sentence. </p>
    <p>It is the End of Eschaton. </p>
    <p>To your shame, you cannot compose yourself properly.  Too quickly, your mind is assaulted with images of wasting and famine.  Of Death.  Instead, it is another voice that rises to quiet the panicked murmur which was arising. </p>
    <p id="Slabal">"The situation is suboptimal.  With our reserves already so taxed, we could not expect to have enough to feed the population should we cut our current harvest short, let alone delay the next one, or even the one after that.  Even if we were to significantly expand the quartzhouses, which allow us to carefully screen for the Blight, I do not think we would make up the difference.  Have you found a solution to this shortage?" </p>
    <p>Blessed, precious Slabal.  Her voice was so cool, so collected.  A calming influence for a panicking people.  You can even see it in The First's eyes.  How he squares himself, not despondent, but... resigned. </p>
    <p>He takes a deep breath, steadies himself.  You can hear his voice shaking. </p>
    <p id="First">"I'm afraid there are no guarantees, but... we... <i>I</i> have devised a solution. </p>
    <p id="First">The first is to do as The Layer has suggested.  We must have more of these Quartzhouses.  I wish I could claim they were to feed our people... but, instead, they must be used to replace what we have lost.  Once the fields become usable once more, we will need the seeds and pulses from these safely contained planters to be able to produce a full harvest. </p>
    <p id="First">However, in this, we still face our ultimate shortage; usable soil.  While numerous enchantments exist to purify or enrich soil, these have so far proven useless against the Blight; we still do not fully understand why.  Instead, I will guide the Bakshish on studying <a href="https://www.google.com/url?q=https://www.d20pfsrd.com/magic-items/wondrous-items/a-b/bag-of-everlasting-dung/&amp;sa=D&amp;ust=1576645751306000">ways</a> of creating fresh, totally new soil, similar to how some of our greatest are able to create water, or even food.  This capability could be of immeasurable utility to the Crag people; although we find our local territories barren, if we had the ability to produce our own rich loam, then our only true limit becomes surface area! </p>
    <p id="First">...But, while a promising new capability, I cannot imagine this being developed quickly, or easily.  In truth, I can find no other workable solution to... to increase our... " </p>
    <p>He's faltering.  Shaking even.  You suddenly feel a deep wave of pity for the young man.  You know he is often arrogant, self assured, but this trial... it reveals just how mortal he is.  How mortal you all are. </p>
    <p>The gods plan for all of you, for Eschaton, for the Crag, is unknowable.  To think otherwise is the greatest hubris.  But the gods are known to guide.  Through portent, through vision. </p>
    <p>Even today, you wondered exactly why you decided to let the Traveller go.  It was unorthodox.  Possibly even foolish.  But now, in this moment, you know why.  After all, it is all things that The First said himself.   </p>
    <p>We cannot survive on our own.  He meant it to mean we would need to spread to the surrounding lands to find a solution.  But it could mean more. </p>
    <p>Now, he reveals that Eschaton can no longer provide for herself, no matter the struggle.  Shocking, but revelatory. This is why the Traveller came.  This is why you were moved to leniency. </p>
    <p>It is time to give your people Hope. </p>
    <p id="Esteemed">"I understand what you are saying, First Among Scholars.  It is an unfortunate reality.  Eschaton cannot provide for itself.  Not right now, and not for some time to come.  A trying trial indeed.  </p>
    <p id="Esteemed">But it is, indeed, a Trial.  And trials are meant to be passed, if one can prove themselves worthy.   </p>
    <p id="Esteemed">Wisdom of our People, hear my words.  As many of you are aware, a stranger came among our people.  A lowlander, but unmistakably Elven.  Many of you will have heard the stories of the Triumphant Aggro who descended into the Lowlands; how they met people there, unmistakably elven; degenerate elves, but our distant relations nonetheless.  In the times of the First Generation, of the generations past that, our ancestors knew that Elves such as these were not to be trusted, to be eschewed, and so the secrecy of our people, of The Path, was of the utmost importance, and in secrecy we thrived... but, to all our chagrin, we no longer live in such idyllic times </p>
    <p id="Esteemed">The Truths of the matter have changed.  Those who found us did cause us untold woe.  But these creatures were not our fellow elves.  They were <span class="animal">Animals</span>. Indeed, when the Aggro descended, these elves were not our enemies, did not seek to extinguish us, but fought a common purpose to ours, fought to protect themselves from Extermination, as we did.  And now, having met with one of these Lowlander elves, I believe the truth of it is clear. </p>
    <p id="Esteemed">The enemies of the First Generation are gone.  History has swallowed them, and in our seclusion, we escaped whatever calamity claimed them.  Now, The World is filled with brand new enemies, brand new horrors, ones which threaten not just us, but all of our Elven kin as well.  The gods have spoken, and we must respond; The Elven People have need of us, and we have need of them.  </p>
    <p id="Esteemed">In my discussion with the Traveller, I learned of a number of nearby encampments.  We will go to them, speak to them, and let them know that we exist; for now, until trust can be established, we will conceal the exact location of Eschaton, but we will barter with them.  Crag craft is fine, and we have plentiful resources, for the Bones of The World themselves shape to our will.  We will speak to them, trade with them, and through them, we shall alleviate our ills until our own lands become sufficient again, until we can become whole once more. </p>
    <p id="Esteemed">Through them, we may even learn once more of the long lost knowledges gained by the First Generation; we may relearn how the made <i>The Tome</i>.  We may reforge The Path, and alloyed by our newfound kin, it may be all the stronger." </p>
    <p>You have spoken true, and clear.  The way is certain.  The future, hopeful.  You open your eyes to look upon your Wisdom, the best of the Crag people. </p>
    <p>... </p>
    <p>Something is wrong.  You do not see hope.  You see fear.  Anxiety.  Anger.  Concern. </p>
    <p>Pity. </p>
    <p>You glance quickly over to Slabal.  She is looking at you, the way she looks at people.  Impassive. </p>
    <p>You look to The First.  He is sneering.  Angry.  Sickened. </p>
    <p>Oh no. </p>
    <p>What have you done? </p>
    <hr>
    <p>don'tgrindyourteethdon'tgrindyourteethdon'tgrindyourteethdon'tgrindyourteeth </p>
    <p>You weren't sure what to expect when the Esteemed interrupted you... admittedly, you were hesitating, after all, it's not everyday you have to square up and admit that the only options left to your people are horrible... but to have been interrupted for that mad tripe? </p>
    <p>It's <i>ludicrous</i>. A <i><b>Childish Flight of Fancy</i></b>.  Which is funny enough, from someone who keeps looking at you as a Child.  One common foe and a single visitor who didn't immediately start killing you does not an ally make!  Sure, they didn't turn on the Aggro while they were both at war with the <span class="animal">Animals</span>, but that's only because they made absolutely sure they never got the chance!  They set course for home the minute those murderous beasts were driven from the land, knowing full well that every day in contact with the Lowlanders risked the very existence of the Crag People! Even you know that! </p>
    <p>One look around the room is all you need to confirm your suspicions.  While you admit you were the one to tell her that you'd need to look beyond Eschaton for survival, you didn't mean exposing your people to another round of Genocide!!  And you were Right!! If she had listened to you when you brought up this issue in the first place, if you had been allowed to study it properly, then maybe it would have meant a couple hungry months, as opposed to the potential extinction of the Crag!!! </p><p>Hoo, fuck you, you are angry.  Time to put it to good use. </p>
    <p id="First">"...<i>While I respect The Wisdom of The Esteemed, I'm afraid I must say that I find that solution overly optimistic.</i>" </p>
    <p>Whoops, shit, you unclench your teeth.  You need to calm down just a tad. </p>
    <p id="First">"While advantageous... if each supposition turned out to be true... it relies on a great deal of unknown factors, leaps of logic, leaps of <i>faith</i>, and in some places does fly in the face of established precedent.  We cannot truly know the intentions of these... Lowlander Elves.  After all, by reports from our Aggro, they are hardly unified themselves.  While our one interaction with them since the Extermination, a Short interaction, I believe, did not end in violence, it did not provide sufficient evidence that we would be accepted, or even tolerated, by the greater whole of these elves. </p>
    <p id="First">I do not wish to object too harshly to the Esteemed's wisdom... after all, she <i>has</i> proven the quality of that wisdom time and time again, as of late... but I fear she may simply be looking for a silver lining, some <i>new factum</i> that might change the dreadful calculus, I'm afraid I must continue my suggestion to the Wisdom as I previously calculated." </p>
    <p><i>Ancestors, that feels good!</i>  You've never been so brazen with your cutting remarks to the old slate-brained crone, and if you're being honest with yourself, it's a Rush! You can read it in her reaction, in her face; <i>this</i> is her comeuppance! She's lived in her dream world of gods and portents for too long! </p>
    <p id="First">"As I stated before, Eschaton will not be able to feed itself on the remains of the harvest and other food sources alone.  But if we ever hope to be able to sow our fields again, we <i>must</i> make this sacrifice... and a sacrifice it must be, for the good of all Crag.  I-I..." </p>
    <p><i>Dammit,</i> losing steam again.  Come on! Crag up! You know the truth, they already know it too... You just have to be the one to say it! </p>
    <p id="First"> "... I have put together a list of how much of the population we <i>can</i> feed with what we will have remaining, and will be able to gather.  If we consider the most vital portion of the pop-" </p>
    <p id="Echo">"I think I've heard just about enough." </p>
    <p>You think you just popped a blood vessel.  Your vision literally goes red for a moment.  You whirl around to see the Lummox lumbering towards you.   </p>
    <p>You aren't putting up with this.  Not this time.  Not from him. </p>
    <p id="First"> "<b><i>Look you big hunk of schist, I don't WANT things to be like this, but you can't get around the numbers just by obstinately saying 'No!' We have to face the facts, LIKE ADULTS, and deal with what we-</i></b>" </p>
    <hr>
    <p>You are <b>Saltik, holder of the Bloody Bloodname of Bergen, Echo of Blood</b>, and you are seizing the discussion, the perspective, and The First's throat, all in one go.  </p>
    <p>Your hands are big enough to do that. </p>
    <p>He's starting to flail and sputter.  You can see him reaching for that goose-sticker he got to play soldier with.  You give him a little squeeze to remind him to stop acting so foolishly.  The gurgle from his throat and the bulging of his eyes tells you that your message got through.  You relent,  making sure he can get enough of the wet air to live, just not enough to keep honking like a cragoose. </p>
    <p>You look around at the assembled crowd. At the "Wisdom".  You had already saw some of the Bakshish nodding along with The First's talk of <i>culling</i>.  You know that's what it was leading up to.  You know the old, bloody histories left in <i>The Tome</i>.  That part is critical for every Aggro to know.  Now, they've got a different look.  Fear.  Uncertainty.  The one you're really looking for is Shame.  You expect to get that in a moment. </p>
    <p>The Esteemed, no better.  For all your suspicions, you still can't believe she openly admitted how she's exposed Eschaton to The World, and how she was planning to make it worse.  You'd shake your head, but even when dealing with fools masquerading as the Wise, a degree of decorum is in order.   </p>
    <p id="Echo">"Assembled Wisdom.  You know who I am.  I am Echo of Blood.  And it has become clear to me that none of you know what awaits us in the Lowlands.   </p>
    <p id="Echo">The Euclast and I are the only ones who truly know what is down there.  What it's people are like.  What it's lands are like.  We've told you the stories, and we see you nodding along.  It's fair enough! Soldiers like to exaggerate their war stories, after all. </p>
    <p id="Echo">When I was first ordered to return to the Lowlands, two seasons ago, I already knew what the solution to our food problem was.  I even told The First and The Esteemed what it was.  I am afraid I may not have made my point clear enough.  Today, I fix that. </p>
    <p id="Echo">Many of you will have, at some point, looked down the mountain, upon the Lowland, on a day clear of clouds.  You will have seen the browns, the blues, but more than that, a whole lot of greens.  Just so much greens.  Greens as far as the eye can see." </p>
    <p>You lift The First a little bit, so you can look him in the eye.  His small legs kick a little. </p>
    <p id="Echo">"<i>Every bit of that green is food.  It is full of plants, critters, and monsters. The monsters taste the best. </i></p>
    <p id="Echo">You are a man sitting atop a giant bun, lamenting that there are no more seeds to eat." </p>
    <p>Important point made, you put him back down, releasing his throat.  He staggers, gasping for air.  You're ready to latch on again if he starts any more screaming tantrums, but the fear in his eyes, and, yes, the small tinge of shame... good, seeing a lot of that around the room... make you confident you won't need to. </p>
    <p id="Echo">"You sent me down into the Lowlands.  You asked for maps, drawings, cart-o-graphies.  I brought you what you needed, food, and you lamented that I didn't bring you better scribblings. You sent me to the Mountain ranges.  You asked for passages, soil richness, how much sunlight you'd get.  I brought you <i>more</i> food, and you lamented that you had no dirt. You hungered and starved, and yet your plan was always for how you'd exploit the land generations from now, instead of how you'd feed off of it <i>now</i>. You have foresight, but you all lack insight. Tomorrow must not cloud Today." </p>
    <p>You look directly at the Esteemed.  Your fury at her nonsense is still there, but it's definitely tinged with a bit of pity.  Sometimes it's too easy to miss the important details when you're trying to keep everything in mind.  That's why you prefer to just attend to the details.  The big picture will sort itself out when all the little pictures are handled. </p>
    <p id="Echo">"Esteemed, I make this request.  If you look for portents, believe the gods tell you things, then look at this one.  When you asked for hunting tools, your finest craftselves gave you weapons of war.  They did not give you the wrong thing.  Let me and my Euclast descend.  Let us go to the Lowlands.  While we are there, we will <i>strip it bare</i> to feed our people.  No grass, no plant, no creature will escape our stewpots, and Eschaton will eat things they will have never experienced before.  It will not always be pleasant.  It will not always be safe.  But it will fill bellies. It will keep you alive.  It will keep <i>Eschaton</i> alive. And if we must strip all the Lowlands to feed our people, then that is what we will do.  The Aggro bloodline lives to protect the Crag people.  Whether it is to protect it from Lowlanders, protect it from Hunger..." </p>
    <p>You look down at The First. </p>
    <p id="Echo">"Or to protect it from itself." </p>
    <p>Silence rings out in the Pagoda.  Tensions ran high today.  Lots of clashes.  Too bad for them, clashes are where you thrive.  You get the feeling you struck a telling blow. Ah, good. There's the shame you wanted. </p>
    <p>The Esteemed has closed her eyes again.  You get the feeling she does that so she doesn't have to look at the faces of the Collected wisdom.  The anger, the shame, the pity, the confusion.  The judgement. </p>
    <p>Still, if there's one thing you've seen The Esteemed manage time and time again, it's to make a completely crocked up situation and then make it seem palatable.  You don't care how she does it... as long as she lets you do what you want. </p>
    <p>She opens her eyes.   </p>
    <p id="Esteemed">"Echo of Blood, if your intention in those times was to communicate this fact, you failed, consistently.  Be mindful of these failures.  Learn from them.   As for your request... I can see little reason to deny it.  You are correct that the Lowlands are a source of sustenance.  If nothing more, your expedition with the Euclast will at least remove the burden of feeding your Aggro Warriors, as you are more than capable of fending for yourselves. </p>
    <p id="Esteemed">You will go in two days.  Collect your Euclast, arm yourselves for a hunt; The Onagi will see to it that you get the equipment you need. I trust the art of war should make your soldiers at least half as good as a Samra hunter, and with your numbers, you may be able to make a difference. </p>
    <p id="Esteemed">However, you will leave your Pathfinding team behind.  I will have a different assignment for them. </p>
    <p id="Esteemed">The concerns of The First are also worth noting, although I question why he would reject my considerations so thoroughly when his alternative was elective suicide.  While I trust in his knowledge, I fear he may have mistaken pessimism for realism.  Remember to differentiate the two. </p>
    <p id="Esteemed">That said, it would be wiser to investigate these Lowlander Elves before parlaying with them.  We shall send the Pathfinders to observe these Elves, and report back on their nature. </p>
    <p id="Esteemed">I agree wholeheartedly that the creation of the Quartz Houses was a masterstroke.  All due credit to our Onagi.  To speed construction efforts, you will use the pre-existing residential areas that are still damaged from the siege; while slated for Eschaton's eventual regrowth, it makes little sense to preserve them for more people when more food is what is needed now. </p>
    <p id="Esteemed">First, direct your Bakshish to whichever research you believe most beneficial.  You have shown great wisdom in directing them thus far; I have faith in your ability to choose wisely. </p>
    <p id="Esteemed">That is all.  Thank you, collected Wisdom, for attending.  You are all dismissed." </p>
    <p>You smile that smile you like to smile.  You flash it down to The First, but he seems distracted.  Oh well.   </p>
    <p>Time to go wage a War on Hunger. </p>
    <hr>
    <p>The other assembled members of The Wisdom pour down the steps of the Pagoda, the tortured creak of the stones ringing in your ears.  Maybe you should prioritize it anyway.  It's been seeing a lot more traffic than it's really used to. </p>
    <p>You glance over at the Esteemed, and the way she flicks her eyes open to look at you tells you you should stay here.  It's just one of the many tells she's established with you.  Ledret really prefers her subtlety.  </p>
    <p>After everyone else is gone, you take a moment to appreciate how much better the wind flows without all the bodies stopping it.  Though it'd be hard for an open Pagoda like this to become stuffy, per se, you can appreciate the skill that went into designing columns that would let the air in, but not force it into narrow channels. </p>
    <p id="Esteemed">"Slabal.  I am sorry to do this to you, but if today has proven anything, it's that you're the only one I can trust.  I know it is not what your Bloodline excels at, but sadly, I do not think any Crag bloodline was directed towards performing as an Envoy." </p>
    <p>...Oh dear. </p>
    <p>A wet wind blows over the mountainside.  It promises a long, unpleasant trip. </p>
    <div style="overflow-x:hidden;">
        <p id="cline">ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc </p>
    </div>
    <h2>Skill Usage</h2>
    <p><b>Economic</b>: <i>Echo's plan to mobilize the mightiest of the Crag, the whole of the Aggro Bloodline, to harvest and strip the Lowlands for sustenance is... ambitious, to say the least.  Though it is not their place, many Samra question the wisdom of attempting to use weapons as tools.  To that end, the Onagi attempt to at least make sure that these bold warriors have the same tools that the Samra would have... or, perhaps, better, if they can. </i></p>
    <p>Attempting to utilize the <b>Mercantile(Accessory)</b> skill to supply the Aggro Euclast "Memories of Shattered Hearth" with <i>Masterwork Survival Kits</i> ( a 50 GP value!)   </p>
    <p>Dice used: 1 Ability   Result(ROLL0001180): 2 advantage, 0 successes, 0 triumphs </p>
    <p><b>Political</b>: <i>Capitalizing on the successes achieved with the existing quartzhouses, The First called for a massive expansion of these structures to serve as a form of active seed vault, serving to recover from the severely depleted reserves of these essential crops.  Hopefully, once the fields are finally fit for use once more, this precaution will allow agriculture to resume full-force. </i></p>
    <p>Attempting to utilize the <b>Recovery(Taxation)</b> skill to once again attempt to trade more of the existing infrastructure of besieged Eschaton for a swift recovery of the Economy, trying to remove 2 Stress from the Economy Track, Remove one, and move the remaining one to the Property Track.  In addition to benefiting from two Boost Die from both the Rested Populace and the Expedition Surplus, this check will attempt the Free Invoke from the newly established <i>Glass Ceilings</i> aspect to add an additional Proficiency Die to this roll. </p>
    <p>Dice used: 2 Boost, 2 Ability, 2 Proficiency Result(ROLL0001181): 3 advantage, 3 successes, 0 triumphs </p>
    <p><b>Military</b>: <i>In spite of the best attempts of the Esteemed, a rift is beginning to open in Crag Elf society.  While her experiences and faith lead her to believe that it may be possible to interact with the Lowlander Elves without dooming Eschaton, it is clear that the Aggro and many others find this plan unfeasible at best.  Instead, they are motivated to prove that Eschaton does not need outside help to survive, even if it means permanently damaging the surrounding territories to do so. </i></p>
    <p>Attempting to utilize the <b>Reconnaissance(Pathfinders)</b> Skill in the lakeside territory indicated by the Traveller; in specific, this will send the expedition to the square containing Fort Alfyr.  While it may not succeed at fully mapping the area, they will make the attempt anyway, as ordered; however, the true goal of this outing is to allow The Layer to make contact with these Lowlanders. </p>
    <p>While this expedition is sent, however, Echo is motivating the Aggro to action.  Knowing that Crag Elves can only rely on themselves, and no others, he will spend a Fate Point to <i>Motivate</i> the Aspect <i>Stone the Crows</i> to entice the Division <i>Memories of Shattered Hearth</i> into the Marshy Lowlands directly to the South of Eschaton (Marked with a Red X).  Once there, he will attempt to <i>Resolve the event <b>The Blight</b></i> by using the <b>Conventional Warfare(Razing)</b> skill, shortsightedly eliminating any potentially beneficial aspects there in return for enough raw biomass to keep the people fed until normal Agriculture can resume. </p>
    <p>Dice used(Reconnaissance): 1 Ability   Result(ROLL0001182): 1 advantage, 0 successes, 0 triumphs </p>
    <p>Dice used (Conventional Warfare): 4 Ability, 1 Proficiency   Result(ROLL0001183): 5 advantage, 3 successes, 0 triumphs    </p>
    <p><b>Mental:</b> <i>The First spoke in depth about some plan to ensure that soil was never in short supply.  While an... interesting idea, it seems that other concerns are plaguing him, preventing him from truly keeping the Bakshish on task. </i></p>
    <p>For their part, the Heads of various Studies are feeling a great deal of motivation to make good on their previous studies;  how much of this is enthusiasm, and how much is spite, is an open question.  Their findings discovered the Blight was possible to eliminate in mere Weeks if starved of a plant host; while The First was padding this for safety margins, perhaps this is a time for bold action instead.  If they can use what they know of various Natural Magics to create something capable of rendering a field totally devoid of plant life, without resorting to poisons or other slow-acting methods, then eliminating the Blight could be a matter of one or two months, rather than one or two seasons! </p>
    <p>Attempting to <i>Resolve the event <b>The Blight</b></i> by using the <b>Mysticism(Magic)</b> Skill to develop a ritual capable of completely defoliating their fields, and keeping them defoliated long enough to starve out The Blight. With an understanding of similar <a href="https://www.google.com/url?q=https://www.d20pfsrd.com/magic/all-spells/d/defoliate/&amp;sa=D&amp;ust=1576645751323000">lesser magics</a> and their prior research into The Blight, they will receive a Bonus Die on this roll. </p>
    <p>Dice used: 1 Bonus, 2 Ability  Result(ROLL0001184): 3 advantage, 1 successes, 0 triumphs </p>
    <p><b>End of Turn </b> </p>
    <h3>Results </h3>
    <p><b>Economic</b> Your elite soldiers are not exactly masters of fieldcraft, but they have strong backs! Instead of well thought out compact kits, they just kind of pack everything and the kitchen sink. It ends up being somewhat less than useful than a survival kit, but the extra gear actually does come in handy, see military below... </p>
    <p><b>Political</b> Mercifully, if there's one thing that crag elves are good at in all this madness it's rationing. More victory gardens are build, more glass houses are made, and supplies generally increase slightly. It's enough to keep you from the brink this time, but things are definitely getting worse. By this point, the average crag elf is starting to notice that you're rearranging the chairs in a burning building. Every new plan results in only slightly less hunger pangs, and then only briefly. People are starting to realize just how bad the situation really is. </p>
    <p>Your next political check will take a <b>setback die</b> due to steadily falling morale. </p>
    <p><b>Military- Razing-</b> Victory and Tragedy walk hand in hand. The Aggro return with a bounty of foraged food and slain game, but the residents of Eschaton are shocked by the scattered few that arrive. Barely more than half the Aggro have returned, and many of those that did have been laid low by what appears to be severe burns and infections. Even the mighty Echo is barely standing, nearly half his body covered in partially healed burns. Once he is able to ensure his Aggro have safely returned to Eschaton, he dutifully delivers his report. </p>
    <p>It seems that the First was right, he had simply been looking in the wrong direction. Whatever else was there, this territory had the Aspect <i>Verdant Valley</i>. It no longer has that Aspect. It now has the Aspect <i>Fire-Fallowed</i>. </p>
    <p>The Aggro stoically did the most they could to hunt game. They aren't hunters by nature or training, so instead of pursuing the decided to drive game into their waiting hammers. When detached scouts couldn't reliably get the animals to flee in a predictable nature, someone had the bright idea to start fires in order to force them to flee in specific directions. </p>
    <p>Given the current condition of the Aggro, this went as well as you'd expect. Quite thankfully and quite by luck, this expedition happened during the rainy season so the wildfires were extinguished before they rolled across the entire lowlands. Your Aggro weren't so luck. Like the game they were trying to drive, they found themselves fleeing and frequently trapped. The piles of random supplies like ladders, ropes, ten foot poles, and nets that the Aggro packed in their "survival" kits ironically do provide the tools for some to escape the flames, but there were still many trapped. The Echo did everything he could to save his soldiers, but even he was driven back by the flames. </p>
    <p>The Aggro have taken <i>Heavy Casualties</i>. If they spend two turns Garrisoned and inactive, passive recruitment and convalescence will bring this up to <i>Light Casualties</i>. Alternatively, you can use the <i>Drill</i> trapping to recruit fresh replacements for the losses. </p>
    <p>In addition, the Echo is shaken by his failure to halt the losses. He will take a Setback die next turn. </p>
    <p>Despite all this, the Aggro were technically successful. They bring back as much food as they are able to carry. Thanks to their losses, however, it's far less than projected. It's not enough for everyone. </p>
    <p>You can use the Aggro's supplies to negate one of the stress points dealt by the Blight next turn- either to your Economic track by distributing it to those most critical to the operations of the city, or to your Morale track by distributing it to those most in need. </p>
    <p><b>Pathfinding</b> Layer Slabal in fact finds the trip wildly unpleasant. In fact, no crag elf has been this far from Eschaton since the Aggro left for the war. The trip doesn't go well, for quite a long time. They struggle with mapping and accurately measuring distance for over a week before Slabal has a bright idea. </p>
    <p>We're aiming for an <i>entire ocean</i>. Specifics don't matter as much. Keep Eschaton directly behind us, setting sun to your left, rising sun to your... No, <i>damnit, </i>never eat sea weed... Rising sun to the left, setting sun to the <i>right</i>. Keep going that way until you hit ocean, then move to your right along the coastline until you hit elf. </p>
    <p>Slabal isn't able to map anything, but late in the season he and his pathfinders are able to reach Fort Alfyr. They are greeted by bewildered yet welcoming Blade Elves who tell them they are about a week early for the Potluck... </p>
    <p><b>Mental- </b>The First's plan turns out to be an issue of scale more than skill. Indeed, the initial experimentation with the Defoliate spell is extremely promising. Several gardens are saved, and usage of the spell allows new glass house gardens to be constructed safely. Most excitingly, soil in gardens razed by Defoliate indeed starves the blight after about a week of waiting. With a glass house over a defoliated blighted garden, the First is able to successfully plant and grow crops in soil that had previously been blighted. There <i>is</i> a way to kill it! </p>
    <p>The issues seems to be in scaling it up. Even a small sproutling carried by the wind can feed the blight. For this to work, you'd have to defoliate <i>all</i> of the farmland in Eschaton and continue the effect for a solid week, two to be safe. Straight up killing that much plant life requires an <i>astronomical</i> amount of magical energy, and the First simply isn't able to get it all together for now. </p>
    <p>Still, a proof of concept is made. A few rare strains of grain are saved. A glimmer of hope in the first truly blight-saved growth is found. The First receives a <b>bonus die</b> on his next attempt to use magic to kill the blight, even if it's not in a ritual. </p>
    <hr/>
    <p>"Home" is only a word. To the crag elves, it is a word that conjures fear and anxiety. Eschaton has been home for as long as any elf can remember. Eschaton is the <i>only </i>home that the crag elves can even conceive of. Yet now, they are at risk of being starved out. Even the crag elves cannot eat cold unyielding stone. The crag elves aren't just anyone, though. Though they are stubborn and hard headed, they are resilient both physically and mentally. Though they are showing cracks, others would have shattered under the strain they have endured. Eschaton <i>will</i> survive. </p>
    <p>You are not, and will never allow yourselves to become, refugees in your own home. </p>
    <p>For completing your first turn and in recognition of the steadfastness with which the crag elves have faced utter disaster, you are rewarded with one skill point to distribute wherever you would like. In addition, you receive one refresh point which may at this time be exchanged for a stunt of your choosing. </p>
    <hr/>
    <p><i>Burned, but not yet Broken, the Aggro's bounty makes its way into grateful Crag hands.  Seeing the most immediate need to be reinvigorating the strength of the people, the nutrition is distributed first among the Samra and Onagi to restore their flagging bodies... and minds.   </i></p>
    <p>The results of the <b>Conventional Warfare</b> check are applied to prevent another tick of <i>Morale</i> damage. </p>
    <p><i>While many of the bloodlines made great strides this year to attempt to aid a Failing Home, One stood head and shoulders above the rest.  The Elpahka (political) bloodlines, though frequently relying on the Onagi or Bakshish to carry them out, were nevertheless responsible for the careful orders and wise use of resources which allowed the Crag to survive in spite of the increasing scarcity of necessary nutrition and services.   </i></p>
    <p>Having fewer failures than any other bloodline this year(although some call cheating since they outright skipped one), the Elpahka receive the Skill point to invest into the Political Spectrum.  <br>They eagerly place it in <b>Recovery, </b>hoping to use it to help Eschaton get back on its feet once this scarcity finally passes.</p>
    <p><i>However, praise also needs to be given to the unsung throng of Samra laborers; the essential core of Crag culture, they often find their labors directed in direct aid of one vital task or another.  Without them, no other Bloodline could function for long.  Though times have been tough, Samra are tougher.  They will endure the coming year with stoic fortitude. </i></p>
    <p>To represent the general nature of Samra helpfulness, the Refresh point is not traded for a feat, instead allowing more copious use of Fate Points to get things done. </p>
<h3><a href="../../Events/02_0.php">The Elves Gather for Their Annual Potluck</a></h3>

    <?php
    include '../../settarget.php'; 
    settarget("Crag",5,null,null);
    if($_SESSION["YEAR"]<2){$_SESSION["YEAR"]=2;}
    include '../footer.php';
    echo getarrows("01_2_Crag.php","02_1_Crag.php");
    setlast("Year/01_4_Crag.php");?>
</body>
