<?php session_start(); ?>
<!DOCTYPE html>

<head>
    <title>
        A Measure of Hospitality
    </title>
    <link rel="stylesheet" type="text/css" href="../../style.css">
</head>
<body>
    <h1>A Measure of Hospitality</h1>
    <p>The first winter has passed for the river elves. While winters in this new land are more mild than the river elves remember, temperatures do get low enough for ice and snow to form. The rivers, of course, flow far too fast for any real ice to form. Moving from water to air can be dangerous as it can make the body lose heat quickly, but the river elves find that if they change to dry clothing and perhaps keep some warm coals ready that keeping the flotilla moving through these winters is manageable.</p>
    <p>In these mild winters, light dustings of snow are still common. These snowfalls rarely stick to the ground for more than a few hours, but cover the land in a thin white blanket that can be quite beautiful if a little chilly. The slight muffling of sound caused by the snow lend a sense of calm to snowy days. The light snowfall and cold water are a nice backdrop to their first winter in this new land, and hardly a great challenge considering what the river elves have faced so far.</p>
    <p>It is on perhaps the last of these snowy mornings for the year, at the dawn of spring, that the river elves depart for Surt. Within only a few hours of the flotilla setting out on this unknown river, the forward scouts of Partager deliver a report to Litoria and Staurois. They found an encampment on the riverbank ahead. The camp is small and concealed, with a single tent nestled under a large spruce tree. They might have missed it entirely if not for the smell of a fire.</p>
    <p>The scouts report seeing a lone blade elf woman in the camp. She’s tall even for an elf, athletic looking, with severe features and long platinum blonde hair. They report that she wears heavy, black traveler’s clothing, complemented with a fur-lined cloak. She wears a simple mithral breastplate and was seen sharpening a huge silver executioner-style sword. The scouts report that they were not seen, but that the flotilla will pass her camp in a few hours. They do not recognize her, and believe she may be some kind of adventurer. Finding out if she poses a danger to the flotilla, or maybe just letting her know they’re coming would be prudent.</p>
    <p>Litoria notes that while Staurois would be the first to welcome her into their company, he may possibly be a little too trusting.  She hops on Sauver’s back and pushes ahead of the flotilla,  leaving Smilisca and Acris with their turtle-pulled raft behind.  She does not hide her approach toward the camp, and makes an effort not to startle the traveler.</p>
    <p>As she hears the sound of someone approaching via the water, the traveler stands slowly. She holds her sword at her side, not in a defensive posture but ready for use if necessary. As Litoria approaches the shore, the traveler watches her carefully with steady eyes.</p>
    <p>“I see you,” She speaks in a level voice, “Why do you approach me?”</p>
    <p>“Tiens, Stranger!” Litoria gives a wave from the paddling hippopotamus.  “Flotilla’s passin through in ‘bou’ an hour.  Want you to come and ride a spell upriver?”</p>
    <p>"Flotilla?" The traveler lowers her sword with genuine surprise in her voice, "You're a river elf, aren't you? You… offer me hospitality so quickly?"</p>
    <p>"A’course!”  Litoria’s gives an open-palmed gesture downriver.  “All elves are welcome, an we see so few we don’t already know o’er this side of the world.”  More seriously, she continues, “We’ll take the measure of this course by the measure of its natives.”</p>
    <p>Sauver’s feet hit firm land, and the hippo begins to emerge from the water at the river’s edge.</p>
    <p>“I see,” The traveler returns her sword to its black cloth wrapped sheath. As she gets closer, Litoria may be able to see the runes engraved on the blade. If she speaks Skaplyndi she may recognize them as runes of that language, though not be able to read them.</p>
    <p>“I… have been traveling alone for some time, and I am not a native of this land,” The traveler shoulders the sheathed blade, “I would appreciate traveling with others, at least for a short time. This land is not a… friendly place. You are headed upriver, then? Towards Surt?”</p>
    <p>Litoria recognizes the runes and does speak Skaplyndi, but Lycan runic magic is the most common sort of enchantment in use during the war.  She assumes this to be a fellow veteran.  </p>
    <p>“Hop up.”  She pats the hippo’s back behind her.  “Weh, we’re fixin to visit our Fire Elf cousins up thisaways.  You been to their new place?  How’s it lookin?”</p>
    <p>"A moment," the elf nods to her camp. She begins breaking down her simple camp.</p>
    <p>"Yes, I have been there. They seem to be doing well, but I must say they seem less hospitable than you. I got into… something of an argument with their innkeeper. I'm afraid I'm not welcome there, though I would be happy to show you how to get there."</p>
    <p>She finishes packing the camp into a compact bag in a matter of moments, then approaches Litoria.</p>
    <p>"I may not be traveling to Surt," she says, "but if it does not strain your hospitality I would like to travel with your flotilla for a few days. I would be quite willing to work for my fare." </p>
    <p>“Mais all elves are welcome.”  Litoria nods sagely.  “An it don’ take a real couyon to set them burnies alight.  Ain’t gon’ hold that ‘gainst ya.”</p>
    <p>She helps lift the other elf onto Sauver’s back with ease.  A tap in the sensitive folds of the hippopotamus’s neck gets her moving again.</p>
    <p>“Weh, we’ll prolly taken ya up on that at some point, but the mos’ work that’s needin done now is just coaxin the turts to haul tail upstream.  Ya can take a rest a while.  Enjoy yerself.”</p>
    <p>The traveler laughs quietly, "Those are words I have not heard in quite some time. I think I will do just that. Thank you."</p>
    <p>With that, the traveler will go with Litoria to the flotilla.</p>
    <p>Litoria passes the ride back to her raft in comfortable silence.  When they arrive, Smilisca waves from the bow of the short little houseboat where he holds their turtle on a lead, occasionally throwing a lump of cabbage or other vegetable ahead for the enormous snapper to bite.  The ease with which he manages the turtle while adjusting the raft’s spacing with the one to its side with his long pole demonstrates his quiet competence at the role.</p>
    <p>Acris, meanwhile, is seated inside the small hut, grinding dry herbs into a fine powder to make incense.  He has his nose scrunched up attempting to hold in a sneeze.  The grinding stone has all of his focus.</p>
    <p>Sauver paddles along side the stern of the raft, and Litoria safely moves the stranger’s bundle aboard without getting it wet.  She then stands on the hippo’s broad shoulder, and offers a hand as help toward the low step.</p>
    <p>The traveler takes her hand and hops onto the boat with deft motion, though it is obvious to the river elves that she is unfamiliar with embarking onto a raft. </p>
    <p>Litoria hops aboard, and sits at the stern to remove her sandals.  She gestures mutely toward a cubby next to the step where the other’s sandals are lapped slowly by the clean river water, rinsing them of any mud.  She cleans her feet and sits with her toes in the icy water, watching Sauver paddle and play in the low wake of the slowly moving raft.</p>
    <p>It takes the traveler a few moments to remove her heavy waxed leather boots and long wool socks. They won't quite fit in one of the cubby holes, so instead she simply sets the boots down next to the rack. She rolls up her pants legs and wiggles her toes on the deck. She looks around at the flotilla curiously.</p>
    <p>"I've never seen a river elf flotilla before," she comments, "It's so… cozy."</p>
    <p>“Weh, it’s all family.”  Litoria looks up toward the raft following theirs.  She recognizes the oarsman, a younger elf working deftly with a pair of fat alligators on the leads.  A crane’s lever arm extends along the side of the raft, and its weight has been countered by building the living space off-center.  “The family that’s left, a ways.  Them a’fore, they’re all my kin.”</p>
    <p>Litoria gestures toward the oarsman at their tail.  “Them’s might not be blood, but they’re family the same.”</p>
    <p>The traveler blinks, trying to keep up with the strange dialect. After a moment or two, she seems to catch Litoria's meaning.</p>
    <p>"Ah," she glances at the group to the front of the raft, "They won't mind my presence, even though I am not of your family?" </p>
    <p>“Naw,” Litoria shakes her head, “we have the space.”  Sauver submerges into the water as a pair of elves rowing a narrow boat scoot past.  “Partager’s a young flotilla.  It’ll be a while ‘afore we grow into it.”</p>
    <p>She quietly stares into the churning water, watching Sauver’s dark shadow as it approaches the rowboat.</p>
    <p>“Mais, you recognized us.”  She gives the other elf a searching glance.  “Have you run into our missing kin out there?”</p>
    <p>She shakes her head, "This is my first time meeting a river elf," she explains, "I have heard other travelers speak of elves wandering the rivers with turtles and hippos, but that was years ago. It was back closer to the center of the continent, shortly after the last battle of the war. I do not know if they spoke of you or another group. I am sorry."</p>
    <p>She inclines her head at Litoria slightly, "Do not despair, though. I see much hope here, and where there is such a bond you are sure to thrive. I wish I could have such a thing."</p>
    <p>She pauses for a long moment, "My family did not survive the war. It is good to see someone's did."</p>
    <p>After the mention of the last battle, Litoria’s attention lapses a bit.  She sits in silence, giving the other elf’s pain the breathing room for the gravitas it deserves, her head hanging sadly.</p>
    <p>“We have paid the price,” she says in a quiet voice, “and we must not let the future forget its cost.”</p>
    <p>Sauver erupts violently from the water beneath the rowboat, swamping it and the causing the two hurrying elves in it to curse as they sink.  The hippopotamus splashes them playfully as they pull the craft to the shore to flip it over and drain it out.</p>
    <p>Litoria looks again at the sword in its wrapping.  And she looks to the silver-edged giggin’ stick hanging on the hook behind her.</p>
    <p>She appears to be considering saying something else, and changes her mind.</p>
    <p>“You want sommat to eat?  We got fish.”</p>
    <p>“I would absolutely love to,” She smiles, “It has been months since I have eaten anything but jerky or foraged berries.” </p>
    <p>Litoria stands and pushes aside the curtains into the small house.  There are hammocks hanging folded on the walls in the first room, with tidy storage chests secured to the floor.  Alligator skins hang from the rafters, and a pair of enormous tusks, carved delicately with intricate writing are bolted over the doorway.  The tusks could only have belonged to a behemoth.  Litoria guides her guest through the sleeping space into the working space at the fore of the raft.  This room contains Acris’s apprentice workspace which he shares with the food preparation space, and the rafters are festooned with the different colored threads, twines, and drying herbs that make up the Navigator’s craft tools.</p>
    <p>“Lunch?” Litoria briefly asks the apprentice, earning a nod, while he continues grinding away.  She pops the hatch on a trapdoor in the floor and nets a fish from within.  She stashes the net back in the live well, and begins to quietly prepare their meal.</p>
    <p>The traveler follows Litoria, giving the living space a curious look. As she passes the hook that Litoria’s spear hangs from, she looks at it for a moment then shrugs the massive sword from her shoulder and leans it against the wall next to the other weapon. She quietly finds a place to sit in the room Litoria guides her to, and watches what both she and the apprentice are up to.</p>
    <p>There’s not any actual cooking involved in preparing a still twitching fish for a meal.  It doesn’t take long for Litoria to gut, debone, and delicately slice the fish.  She rubs it with a spice paste, and wraps it in an almost transparent seaweed paper with cut up vegetables she pulls from a coldwell in another trap door in the floor of the raft.  The stranger is getting a good view of how the barge’s various personal storage systems work.</p>
    <p>When finished, Litoria brings a wrap out to Smilisca, serving the oarmaster at work first, and then gives one to the guest and then the apprentice.  Acris stops to wash his hands of the herbal charcoal paste.  Before they eat, Litoria and Acris quietly thank the river for its bounty.</p>
    <p>“So who’s this, Tante Litoria?” Acris asks brightly, and Litoria, knowing she has not demanded a name, looks to the stranger expectantly.</p>
    <p>She raises an eyebrow at Acris but responds, "Just a stray traveler Litoria picked up. Does she bring back elves as strange as me often?"</p>
    <p>Acris looks the stranger up and down and then shrugs.</p>
    <p>“Oarmaster Staurois say he had dinner with a cryptid once.  And Master Nonc, he keep bringin a blade elf like yourself for supper whole time we’re in close to Fort Alfyr.”</p>
    <p>"Cryptid… Cryptid elves? Those are real?" She seems genuinely taken aback. </p>
    <p>“Mais, we only see the one,” Acris is eager to share, “mais, weh!  They’re taller en most a gator, real narrow like too.”</p>
    <p>The stranger seems more than happy to change the subject. She also seems to quite enjoy the food she is given, though she takes a little bit of time to get used to the spices. She continues being pleasant and polite, and expresses genuine interest in the river elves and their way of life.</p>
    <p>They spend the day relaxing on the water, enjoying conversation, and silence in turns.  Acris is always happy to show off the things he’s learned, and it is easy to distract him.</p>
    <p>When the conversation turns to her though, she answers very few questions. When asked, she politely declines to give her name and is more than satisfied being called “stranger.” She answers questions about her past only in the vaguest terms, and quickly changes the subject. The river elves seem to take this in stride, as they do not want their guest to feel uncomfortable. As dinner comes to a close, she asks where they would like her to stay.</p>
    <p>Litoria looks to the skies outside, judging the state of the weather in the deep gloom of the night.  The raft is grounded and the turtle is curled up on shore to sleep.</p>
    <p>“We’ve more hooks then we need,” she hands a net hammock to the guest, “an more hammocks too, weh.  Yer welcome to hang yours inside where you will, or sleep out on the porch.”  The air is cold, but after carefully considering the options, Litoria hangs her hammock outside, in arm’s reach of Sauver.</p>
    <p>The stranger considers the hammock for a moment, “You know… I had been complaining about not sleeping with a roof over my head for so long, but I think I may have developed claustrophobia in the meantime. Ah… a porch counts.”</p>
    <p>The stranger strings her hammock safely under the overhang of the porch and well enough away from Litoria to still give her space, but still on the same side of the raft. The stranger removes her armor and the heavier layers of clothes, using her fur-lined cloak as something of a blanket. She spends a few minutes quietly maintaining her gear and cleaning her boots.</p>
    <p>Perhaps as a force of habit, she moves her sword within arm’s reach and lays out her boots and socks neatly next to her hammock, with the tongue of the boots pulled open for quick donning. She sits quietly for a few minutes in the hammock, listening to the gentle lapping of water and looking over at the lights of the flotilla trailing down the riverbank.</p>
    <p>“This…” She glances at Litoria, though clearly not wishing to disturb her, “Is… nice.”</p>
    <p>Without further comment, the stranger swings back into the hammock and pulls her cloak over her. </p>
    <p>Litoria almost smiles, and lays down on her hammock in the dark, alligator hides to keep in the damp, thick, heavy woven blankets to keep in the warmth.</p>
    <p>In the dark she listens carefully while Smilisca makes his nightly obligations to the ghosts of the fallen.  The smell of incense drifts through the cool night air, and his soft voice echoes across the open water, singing a refrain of regret.</p>
    <p>From the raft ahead, an accordion picks up the tune.  From the raft behind, a fiddle.  What begins with one elf’s solemn mourning of the dead echoes up and down the flotilla, beached on the riverbank, as a chorus of hope.  The song is in River Sylvan, which is a close enough cousin to Sylvan to be understood if the stranger knows it.</p>
    <p>The stranger quietly lies awake for some time, letting the pleasant music she does not understand lul her to sleep. She is blissfully unaware of just how mournful the lyrics are, though the cathartic nature of the song does reach her. As she falls asleep, she wonders when the last time she heard music was. She cannot remember. </p>
    <p>They spend the next few days relaxing on the raft in much the same way.  Litoria leaves the stranger with Smilisca for a while to attend her duties as Warmaster in the morning, taking reports from scouts, arranging duty schedules, working on the Archerfish recruitment drive, and making sure every one of the Crocodilians has a chance to rest and be off shift a while.  The stranger will note that Litoria spends a while at the start of every day checking the silversheen on her weapon.</p>
    <p>Early in the morning, the day before the stranger’s said she plans to depart, Litoria offers to take her fishing.  The stranger accepts the offer, and Litoria picks up her actual fishing giggin’ stick - the one without the silver on the tines, and borrows a spare from Smilisca.  They take Sauver and race ahead of the flotilla, where the water has not yet been churned to muddy stew.</p>
    <p>Litoria and the stranger enjoy a bonding montage involving noodling, accidentally encountering a dire muskrat, and forking it with giggin’ sticks.  The stranger is surprised by just how heavy the giggin’ stick really is and they have a pointed conversation about how it makes a good weapon for cavalry as well as a fishing implement.  Litoria mentions that Sauver hasn’t yet grown into the war harness and the stranger expresses surprise that hippos get any bigger than she already is.</p>
    <p>On the last day, the stranger has gathered her equipment and prepared her gear early in the morning just as the sun is rising. It is a warmer day now and the snow has melted. It is finally beginning to feel like spring. Not one for long goodbyes, the stranger quietly greets Litoria when she awakens and asks her and Sauver to take her to the far river bank. </p>
    <p>Litoria agrees, and presses travel food from their larder into the stranger’s hands before they leave.  She doesn’t take no for an answer on this. The stranger very happily accepts, as she has come to enjoy the river elves’ flavorful cooking over the last few days.</p>
    <p>As Litoria drops the stranger off on the far bank, she hops onto the rocky soil and adjusts her equipment. She gives the flotilla one last look before turning to Litoria.</p>
    <p>“Thank you again,” She says, “I haven’t felt welcome anywhere in a long time.”</p>
    <p>Litoria thoughtfully looks over the stranger, taking in the furs and the silver sword, and recalling the other things that she’s said over the last few days.</p>
    <p>“Every elf is welcome.”  There’s a seriousness to her tone that can’t be missed.  “I ain’t gon’ pry.  You haven’t told us a name to call you by.  You came as a stranger, but I hope you’re leavin’ as a friend.”</p>
    <p>Before the stranger can accept that as a goodbye, she adds, more quietly, “Thems such as us, you an me, we’re still fighting that war.”  She touches a webbed hand to her head, and holds it over her heart.  “If’n you feel you need to, you can always take a leave with our family.  You are one of the cousins.”</p>
    <p>The stranger lets out a heavy breath and her eyes drop, as if unable to meet Litoria’s, “I… When you reach Surt, they will doubtlessly speak of me. I made mistakes when I was there. I hurt people. It was my fault. If, when you learn what I did there, I am… you are unable to welcome me here, I understand. I… hope you will still think of me as a friend. A cousin.” </p>
    <p>Litoria nods.</p>
    <p>“All families have their arguments, no?  Wouldn’t be natural if’n they didn’.”</p>
    <p>The stranger nods, and raises her eyes to meet Litoria’s, “Thank you. I hope our war ends some day.”</p>
    <p>With that, she turns to quietly leave. After a few steps, she pauses and turns back to Litoria.</p>
    <p>“My name is Bryti.”</p>
    <?php 
        include '../footer.php';
        echo getarrows("../Year/01_4_River.php#jump",null);
    ?>
</body>
</html>
