<?php session_start(); ?>
<!DOCTYPE html>

<head><?php include '../../header.php'; ?>
    <title>
        A Scholarly Pursuit
    </title>
    <link rel="stylesheet" type="text/css" href="../../style.css">
    <link rel="stylesheet" type="text/css" href="../River.css">
</head>
<body>
    <h1>A Scholarly Pursuit</h1>
    <p>It is a surprisingly short amount of time before the questionably invited guest is spotted. It’s a late evening in early spring when she’s spotted, just as the sun is starting to set. One of the researchers who was scouting locations for cliffside houses spotted the tall black figure with another elf beside them standing at the base of the Watchtower. They immediately reported it to Anasatri and Naleryn. While the basket is being prepared, the two elves fly down to greet their strange guests. </p>
    <p>Anasatri and Naleryn circle slowly down, making their approach clear and obvious. Anasatri takes the lead, with Naleryn gliding behind her, and lands a short distance away from the two visitors. “Hi! Glad you made it safely!” </p>
    <p>Bryti looks up as Anasatri glides down. She smirks slightly, “Hello, Anasatri. I brought the fur coat as  you asked, but I do not see a ladder. Perhaps you will carry us?”</p>
    <p>She gestures to the river elf beside her. Anasatri recognizes him. It’s Allophryne, though mercifully, Blinkin is nowhere to be seen. </p>
    <p>Anasatri grins, “You guessed it. They’re working on the basket upstairs, making sure it’s good to go.” She turns her smile to Allophryne, “Hello! I’d wondered if you might be the guest she mentioned. I’m glad to see you’re all healed up! How have you been?” </p>
    <p>Allophryne shrugs.</p>
    <p>“I’ve been dryer, but not recentlike, non.”  He eyes the height.  “How’re yall gon’ handle this, weh?”</p>
    <p>Anasatri shades her eyes, squinting back up the cliff, “Oh they’re waiting up there to be sure that we don’t get eaten, and then they’ll come down with the basket. Hope you aren’t afraid of heights! I think I remember that Smilisca’s apprentice had fun when he went out with our scouts to check out the river.” She taps her chin a few times, and waves generally upward.</p>
    <p>“Well, I am a bit peckish, but I <i>suppose</i> I can abide,” Bryti folds her arms and mocks a glare at Anasatri.</p>
    <p>The other winged elf, a smaller woman with black hair and pale grey wings sighs dramatically and leans around Anasatri. “<I>Hello</i>. I’m Naleryn, one of the researchers here. Anasatri told us you were coming, and exactly nothing else important like names.” She peers curiously up at Bryti, studying her armor and what parts of The Sword™ are visible. </p>
    <p>Allophryne looks at the cliff again, as if mentally measuring it.  He mutters something under his breath that might be “pulleys.”</p>
    <p>Bryti gives a polite bow to Naleryn, “Then thank you for allowing my presence. Levity aside, I… understand it might be difficult. For what it is worth, I promise that I mean you and yours no harm. This is a holy site for me. It would be sacrilege for me to spill blood. I… normally do not give my true name, but you have given me yours and in this instance, I am asking you for a great deal of trust. My name is Bryti.” </p>
    <p>Naleryn looks...surprised. Her wings dip a little, the feathers fluffing, before she composes herself and gives a small bow back. “Satri told us you were responsible for what little information we had to go on from the beginning. We want to preserve what’s here, and if you’re willing to share your secrets and help us understand it, it’s worth the possible risks to us.” She glances up as a shadow passes over them, and a team of winged elves glide down, carrying what looks to be a sturdy coracle. As it slowly comes to a gentle landing a short distance from them, she gestures and raises her eyebrows, “Your chariot awaits.”</p>
    <p>Bryti gives the apparatus a distrustful look, then raises her head and gives the towering cliff face a mournful look. She sighs and turns to Allophryne, “I told you there would be great challenges ahead.” </p>
    <p>“Pfooo-wee,” Allophryne gives a sad sigh, “y’ain’t kiddin, non.”  He swallows his fears and nods slowly.</p>
    <p>Anasatri goes over to the basket, rummaging around inside it and coming up with a sturdy rope. “There is a safety line, if that helps. And you can keep your eyes closed, Allophryne. Some people find that easier.” She looks apologetic, “There wasn’t time for a more, um, permanent solution, and we, ah, like how inaccessible this place is. With all the...bandit problems.”</p>
    <p>The team carrying the basket give Allophryne curious looks, and Bryti some dubious ones. “You first, river-friend, if you can. Laying down in it might help cut down on the movement for you.” </p>
    <p>“Call it a test of your resolve,” Bryti grins at him.</p>
    <p>Allophryne eyes the werewolf.  And then nods solemnly.</p>
    <p>“Weh, I understand.”  He bows in deference to Bryti.  “I’ll let ‘em test it on me.  If’n it works it’ll be safe fer you.” </p>
    <p>Bryti shrugs, “A maneuver can have more than one objective.”</p>
    <p>The carrying team securely ties the safety rope around his waist, and help him into the basket. “Just think of it like a small boat?” one offers, probably unhelpfully.</p>
    <p>Anasatri and Naleryn step back, shielding their eyes. The carrying team fling themselves upwards, jerking the basket up after them and quickly pulling away from the Watchtower. Hot winds blowing off the desert give them a boost, and those on the ground watch the dwindling basket as it slowly circles higher and higher, finally vanishing over the lip of the tower.</p>
    <p>“That went well!” Anasatri turns to Bryti, “They’ll take a moment up there to make sure he’s back on his feet and swap out the team. It’s um, a lot of work to move one of those.” </p>
    <p>Bryti nods and folds her arms, glancing between the two elves, “Very well. If.. it is no insult, I would prefer to keep my name private. Tourist is fine, when talking to others. It’s clever, at any rate.” </p>
    <p>“Travel the countryside, see the sights, only occasionally punch things?” Naleryn comments with a quirked eyebrow.</p>
    <p>She shrugs, “I’m a creature of habit.” </p>
    <p>Bryti appears to handle the ride with a bit more stoicism than Allophryne, who looks a bit more green than he should, and the team with the basket takes off with it to return to the Observatory. Naleryn and Anasatri watch it go, and Anasatri gestures after it, “It’s not quite a mile to the Observatory. Shall we?” </p>
    <p>“Of course,” Bryti nods as the group begins to walk.</p>
    <p>The terrain across the top of the Tower is rough, but the steady wind keeps it from being too hot. The Observatory itself is visible on the horizon if you know what to look for amid the rocky outcrops, and Anasatri and Naleryn are now more aware of the tumbled monoliths that aren’t natural structures. The broad space in front of the Observatory has been flattened , and Luna’s holy symbol is still present, if hard to see from ground level. The main doors of the building are opened, as are most of the visible windows. It is otherwise quiet. </p>
    <p>As she approaches the observatory, Bryti begins walking at a faster pace. She heads away from the observatory building itself. Absentmindedly, she drags a hand along one of the fallen monoliths. She stops at the edge of the holy symbol of Luna that is carved into the rock, a full fifty feet wide. She kneels and runs a hand along it, then stands and rubs the dust between her fingers.</p>
    <p>“You didn’t deface it,” she speaks to no one in particular, “I had assumed…” </p>
    <p>Anasatri and Naleryn exchange a glance, “We...had considering adding an arrow to it, as a nod to Calestros as well.” Anasatri looks uncomfortable, twisting her hands together, “No one but Naleryn knows that I’ve been...talking to Luna. People are...nervous. Less so, us here, but more people are going to be coming here soon.” She shakes her head, “I’m sorry, I’m not helping. Shall we go inside?”</p>
    <p>“Hm,” Bryti continues without looking away from the holy symbol, “Anasatri, you are a loremaster. Would you like to hear a new story?”</p>
    <p>Naleryn snorts, “Now you’ve done it. She already wasn’t going to leave you alone.” </p>
    <p>Anasatri sticks her tongue out before turning back to Bryti, “Absolutely.”</p>
    <p>Bryti nods to Allophryne, “You listen too. This is something you need to know.”</p>
    <p>The Lycan takes a long slow breath in and out. She closes her eyes and begins to speak solemnly.</p>
    <p>“In the Age of Myth, when the Creator gods walked among their Chosen, there was a sense of great happiness and belonging shared by all mortals of the World. All, except a few. They were Chosen, and though they loved their Creators and felt connected, they also felt incomplete. They felt as if there was something vital missing, as if some deep part of their being stood apart from the rest of the Chosen. They were of many races, many different kinds, many different Chosen, but they felt a strong sense of otherness; that there was somewhere else they belonged, as if their very souls were different than their kin.</p>
    <p>“As the Age of Myth came to a close, as the Creators began to leave the World in the care of their Chosen, a night came when the moon was full, larger and brighter than ever before, for a full year. It was on this long night that a great gift was given to these adrift mortals. The incompleteness of their souls was recognized, for while they were fully the Chosen races they appeared to be, they were also something more. They possessed a hybrid soul, one that is both fully rational animal and fully wild animal. They were granted bodies to match their souls, and as they retained their Chosen bodies they were also granted the ability to take the form of an animal that matched the other half of their soul. They rejoiced as they were finally complete, and they hurried to share their joy with their families and friends.</p>
    <p>“Bellaphex, however, corrupted their divine gift as she corrupted all the gifts of the Creators. As those of hybrid soul greeted their loved ones in their new bodies, a horrible Affliction spread. This curse was a corruption of the hybrid soul, a vile cancerous perversion of the gift that the hybrids had been given. While a hybrid soul is something in balance, something sacred, the soul of a wild animal is a monstrosity upon the soul of one who was not Chosen for it and it drives them inevitably to madness. As this abomination was visited upon the ones the hybrids loved most, their own kin turned against them. They were seen as monsters, as cursed themselves, as terrifying creatures. They were hated. Their own friends and families hunted them. With no other choice, the hybrids fled their homes and into the wild places of the world.</p>
    <p>“It was there that the hybrids came together. Thousands of different stories, different animals, different races, from all over the world, but they had all come to the same point. In the wild, they found each other as if destined to. Even though they were wildly different from one another, they felt as though they belonged. As though they were understood. As though they were family.</p>
    <p>“After rejoicing their newfound bond, they began to wonder why. Their new senses were sharp, their bodies strong. They saw the world as never before. Their keen eyes saw more stars in the sky than ever before. There, they saw the moon. They were drawn to its light, drawn to its deep well of power, called by its perfect form. They began to ask it for guidance, to seek its wisdom. They sought to see, to understand, the infinite mystery of the night skies above them.</p>
    <p>“They cleared sacred groves in the deep wild places, set these holy sites upon mountain tops, in tundra and desert. They built monoliths, stone sentinels to mark the passage of the sky. With the stones as guides, they watched the stars, counted them, mapped them, tried to understand. There, in the stars, they saw the ancestors. The eternal beings whose divine essence made a part of the hybrid’s own souls. They tracked these ancient beings, asked them for guidance, and as they consulted their ancestors in these sacred groves, they were given their answer: Look to Her.</p>
    <p>“Through the stars and the ancestors and the sacred groves, they discovered Luna. Her infinite mystery, her eternal gaze, had been watching them from the very beginning. Luna was a Creator, the last and most mysterious. She had marked her Children from the very beginning, placed her essence into their souls. She had been watching them, waiting for a time when they could fully embrace what they had always been meant to be. Now finally, they were ready. They embraced their hybrid souls, fully accepted their ancestors, and took both forms as their own. Finally understanding, finally whole, with Luna’s guidance, they sought to return to the world.</p>
    <p>They were the first Lycans.”</p>
    <p>Bryti turns back to the other elves.</p>
    <p>“Those sacred groves? Those were the first observatories. Before the orreries, before telescopes, before we even had walls, we tracked the stars by the positions of the monoliths. It was in learning about the stars and about Luna that we first learned who we are. That is the importance of an observatory, why it is a holy site. It connects us to those first hybrid souls, lost in the wild striving for meaning. That is why we maintained the monoliths, the first method of tracking the stars, so that we might never forget that connection to our humble beginnings. That is why this is the center of the observatory, and this is the truth that gives this place purpose.” </p>
    <p>She turns back towards the holy symbol and lowers her head, “At least it did. To us.”</p>
    <p>Anasatri looks thoughtful, “She showed me the ancestors in the stars.” She looks at the holy symbol, quiet for a long moment. “It should stay important. Stars aren’t...anything we really know about. For a people who live in the sky, we only know anything about half of it.” She gives Bryti a sympathetic look, “We want to preserve what’s here. <I>All</i> of it. Purpose included.”</p>
    <p>Allophryne squints up at the sky.</p>
    <p>“Hm.”  He mumbles under his breath.  “Spicy.”</p>
    <p>Bryti gives Allophryne a raised eyebrow, then turns to Anasatri, "This… isn't your religion. Not your Goddess. Not your ancestors. You have no obligation to preserve any of this. Great atrocities were committed under the banner of this symbol, many of them against your own people. I wouldn't blame you if you burned it to the ground."</p>
    <p>She tilts her head and looks between the two researchers, "But you didn't. You chose to try to save it. To understand. You… <i>asked</i> for help. I am… I am very grateful for that, but I have to know… after all the horrors we inflicted on you, why did you want to preserve this relic of ours instead of razing all memory of it to the ground?" </p>
    <p>Anasatri and Naleryn glance at each other, frowning slightly. “Why <i>wouldn’t</i> we?” Anasatri asks. “It...yes there are memories, but...it’s not that it doesn’t bother people? I don’t…” She makes a frustrated sound and looks to Naleryn for help.</p>
    <p>“It’s knowledge. It’s information. We don’t care who it came from. If it’s solid and useful, we’ll use it.” Naleryn sweeps her arm toward the building, “While Skaplyndi was falling apart and Lock’s underlings were trying to oust him, we raided the city’s libraries and archives and brought what we could with us. The Empire did incredible things. There’s no denying that. You didn’t make it as far as you did by being incompetent. Why <i>wouldn’t</i> we build on that? As for the Observatory itself...same thing. There’s a solid, sturdy building here, full of useful and interesting things. We wouldn’t throw away something like that.”</p>
    <p>“Trying to erase the Lycan heritage would be a lie,” Anasatri adds, having collected her thoughts. “We don’t...some of us don’t <i>want</i> to hang onto the memories of the War. The Empire is gone. Now...we treat your cultural artifacts the same way we would anyone elses’. With as much respect as we can. That’s just...how we are.” </p>
    <p>"You saved some of the libraries?" Bryti seems surprised, but gives them a contemplative look, "I… see, I think. You need to know, I am not an expert on the observatories. I know more than most and I have used one, but the keepers of these places were privy to deeper mysteries that I was not. If you are so devoted to preservation… I will help how I can. It's the least I can offer for the privilege of being allowed to visit this place."</p>
    <p>She glances at Allophryne, "There are some things that shouldn't be forgotten. We can discuss what you should do with the symbol soon enough. I think I have rambled enough at you for the moment. We can go inside now."</p>
    <p>The main entry hall is empty, but voices can be heard further into the building. All the windows are open, letting in the sun and the cool breeze. The walls and pillars have been decorated with cheerful paint, further brightening the interior. All of the doors have been repaired, and many of them sport decorative carvings or paintings to identify where they lead. As they walk, Anasatri chatters excitedly, pointing out the newly-renovated spaces. </p>
    <p>The bottom floor has a communal dining room, now with sturdy tables, and a large kitchen. More rooms have been converted into smaller study rooms and living spaces. Anasatri takes them upstairs where there’s another living space and some small sleeping rooms. “Having actual sleeping space has been <i>really</i> nice,” she says. “We’ve all been down in the basement all this time, because nothing up here had been repaired, and it gets <i>cold</i>. But with the repairs and some great cloth from the Dreamdust elves, it’s much more homey and warmer up here.” She gestures toward one of the rooms, “Some of these are intended as guest space, so the two of you can sleep indoors while you’re here.”</p>
    <p>At the end of the hallway is another short flight of stairs. Anasatri smiles at Bryti and gestures upward, “After you!” </p>
    <p>Bryti nods and gestures Allophryne to follow. Silently, she walks up the steps into the observatory's dome.</p>
    <p>The structure is in much better shape than when it was discovered. The cracks in the dome have been patched, the layer of dust and dirt has been cleaned. The dome has been carefully reinforced, and the heavy shutters that protect the tall and narrow observation windows can be used again. Perhaps in preparation for their guests, the shutters are open providing an excellent view of the night sky now that the sun has set.</p>
    <p>The contents are still a confused jumble, though slightly less so now. The researchers have organized the broken parts into careful piles, each part carefully tagged and documented by size, shape, and where it was found in the room. The smaller pieces have been carefully placed in protective cases, as have the delicately carved planar spheres. The larger central assembly has been covered in a protective tarp to prevent it being damaged by the elements.  Near the door are the telescopes, one covered, one partially disassembled, and two that have been restored. </p>
    <p>Bryri looks around the room with a tense expression on her face. She walks over to the central assembly and gently pulls back the protective cover. She looks at the damaged instrument for a short while before pulling the cover off completely to get a look at the whole thing. The ten foot tall central assembly stands like a dead tree, with empty broken branches sticking out in all directions.</p>
    <p>"I think the mechanism is… mostly intact. The gears are the important part, and I think I can see them… it looks like clean breaks, like it was hit with something. Shattered like glass. Hm. It could be a lot worse, I think." </p>
    <p>Naleryn’s ears perked, “So you think it was damaged, then? We thought so, but weren’t sure. There was no sign of anyone up here since the Loremaster died…”</p>
    <p>“I am not certain. I don’t know why it would just… break like this. Regardless, the orrery itself is actually not what I am most concerned about. It’s a complicated device, yes, but it can be recreated by anyone with mechanical skill and a solid grasp of mathematics. It’s a marvel, yes, but it can be reconstructed even if there’s almost nothing left of it. This, though…”</p>
    <p>Bryti steps towards the center of the chamber and kneels next to the large crystal lens set into the floor, “This focusing crystal is the heart of the orrery. Each one is… well, even I actually don’t know how they were made. Only a small handful of masters ever knew. The patterns are etched deep into the crystal itself, in a method that even I don’t understand. You can’t even see it with the naked eye. Their creation, and their magical properties, are something only a couple dozen people at most ever understood.”</p>
    <p>Bryti pauses, then traces a simple Lycan rune on the surface of the lens with her finger. She casts a simple light spell. Immediately, the lens hums with a dull glow. Bryti steps back and looks up. From the crystal, light projects onto the domed roof of the observatory. It projects a pattern of thousands upon thousands of stars, varying in intensity and position, in a complexity and level of detail that can scarcely be believed. Bryti kneels down again and carefully rotates some of the layered dials that surround the lens’ setpiece. The lens moves a barely perceptible amount, but the pattern of stars shifts dramatically. Bryti takes a deep breath, then stands and looks at the projection.</p>
    <p>“It works. No damage. The adjustment mechanism is even intact. That… is good news.” </p>
    <p>Anasatri walks over to her, looking up at the patterns. “So that’s how you adjust it...But how do you figure out when and where this sky is?” </p>
    <p>“That’s the purpose of the orrery,” Bryti looks at her, “You’ll have to find reference points in the star charts you already have, but once you have a set reference point, you can check the mathematics. Some of the charts should have it written down. Work backwards from a known point, add in planets as you go. Once you’ve reconstructed enough to add the World’s sphere, you can move it with quite a bit of precision to determine your location on it. Not that we know what the rest of the World looks like, of course. Still, the point is the same. Once you have a reference point, you can work backwards and slowly reconstruct pieces. You’ll probably be wrong the first time, of course, but you can check your math by adjusting it do different star charts. If you make an adjustment and don’t end up with quite the right starfield, you know the math is wrong somewhere. Then you can slowly adjust it, with more star charts as reference points you can refine the calculations until they are correct.” Bryti blinks, “Obviously, that’s far more difficult than I just made it sound. That will work, in theory. Mathematics was never my strongest study.” </p>
    <p>Anasatri’s expression is somewhere between resignation and horror. “It’s...not mine either…and that sounded plenty difficult enough as is...”</p>
    <p>Naleryn claps her on the shoulder, “Which is why there’s an entire team here. If none of us have the head for it, we’ll ask the engineers. Someone will be able to figure it out now that we have the idea.” She glances up at Bryti, “If you can help us identify which planes those models are meant to be too, that would help very much.”</p>
    <p>“Planes?” Bryti turns to Naleryn, “Er, Naleryn… what do you think these models represent?”</p>
    <p>“The Inner Planes, yes? Fire, Earth, Positive Energy, Water, Material, Air, Negative Energy.” She squints up at Bryti, “Unless you all know something we don’t?” </p>
    <p>Bryti breathes sharply out her nose, “Well… I know that of all the marvels the empire will be remembered for, its education system isn’t one of them. I suppose we didn’t think slaves needed to know astronomy… I… sorry. I suppose hoarding knowledge is simply one more crime. Allow me to address it.”</p>
    <p>Bryti steps over to the case that contains the models of the spheres. She carefully takes out the smooth bronze sphere that represents the World, the small mithral one that represents Luna, then the larger blue one that represents Aquuan. She sets them next to eachother.</p>
    <p>“I… suppose it’s simple enough to explain. We know that the World is a physical thing, right? We can measure it, stand on it, use math to calculate how big it is and its shape. Well… she is a Goddess, yes, but Luna has a physical form. She also a physical object, like the World, though much smaller and very close. All of the other spheres… they too are physical objects, worlds in and of themselves. We don’t know much about them, but Lycan astronomers were able to calculate that they are not some magic other reality, but actual things that exist, separated by only vast distances. The specifics of how that works… well, we had a lot to learn too. We were, however, able to check the math. They are real objects, real places. They can be tracked and measured, just like our World can be.” </p>
    <p>Naleryn looks at the models, “Of all the things I would have guessed the Empire was good at, complex mathematics would not have been on the list.” She lifts an eyebrow toward Bryti, “You aren’t a scholar, but you have a grasp of the basics? I’m impressed.” She picks up the model of Aquuan, “So, other bodies like our world. I’m not immediately taking that as writ, but not rejecting it either. There’s certainly logic to it. Maybe we can get the books from Skaplyndi sent over here to dig through…Satri, you should tell her your big plan.”</p>
    <p>“My what?” Anasatri has been staring up at the star patterns this entire time. </p>
    <p>“The archive.”</p>
    <p>“Oh! I’m hoping to make a library. Everything that’s here, plus what we have back at Asavardi, and what’s in my head, once we get it all written down.” She smiles brightly, “I’ve already gotten the first contribution! Maybe someday you can write up something for it.” </p>
    <p>“That’s a noble idea,” Bryti nods, “It would be a shame to let chaos claim the knowledge of so many generations. I… am thankful that someone decided to try to preserve something from the fires. I am no scholar, but… I am from… was from a noble family, education was a mark of status. Another privilege I suppose. Hm.” She looks at the starfield thoughtfully. </p>
    <p>Naleryn gives Anasatri a push back toward the stairs, “It’s almost time for dinner, and then we tend to quiet down for the night. You’re more than welcome to come up here and tinker with the thing all you want, but once people’s curiosity overcomes their nerves, you’ll probably be inundated with questions.” She grins, showing teeth, “I’ve seen the list. It’s an impressive stack. Let me point you both to the guest rooms, and then you can come down and get food when you want.” She looks over at Allophryne, “There’s a working well and a decent bathing room if you start getting uncomfortably parched. Make yourself at home.”</p>
    <p>Allophryne immediately seeks out the well, aiming to fetch water to have a long cold drink. And he finds no well.  But it's not like he really expected it.  Even the Lycans couldn't dig that deep in this terrain. </p>
    <p>He hides in the back of the access room to the cistern and massages water into his flaking ears.</p>
    <p>Bryti accepts a simple, out of the way guest room. She only has a few personal possessions that she places in the room. She requests a few minutes of privacy for prayer before she comes to the dining hall. Somewhat curious, she confirms that she's actually invited and won't cause a scene. </p>
    <p>Anasatri is waiting for her in the main hall. Voices and clattering can be heard from the dining room. “Hope you’re hungry!”</p>
    <p>The dining room is one of the most decorated that Bryti and Allophryne have seen so far. The walls are covered with improvised tapestries, and a few have rough paper sketches tacked to them for future paintings. The windows are open to the evening breeze, and lamps on the walls, rafters, and tables fill the room with cheerful light. </p>
    <p>Instead of a single large table, there are several smaller tables, suiting the winged elf family-style meals. Allophryne has already been dragged to one of the tables, and is being plied with food and questions. “Most of our supplies come from Asavardi,” Anasatri tells Bryti. “We’ve started a garden plot here, but we’re definitely not self-sufficient yet.”</p>
    <p>There is a visible hiccup in conversation when Bryti walks in, every eye fixed on her for a brief moment. Before it can get uncomfortable, Anasatri leaps into the breach, “Evening, everyone! This is...Anvesakya. Here, come sit with us over here. Thuridan there is the lead researcher here, so the two of you can discuss an actual plan.”</p>
    <p>Naleryn is at the table as well, but the others seem to be giving it some space. Thuridan is an older man with warm gold feathers, streaked with cream. If his greeting smile is nervous, it’s at least sincere. “We’re glad you made it, what with all the bandit nonsense going on down there.” </p>
    <p>Bryti gives Anasatri a raised eyebrow at the name, but then turns and gives a polite head tilt to Thuridan, "Thank you. The bandits are indeed fortunate that they did not encounter me."</p>
    <p>Thuridan blinks and barks a laugh, “Fair enough. You’ve come a long way; eat, and then we can talk. We don’t plan to throw real work at you until you’ve had a night to rest.” </p>
    <p>There are plates of thick, soft flatbreads, layered with slices of meat and vegetables, as well as other platters and bowls of fruit, small puffed pastries, and some kinds of sauces. The winged elves are all sharing from the serving plates; Anasatri passes Bryti a small personal plate, and starts filling her own. </p>
    <p>Bryti gratefully accepts the food and politely leans over to Allophryne to point out which foods have cheese in them so he can avoid them. Other than that, Bryti mostly stays quiet. She tries to avoid drawing too much attention to herself, though she is not exactly successful. When spoken to, she happily responds but politely avoids talking about herself. </p>
    <p>As the meal winds down, Thuridan glances over at Anasatri, “Will you give us a story tonight, Satri?”</p>
    <p>Anasatri finishes the last thing on her plate, “Certainly!” She gives Bryti a glance, “Since you gave me one earlier, it’s only polite. That’s really what Loremasters do,” she clarifies. “All our histories are oral, and Loremasters are the ones who keep all that information.” As she stands up, all other conversation quiets and everyone looks over in anticipation. </p>
    <p>“Two tonight, I think,” she says, raising her arms over her head, “because first, <a href="../../Winged/5_Creation Myth.php">this is the story of how the winged elves got their wings.</a>” She takes a deep breath, and when she lets it out, her voice is more resonant, and echoes with layers of sound. “Back when the winds were still and the sky was silent, when the World was new and gods walked among the people, the elves were one and they were loved…”</p>
    <p>Anasatri tells the story with her entire body, almost dancing through it. She dances the first part, her voice light and warm as she tells of Calestros living among her people, and the joy they took in knowing their Mother. Her motions slow, her voice dipping down, as Calestros bids her children farewell, leaving them behind to seek answers. </p>
    <p>Then she tells of the Shattering. Her voice is jagged, discordant, and her motions jerky. Her wings form a constantly shifting backdrop, accenting motion, creating direction, and adding sounds. Up to this point, the story is nothing new to Bryti; the Shattering is a well-known cautionary tale. </p>
    <p>“And there She would have stayed, alone and trapped with her madness. But some of her children reached out to her…”</p>
    <p>Then the story is told with desperation, with grief, as the elves try to help or at least comfort their Mother. Anasatri’s voice quivers, her wings dipping low to brush across the floor with a soft whisper. She sinks low, almost kneeling, when she tells of the elves finally being forced to leave Calestros behind.</p>
    <p>“They clung together and cried out their final love to their Mother as the stairs crumbled and they fell…”</p>
    <p>Her voice lifts again along with her arms and wings as she tells of Calestros giving her feathers to her children, giving them wings to save them one final time. “These were the first of the winged elves. Ever after, they turned their eyes to the sky, listening for her voice as they rode the winds.” She finishes in the same pose she began in, wings and arms lifted. She holds the pose for several heartbeats before slowly shifting, arms out to her sides and her wings draping behind her shoulders like a cape, “And now, Adinath and the Door to Nowhere.”</p>
    <p>The second story is a comedy about a poor wizard who accidentally created an enchanted door that couldn’t be used. “Adinath couldn’t pass through, but strange sounds came from the door, as if it led somewhere he couldn’t see.”</p>
    <p>The bulk of the story is an increasingly-improbable series of attempts to lock or dispel the door, which seems to have a mind of its own. “After finding the door open and the key spinning in the lock on its own, Adinath tried a chain. After finding the door open and the chain on the ground, sprouting small metal twigs, Adinath tried an armoire…”</p>
    <p>Anasatri does an excellent job of telling the story, hitting all the dramatic moments and startling laughs from her audience at the hapless wizard’s frustrated misfortune. “And so, Adinath resigned himself to the blue chickens. They only spoke once a fortnight, and the eggs sold quite well.” She once again finishes in the same position she started in, holding for a moment before relaxing into a normal pose and grinning.</p>
    <p>Bryti, along with the rest of the crowd, gets a genuine laugh from the story. She seems to have been enjoying Anasatri’s tales, paying rapt attention the entire time. As the crowd calms down a little, Bryti turns to Allophryne.</p>
    <p>“You know,” she asks him, “I don’t think I’ve ever heard the river elves’ version of how they came to be. Do you have a story about that?” </p>
    <p>“Weh, we do.”  Allophryne mumbles around the mouthful of food he’s shoved in his mouth.  “You really want to hear it?”</p>
    <p>Bryti raises an eyebrow, “If there’s any reason I would say no, I think Anasatri would throw me off the tower before I got past the ‘n-’.”</p>
    <p>“So how we tell it,” Allophryne begins, propping his elbows on the table, “In them days right after the Shatter when all them elves were still learnin’ how things done changed, Boudreaux and Thibodeaux built themselves a pirogue and went out on the river for a spell.  They spent the day a fishin’ and a drinkin’ and they done lost sight of the way they come.  Both Boudreaux an Thibodeaux got themselves ass-lost.</p>
    <p>Now neither one of them could admit to the other that they was lost, so they just kept followin the river an pretendin they both know where they’re goin.  When they hit the ocean where Grand-mère Grand-père Calestros is always there, they hit a rock an the boat, she began to sink.</p>
    <p>Now Grand-mère Grand-père Calestros, He don’ really know much about things that float on the water.  But He is our Goddess and He does know water and He knows us.  He saw Boudreaux and Thibodeaux drownin’ an He put a stop to it.</p>
    <p>‘Oh babies!  No, don’t you drown!’ Grand-mère Grand-père Calestros say, wavin His hands and sendin godly powers their way.  So they didn’t drown.</p>
    <p>Mais, they can’t admit still that they is ass-lost.  So they finished their fishin’ an’ build themselves a new pirogue an loaded it with redfish.  Still, not admittin’ that they’re ass-lost, they started back up the river.</p>
    <p>Upriver, they found themselves encounterin’ a city of hobgoblins.  Still not admittin’ they’re ass-lost, Boudreaux and Thibodeaux they ask to trade the redfish for a map.  The hobgoblins agreed to the trade, an took all them redfish.  But them hobgoblins ain’t elves, and anyone that ain’t an elf ain’t to be trusted.  So they pushed Boudreaux an’ Thibodeaux into the river.</p>
    <p>But Boudreaux and Thibodeaux, they don’t drown.  Instead they float downstream to the coast again.  An they built themselves another pirogue.  This time they loaded it with crabs.  Still not admittin’ that they’re ass-lost, they started back on up the river.</p>
    <p>Upriver, they found themselves encounterin’ a city of dwarves.  Still not admittin’ they’re ass-lost, Boudreaux and Thibodeaux they ask to trade the crabs for a map.  The dwarves agreed to the trade, an took all them crabs.  But them dwarves ain’t elves, and anyone that ain’t an elf ain’t to be trusted.  So they pushed Boudreaux an’ Thobodeaux into the river.</p>
    <p>But Boudreaux and Thibodeaux, they don’t drown.  Instead they float downstream to the coast again.  An they built themselves another pirogue.  This time they loaded it with shramp.  Still not admittin’ that they’re ass-lost they started back on up the river.</p>
    <p>Upriver, they found themselves encouterin’ a city of humans.  Still not admittin’ they’re ass-lost, Boudreaux and Thobodeaux they ask to trade the shramp for a map.  The humans agreed to the trade, an took all them shramp.  But them humans, they ain’t no elves neither.  And anyone that ain’t an elf ain’t to be trusted.  So they pushed Boudreaux an’ Thibodeaux into the river.”</p>
    <p>“Let me guess,” Bryti comments, “Catfish and halflings next?”</p>
    <p>“Weh non!” Allophryne interjects, “Clams!  An’ kobolds.”  He winks.  “An by then many years they gone by and Boudreaux and Thibodeaux were old.  An they still ain’t admitted that they had done got themselves ass-lost.  They keep goin’ up an down the river, an’ their families they come with.  An tradition is just repeatin’ the same things for generations.  So Boudreaux an Thibodeaux die and their families keep on ridin currents.  An’ that’s how we river elves started on the rivers.”</p>
    <p>Anasatri appears over Bryti’s shoulder, grinning, “Great story! Fits you all perfectly. But I had one question. You said ‘Grand-mère Grand-père Calestros’ - did I say that right? - what does that mean? Grandmother and grandfather?”</p>
    <p>Byrti tenses as Anasatri jumps behind her. She grips the table top for a tense moment, but then lets out a breath. She relaxes and returns to smiling, perhaps with Anasatri not noticing the near accident.</p>
    <p>“Weh?”  Allophryne raises an eyebrow curiously.</p>
    <p>Anasatri nods, “I’ve tripped up with Sylvan before, so I wanted to be sure I understood.” She sits back down at the table, snagging a forgotten piece of fruit before the platter is taken by someone else. “This is usually about it for us for the night. Some people might do some more reading, but things will quiet down now. Feel free to wander around as much as you like.”</p>
    <p>Bryti nods, “I’ve travelled a long way. I would prefer to have some time to myself for prayer and reflection. I will be ready tomorrow, for when your friends grow accustomed to the big bad wolf.”</p>
    <p>Despite the increasingly curious sideways looks she is getting from the now slightly less spooked  research team, Bryti and Allophryne depart for their rooms. Once they have stepped out of the dining hall and are alone in the hallway, Bryti places a hand on his shoulder.</p>
    <p>“The observatories, and the centers of the sacred groves, are the oldest and most holy locations in my religion. They are where we first learned of Her. There is a full moon coming in a few days. There is no place closer to Her. So if you had a question…”</p>
    <p>Bryti shrugs and pats him on the shoulder, then heads to her room for the rest of the night. Allophryne nods.</p>
    <p>He stays outside, plops himself down on the holy symbol of the moon, and waits.</p>
    <p>His answer is the same as it has been.</p>
    <hr/>
    <p>The following morning, Bryti’s nose leads her back to the dining room. There are fewer people this morning, and food is on a separate table on the wall leading to the kitchen. She recognizes everyone from the previous evening, but Thuridan is the only one she’s been introduced to. He glances up and waves her toward the table, “Help yourself. Most of our meals are a bit more free-form than dinner is. Come join me when you’re set.” </p>
    <p>In addition to the usual fruit and bread, breakfast is a large concoction of eggs, diced meat, vegetables, and cheese. She does note, however, that there is a separate serving bowl marked as having no cheese.</p>
    <p>Bryti initially assumes that she is being given a large portion due to her nature, but after she realizes how much food a winged elf can pack away she realizes it's pretty average. After a hearty breakfast, she quietly approaches Thuridan. </p>
    <p>When Allophryne comes to breakfast he’s in a contemplative mood.  He tracks down Anasatri as soon as she’s available.</p>
    <p>“Chu’ got anythin’ needs doin?” he asks, looking somewhat hopeful, “I ain’t much use for most things, but while we here I ken do some work.”</p>
    <p>“Oh! Of course.” Anasatri taps her lip, “Do you have an eye for building? We’ve been working on renovations.”</p>
    <p>“Weh, much as any other I ken say.”  He runs a webbed hand through his hair.  “You need the debris washed out’cher cistern?  Pass a broom over the gutters?”</p>
    <p>“Any of that would be wonderful! Here, I’ll show you where we have our tools stored.” </p>
    <p>Thuridan glances up as Bryti sits down, “Sleep alright? And food good for you?”</p>
    <p>Bryti nods to him, “Yes, perfect. I am beginning to wonder if there is an elven conspiracy to fatten me up so that I do not run so quickly.” </p>
    <p>Thuridan laughs, “You’ve been with the river elves, yes? They’re as big on food as we are. Flying and swimming take a lot of energy. As does running cross-country, I suppose.” He pushes a stack of paper toward her, “When Satri told us you were coming, we put together the questions we had, because we knew we’d forget something otherwise. If you’ll come with me down to the archive, untangling the organization down there is our current headache.” He raises an eyebrow as he stands up, “Some kind of complicated cultural basis to it that we can’t figure out.” </p>
    <p>“Hm,” Bryti takes the page and begins to look it over. And then the second page. And then the one after that. She frowns slightly.</p>
    <p>“No shortage of curiosity, I see.” </p>
    <p>He grins, “Never. But your people left us plenty to work with here.” He heads out of the dining hall and toward the small, nondescript door leading down into the archive. There’s a lot of activity down there; several small podiums have been set up, and a large table is covered in jotted notes. A large slate on the wall has lists, notes, and random diagrams and doodles. Conspicuous on the end of one of the shelves is a large grey feather, decorated with a ribbon and a few small beads. </p>
    <p>Several people glance over as they come down the stairs, but there’s much more curiosity and interest than nervousness. Thuridan takes a stool at the large table and sweeps some of the papers into a tidy-ish pile, “So! Shall we start with that list?”</p>
    <p>“How is your handwriting so tiny…” Bryti grumbles, “I feel like I am in school again. Let me look through this for a few moments, if you don’t mind.” </p>
    <p>Thuridan chuckles, “Of course, take your time. We also do know that observatories aren’t your area of expertise, and there’s no shame in saying you don’t know some of what we’re asking. But you’re the only actual ‘expert’ we’ve got available to us.”</p>
    <p>Bryti sighs, “Well, I suppose that’s your bad luck. My old tutors would be ashamed.”</p>
    <p>She flips through the pages once again as she sits at one of the tables. After her first pass through, she reads through it again more slowly. After a few minutes of reading, she looks up at Thuridan.</p>
    <p>“You don’t actually know all the Ancestor constellations, do you?” she asks. </p>
    <p>“Wouldn’t surprise me,” he says, pulling over a blank sheet of paper. “Satri wrote up that list. What are we missing?” </p>
    <p>She flips through the pages again, “Around twenty?” </p>
    <p>“...<i>Well</i>. Alright, hit me.” He grabs a pen.</p>
    <p>“One moment,” she looks up at the ceiling and begins speaking in Skaplyndi in a singsong voice, “Father Wolf has four stars north, but Brother Bear calls six stars forth… Sister Badger carries five stars west, while Mother Crow has four in nest…”</p>
    <p>It rhymes better in her language.</p>
    <p>She continues for a few moments before glancing at Thuridan, “Perhaps I should simply write it down. It’s a long rhyme.” </p>
    <p>Thuridan glances up from where he’s been transcribing, “I imagine so, if we’re missing twenty of them on top of what we already have listed.” He pushes the paper to her, “So these constellations, each represents a type of Lycan? Are there any that don’t match up to people? Or people who don’t have a constellation?” </p>
    <p>“Yes and yes,” She begins writing down the rhyme, “The old tales of the ancestors were from when we lived in the far north, where our culture came from. Lycans tend to be the type of animals native to their homes, so at the time we knew of only those types of animals that lived there. As we… as the empire expanded south, we encountered many more types of Lycan. Some joined us, others didn’t. There… were religious debates about that. Some wanted to add more constellations… hm. Like I needed to memorize more. That, and some of the constellations represent a core aspect or value that an ancestor embodies, such as old Mother Crow’s nest I just mentioned. Brother Bear has a cave to symbolize his protective nature, and Father Stag has a tree to mark his stewardship of forests… though I always suspected that is because an old starwatcher got tired of making complex shapes and wanted to add a few straight lines…” Her pen scribbles as she transcribes with surprisingly good handwriting. </p>
    <p>Thuridan watches curiously, “Makes sense, there does seem to be an awful lot of variety. Are those used as major navigation landmarks, I assume?”</p>
    <p>“Yes, in a more practical sense, though I was required to observe them as a religious observance. The fact that it keeps me from getting lost all the time is a coincidence, I am sure…” she pauses, “I… never thought my old nursery rhymes would be some kind of… great secret knowledge that must be passed on. Is that how thorough our fall really was?” she stops writing and stares at the page with a distant look on her face. </p>
    <p>Thuridan busies himself with the stack of papers, sorting them into some kind of order while Bryti collects herself. “Did Satri explain the name she slapped on you?” </p>
    <p>She snaps out of her reverie at the statement, “Actually, no. I was rather curious, it hardly sounded random.” </p>
    <p>He chuckles, “You know the rumors about you, I’m sure, that the fire elves started calling you a tourist, and it just stuck from there. Anvesakya means explorer, wanderer… tourist. If people start calling you Sakya, that means they consider you a friend. Or, well, in this case, aren’t afraid of you.” </p>
    <p>"Well it's certainly more dignified…" Bryti looks at him curiously, "I've noticed a distinct lack of armed guards and silver weapons pointed at me. I am surprised by that. Anasatri must have been very convincing, speaking on my behalf." </p>
    <p>Thuridan gestures around the room, “None of us here are fighters. We have some rangers with us, but Varna and Shadimon have been using this as a way to train new scouts. Satri believes the best of everyone and wants to be friends. Yes, she told us that you were friends, but more importantly she told us about your helping the river elves fight, curing some of them of the Affliction, and that you sent a message to check on Shadimon, when, as far as we know, no one else did. We all love Satri, but she’s a bit too optimistic sometimes. However, she’s never wrong about reporting events she’s seen. You even brought a river elf with you, which just backs up her story. So,” he shrugs, “we need the help, and to us, the knowledge you have is worth the risks to us.” </p>
    <p>"In that case, I genuinely appreciate the hospitality," Bryti inclines her head at him.</p>
    <p>"And… Anasatri isn't the only one who is too optimistic." Bryti glances around the room, then speaks quietly, "It cannot last. Anasatri, the river elves… they seem to believe that if they just tell people who I really am, I will be simply accepted and might… live here. That isn't possible. I am not only a Lycan, I am of the <i>bloodline</i>. Whether I want to be or not, I am a walking casus belli for half the nations on this continent. Even if you somehow convince the other elves to tolerate my presence… the hobgoblins, the halflings, the city states, the humans, Hel, Lock <i>alone…</i> it's too much risk. I endanger everything all of you have built here."</p>
    <p>She pauses, "So, I will help you. I… I hate what we made, but I can't let Luna and our ancestors be forgotten. I want to help your new nations thrive, to perhaps balance the terrible legacy we leave, but that's all. I cannot live here. I'm telling <i>you</i> this, because if I told Anasatri or the river elves, they would double their efforts to save me. You, however, seem a pragmatist."</p>
    <p>She gives him a strange look, as if she is looking through him, "I need you to help me make sure the few good things about us aren't forgotten, and I may need you to help them understand why there isn't a happy ending for me." </p>
    <p>Thuridan watches her calmly through her speech, “Is that the only reason you keep coming back? Why you spend time on the flotilla, why you go tearing off across the entire country on a whim? Why you check on people you’ve only met once? Because you’re concerned about the legacy of your people? Or because you’re just a person like the rest of us, and you’re going crazy when you’re all alone?” He points at her, “I am a pragmatist, and you’re not. You’ve got your head as far up in the stars as Satri does, and all they show you is a reflection of the inside of your own head.</p>
    <p>“You’re taking more risks than any of us, by coming to us. All of us here are going to keep this visit a secret until we don’t have to anymore, but the worst we could expect? Political difficulties. You though? Every time you step out of the wild, someone could kill you. But you keep doing it, and I don’t think your legacy has anything really to do with it.”</p>
    <p>He drums his fingers on the table for a moment, “If I understand correctly, Lycans see themselves as both their animal form and their humanoid form. So, as far as you’re concerned, you are a wolf and you are an elf, correct? Both of which are very social creatures. There aren’t any more werewolves, but there are suddenly a lot of elves around here. Will people suddenly like and accept you? No, likely not. But you’ve already covered one of the major hurdles. If Litoria didn’t kill you on sight and the river elves have taken you in? That will go a long way with the others. You are a blade elf, which might confuse them into pausing.</p>
    <p>“My <i>point</i>, which I think I’ve talked around and not gotten to, is this: Don’t let yourself drown in your own head. Don’t let that woe-is-me drag you down, and don’t let other people’s idea of what it means to be a Lycan tear you apart. You seem like a decent person. Presumably you had a family and friends just like we did, and presumably you didn’t wake up every day and think ‘ah, how shall I subjugate other people today?’ Don’t stop thinking of yourself as a <i>person</i> first. It may not help outside opinions, but it’ll help <i>you</i>.” </p>
    <p>Bryti gives him a serious look, "Thuridan… I have found friends here. I have found people I care about. A place it almost feels like I belong. I have found real happiness, all things I thought I would never have again, and that is <i>exactly</i> why I cannot stay here. Not long term. You see the way Allophryne watches me. The river elves, even though they've only known me for a short time, would go to <i>war</i> for me without hesitation. Is it because my lofty bloodline draws me to positions of import, or simply because they think I'm a good person? Is there even a difference? It doesn't matter.</p>
    <p>"I appreciate your concern for me, Thuridan. I genuinely do. In some ways, you are right. It may be possible to convince the other elves to tolerate my presence, and might be worth the risk to try, but the world at large never will. A werewolf of the bloodline will always be seen as a threat, a potential resurgent empire waiting to happen, and now the river elves will <i>absolutely</i> fight to protect me. That's why I cannot stay, not permanently. Not because I don't think I can be happy, but because I would rather <i>die</i> than watch the people who gave me happiness throw away their lives and homes for my sake." </p>
    <p>“It’s their choice, isn’t it. Maybe they’d rather fight than see you dead or exiled. Martyrs, just circling each other and waiting for a chance to jump on a sword first to save the other, hm?” </p>
    <p>Bryti shrugs differentially, "Well, I <i>am</i> a blade elf."</p>
    <p>“With just as much sense, yes. Now, you’ve said ‘bloodline’ several times. What do you mean by that?”</p>
    <p>She raises an eyebrow, "You mean you don't know? I suppose we never spoke much of it to outsiders… hm. I am a descendant of Lord Drogyr the Huntress, the first Lycan Lord who united the tribes and made us one culture and one nation. Her descendants are werewolves of notable strength and stature, but more importantly known for our strength of will and drive. Those who express the bloodline are universally of strong mind and ambition, drawn to great power and great acts by our very nature. Almost all the Lords were wolves of the bloodline, and any wolf of the bloodline will end up being someone important. Many are drawn to conquer, to rule. That is what we have a reputation for. That is what I will be seen as: a potential tyrant in waiting."</p>
    <p>She pauses, "I am not. It… was a surprise when I expressed the bloodline. No one in my family line ever had. I feel the call of my bloodline, yes, but for me it's a call to a different kind of power. One separate from the mortal world." </p>
    <p>Thuridan finishes jotting notes and glances at the sword hilt visible over her shoulder, “Explains a few things. Also why Satri latched onto you so hard. She hasn’t told us what she’s doing alone late at night, but it doesn’t take a genius to make some guesses.” He went back to the paper, his voice very bland, “Your blade elf father must have been a <i>very</i> brave man.”</p>
    <p>She smirks slightly, "He most certainly was." </p>
    <p>“Alright, I’ll stop grilling you on existential questions for a bit. I’ve got some work to do on one of the shelves, so if you’re alright working through that list on your own for awhile?” </p>
    <p>Bryti looks down at the half-finished page in front of her, "Yes, it seems I have agreed to quite a bit of work. I will continue, then. Perhaps I will think of something else that could help you."</p>
    <p>With that, Bryti returns to writing and examining the long list of questions she has. </p>
    <hr/>
    <p>Elsewhere, Anasatri is searching for Allophryne. She had shown him their tool storage after breakfast, but doesn’t know where he’s gone. She wanders the now-familiar halls of the observatory, listening and poking her nose into the various rooms.</p>
    <p>He’s not in the well room, but there are several bags of damp sand.  Anasatri did not expect that he would go back outdoors, but that’s where she finds him.  Allophryne is carefully sweeping dust and sand off of the giant symbol of Luna outside.</p>
    <p>Anasatri walks over to him, lifting one wing to give him a little shade, “Thank you for doing this. The others here don’t know about...what I’ve been doing, and I haven’t wanted to push about it, so it’s just been...neglected. Are you doing all right? Need water or anything?”</p>
    <p>Allophryne gives the winged elf a sharp look.</p>
    <p>“This,” he gestures at the symbol, “it cain’t be neglected no more.”  He walks over to the edge and points out a hole in the stone.  “Thems here is yall’s gutters.  Lookit how it’s canted, an the slope of the ground.  This feeds the cistern, weh.”</p>
    <p>He gives a shrug.</p>
    <p>“Mais, can’t say if it’s Luna’s tears or Her sweat yer drinkin’ but foh shore yall will want to wash Her face more frequent like, weh.”</p>
    <p>Anasatri covers her face and laughs, “I was with you until that metaphor! But really? This is how it fills? We thought it was a spring!” She leans over to study the channels, “We had no idea this was actually practical.” She looks up at him, a bit more sober, “Everyone here is fine with repurposing Lycan knowledge, but Luna is a bridge too far for some people. It’s the one thing we really haven’t sat down to discuss yet. How...do the other river elves take it? You having a connection to Her? Or do they know?”</p>
    <p>“I axe for a connection to Her, an all I git is more of the same from Him what rules the water.”  Allophryne stoops to sweep desert dust into a sack.  “Et’s complicated, weh?”</p>
    <p>“It is. I...can try to help you, if you’d like. It’s hit or miss with both of them, but there’s some magic I’ve had good luck with.”</p>
    <p>"Non," the river elf answers, rubbing the scar on his shoulder, "wouldn't be right to use someone else's magic if'n I can't do this right proper."  He keeps working.  "Mais... if yall don't want to run outa drinkin water yall gotta take care of Her."</p>
    <p>“Thanks, we’ll be sure to get that on the chore list.” She gives him a worried look as he goes back to work, “Will you let me know if you need help? Me or Bryti, if that’s easier. I won’t pry into your business, but if you’re here to try to get in touch with Her, I wish you as much good luck as I can.”</p>
    <p>“Non, cher, I ain’t here to reach Her.”  Allophryne gives Anasatri a sad smile and a slow shake of his head.  “I’m here for her.”</p>
    <p>Anasatri frowns a little and glances back toward the Observatory, “Bryti? What’s going on?”</p>
    <p>“Our wolf’s got her secrets,” the green elf keeps working, “I’m just learnin’ her trade, weh?”</p>
    <p>Anasatri blinks, “Her trade is killing Afflicted with a sword that’s as big as I am.”</p>
    <p>“If’n that’s what you think it is, you ain’t learned enough about our wolf yet.”  He grins, all teeth.</p>
    <p>She throws her hands up, “I’m <i>trying</i>.” She huffs at him, mock-irritated, “Fine, fine, you keep your secrets too.” Anasatri pauses, “But so you know, since she seems to trust you...I need to talk to her about something, and it’s going to hurt. Don’t know if she’ll want to go to you about it, but just in case she does…” She shrugs her wings.</p>
    <p>“<span class="tooltip">Quoi d'autre?<span class="tooltiptext">What else?</span></span>”</p>
    <p>She makes a frustrated noise and looks out away from the Observatory, “More secrets about your wolf. Does Calestros talk to you? With dreams?”</p>
    <p>"Weh?"</p>
    <p>“Just curious.” She shakes her head, “All right, I’ll let you get back to what you’re doing. Thanks again for the help, and fixing up our water system!” She looks up at the sky for a moment before wandering back toward the building.</p>
    <hr/>
    <p>It takes Anasatri until the next day to work up enough courage to talk to Bryti. It doesn’t help that the other researchers are starting to lose their fear of her and the werewolf is putting up with a constant barrage of questions. Late in the evening, Bryti requests a break from research work. Seeing no other way to talk to her alone, Anasatri goes to find her.</p>
    <p>Anasatri finds Bryti standing in the observatory dome. She has lit the lens again and is standing on the edge of the room, looking at the star patterns with folded arms. She gives Anasatri a nod of acknowledgement as she enters the room. </p>
    <p>Anasatri goes to stand beside her, also looking up at the stars. “Is this a good time? I need to talk to you, but I can wait if you need some alone time.”</p>
    <p>Bryti looks down at the shorter elf, “No, it is fine. You are a friend. We can talk.” </p>
    <p>Anasatri sighs, “I may not be after this…” She shakes out her wings and shoulders, “You may not remember, I didn’t put a lot of focus on it, but when I was telling you about the vision Luna showed me, the last thing in it was starfields. A...lot of starfields. I can still remember each of them, and I’ve been combing through the archives here looking for matches. I’ve found a few, but for the rest, I’ll need this thing.” She grimaces, “And apparently a lot more help than I thought. Anyway, as I’ve found matching times and locations for the stars, I’ve had a dream about it, about whatever Luna wanted me to know.” </p>
    <p>She takes a deep breath, “One of the locations was Novarsk, about forty years ago. You told me that you’d met Dreyrugr before. I...saw that. From your perspective.”</p>
    <p>Bryti pauses and turns to Anasatri. She doesn’t look angry, but more confused. She doesn’t respond for several seconds.</p>
    <p>“But…” she takes a moment to collect her thoughts, “You mean… You saw all of it? Not just me and Dreyrugr, but… Katya, Fyrir, Vigr… all of it?” </p>
    <p>Anasatri nods, “From the moment you saw him until Katya led the way home.”</p>
    <p>Bryti breathes out slowly and sits down. She looks up at the ceiling for a few moments before speaking again.</p>
    <p>“That would mean… If you could only see what was already recorded here… that not only did Luna lead you to a vision of that day, but the stargazers here felt the need to record a star chart of that exact night at Novarsk. That’s...  I…” she trails off before picking up again, “I do not understand.” </p>
    <p>“Neither do I,” Anasatri sits down next to her. “You figured that the giant wolf I saw in the first vision was Dreyrugr, but other than involving both you and him, I’m not sure what the connection is.” She shudders, “I’m very, very glad he’s dead. That was...terrifying.”</p>
    <p>She looks back up at the stars, “There was another vision, from Calestros. She’s worried sick about Luna. I saw Luna in the sky, but...cracked, and damaged like in the first vision. And below, she was reflected in water. But it wasn’t water, it was Calestros’s cracked mirror, and the patterns on the mirror and the moon were the same. Calestros said ‘it’s happening again’, and that She doesn’t want Luna to be like Her.” </p>
    <p>She closes her eyes, focusing on the memory, “I don't know why, but it's happening to Her. Oh, it's not right! I don't want Her to be like me. I don't want it to happen again, it shouldn't happen to anyone. I am so sorry Anasatri, so sorry for how I failed my children. She didn't do anything wrong like I did, She doesn't deserve this. Please, don't let it happen again, please make sure She does not end up like me. It's not too late…” </p>
    <p>Bryti puts a hand on Anasatri's shoulder, "Are you alright?" </p>
    <p>“I think so. I’m afraid this is fairly normal for me.” She pauses, “Not...gods talking to me by name, that was new. I just wish I understood! They’re both trying so hard, but I just can’t understand.”</p>
    <p>Bryti stands next to her, "They wouldn't have chosen you if you were not the right person."</p>
    <p>She pauses at that statement before continuing, "You have taken on an incredible burden. There… there is no way to make understanding the gods easy, especially not one who is mad and one who does not speak… trust me on that last one… but… oh… Oh!"</p>
    <p>Bryti blinks, then suddenly turns and gives Anasatri a hug so intense she is literally lifted from the ground. </p>
    <p>Anasatri squeaks, shocked, “What? What!”</p>
    <p>"What Calestros told you!" Bryti answers, "It's not too late!" </p>
    <p>“That’s...true! And if they’re going to so much effort to talk to me, and Allophryne said Calestros talks to him, maybe we actually have a chance of helping? Definitively?” </p>
    <p>Bryti sets the other elf down, "I think that is as close to definitive as one gets when talking to the gods. There has to be a reason for what you were shown, for being guided to me and Allophryne. If it's not too late… then we have to keep trying."</p>
    <p>Bryti gives Anasatri a more serious look, "I remember that day, and think about it frequently. What if I had said or done something differently, what if Katya had, what if I had just left the temple five damned minutes earlier… Dreyrugr was a hateful beast. That was the day he decided to kill my family, I'm sure of it. He would remember an insult like that. It just took him a while to find an excuse. As to why Luna would show you that, or why the keepers would record that day and place… I do not know. One thing is clear to me now, though. I absolutely must help you rebuild this observatory however I can. If what you’re saying is right, it will be necessary for this.” </p>
    <p>Anasatri looks excited, before her expression sobers, “I’d love that. We’re definitely going to need the help. But...I asked you here without talking to anyone else who lives here, and that could have been trouble. For anything...longer term? I think I’d have to ask Shadimon. It’s risky, if word gets out, and that’s not something he should be blindsided by. Not that I think he’d object,” she hastens to add. “But I should at least officially ask. I think.” </p>
    <p>Bryti chuckles, "That explains a few things. Yes, that would be wise. Longer term, though? I am not sure how much help I will be. I have a few stories and a few secrets left still, but after a few weeks of keeping up with your friends, I imagine there won't be much left I can do to help you decipher this place. Still, it seems we are all in whatever this is together."</p>
    <p>“So we are. In Novarsk, you said you had taken the oath of the Purifier, which allows you to carry silver. Are you a priest?” </p>
    <p>"Not… precisely," Bryti begins, "I am a servant of Luna, yes, but my role is a bit more… specialized. I do not serve Her church, nor did I serve the Empire. A Purifier is beholden only to Luna, as my duty is to face the oldest and most foul corruption of Her grace. I fight the affliction, not the afflicted. I fight that curse, and any who might embrace or spread it. I suppose it might sound strange to an outsider, an entire order devoted to hunting down and fighting a single curse in a world filled with terrible ones. If outsiders understood what the curse really is, what fighting it really means, they might realize why."</p>
    <p>Bryti gives Anasatri a level look, "It is my duty to make sure that they don't." </p>
    <p>“The affliction is always a death-sentence,” Anasatri says quietly. “But you can cure it, as well as...fighting it. Allophryne said he had it, but you saved him.” </p>
    <p>She nods, "I fight the affliction, not the afflicted. The afflicted themselves are victims. Even when I can't save them. At least in life." </p>
    <p>Satri thinks for a moment, “If you can <i>cure</i> the affliction...can you stop it from being passed on in the first place?” </p>
    <p>“That is beyond mortal means,” Bryti smiles slightly, “But not beyond Luna. As a blessing to help me carry out my service, Luna has cleansed my body of the affliction. You don’t have to worry about me accidentally nipping Litoria’s cheek with a kiss.” </p>
    <p>Anasatri laughs, “That’s a relief!” She grins and raises her eyebrows, “So how <i>is</i> Litoria doing?”</p>
    <p>“Well, I hope. She’s going to Coldwater to participate in the siege.” </p>
    <p>“They’re taking the fight to Coyote, then? We might see the Harriers go by soon. Shadimon probably has a score to settle, if he can manage it. Can I ask a weird question? Weirder than the other ones so far.”</p>
    <p>“Ask what you wish,” she raises an eyebrow, “I make no promises, however.” </p>
    <p>"What's it like to change shape?"</p>
    <p>"Hm," Bryti gives a distant looking smile, then looks up at the projected stars, "It feels… right. Like returning home, or… perhaps like putting on an old pair of boots that are well worn to you. It is more mental than physical. There is nothing to force or control. The wolf and the elf are both always a part of me, never dormant. It is as simple as… existing. I think of myself of the wolf, and I am, as if I always had been. I have spent many years in each form, so I am quite comfortable in each. Some Lycans prefer one form to another and must focus more to change, but for me? It's simpler than a thought. It's as easy as an instinct." </p>
    <p>“Can I see?” Anasatri gives a lopsided smile, “I won’t be afraid.”</p>
    <p>Before she has even finished the second part of her question, Anasatri is sitting next to a wolf. The change happens so quickly and so quietly that she can scarcely catch it. Bryti's wolf form is still quite large, but not as towering as her other two. Interestingly, her holy symbol does not shift with her. It has five memory beads and a green tarnished copper symbol of Calestros attached to the cord. The wolf peers at Anasatri and tilts her head. </p>
    <p>“Oh, wow, I see what you mean. I didn’t know it could be so quick!” She looks the wolf over, “And everything you were wearing or carrying changed too, except that holy symbol. Why not that? Is it a conscious choice? Oh, you can’t talk in this form can you.” She pauses, “Also you’re much fluffier than I expected.” </p>
    <p>The wolf looks at Anasatri, then glances at her hand. The wolf only rolls her eyes very slightly before lower her head towards Anasatri. </p>
    <p>Anasatri slowly reaches out and strokes between Bryti’s ears, before trailing down to the thick ruff of fur across her neck and shoulders. “Oh wow, how long <i>is</i> your fur?” She works her fingers through the dense fur, her hands nearly disappearing before she finally finds skin underneath it. “Oh, um, sorry, that’s probably not dignified at all…” </p>
    <p>The wolf makes a low noise that might be a laugh before sitting up in what can only be assumed to be perfect wolf posture with a haughty expression. </p>
    <p>Anasatri laughs and reaches up to flick one of her ears, “Right, surplus of dignity. I won’t tell anyone you like being petted.” </p>
    <p>Bryti steps back and shifts to her elven form again. She quietly rearranges her braid. She removes her holy symbol from under her shirt where it has settled and shows it to Anasatri.</p>
    <p>"It is one of the minor signs of Luna's power. A holy symbol of Luna does not change when the bearer changes form, instead finding a place on the wearer's new body. This happens even if the symbol is not magical. Apparently, this includes other small things attached to it. Calestros… seems not to mind." </p>
    <p>Anasatri peers at it, “You <i>are</i> still an elf. Have you ever tried talking to Calestros?”</p>
    <p>Bryti runs a finger over the elven holy symbol, “Allophryne gave this to me on the condition that I try to speak with Her. I… I confess that I have not had the courage.” </p>
    <p>“Ahh, I understand. Probably about how I felt talking to Luna for the first time. I offered to help Allophryne if he wanted it, and I’ll offer the same thing to you.” She smiles a little bit, “I can at least make introductions.”</p>
    <p>“I think I need to do it on my own,” Bryti frowns, “If you can gather the courage to speak to a deity like Luna, then I have no excuse for not talking to Calestros… I am an elf, after all. I will try. I promise.” </p>
    <p>“I understand. Thanks for talking to me, and good luck.” She comfortingly pats Bryti’s shoulder, and leaves her to the quiet observatory. </p>
    <p>Bryti returns to looking at the starfield. She holds her holy symbol in her hands. As she leaves, Anasatri notices that Bryti is running her fingers over the memory beads.</p>
    <hr/>
    <p>Several days later, Allophryne is waiting for Luna to rise. He has cleaned off Her holy symbol. Beneath the layer of dirt and sand was a layer of gray stone, polished until it was nearly reflective. It looks much nicer now, and the drains work much better.</p>
    <p>As he waits for Luna, he hears a low rumble. He glances up to see clouds rolling in. He feels a drop of cool water touch his shoulder. Of course it would immediately start raining on the first full moon, even in the middle of the desert. That's his luck.</p>
    <p>He tries not to get discouraged. He doubts some clouds can stop a Goddess' vision, even if it stops his. Besides, it doesn't hurt to keep asking.</p>
    <p>He stays kneeling in the holy symbol as the storm picks up. It's a surprisingly intense storm. Small rivers of water drain into the holy symbol's depression and start slowly entering the drains. He feels the water touch his knees, and his sensitive river elf skin allows him to feel the flow of water through the entire holy symbol's area.</p>
    <p>The rain picks up until Allophryne can't see outside the holy symbol's area. The water begins to fill the depression faster than the drains can empty it. He stays kneeling.</p>
    <p>Suddenly the rain slows to a stop. He still hears the low hum of rain falling around him. He looks up to see a gap in the clouds above him. rain still falls on the plateau around him, but not his immediate area.</p>
    <p>The water in the holy symbol becomes still. It is perfectly reflective, almost like a mirror. Allophryne sees a glow above him. Luna fills the gap in the clouds, at full brightness. Allophryne can see Her reflected in the water around him, and the water begins to glow faintly with moonlight reflected from the polished stone at the bottom.</p>
    <p>Allophryne feels a presence. A silence, but a patient one. He looks up to Luna. She is listening.  And he waits, patiently, in return.</p>
    <p>“I’m still answerin’ th’ call. Put me to Your service.”</p>
    <p>Silence and stillness answer him. The water around him swirls slightly, making the reflected light shimmer. The presence stays. Allophryne becomes aware of movement in the water. He looks down, and is surprised to see Bryti walking towards him.</p>
    <p>She is in her hybrid form, with her eyes glowing the same blue that they did when she pulled the affliction from his body. As she approaches him, he sees the reflected glow from the water shimmer, then slowly spread to surrounded her like an aura. She walks up to him and stops.</p>
    <p>"Allophryne Allophrynidae," She speaks in a cool voice that sounds almost not her own, "Why do you seek to serve a Goddess who is not yours?"</p>
    <p>"My Goddess commands, weh.  And I axe because I live.  I live an' them don't. Et ain't fair fer me to git a third chance an them not hardly one.  I got to give back.  Mais la, this life ain't mine alone to waste."  He pauses, realizing that he's getting close to tears.  "I don't deserve to live, non, so I best be givin' it back to thems that do."  And that doesn't end in a question.</p>
    <p>"Allophryne…" Bryti's voice is firm, "The only thing you did not deserve was to have our curse put upon you. You owe me, owe <i>Her</i>, no debt. You have done nothing wrong. Luna decided that you were worth saving, with no requirements. All that I ask in return is that you live your life as you wish, without our spectre hanging over you. There were fourteen others cured of the affliction alongside you. None of them are here. You are. This is your choice, not the gods'. You must make it with open eyes. Is this an expression of guilt for those who could not be saved, or is it truly how you want to live your life from now on?"</p>
    <p>"Weh," he nods solemnly, "I can't 'magine anywhat else."</p>
    <p>The werewolf reaches forward and places her hand on the top of her head. Allophryne feels the water around him ripple slightly. A cool, tingling sensation rolls over his skin. His senses open up, becoming aware of things he never had before. He sees Bryti before him in her hybrid form, but he also sees the elf and the wolf, all occupying the same entity. For the first time, he can see what she really is.</p>
    <p>He looks down at himself. He realizes that he has been covered in the same aura of reflected moonlight that she is.</p>
    <p>"Allophryne Allophrynidae," Bryti speaks, "Luna has accepted your service."</p>
    <p>"Thank you," a pause for consideration, "master?"</p>
    <p>The werewolf chuckles. She removes her hand from his head. She speaks with a voice that sounds much more like herself as she says, "<i>Please</i> just call me Bryti."</p>
    
    <p class="center">-FIN-</p>
    <?php 
        include '../../settarget.php'; 
        settarget("River",null,6,11);
        include '../footer.php';
        echo getarrows("../Year/03_4_River.php#back2","../Year/03_4_River.php#back2");
        setlast("Bonus/11_A Scholarly Pursuit.php");
    ?>
</body>
</html>
