<?php
// Experimental DOMDocument version of the rouges_gallery_popups.inc

function nametag($arg1,$arg2) {

}

?>

<characters>
    <id_tag>
        <id>Ehra_Indrek</id>
    </id_tag>
    <full_name>
        <name>Ehra Indrek</name>
    </full_name>
    <colors>
        <race_color>w3-indigo</race_color>
        <race_accent>w3-blue</race_accent>
        <race_hover>w3-hover-blue</race_hover>
    </colors>
    <image>
        <portrait>/Blade/Images/Grandmaster.png</portrait>
    </image>
    <details>
        <detail>Male Blade Elf</detail>
    </details>
</characters>




<div id="Ehra_Indrek" class="w3-modal">
    <div class="w3-modal-content w3-large w3-round-xxlarge w3-indigo w3-responsive">
        <header class="w3-container">
            <span onclick="document.getElementById('Ehra_Indrek').style.display='none'" class="w3-button w3-display-topright">&times;</span>
        </header>
        <div class="w3-container w3-padding-large w3-cell" style='vertical-align:middle'>
            <img class="w3-padding-large" alt="Ehra Indrek" src="../Blade/Images/Grandmaster.png">
        </div>
        <div class="w3-container w3-cell">
            <ul class="w3-ul">
                <li><h3>Ehra Indrek</h3></li>
                <li>Male Blade Elf</li>
                <li>Grandmaster oldman</li>
                <li>Battle Grandpa</li>
                <li>Tends to ramble</li>
            </ul>
        </div>
    </div>
</div>

<div id="Siiri_Maar" class="w3-modal">
    <div class="w3-modal-content w3-large w3-round-xxlarge w3-indigo w3-responsive">
        <header class="w3-container">
            <span onclick="document.getElementById('Siiri_Maar').style.display='none'" class="w3-button w3-display-topright">×</span>
        </header>
        <div class="w3-container">
            <div class="w3-container w3-cell" style='vertical-align:middle'>
                <img class="avatar w3-center" alt="Siiri Maar" src="../Blade/Images/Corpsmaster.png">
            </div>
            <div class="w3-container w3-cell">
                <ul class="w3-ul">
                    <li><h3>Siiri Maar</h3></li>
                    <li>Female Blade Elf</li>
                    <li>Salty healer alchemist</li>
                    <li>Overprotective of Ehra</li>
                    <li>Has had enough of your bullshit already</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="Katiin_Paavi" class="w3-modal">
    <div class="w3-modal-content w3-large w3-round-xxlarge w3-indigo w3-responsive">
        <header class="w3-container">
            <span onclick="document.getElementById('Katiin_Paavi').style.display='none'" class="w3-button w3-display-topright">×</span>
        </header>
        <div class="w3-container">
            <div class="w3-container w3-cell" style='vertical-align:middle'>
                <img class="w3-center" alt="Katiin Paavi" src="../Blade/Images/Warmaster.png">
            </div>
            <div class="w3-container w3-cell">
                <ul class="w3-ul">
                    <li><h3>Katiin Paavi</h3></li>
                    <li>Female Blade Elf</li>
                    <li>Terrible at small talk</li>
                    <li>New to the job</li>
                    <li>Lost her unit and father late in the war</li>
                </ul>
            </div>
        </div>
    </div>
</div>

Shadimon
    <div class="w3-modal-content w3-large w3-round-xxlarge w3-cyan w3-responsive">
        <header class="w3-container">
            <span onclick="document.getElementById('Shadimon').style.display='none'" class="w3-button w3-display-topright">&times;</span>
        </header>
        <div class="w3-container w3-padding-large w3-cell" style='vertical-align:middle'>
            <img class="w3-padding-large" alt="Shadimon" src="../Winged/Images/Shadimon.png">
        </div>
        <div class="w3-container w3-cell">
            <ul class="w3-ul">
                <li><h3>Shadimon</h3></li>
                <li>Male Winged Elf</li>
                <li>Leader, chill</li>
                <li>Would like to quit, too responsible to do so</li>
                <li>Marsh harrier feathers</li>
            </ul>
        </div>
    </div>
</div>