<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../../header.php'; ?>
    <title>
        A Soldier and a Warrior
    </title>
    <link rel="stylesheet" type="text/css" href="../style.css">
</head>
<body>
    <h1>A Soldier and a Warrior</h1>
    <p id="cline">
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    </p>
    <p>Ehra Indrek examines the training report he has been given. His role as Grandmaster is far more than ceremonial. He must examine and approve all additions by the war scholars to any ongoing curriculum or training regimens. This time, it’s a report on river elf Archerfish. The rivers have been a constant presence at the fort this year, and their adaptable forces a welcome breath of fresh air from more sword squares. Maybe not as interesting as the bagpipers were, but still.</p>
    <p>He lowers his papers as there is a knock on the door. One of the swordelves assigned to his protection detail salutes him with a somewhat nervous look.</p>
    <p>“Grandmaster… you have a guest.” He clears his throat.</p>
    <p>Ehra places his papers down on the desk and folds his hands, “A guest? I wouldn’t think that would be an issue.”</p>
    <p>“Well, normally not sir, but it’s Echo of Blood.”</p>
    <p>Ehra raises his eyebrows, “Really? The living mountain has asked to talk to me? He’s been so busy looming around the last few months, I wondered if he could talk.”</p>
    <p>“He, uh, definitely can sir. He wants to talk to you. Kind of demanding to, actually. I told him that we would speak to you as soon as we could arrange a meeting, but now he’s just kind of standing there in the hall…”</p>
    <p>“Send him in,” Ehra answers immediately, “Odd as they may be, the Crag are part of our extended family and until they give us a reason, we will treat them as such. I’d be happy to talk to him.”</p>
    <p>“Uh, yes sir… right now? You’re sure? Want me to get more guards?”</p>
    <p>“No. I wouldn’t have guards when talking to Litoria or Terror, why Echo?”</p>
    <p>The guard gives him a worried look, but only responds with a “Yes, Grandmaster,” as he goes to fetch the Crag.</p>
    <p>Once the guard leaves, Ehra leans back in his chair and wonders what will happen next. He very valiantly manages not to jump out of his chair when a raspy voice speaks directly into his ear. He’s starting to get used to it.</p>
    <p>“Want me to keep an eye out?” Skulk asks from behind him, “That lunk couldn’t spot me if I had a torch up my ass.”</p>
    <p>“No,” Ehra orders her maintaining a straight face, “Stay outside. He’s a guest.”</p>
    <p>“Suit yourself,” is all the Cryptid says before vanishing once again.</p>
    <p>Ehra arranges his papers and waits for the Crag to arrive. </p>
    <p>Weeks of training have prepared Echo of Blood for the single most challenging task he has found among the Sword elves; namely, how to lean and flex as to fit through their architecture, while still maintaining some manner of dignity.  Entering the Grandmaster’s office, he puts this new skill on display, unfolding to full height once within it’s sufficient ceiling space.</p>
    <p>Once there, however, he does not speak immediately.  He usually doesn’t.  He is a man of few words, and those words are slowly considered.  Instead, he opts to merely stare down at Ehra.  His expression is one of disdain… but that is merely an affectation for the uncertainty he feels.</p>
    <p>Ehra stands up from his desk and looks up - way up - at the towering otherelf. He watches the Crag carefully for just a heartbeat before speaking.</p>
    <p>“Welcome, Echo of Blood,” he provides a slight nod of the head as if he were greeting one of his high ranking officers, “I’m told you want to speak to me. Please, speak freely. I am very interested to hear what you have to say.” </p>
    <p>Though he doesn’t move immediately, this seems to be the prompt Echo needed to finally get down to business.  He clears his throat, and then begins his carefully prepared piece.</p>
    <p id="Echo">“Grandmaster.  Honored and Esteemed among the Blades.  I have heard said by many of your ilk that you are the heart, the mind, the soul of the Blade lowlanders. Of what I have seen, if that is true, then the respect granted you is… deserved.</p>
    <p id="Echo">	I come to parlay with you, for as you are revered among all who stand at arms in your people, so too am I revered for my killing prowess.  Of the stories I have heard, many speak that you, too, are no stranger to blood.  And yet, with many more decades of existence you have seen, I would hope you would bear wisdom gained through those years.  You are Honored Senret, a Tutor Revered.  And so, I come bearing question.</p>
    <p id="Echo">What is it that you fear?”</p>
    <p>Ehra rubs his chin, and a weary expression grows on his face, “You don’t ask easy questions, do you? Quite a way to cut to the heart of the matter. You are correct. If it’s not painfully obvious, I am nearing the end of my life. I have seen more bloodshed, death, and loss than some entire cultures. I don’t fear death, I don’t fear bloodshed. I don’t even fear the inevitable loss of life that follows every decision I will make regarding war. Don’t misunderstand me. Every soldier here trusts my decisions, and every death in every battle is felt as deeply as the last. Pain and loss, however, are not the same thing as fear.</p>
    <p>As to what I fear… it is that those deaths, those sacrifices, will come to naught. That the reasons why will be forgotten. That the purpose will become muddied with time. Every death has been with the purpose of stopping the atrocities of the Lycans, with the hope that we could become more than the weapons they made us to be. </p>
    <p>I fear that we will become too soft. That we will lose our edge. That long peace will make us forget why we need soldiers. That the blood and pain will lose their sting. That when another tyrant comes, we will no longer have the strength to stop them,”</p>
    <p>His expression grows more serious, weary, and aged, “But more than anything else? I fear that we will become too <i>hard.</i> When all you have is a sword, every problem appears to need a cut. I fear that we will forget not <i>that</i> we rebelled against our masters, but <i>why</i> it was necessary to do so. I fear that when that next tyrant comes, we won’t stand against them because we have <i>become</i> that tyrant. Blades cut both ways.”</p>
    <p>He gives Echo a curious look, “And there it is, the rambling of an old man. Have I addressed your question?” </p>
    <p>As Ehra speaks, Echo’s expression softens.  Although it seems as though he is always grimacing, always annoyed, now the mask has fallen.  And when the Grandmaster’s speech is complete, it seems as though Echo cannot even manage to meet his eyes.  He gazes over one of the walls of the room, as though intent on it.  When next he speaks, his tone is much softer than before.   </p>
    <p id="Echo">“You fear softness.  You fear hardness.  Even in fear, Lowlander minds travel in dizzying circles.  But…  But I can see that the reverence for your wisdom is earned.  This is not the first time I have seen such circles.”</p>
    <p>He pauses, and looks over at Ehra… before then looking away again.</p>
    <p id="Echo">“Too hard.  Too soft.  You fear the <i>future</i>. The ultimate fate of your people.  The end of…”</p>
    <p>He hesitates again.  He’s looking for words.  He doesn’t know them, for he was never meant to be equipped with them.  So, he’s forced to use the ones he knows.  It is the only way forward.</p>
    <p id="Echo">“The end of your Path.  Where you will be.  Where you are Finished.  To see that such is the greatest fear of a Lowlander… It is not what I expected to see.  Perhaps I did not know what I expected to see.”</p>
    <p>Now, he finally manages to look at Ehra again.  Now, it is anger that crawls across his face… but, strangely enough, not for the Grandmaster, or indeed, any other present.  His words are curt, but low… almost a whisper, by his standards.</p>
    <p>“Grandmaster… do you seek an end to War?”</p>
    <p>“Yes,” Ehra answers without hesitation, “For isn’t that the job of a soldier? To end the war they are set to? I also, however, understand the futility of that task. We can end a war, yes, but ending war itself? It will never be possible, and we must understand that.  I believe we must also understand, however, that there is merit in trying. That it should be our goal, if not our endpoint.”</p>
    <p>Ehra pauses, giving Echo a curious look, “Your summary is quite accurate. And end to our Path, where we will be, what you we will become… You have to understand. The Lycans created a path for us. To be unthinking, unfeeling weapons. We turned away from that path, and forged our own. To believe that our skills can be used for our own ends, to support our own beliefs. That path is one we have decided on for ourselves, and every step we take is new ground. I do my best to keep us on that path, but…” he shrugs, “Mortality, like war, can never be conquered.” </p>
    <p>The anger crawling on onto Echo’s face seems to take on a brief life of its own.  As Ehra explains the futile task that is pacifism, it flare into a rictus of fury, his teeth grinding together.  Before it can go further, however, Echo masters himself, biting the inside of his cheek hard, hard enough to draw blood… normally.  Fortunately somewhat for relations, said blood does not fill his mouth.</p>
    <p>As Ehra finishes, he still takes another spare moment to calm himself before speaking. Even so, his words are halting, and uncertain. </p>
    <p>“And so now, you, your people, are here.  Stranded in the present.  You do not have a destination you know exists.  Only a Pace and Vector you hope will take you there.  But with no guide, no certainty, you have no way to know even whether your Vector has already strayed.” Giving voice to it seems to bolden him.  Firm his resolve.  </p>
    <p id="Echo">“Wizened Senret, you have exposed your fears to me.  A trusting act.  A trust that should not be betrayed.  To return this kindness… I must tell you of an ancient Wisdom.”</p>
    <p>He begins to recite from rote, words he has heard over a hundred times before. </p>
    <p id="Echo">“There is an Ancient Wisdom of the Aggro, stretching back across time, to the time before the Aggro were the Aggro, before even the Crag were the Crag.  In the Times of the First Generation, those who survived the predations and depravities of the lowlands to begin their way along the Path, there were those who knew that even protected, Strife would be a constant companion.  Among them was a one of Wisdom, to whom a question was placed; ‘We have all know Strife, for before, it is all we knew.  We have seen the mistakes and misfortunes.  How may we avoid them?’  To this, the Wise replied: ‘The failings of before was not in strength, not in body, not in mind.  The failings of before were in soul.  Before, we would fend off Strife.  We would dismiss it, hate it, banish it.  Strife, however, knows no boundary.  It is held by no wall.  It fears no weapon.  To avoid these failings, we must not be as before, not be Guards, not be Soldiers.  We must be Warriors, for War must not be our enemy, it must be our Self.  We must become Strife.’  ‘Wise,’ they asked once more, ‘None of us have been Strife, none have truly been Warriors.   How will we know when we travel true?’  To this the Wise finally replied, ‘Question this in your hearts; do you wish Strife to end?  For that will be the truest telling between Warrior, and mere Soldier.  The Soldier wishes to survive to the end of War, so he may cease being a Soldier.  A Warrior does not wish for an End to War; it would be as a Potter seeking an end to Clay, a Farmer seeking an end to Rye.  War is what we seek.  Strife is what we cultivate.  Struggle is what we know.  Feel this in your hearts, and you will know; Whether you be Soldier… or Warrior.’ ”  </p>
    <p>This is the longest stretch Ehra, or any sword elf, or really anyone else down in the lowlands, has seen an Aggro speak.  It’s somewhat disconcerting how he manages the tale in a single breath.  Echo’s gaze was wistful, far away as he recited, but now snaps back to the Grandmaster.  </p>
    <p id="Echo">“It seems a great wisdom, quineg?”</p>
    <p>Ehra gives the massive Crag a surprised look, “It does seem so. I am glad to know that the Aggro are taught philosophy, and that you know it so well. I… think I’m starting to understand. War is not for the meek or shy. If all you want is to end it and survive, then you will be overwhelmed by an opponent who is truly willing to risk any cost to win, who is willing to embrace conflict. On that, we can certainly agree. Let me make myself clear, Echo, before we continue. I want you to speak freely. If you consider me a coward, call me a coward. I’ve been called much worse, by people far more terrifying than you. No tricks. I am genuinely curious. Since I consider myself a soldier rather than a warrior, do you consider me a coward?” </p>
    <p>Now it’s Echo’s turn for surprise, and curiously, a note of mirth.  </p>
    <p id="Echo">“A coward?  Are there those that call you that?  Do they call you a dweeb or plopface as well?”</p>
    <p>Ehra chuckles, “You’d be surprised…”</p>
    <p>As quickly as Echo’s mirth appeared, however, it vanishes.  </p>
    <p id="Echo">“Perhaps it has stronger force in this place, but it seems a juvenile insult, when used among those of the sword.  No.  I do not call you a coward.  I call you a soldier.  Or, may have.  Now, I am uncertain as to the true meaning.</p>
    <p id="Echo">The tale is a nice one, well placed to help juves and youths to learn of our place.  But, from what I have seen… it is an <i>ignorance</i>, if not a deliberate <i>falsehood</i>.” </p>
    <p>He sweeps his arm, as if to indicate the whole of Fort Alfyr, but ends up smacking it against a nearby wall.  He does his best to shake off the gaffe.</p>
    <p id="Echo">“You are Soldiers, seeking your opportunity to abandon war, hoping, waiting for its end… except in no way have I seen that to be true.  You prepare, you train, you, greatest of their Wisdom, espouse the truth that Strife is ever present.  Yet, still, you have those who will prepare earnestly for war, anticipate it’s approach, make it your life, as Warriors are… and then, perhaps, seek another calling in time, as Soldiers or Guards would act.  It is unfamiliar.  It is perplexing.  And… it illuminates the Fear I now share in the balance.</p>
    <p id="Echo">I do not fear bloodshed.  In truth, when that flows, only then do I see the world as it is.  I do not fear death.  I have seen it’s approach, stared into its eyes, and yet each time, it is the first to blink.  I do not fear the loss of my Kin to war and strife.  They fall honored, having performed the Duty of the Aggro to it’s ultimate culmination, saved the embarrassing predations of time and entropy upon their form.  There is no threat that I have seen and faced, and felt any trepidation to what must be done to defeat it.</p>
    <p id="Echo">But, ever since I descended into this dizzying land… since those creatures thrust themselves into our haven and tore down all sense, plunging us into insanity… since I travelled the maddening greens in search of unyielding Vengeance…  I find myself, time and time again, faced with a fear I have never known before.</p>
    <p id="Echo">Fear of <i>Ignorance.</i>  Of the Threat I do not see, for I have never imagined, never been told of its existence.  Of the unfamiliar, the alien, the incomprehensible.  For all too often, my strength against such is <i>wholly useless.</i>  And the lives of my ilk I spend?  <i>Spent without Purpose!</i>”</p>
    <p>That rictus of rage stands out on his face once more, threatening to consume his whole being.  Still, it is held just barely at bay, as he grunts out his pleading question.</p>
    <p id="Echo">“Grandmaster, Wisdom of the Blades! You fear the future, but to I, it is the Present that is the truest foe, for it thrusts me into the wailing vortex of <i>insanity!</i> All I know is called into question.  How do you know what you <i>know</i> is <i>true?!</i>” </p>
    <p>Ehra smiles, “Echo of Blood, there is great wisdom in what you just asked me. You… are right. One cannot change the past or the future, only the present. Like any other fight, we must make every motion in the present, as this is all that exists.</p>
    <p>I can only answer that question personally. For me… I understand that wisdom, like strength or skill, is not an endpoint. It is not something that someone reaches and sits on their laurels showing off like a trophy. Like muscle, it atrophies. Like skill, it depreciates. Wisdom, like prowess, is constantly challenged. It must be constantly exercised and strained to be effective. Hm, I think I can explain. We live in the present, yes? We fight in the present, not the future. You are no stranger to a fight. If you are in a fight to the death, knowing that we live in the present and cannot see the future, how do you know that you are winning, even if you are close to death yourself?” </p>
    <p>A change seems to come over Echo.  Although struggling with his temper, the Grandmaster’s calm and confident tone seems to pierce through the red fog.  In particular, the last question seems to elicit a canned response; </p>
    <p id="Echo">“Personally, Tactically, or Strategically?”</p>
    <p>"To keep the metaphor going, let's start with personally." </p>
    <p id="Echo">“You must look to posture, stance, speed; all the signs of exhaustion.  Once deprived of the strength of their body, then whatever injury avails, an Aggro knows the fight is won.” The response is automatic.  Despite his ongoing crisis of faith, he seems to still accept this basic truth. </p>
    <p>"And tactically? Strategically?" </p>
    <p id="Echo">“Tactically, you must look to their disposition, their formation, their eyes; all the signs of fear.  The Body may win the Personal fight, but it is the Spirit which wins the Tactical, for once robbed of their will to fight, no amount of strength will prevail.</p>
    <p id="Echo">Strategically, you must look to equipment, numbers, and skill; all the signs of capability;  While Body wins the Personal, and Spirit wins the Tactical, it is the Mind which wins the Strategic.  Deprived of resources, reserves, and resolve, no amount of strength will win, no amount of will will continue the fight.</p>
    <p id="Echo">In these three fields, the Strife is thus concluded, and thus in all three fields must an Aggro excel.”</p>
    <p>The massive Crag, though looking at Ehra, seems to be looking more through him than at him.</p>
    <p>Ehra takes the look with the same calm attitude as before. His tone is not one of condescension or rote instruction, but of genuine interest and insight, "Outstanding answers on all three counts. Now, when you take all three of those answers and boil them down to their most basic, how are they the same? When rendered to their most essential form, what process do all three of those methods follow?" </p>
    <p>To this, Echo does not have a rote response.  But eventually… </p>
    <p id="Echo">“They are based on what you can see.  What can be observed.   Unless there is some deeper wisdom you pursue?”</p>
    <p>Ehra smiles, "Actually, that's the exact word I was hoping you would use. Observe. We are mortals. We are finite, our perspectives limited. We can only see the present, and merely guess at the past or future. To solve any problem, we must observe that there is a problem. You can't change the past and you can't see the future, so do your best to understand and pay attention to the present. Not to pry into your business, but judging by your questions, you’ve already completed this step for whatever question is plaguing you.</p>
    <p>“So your next step is to Orient. Orient yourself in time and place, as well as in perspective and culture. You can’t win a fight while wondering if you left the kettle on, similarly you can’t solve a problem while wondering what might have happened to change it. Focus on the present, and orient yourself to all available information and factors that may influence your decision. By coming to me with questions, I believe you are trying to orient yourself in the world. That’s a good start. I suggest accepting your flawed and limited viewpoint as a mortal, discovering what factors may influence your decision in the present, and accepting that you can’t possibly know everything.</p>
    <p>“Next, of course is Decide. I’m sure you’ve seen many a warrior on a battlefield freeze. They can see the enemy, they know what must be done, but they cannot decide what to do. That, of course, kills. The same goes for any decision. Get too carried away with what-ifs, and if-thens and you will spend so long planning a course of action that the opportunity passes you by. Accept that you will never make a perfect plan, understand the points that you have observed oriented on, and make the best decision possible with the information you have. A mediocre decision in time is better than the best plan that arrives too late. So, understand what you wish to happen - what your goals really are - and decide the course of action that you have available now that gets you as close as possible to those goals.</p>
    <p>“The last step is, of course, to Act... “ Ehra chuckles, “And well, Echo of Blood, you do not strike me as the kind of individual who has problems with that step. So you see, you have already been accustomed to the types of action that you need now. Personal, tactical, strategic, or lifelong, it’s simply a matter of scale”.</p>
    <p>As Ehra continues, Echo’s expression becomes one of, well, relative serenity.  His scowl drops, but rather than being replaced by some other obvious emotion, it just becomes flat, and calm. </p>
    <p id="Echo">“You… Grandmaster, your speech is nearly the perfect twin of one of those who tutored in my youth.  Different words, a different truth, but all the same presented with such solemn wisdom.  That I could find it here once more… it is shocking.  Perhaps, at this point, it should not be.</p>
    <p id="Echo">There is an Aggro Aphorism.  ‘We are the Uncut.’ It is recognition of much of what you say.  We are unfinished.  But, with every blow struck against us, ever cut and chip, we become more finished.  We will fail.  We will suffer consequences.  But through failure, learning. It was a fitting saying for what we are… what we were.</p>
    <p id="Echo">Now, I do not have the luxury to fail so many times as to learn the perils of the Lowlands through such trials.  I have… done so, far, far too many times already.  I am held in great esteem among my kind for my prowess, for my ability.   But my people do not need slaughter.  Not today.  Today, they need Wisdom.  They do not need a Warrior.</p>
    <p id="Echo">They need a Warmaster.”</p>
    <p>Echo points a massive finger at Ehra.  There is burning intent in his eyes.  A promise of a goal chosen.  Of a path, waiting to be charted.</p>
    <p id="Echo">“Your kind pride themselves on their knowledge of war, their preparation for it, how they have embraced it.  That pride is deserved.  And yet, it is your claim that you do not wish to see that pride hoarded.  You wish to share it with all.  I call you to give truth to your word.</p>
    <p id="echo">I have seen more than enough of how Lowlanders fight, Grandmaster.  Now, I will learn how Lowlanders <i>War</i>.  Not from any of your Lessers.  They have their strengths, but though I am unlearned, I will not tolerate any chance of failure.  I will not tolerate any Truth unlearned.  I will not tolerate my ignorance any further.  Not. A. <i>Single. Time. MORE.</i>”</p>
    <p>Ehra’s expression is serious, with a hint of a smile restrained, “The Academy is open to <i>all</i> elves. This includes the Crag. You are welcome here, as is your knowledge. Truthfully, from what you have told me, I am quite interested to learn more of how the Aggro handle Strife. The wisdom of your ancestors must have been hard earned, and I imagine there is much even we could stand to hear from it.”</p>
    <p>“Echo of Blood, you are formally invited to attend the Academy at Fort Alfyr in any capacity you wish, be it alone or as part of a larger training effort. My personal aid and that of the war scholars is yours, provided you allow us to also learn of the ways that you make war. I… admit, I’m surprised by you, as well as the other Aggro I have met, such as Embebi. I’m quite eager to see what your impressive determination can manage. Is that acceptable, Echo?” </p>
    <p>At the mention of Embebi, Echo is once again surprised, but the name actually causes a staccato mix of emotions; happiness, sorrow, anger, and ultimately, resolution.  </p>
    <p id="Echo">“It is acceptable and more, Grandmaster.  This very hour, I will speak to those Euclast who travelled with me.  Those who do not share the merit of your wisdom will be dismissed to return to our home.  For those who remain… they shall remain true until our ignorance is slain.  As you have said, I shall learn my fill, until I never again will be bested, not by others strength, but by my own <i>infirmity.</i>” </p>
    <p>This word is spoken with full venom, filled with an uncomfortable degree of loathing.  </p>
    <p id="Echo">“In return, you will have the knowledge I hold of war, and more.  Lead me from ignorance, and I will do what I know how to do.  The one ignorance I do not hold.  <u>I will free you from those you consider foes.</u></p>
    <p id="Echo">Bargained well, and done, Grandmaster.  I will return only with the truly Determined in tow.”</p>
    <p>With that, he begins the slow and careful process of flexing his way out the door.</p>
    <p>“Echo,” Ehra stops him with a carefully calm word, “I do have one last piece of advice, given freely if you would listen.” </p>
    <p>Echo stops in the doorway, dignity in peril but still holding for now.</p>
    <p>“It is the nature of us mortals to make mistakes and fail. It is the burden of leaders that the mistakes we make fall on the lives of others before they fall on ourselves,” Ehra pauses, and speaks very respectfully, “The best we can do to honor those who fall in the name of our own flaws, is to learn from their sacrifices and move forward determined to never make the same mistake twice. No amount of self hatred has ever brought back the dead. Trust me. I have tried.” </p>
    <p>Hanging in the doorway, Echo’s head dips.  Again, his tone becomes low.</p>
    <p>“You even understand what it is to Be Uncut.  Incomplete.  Unfinished.  Refined with every strike.”  He closes his eyes, turning away from Ehra.  “It seems the hidden Wisdom may be that your Ilk is more alike to Aggro than any other Crag could hope to be.”</p>
    <p>He opens his eyes, staring into the hallway.  “I fear to learn how True that Wisdom holds.” </p>
    <p>Then, unless otherwise stopped, he leaves as intended. Ehra doesn’t interrupt him again as he goes. He returns to his desk and sits down heavily. He makes a mental note to warn his war scholars that the living mountain was going to be coming to them for training. That was going to get interesting. He takes a slow breath and reaches for his paperwork.</p>
    <p>“We coulda taken him,” Skulk whispers behind him.</p>
    <p>“Thank you, Skulk,” Ehra hisses through clenched teeth as he tries not to have a heart attack.</p>
    <p class="Center">-FIN-</p>
<p id="cline">ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc</p>


    <?php 
        include '../footer.php';
        echo getarrows("../Year/03_3_Crag.php#jump","../Year/03_3_Crag.php#jump");
        setlast("Bonus/2_A Soldier and a Warrior.php");
    ?>
</body>
</html>
