<head>
    <link rel="stylesheet" type="text/css" href="../style.css">
    <title>
        Fire Elf Leadership
    </title>
</head>

<body>
<h1><strong>LEADERSHIP</strong></h1>
<h2><strong>Central Leader</strong></h2>
<!--<p><em>&ldquo;We all died at Muspelham. You just aren&rsquo;t in your grave.&rdquo;</em></p>
<p><strong>The Terror</strong> started the Conflagration as Aquila Leafsplitter, Signifier of Black Eagles &ldquo;free legion&rdquo;, and divine champion of Calestros. And started is an accurate term; it was her fault Muspelham fell.</p>
<p>Five times she challenged Lycan champions in the open field, defeating &lsquo;skinwalkers&rsquo; twice her size in open combat, and rallying the Black Eagles to victory against unlikely odds. Six times she cast down Lycanthropic warriors, humiliating them at the gates of their own cities, and sending them back shamed or dead. Seven times the Black Eagles flew free, evading traps laid out by Lycan generals, or shifting through loyalist auxiliaries like water through a sieve.</p>
<p>Eight times would be more than the Lycans would stand; they made this quite clear to the governor, and posted signs throughout Muspelham to that effect. They knew the Black Eagles came from Muspelham, but not where they hid or how to catch them; the only response they had been left was to burn them out.</p>
<p>The Terror that rose from burnt Muspelham and dragged her brethren from the ashes of their former lives was no longer and could no longer be a paladin of Calestros; the divine power had been burnt from her, and replaced with a newer, angrier source -- one that cursed her god for this terrible fate, her former commanders (most of whom were dead), and herself, for inviting the Lycan scouring with her arrogance and bravado.</p>
<p>As the last senior officer, and one of only three leaders to rally Muspelham and survive, the Terror took it upon herself to right the wrong she had created. She stood with the other two, whose names she&rsquo;s deliberately forgotten, and with them forged a bronze mask from the shields of her former commanders, and donned it, swearing to speak rarely, and never again with the bravado and false-courage that had killed so many. Aquila Leafsplitter was forgotten; instead, there would always be the Terror.</p>-->
    <p><b>The Terror</b> is both the true leader and the military commander of the Triumvirate. It was her skill and wrath that brought the Fire Elves victory in the Rebellion, her leadership and presence that forged the survivors of Muspelham into a cohesive whole, and her strength and hatred that put helped put Dreyugr down for good.
Stolid and silent, the Terror speaks little, and when she does so, it is with a voice that sounds of grinding metal, or whispers as if out of a empty grave. She is quite good at getting her point across with gestures, body language, and sheer looming presence. Descriptions of her as "the scariest elf still living" are not necessarily inaccurate.
Most Fire Elves credit her with pulling the survivors of the Conflagration together into an armed band and people in their own right. The speculation as to who she was before she chose to 'bear a mask' (a ritual that has oodles of speculation in its own right) is rampant, but most generally assume that she was a high-ranking Elven commander -- perhaps even the commander of the Black Eagles, the Imperial Auxiliary Legion that joined the rebellion well before Muspelham burned. 
Its well known that the Charred Eagles, the Fire Elves' most veteran unit, and the only company to entirely survive the Battle of Skaplyndi and the end of the war, started as the remnants of the Black Eagles. Its also well known that the Charred Eagles serve as the Terror's personal command. Beyond that? Rumors run wild. All that is really known is the Terror is a skilled commander and a horrifying combatant.</p>
    <p><strong>High Concept</strong>: A silent, bronze-armored warrior-knight whose tenacity dragged the survivors of Mispelham from their ashen graves, now committed to protect against shackles real and imagined.</p>
<p><strong>Trouble Concept: </strong>Inferno<br />Once committed to an action, physically or emotionally, the Terror cannot and will not stop until the finished.</p>
<p><strong>Character Levels: </strong>Bloodrager 10</p>
<p><strong>Cohort: the Smoke</strong></p>
<!--<p>The daughter of a farm family that lived outside of Mispelham, Vita Grassforest and her parents and siblings had the ill-luck to be in town making necessary trades when the Conflagration hit. Emerging from the ashes terrified and coldly furious, Vita latched onto the Terror as the sole source of stability in her changed world. At first she tried to serve the Terror as a page and squire, but her keen intellect (and poor physical strength) rapidly pushed her into logistics and strategic support, where she showed subtlety, a keen eye for weaknesses, and a skill at turning a disadvantage into an edge. That, combined with her early tendency to follow the Terror around, earned her the nickname &ldquo;the Smoke&rdquo; from some of her less respectful coworkers.</p>
<p>Since Skaplyndi, Grassforest has been leading and coordinating several of the largest bands of lost Fire Elves, using her good forestry skills and spellcasting ability to guide them safely through the wilds of the former Lycan territories; some refugees were even considering creating a new Triumvirate with her at the lead, should it have turned out that the battle of Skaplyndi had been lost. That said, for all of her subtlety in battlefield tactics, her tendency to browbeat the opposition and flood the forum with her ideas has earned her more than a few enemies.</p>
<p>Grassforest is short, even for a Fire Elf, with pale orange-brown skin and a large tuft of curly black hair, fading to brown and grey at the edges. She often attempts to hide the hair with a fairly traditional pointy hat. Her ears are narrowy and pointy, and split to two points asymmetrically along their length. Of the Fire Elf leadership, Vita is considered one of the most generally cheerful -- though more than a few have learned that the smile on her face isn&rsquo;t always a friendly one.</p>-->
<p>Character Levels: Witch 6 (Patron: Trickery)</p>
<h2><strong>Arcane</strong></h2>
<p><em>&ldquo;Fire will be our home the way that chains and ash never were.&rdquo;</em></p>
    <p><b>The Fury</b> -- both the most vivacious and the most volatile member of the Triumvirate. She is nominally in charge of arcane and thaumic functions and activities in Surt. In practice, she is also the most social member of the Triumvirate, and thus the most willing to participate in and lead public events, or listen to the requests of the citizenry and advocate on their behalf. In that way, she acts as the "Vox Populi", balancing against the Hunger's bureaucracy and the Terror's leadership.
She's also considered the most erratic of the three. Sorcerers are often viewed as the most "unstable" of the arcane spellcasters, and her preference for and unusual power with fire and fire-oriented spellcasting has done little to diminish that reputation. Neither has her tendency to wear her heart on her sleeve (or on her skin, in blinding pulses of light and regularly charred furniture).
Despite this, she is the most generally popular Triarch, with many Fire Elves (the Ashen especially) crediting her directly with their survival in Muspelham and the physical changes brought with it. More than a few elves only survived the Conflagration because the flames she brought with her sealed wounds and rebuilt charred bones, and few have forgotten it.</p>
<!--<p><strong>The Fury</strong> started the Conflagration as Aelia Bonebear, court sorcerer and slave to the Governor of Muspelham. And started is an accurate term; it was her fault Muspelham fell.</p>
<p>Suave, smart, and sorcerous, Aelia had glided through the Governor&rsquo;s court, bound to the Governor&rsquo;s ownership, but utterly untouchable by the rest of the court -- a situation she revelled in, for what better source for rebellion intelligence than the Governor&rsquo;s own sorcerer-bodyguard?</p>
<p>But &lsquo;spy&rsquo; was never a title enough for Ae, and the descriptions used by others in the court -- the &ldquo;trophy sorcerer&rdquo;, the &ldquo;Governor&rsquo;s bed-warmer&rdquo; -- ate and festered at her insides. Was she not a powerful spellcaster? It was her might and her mind that the Rebellion needed -- wasn&rsquo;t it?</p>
<p>The Governor kept a menagerie -- a host of living trophies taken in his youth, or given to him by privileged elites or power-hungry adventurers. Within it dwelled a white Phoenix, bound by Lycan mithral, and treasured by the Governor, who thought it could grant him eternal life. Ae arranged with the Governor to conduct rituals she promised would get him closer to that, as cover for other rituals the Phoenix promised would free them both.</p>
<p>And at the last second of the final ritual, she panicked.</p>
<p>She awoke to a city in flames -- the Conflagration, at its height -- leaking a torrent of fire that turned stone to ash, but poured life back into the dead. It was that fire that reshaped her, and changed the dying elves of Muspelham to flame-filled survivors whose breath smoked and eyes burned like coals.</p>
<p>As the savior of the few (and in her mind, the killer of the many), Ae took it upon herself to give her &lsquo;victims&rsquo; a better future, where the slavery and death of the past could stay dead and buried. She stood by the side of the other two leaders -- names she never learned -- and with them forged a bronze mask from the chains that bound her in life. In that moment, Aelia Bonebear was erased, and only the Fury remained.</p>-->
<p><strong>High Concept:</strong> A brash youth dreaming of a bright future, who is perhaps a little too sure of herself, and definitely too eager to burn away the past.</p>
<p><strong>Trouble Concept:</strong> Erratic.<br />Despite her best intentions, the Fury's mood (and attention) can be fitful, and her interest in any topic can go from overwhelming to sputtering in an instant.</p>
<p><strong>Character Levels:</strong> Sorcerer 7 (crossblooded)</p>
<h2><strong>Civil</strong></h2>
<p><em>&ldquo;The fault is not within our stars, but in ourselves.&rdquo;</em></p>
    <p><b>The Hunger</b> is the bureaucratic wing of the Triumvirate. During the war, he was head of their logistics, and a strong proponent of the resource-denial strategy that helped to cripple and ruin the Lycans' ability to respond and retaliate. Since then, he has been their foremost settlement planner and lawmaker, using his considerable financial and litigation talents to plan the Triumvirate's short and long term strategies and overall economic policies.
He is also rumored to be a skilled alchemist -- based in part on the skills and supplies he provided during the Conflagration (such as the Wolfsbane Test and similar alchemically-baed Lycanthropy detection systems), and part on suggestions that the "mask ritual" that hides the Triumvirate's old identities was his idea.
The ritual helped to conceal the Triumvirate from magical spying -- an important advantage, given the Lycans' notoriously powerful divine support, and the rebellion's overall limited resources. It also serves to hide all three Triarchs' previous identities, clouding memories and obscuring details, so that not even their own families (if any) would recognize them.
This has, of course, led to numerous rumors about who the Hunger truly is. Most of them are quite dark.</p>
<!--<p><strong>The Hunger</strong> started the Conflagration as Gaius Freshleaf, tax assessor, popular public servant, and secret alchemist. And started is an accurate term; it was his fault Muspelham fell.</p>
<p>&nbsp;As &ldquo;free&rdquo; as an Elf could truly be in Lycan society, Gaius revelled in what he considered the simple things -- his estate, twice the size of the average hovel; his position, respected and treated as intelligent by all Elves and the occasional Lycan; and his popularity, for there were few in Muspelham who had not heard of Gaius Freshleaf. True, he earned some of that -- a few bookkeeping tricks could save families and lives, and earn the Governor&rsquo;s respect at the same time -- but he always believed he acted only for selfish reasons, and the love of the people was merely a side effect of his luck and cunning.</p>
<p>But the Governor&rsquo;s respect turned into the Governor&rsquo;s employment, and with a bit of cunning and a new partner, Gaius found himself reveling in a new passion -- alchemy, and the pursuit of eternal life, that glorious goal promised by Calestros but forever dangling out of reach. Gaius was a mad hand at it; years of detail work and eagerness for tricks and experimentation came to fruition, and he rose from mere bookkeeper to Second Apprentice in a mere decade.&nbsp;</p>
<p>And then the Conflagration. What should have been a minor experiment -- an attempt to gift the power of dragons onto the only subject on hand (himself) went out of control, spinning out into an unstoppable wave of flame that welled out of his secret lab and left him shrieking and burning on the laboratory floor. When he finally rose, his skin had reddened, and the houses outside were in cinders. Frantic, Gaius dug through the rubble, pulling the living from the debris, all the while screaming &ldquo;I&rsquo;m sorry&rdquo; until his voice became a dusty croak.</p>
<p>But the survivors needed leadership, and Gaius&rsquo; thoughtful demeanor and clever nature made claiming a position easy. A necessary decision, for was it not his hand who sparked the fire? Should it not be his job to rescue them? And who else but a grand alchemist could help the Elves of Muspelham recover from this setback? Who else would be ready if the Governor ever returned?</p>
<p>He stood next to the two other leaders -- whose names he wrote in code, on a scrap of parchment buried beneath his old lab -- and forged a bronze mask from the Governor&rsquo;s favorite dining set.</p>
<p>It wasn&rsquo;t for nothing. It can&rsquo;t all have been for nothing. It <em>will not</em> be for nothing, even if the Hunger has to lay every brick, scribe every scroll, and carve into stone every memory of Muspelham <em>by himself</em>.</p>-->
<p><strong>High Concept:</strong><br />A clever and popular politician and civil servant, with no small skill at oratory, laws, and business, who hides from the public his dark alchemical experiments and unsavory former apprenticeship.</p>
<p><strong>Trouble Concept:</strong> Voracious<br />Driven towards power, victory, and immortality, and callous towards their expense in resources, alliances, and lives. Cunning, implacable, and ruthless, even when unnecessary.</p>
<p><strong>Character Levels</strong>: Alchemist 7</p>
<h2><strong>Ashwalker</strong></h2>
<p><strong>Ashwalker Auburn Tsun</strong> -- Born to expert horsetenders who perished in the Conflagration, Auburn Tsun is the youngest political leader among the Fire Elves, and one of the only leading organized monastic warriors left among them. Tsun joined the War Scholars immediately after surviving the Conflagration; sadly, before the war&rsquo;s end, most of the serious scholars were long dead.&nbsp;</p>
<p>The Mispelham &ldquo;War Scholars&rdquo; dropped the name not long after the fall of Mispelham, transitioning mostly into scout and archer roles. In time, these eventually formed into a new tradition -- the &ldquo;Ashkin&rdquo;, a semi-derogatory name picked up from Lycan auxiliary forces. As an unusually fast and skilled warrior, Auburn Tsun rose rapidly through the (frequently cycling) Ashkin ranks.&nbsp;</p>
<p>And even monks can be swayed with strong rhetoric. Despite her harsh origins, Tsun is not a bitter, or even xenophobic individual; she has adopted the Conflagration as a moment of change, a trial that reshaped the Fire Elves into a new creation, free from the curse of the past, to stand united as something entirely new. The view she has impressed on the followers of Ash (Ashen, Ashkin&hellip; there are as many names as there are microfactions, and almost as many microfactions as there are Fire Elves) is that the past must die, and a new, united people are all that matters.</p>
<p>In person, Tsun is quiet and reserved; friendly but distant to most, especially outsiders.&nbsp;</p>
<p><strong>High Concept</strong>: A grim monk who sees strong relations with outsiders as risking the Fire Elves&rsquo; future in the name of their lost past.</p>
<p><strong>Trouble Concept</strong>: All Will Be Fire<br />From her position, to be a Fire Elf must mean to exclude outside influences and embrace solely your origin and your rebirth. Outsiders who have not been reborn as such will inevitably try to tear you back down to your roots. Thus, Fire Elves must be united and of the same culture, or they will be lost.</p>
<p><strong>Character Levels: </strong>Unchained Monk 6</p>
<h2><strong>Phoenix Lord</strong></h2>
<p><strong>Phoenix Lord Barrabus Leafstorm</strong> -- Barry to his friends, &ldquo;Barrabus!&rdquo; to his numerous enemies -- is a well-established gentleelf, known for his fashionable clothing, derring-do, and bravery in the face of insurmountable odds. Of those, only the first is truly accurate.</p>
<p>Barrabas was once a lowly musician in the governor&rsquo;s court, content to a menial and generally unnoticed life of music, relative comfort, and the semi-freedom of a low-level lackey. The Conflagration changed him, and not just in flesh -- while he *did* run into burning buildings to save innocents from the flames (as described in the popular ballad &ldquo;Leafstorm&rdquo;, written by a now-rich fellow bard), it was only a small number of innocents, and his twiglike bard arms made him almost more a hindrance than a help; still, the image stuck, and Barrabas was transformed overnight from third-chair violinist to dashing, confident hero.</p>
<p>His exploits in the Liberation (which were heavily influenced by luck), good looks, and great singing voice have elevated him to the head of the Phoenix Imperialis movement, thanks in no small part to a few business interests who recognized a good figurehead when they saw one. In truth, Barrabas is a little overwhelmed, and not nearly as brave as is claimed. Even so, he has taken his new position to heart, and committed himself to rebuilding his people as the figures he thinks they should be&hellip; even if that means he keeps tripping over disasters while doing so.</p>
<p>&ldquo;Phoenix Lord&rdquo; is a heavily over-aggrandized title, given to him as part of setting Barrabus up as *the* Imperialis figurehead. Barrabus himself does not think it's going to stick, but to be fair, a new people deserve fancy new titles.</p>
<p><strong>High Concept:</strong> A dashing elf&rsquo;s elf with a stirring battlefield reputation that is more luck and showmanship than bravery.</p>
<p><strong>Trouble Concept: </strong>On the Threshold of Adventure(r)<br />.Bad luck tends to follow Barrabus, or at least crash into him at high speed, playing merry hell on his preference to lie around and not get up to much. If anyone is likely to be dragged off on a quest unwillingly, its him.</p>
<p><strong>Character Levels</strong>: Bard (Buccaneer) 2 / Unchained Rogue (Rake) 2 / Swashbuckler 3</p>
<?php
    include '../settarget.php'; 
    settarget("Fire",null,3,null);
    include '../footer.php';
    echo getarrows("1_Factions.php","3_Stunts and Rituals.php");?>
</body>
</html>
