<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../header.php'; ?>
    <link rel="stylesheet" type="text/css" href="../style.css">
    <link rel="stylesheet" type="text/css" href="Fire.css">
    <title>
        Ecology of the Burning Maar
    </title>
</head>

<body>
    <p><h1><strong>The Ecology of the Burning Marr</strong></h1></p>
<p>A treatise on local ecological business value</p>
<p><small>Phoenix Imperialis Publishing ltd</small></p>

<p><h1><strong>Geography and Climate</strong></h1></p>
<p>The Burning Marr is a xeric shrubland over an expansive volcanic field, just south of the Thermodontia (mountain range named as of Surt Year 2). Cyclic wind patterns over the Mainland Continent carry rainfall from the Eastern Sea and surrounding areas over to the Eastern Thermodontia, which blocks the vast majority of precipitation heading westward, trapping it in the swamps and jungles just south of the mountains. This leaves the Burning Marr with a dry climate, supported by snowmelt from the nearby mountaintops and lakes of (often alkaline) water at the center of the Marr. The Marr&rsquo;s center traps enough water to support swamp and forestland on its western edge; this water is currently believed to originate from underground passages and geysers running underneath the mountains to the north, but some runoff from the nearby mountians is also likely to take place.&nbsp;</p>
<p>The dry and alkaline nature of the local water sources, combined with the regular volcanic activity and the regular snowmelt from the mountains to the north leave the Marr with a scrubland ecosystem, supported by regular floral blooms created through the area&rsquo;s highly nutritious soil and sporadic waterflow events. Trees are relatively rare, though not unknown, and there is some evidence that forests were common in this area some time previous. Local flora and fauna tend to be well adapted to the heat, drought, and famine, and as such tend to be small and prairie-oriented. More than a few large herbivores pass through the Marr, where they are preyed upon by larger predators dwelling in the upper reaches of the Thermodontia.&nbsp;</p>

<p><h1><strong>Elemental organisms of the Marr</strong></h1></p>
<p><strong>Passive</strong></p>
<p>"Highly Trainable" magma rocks -- this elemental order consists of any of a number of loose mineral deposits within the Marr that show unusually friendly and active behavior compared to most of their fellows. Their name comes from their discoverer, geologist Apella "Highly Trainable" Rockbush. Sightings are rare, but Rockbush estimates that their pleasant demeanor and inquisitive nature would make breeding a domestic variant an extremely lucrative venture.&nbsp;</p>
<p><strong>Active</strong></p>
<p><a href="https://www.d20pfsrd.com/bestiary/monster-listings/outsiders/elemental/thoqqua/">Thoqqua</a> -- an extremely rare sight in the Marr, with less than a handful of known sightings within the past two years. Thoqqua are a wild metallivore species, normally native to the border regions between the Earth and Fire planes. They are believed to be intelligent, but show no interest in society, save as a source of metallic currency to consume (this makes them terrible customers). They burrow through the volcanic planes, harvesting and devouring some of the minerals brought to the surface by magmatic action. Their burrowing relies heavily on a natural superheating ability, which should be considered dangerous even to Fire Elves. Avoiding mining or construction in any area known to have Thoqqua activity is recommended.</p>

<p><h1><strong>Flora of the Marr</strong></h1></p>
<p>Agave -- A variety of species of agave plant grow in the Burning Marr, ranging from the common red and blue agave plants, to the frost octopus agave found in the northern reaches of the Thermodontia, and the black agave found in crevices close to the Marr&rsquo;s alkali lakes. All but the black agave are edible, and most are considered quite palatable, with some being used in subsidiary products (such as pulque, a semi-fermented thick beverage originating from a few old recipes supposedly native to the region). Agave grow very slowly, with some examples shown to have taken ten years or more to grow into a fruiting plant. Given the presence of related species in the deserts south of the Marr, it is very likely that the agave population here are offshoots of the massive populations there.</p>
<p>Sunflower -- Several sunflower species range across the Marr. Most of them are multichromal, such as the &ldquo;ring of fire&rdquo; and &ldquo;strawberry blonde&rdquo; subspecies that are very popular in Surt&rsquo;s marketplace, or &ldquo;teddy bear&rdquo; and &ldquo;kaleidoscope&rdquo; varieties found decorating the rooftops of noble villas.&nbsp;</p>
<p>Chaos star -- a small grasslike plant, known for having a widespread root system. Its flowers are known for their brilliant colors, which vary wildly between specimens, and typically form a &ldquo;rainbow-like&rdquo; gradient pattern across the flower (or, as per some reports, across entire fields of flowers). Investigation into the potential alchemical usage of this plant is ongoing.</p>
<p>Sagebrush --&nbsp;</p>
<p>Buckbrush --&nbsp;</p>
<p>Wight sage --</p>
<p>Poison cedar -- one of the few trees found in the harshest depths of the Marr, the poison cedar is easily identified thanks to its thick, &lsquo;charred-black&rsquo; bark and the distinct cedar smell it exudes. That smell is the first sign of its deadly capabilities; the poison cedar is naturally toxic, and exudes a nauseating chemical concoction that deters the majority of animals that approach it. Poison cedars often form a &ldquo;green oasis&rdquo;, protecting many of the plants in their area from potential predation; lost travelers who approach these spots are in for an uncomfortable surprise. Poison cedar wood is naturally fire resistant, making it potentially very valuable; its nuts are also being evaluated for potential edibility, as experiments in soaking the nuts in alkali water show that the cedar&rsquo;s toxins can be removed, or at least reduced.</p>
<p>Wizenedwarf sequoia -- named for its stocky and crinkled appearance compared to most redwoods, the wizendwarf sequoia forms isolated copses near alkali lakes and the Marr&rsquo;s few streams. Its wood is hard and difficult to work with, but has a clean stain and naturally smokey scent that makes it very popular.</p>
<p>Atrocity grass -- found only near the worst parts of the Marr&rsquo;s openly lava-filled geography, atrocity grass is named for how it is commonly seen -- covered in a thick carpet of charred, dead insects. The grass is naturally sticky (though only to the point where insects are endangered), and seemingly very fire resistant; insects trapped on it are stuck until the next geyser eruption, steamcloud, or lava flow washes over the area, at which point the victims die, and the grass gets fertilized and saved from potential predators. Some insects, such as honeytrap ants, are able to avoid or resist the grass&rsquo; natural glue, and thus use patches of atrocity grass as shelter -- even surviving eruptions by sheltering within or underneath patches of it.</p>
<p>Scrubland cabbage --</p>
<p>Savage garlic --</p>
<p>Moss --</p>
<p>Sandwich cactus --&nbsp;</p>
<p>Roper cactus --</p>
<p>Geyser-root cactus --&nbsp;</p>
<p>Magmatic cactus --</p>
<p>Fig trees and related --</p>

<p><h1><strong>Fauna of the Marr</strong></h1></p>
<p><strong>Birds</strong></p>
<p>Greater Sentinel Shrike -- a predatory bird, eight to twelve inches in length; typically grey in coloration, with dark markings around the eyes, and a short, clipped bill. Also referred to as a &ldquo;butcher bird&rdquo;, for their tendency to &lsquo;nail&rsquo; their prey (usually small rodents) to the spines and needles of local flora, in order to preserve them for later eating, or to serve as decoration in mating rituals. Shrike are usually found in groups of 3-18, averaging 13.5. Dire members of this species can get to be a little larger than a chicken, feed on hares and other tiny mammals, and are considered quite tasty. There have been no reported successful domestication attempts at this time.</p>
<p>Enormous Ostrich -- first identified as a new, non-dire specimen by B.G. Enormous, the Enormous Ostrich reaches 11&rsquo; in height, travels in packs of 1-6, and is regularly aggressive to passing travelers. Fortunately, the ostrich tends to avoid most high-traffic areas, and while dire variants have been speculated about, there have been no known sightings of such a creature. The Enormous Ostrich is primarily herbivorous, dining on agave, shrubs, and lichen, but have been known to eat small mammals and insects (including raiding honeybee hives).&nbsp;</p>

    <p><strong>Insects and Vermin</strong></p>
<p>Honeybee -- while the domestic honeybee within Surt&rsquo;s borders are transplants from farms and plantations within the Empire, honeybees of similar make and ken can be found throughout the Burning Marr. Most show similar temperament and nature to the domestic bee found in most apiaries throughout the mainland. However, there are some distinct differences. The wild honeybees of the Marr are notably more smoke-tolerant, and tend to have a reddish or vibrant blue coloration distinct from the domestic. Few of these hives survive winter, save for those closest to active geothermal spots or other prominent sources of warmth. They are preyed upon primarily by local birds, though some ants and some much larger creatures have been known to attack or harvest from their nests.</p>
<p><a href="https://www.d20pfsrd.com/bestiary/monster-listings/vermin/centipede/centipede-hissing">Bristleback worm</a> -- technically an annelid, the bristleback worm is a ferocious, highly poisonous segmented worm found living in the geyser fields of the deep Marr. They are most frequently found around the most alkaline water spots in the Marr, and some scholars theorize that they are actually native to much deeper areas, and are only brought to the surface by the force of the Marr&rsquo;s myriad geysers. Bristleback worms are aggressive, but primarily scavengers, though they have been known to hunt hares or larger critters. Bristleback toxin is reasonably powerful, and there are plenty of opportunities for enterprising individuals to engage in &ldquo;worm milking&rdquo; for future sales.</p>
<p>Honeytrap ant -- A standard ant -- tiny, reddish, and insecty -- with an unusual subtype. The honeytrap ant, like some ant species, dedicates some hive members as &lsquo;food storage units&rsquo;; their rear ends swell with sugary nectar to more than a dozen times normal size. Unlike most species that use this tactic, honeytrap ant nectar is corrosive and volatile, capable of severely injuring most would-be predators. The ants have even been known to lead their storage-ants into the open, using them to attack other colonies or even forming slow-moving swarms with mildly explosive potential. Fortunately, these ants are mostly herbivorous (the only way to get the nectar they live on), and swarms are rare, save for during occasional storms of hive migrations.</p>
<p><a href="https://www.d20pfsrd.com/bestiary/monster-listings/vermin/ant/ant-giant-worker/">Strider ant</a> -- an exceptionally large species of ant, reaching almost two feet in height, with the majority of that stemming from their extremely long legs. The strider ant is a &ldquo;giant ant&rdquo; (any variety of ants that reaches housecat size or larger), but is only of limited threat to humanoid life; unlike most species of giant ant, the strider ant is fairly skittish, and is only occasionally found in swarms of more than five individuals, rumors of vast hives underground notwithstanding. Strider ants typically prey on small birds, lizards, and mammals, where their great speed and burrowing capability serves them well, but most of their food is believed to come from the surface vegetation they harvest -- either directly, or as fertilizer for underground fungal farms (as theorized by some scholars). Their weak joints and low intelligence make them frequent prey for pack hunters, or really any species their size or larger. Some trappers have reported that they can be quite tasty when properly cooked; the first entrepreneur to successfully domesticate these creatures may make significant profit from culinary endevors.</p>

    <p><strong>Mammals</strong></p>
<p>Black-tailed jackrabbit -- large scrublands hare, notorious for its popularity among the local predators and parasites. Their preferred dens (bushes and small, vegetation-heavy depressions) leave them exceptionally vulnerable to fleas and ticks, and thus game hunters typically avoid them. They do not burrow, and are generally considered a major threat to exposed agriculture.</p>
<p>Booted mouse -- favored prey of local shrikes. They have disproportionately large eyes for their size, and often appear in unusual two-tone patterns (most typically brown with a white underbelly, but stranger colorations have been seen). Despite their general cuteness, these are a nasty potential threat to any dry storehouse or open agricultural area, and their good speed and climbing skills make them a threat to even the rooftop gardens of Surt (though its notable that they tend to avoid areas that smell of sulfur). Some variants are known to carve homes out of living trees or cacti, hiding from predators within their hard shells, and eating the local pests in return.</p>
<p>Ember hippo -- also referred to as the &ldquo;dwarf fire hippo&rdquo;, the &ldquo;ignis river pig&rdquo;, or the &ldquo;potbelly hippo&rdquo;, the Ember hippo is a small hippopotamus relative, getting to between 2.5&rsquo; and 3&rsquo; high at the shoulder. They are a little fatter and squarer in shape and appearance than most hippos (and of course about half the size and a quarter of the weight), and display slightly more omnivorous tendencies, having been witnessed assaulting fish and small birds at the riverside. They also tend to be slightly redder in coloration than most hippos, though in most cases that is because of their enhanced sweat, which is thicker and stickier than it is in most species of hippopotamus, and appears to provide them with some degree of fire resistance [Fire Resistance 3]. While most commonly found along the Ignis Lupus, they are actually very common along the alkali ponds and lakes of the Marr, where they wallow through the alkali waters with relatively few negative effects, and are free to consume the shrubs and plantmatter surrounding the Marr&rsquo;s numerous geysers and hot springs.</p>
<p>Venomous dwarf pygmy shrew -- the tiniest mammal in the Marr area, clocking in at 1-1.5&rdquo; long. This shrew has a natural toxin in its mouth that it uses to paralyze its prey, which usually consists of insects, spiders, and various forms of worm. Attempts to analyze the toxin as a natural muscle relaxant or pain relief method have provided little, and most elves appear to be naturally mildly allergic to the shrew&rsquo;s bite. Venomous dwarf pygmy shrews prefer to burrow in rotting wood or dirt, and typically stay in groups of 2-20 individuals, but have been observed to &ldquo;swarm&rdquo; during large floral blooms, where they can be a danger to even large animals (such as ostriches). Purple ones are to be avoided wherever possible.</p>
<p>Dunecrawler Onager -- the only equine to frequent the Marr, the wild dunecrawler onager is more frequently seen in (and named for) on the open dunes of the deserts far to the south. How so many specimens of them ended up in the Marr is uncertain. The dunecrawler onager is small, with a low-slung body, and an exterior traced with wavelike patterns that some theorize assist them in blending in with distant sand dunes. Like most onagers, the dunecrawler is completely untrainable, and is considered more of a pest than a potential source of animal labor.</p>
<p><a href="https://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/cinder-wolf/">Cinder Wolf</a> -- an extremely rare find in the open Marr, cinder wolves are an unusual and highly fire resistant canine variety known for their thick hides and natural heat. Their skin sports a coal-black exterior similar to that of carbon charring, and some hunters have successfully used their skin to craft fire-resistant hide with a lower total reagent cost than average. Like most canines, cinder wolves are endurance pack hunters, preferring to chase down and exhaust their prey before going in for aggressive group assaults. Those few that have been spotted have been found mostly in the upper Thermodontia, where it is believed they hunt the wild goats that dwell there; some explorers speculate that they may just prefer to den in the mountains, and instead come down into the Marr to hunt hippo, jackrabbit, and ostrich on a regular basis. Cinder wolves are notoriously freespirited and difficult to train.</p>
<p><a href="https://www.d20pfsrd.com/bestiary/monster-listings/animals/jackal-switchback/">Switchback Jackal</a> -- Though much more common in the areas to the east of the Marr, the Switchback Jackal is one of the Marr&rsquo;s primary predators of black-tailed jackrabbits and strider ants, and is a serious potential threat to livestock throughout the general area. Switchback jackals, named for the odd &ldquo;popped collar&rdquo; mane common to adult specimens, are notoriously clever creatures. Trappers throughout the region have reported examples of the jackals evading or outright disabling traps, opening unsecured gates, sneaking onto riverboats, or dousing candles (usually followed by eating said candles -- switchback jackals are not picky). They are too small to be a significant threat to elves, horses, or cattle, but have been known to kill young or isolated goats or sheep, as well as dogs and cats. They generally avoid volcanic active areas.</p>

<p><strong>Amphibians</strong></p>
<p><a href="https://www.d20pfsrd.com/bestiary/monster-listings/animals/lich-newt/">Darcy&rsquo;s Lichnewt</a> -- a Marr variant of a fairly uncommon boney newt. The Darcy&rsquo;s Lichnewt, named for the employer of the explorer who found it, is a 6-8&rdquo; long newt common to the more sulphur-heavy hotsprings and tributaries to the Ignis Lupus. It features boney ridges along its back, giving it an unfortunately skeletal appearance, which is enhanced by the deep blue and purple skin coloration common to the Darcy&rsquo;s variant. Their paralytic secretions (used to defend themselves against predators) are mild but irritating, and direct physical contact should generally be avoided unless you want your fingers to be numb for the next day. Darcy&rsquo;s lichnewts are primarily insectivores and scavengers, and have been known to swarm over fallen animals in a disconcerting mass.&nbsp;</p>
<p>Darcy&rsquo;s Skelenewt -- another Marr variant of the boney newt, this species (notably more common, larger, and lighter in coloration) has an alternate version of the natural paralytic secretions of lichnewts, shown to have absolutely no effect on mammals. Typically brilliant blue with mottled patterns, around the sharp white of their natural ridges, the skelenewt is rapidly becoming a popular pet (and &lsquo;exotic&rsquo; delicacy) within Surt, which has led to more than a few unfortunate incidents where people have picked up Lichnewts by mistake. Like lichnewts, skelenewts are primarily insectivores, though they have been observed eating small fish and other amphibians. They typically live in small groups of 3 to 60 individuals, but rarely form scavenging swarms.</p>
<p>Sandpaper Chubtoad -- frequently found in the brush near geyser deposits, the sandpaper chubtoad is about 5-7&rdquo; in diameter at adulthood, and is a rough, misshapen creature easily mistaken for a rock or stone. Aside from their extremely rough skin, which can be sharp enough to scrape the skin of predators, the sandpaper chubtoad secretes a natural toxin, similar to that produced by its favored food, the venemous dwarf pygmy shrew. Unlike the shrew, the toxic secretions of chubtoad skin has been known to produce light euphoric effects in humanoids (which is pretty common to a lot of chubtoad species). Its currently uncertain whether the effects of this toxin can be concentrated or enhanced with proper alchemical research. Only a few predators bother with the sandpaper chubtoad; one of the most common is the sentinel shrike, which has been known to leave chubtoad corpses out in the sun for several days before devouring them (likely to allow the toxins to drain out).</p>
<p>Reptiles</p>
<p><a href="https://www.d20pfsrd.com/bestiary/monster-listings/animals/snake/snake-viper/">Splitviper</a> -- named for its peculiar physical form, the splitviper is an odd venomous snake naturally adapted to blend in with its local environment. Splitvipers are &ldquo;flat&rdquo; on their right side, much like flounder fish, which allows them to blend in with the natural contours of the terrain. This also cocks their jaw to the side, putting them at a perfect natural angle to launch for the throat of their prey (such as jackrabbits), or launch for important bits of predators (such as the legs, throat, and nose of Switchback Jackals). While not naturally aggressive, splitvipers are infamous for &ldquo;leaping before they look&rdquo;, and more than a few unwary travelers have been surprised by splitvipers launching themselves out of the underbrush.</p>

<?php
    include '../settarget.php'; 
    settarget("Fire",null,6,null);
    include 'footer.php';
    echo getarrows("4_Details and Design Notes.php","6_Settlements.php");
    echo goback();?>
</body>
</html>
