<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../header.php'; ?>
    <title>
        River Elf Cultural Details
    </title>
    <link rel="stylesheet" type="text/css" href="../style.css">
</head>

<body>
    <h1>100% Pure Flavor Text</h1>
    <h2>Key Virtues</h2>
    <ol>
        <li>Sharing - While it could be said that the river elves see generosity as a virtue, it’s not entirely accurate.  While they are generous, they do rather expect that it will be reciprocal, if not in kind.</li>
        <li>Patience - River elves take a very long view of life.  They do not leap at every opportunity, but wait for just the right timing.  They view patience as one of the keys to building a best life.  And they are, after all, ambush predators.</li>
        <li>Calm - River elves value mental calm as much as they value calm water.  They do not like disturbances and seek to maintain their relaxed lifestyle.  It takes quite a bit to rouse them to react with anger.</li>
    </ol>
    <h2>Cuisine</h2>
    <p>Because they live on rafts and are not always able to access fire for cooking, river elves have a tendency to eat raw, sometimes live, food that has been <a href="https://en.wikipedia.org/wiki/Gejang">marinated heavily instead of cooked</a>.  Usually seafood, particularly crabs, these meals are placed alive into stoneware crocks with large quantities of salt, herbs, spices, and vinegar until the animal has died and become delicious.  They are very particular about the length of time marinated seafood is allowed to sit until it is eaten, and swear that this ensures that the food will not be contaminated.  </p>
    <p>Their food tends to be extremely spicy, and contain a lot of foraged roots.  It is not uncommon for them to plant onions, garlic, or ginger as they travel upstream and collect the harvest on the way back downstream.  In their winter quarters, they commonly plant rice in floating semi-submerged rafts, which they use to make rice vinegar, and store dry for the lean times.  They will also happily boil a meal for special occasions.</p>
    <h2>Decoration</h2>
    <p>Due to the fact that it is an easy metal to work with under relatively low temperatures and tarnishes to a lovely shade of green, river elves prefer to use copper for decoration rather than gold.  They use copper washes on their arms and armor to prevent corrosion because everything they wear must be able to withstand being frequently submerged.  Being amphibious, they spend a lot of time in water.</p>
    <p>The river elves have had a mutually beneficial relationship with massive hippopotamuses for many centuries.  When their beloved fellow travelers pass away, they collect their ivory teeth to carve with the names of those who raised them.  These decorated tusks are kept on display on the raft of the family that cared for the hippo, providing a carved record of oarsmen and herders of the family’s past.  Many of these relics were lost, and the ones that remain were mostly collected from the dead of the sacking of Skaplyndi, and have been carved to remember those slain in that battle.</p>
    <p>They often decorate their homes with polished turtle shells, beads of mother of pearl from freshwater clams and oysters, and alligator hides.  These are polished until they gleam, and are typically hung from the rafters of their barge’s buildings.  River elves use sturdy stoneware for their dishes and cooking implements, as anything they use does have to survive the conditions of their travel, which do involve the occasional rapids and short waterfalls.  Everything inside their home is kept tied down in case of sudden shocks.</p>
    <h2>Fashion</h2>
    <p>The need to be able to swim frequently also leads them to avoid using patterned cloth, as dye that bleeds disrupts patterns too easily.  They find that it looks better to simply have their clothes be one color than to have multiple colors that bleed together and lose their distinctness.  It is typical of their tastes to choose colors close to their own skin tone to wear.  Since they have such a wide range of skin colors, anywhere between green and grey to brown and orange, they like to accent this natural variation with their clothing choices.</p>
    <p>Typical river elf fashion is to wear shorts with a solid colored shirt and leather sandals.  Current fashion is to have a high collar, and knot or pin narrow woven scarves around the waist and shoulders.  Cloaks are common when they are going to be away from the flotilla for a long period of time, as having an extra layer helps preserve moisture in their sensitive skin.  Since they do breathe through their skin under water, they prefer to leave as much surface area as is practical bare.  In high summer, when there are no outsiders around, the flotilla tends toward nudity as its members stay submerged.  This is something of a secret, as it’s not something they confess to around other elves.</p>
    <p>River elven women typically wear their hair tied up, but leave long tails of hair dangling in front of their ears.  If asked, they claim it is a religious observance, showing their connection to their other elven cousins, but can’t pinpoint how it began or the symbolism behind the style.  Men among the river elves rarely do the same.</p>
    <h2>Animal Husbandry</h2>
    <p>River elves are known to keep ducks for eggs and poultry.  Chickens do not do very well with their nomadic waterborne lifestyle, but ducks will keep on a raft just fine.  They do not have the space available to keep large livestock that cannot also be used to tow the barges.  For this reason, they do not have cows and do not drink milk or eat cheese.  The cultural lack of dairy does lead them to be somewhat lactose intolerant.</p>
    <p>Their diet, however, is largely pescatarian.  They keep large reptiles and hope for hippopotamuses for transportation, but do not eat their rides.  Live wells in the barges store fish and crabs, and they raise catfish in nets that follow the flotilla and feed them waste food.</p>
    <h2>Marriage and Sexuality</h2>
    <p>River Elves have two different kinds of marriage: a river bond and a raft bond.  Because the flotilla’s makeup changes yearly, there isn’t a guarantee that the same rafts will travel together when they set forth from the swamp in the Spring.  For this reason, some will choose a temporary river bond, rather than a permanent raft bond.  This is not considered a trial period or the step between courtship and a raft bond.  Often, when the pair are reunited another year they rejoin as though no time had passed.  On occasion, a river elf may have more than one different river bond.</p>
    <p>They do not, however, otherwise practice polygamy.  Most rafts belong to and are crewed by a single family, including multiple generations.  It is simply too many elves on one boat to combine multiple families at once.  A raft bond, however, is exactly that.  Two elves in love will decide whose raft to cohabitate and will merge their families or build a new raft for themselves if their families are too large or disfunctional to inhabit one together.  River elves with raft bonds do not take additional river bonds.  It’s a logistical nightmare to keep all of it organized, so they opt for simplicity.</p>
    <p>The easy way to think of raft bonds vs. river bonds is that a river bond is for people who do not want to join whole families.  Both are permanent, but raft bonds require a much closer commitment, as this joins households.</p>
    <p>Living on rafts with not a lot of privacy does, however, put something of a limit on their sexual practices.  Among elves, they are probably the most sexually repressed right up until they retire to their Winter Quarters after the yearly expedition.  “Disturbing the crocodiles” is a euphemism for stealthy sex underwater.  While they do bond only as pairs, they do not have any taboo against same sex pairings.  Unbonded river elves spend the winters having wonderful romantic flings with other unbonded river elves.</p>
    <p>To comply with cultural expectations of wearing wedding rings, river elves pierce the web between their last two fingers and wear a snug-fitting captured ball ring on their last finger.  Someone with multiple raft bonds will wear multiple rings.  The piercing, they feel, shows the depth of their commitment, and they do not wear rings for reasons other than deeply important vows.  For safety purposes, those with particularly physical jobs will instead tie a thin, breakable wire or thread through the hole when working, and put in the metal ring while off duty.</p>
    <h2>Children</h2>
    <p>River Elves spread like duckweed.  There are always children underfoot, underraft, and around.  One of the great sadnesses of their current situation is that so many families are separated from their youngest members who were lost with the larger share of the civilian population.  Children belong to the raft of their birth mother, and are raised by all who live on it.  This means that the children of river bonded parents will be raised by their mother and all of her family that she shares a raft with.  Raft bonded parents share parental duties equally.  </p>
    <p>It is generally assumed that all families want children.  Even same-sex pairings will usually have a couple.  Life, uh, finds a way.</p>
    <p>Unbonded parents are rare, as they would avoid pregnancy unless willing to share the responsibility.  On occasion, due to their extensive travels, half-river elven children are born to the flotilla.  If they can be returned to their land-bound parent this is usually attempted, as it is a great concern that they may not be capable of breathing well enough through their skin to survive underwater.  If the non-amphibious parent is willing to join the flotilla then the mixed child is accepted, but concerns over drowning will always linger.</p>
    <h3>A Note on Infertility</h3>
    <p>	While it’s fun to just make a reference to  frogs and Jurassic Park and leave it at that, events conspire to make this actually a relevant piece of information.  Because river elves strongly believe that the health of a family is measured in the strength and breadth of its ties, couples always have the option to reach out to their closest family members for help when it's needed for any reason.  The person who agrees to help them conceive then stays with them until no longer needed.  The donor of life then acts as a much beloved aunt or uncle to the child and can choose to be in their child’s life as much as desired.</p>
    <h2>Education</h2>
    <p>It is always the responsibility of parents to see to their children’s education.  For the river elves, this involves making certain that the children of your Family’s raft are included in your Family’s trade and learn the tools they will need to be successful when running their own raft.  While rafting skills, barge building, cooking, maintenance, and cleaning, are all taught by their own family at home, formal skills such as reading, writing, and a specific trade are taught through apprenticeship.  Young elves are tasked with trying out a few different trades by apprenticing to other rafts for a decade or so at a time.  During this time they still live with their family, but spend the working hours with their master as a student.  Young river elves are encouraged to try a few different jobs before settling down with one particular master.</p>
    <p>Once a young river elf has found their calling, they graduate from apprentice to journeyman.  At this point, if their family ends up separating from their master’s raft to ride a different river, they will stay with the master instead of following their family.  They do not have to live full time on the other raft, but they do start to accumulate the tools of their new trade on the raft where they live.  When the master determines that they are capable of handling the requirements of the job on their own raft, they’re declared a master themselves.  At this point they can manage that responsibility alone and do not have to stay with their master if they choose a different river.  Usually a river elf makes their journeyman choice just as they’re entering adulthood, and by the time they’ve made it to master they’re starting their own family.</p>
    <h2>Death</h2>
    <p>Frequent travel through a variety of terrain makes it very difficult for the river elves to stick with any one particular burial practice.  They do honor their dead, and believe that this is important.  When they are traveling through territory where other elves live, they follow the funeral customs of their temporary hosts.  These customs vary wildly, but they strongly feel that local customs are appropriate to local terrain, and as all elves are reflections of the divine, clearly these customs are as valid as their own.</p>
    <p>When alone, or traveling through territory not occupied by other elves, they instead follow a complicated practice of honoring a person’s life and death with rituals determined by their profession.  Due to the somewhat recent (in elf terms anyway) loss of the books of lists for what those rituals ought to be, they are in the process of describing new ones as needed.  Currently, it is known that soldiers are cremated, their ashes dissolved in the water of the river so that they may always be a part of its flow.</p>
    <p>They have long treasured the ivory teeth of their beloved hippopotamuses.  In generations past, these teeth would be saved by the Family who the hippo belonged to, and would be carved with all the names of those who cared for it.  With no hippos remaining, there is no longer a permanent record being created for them to feel this connection to their ancestors.  With uncertainty about the turtles effectiveness lingering, some river elves have quietly collected their dead loved ones’ own teeth to inscribe with their name and keep with the Family treasures.  This practice is not yet common among all river elves, and they are not discussing it publicly, but it is a growing practice rather than a shrinking one.</p>
    <p>It is not uncommon to hear river elves talk about their deceased loved ones as “Resting.”  This is because the river elf culture is a culture on the move.  If a river elf is completely at rest with no plans to move again, they are most definitely deceased.</p>
    <h2>Justice</h2>
    <p>For most crimes, river elves use public humiliation as a general purpose punishment.  In such a small, tightly knit, community, being forced to wear a sign that says, “I stole from Robeaux,” while standing on one foot on the lead barge for a few hours every day is punishment enough.  Their worst criminals, those who have committed murder, or have harmed a hippopotamus or turtle, are stripped naked, walked out into the wilderness, handed a knife and a noose, and left alone to do what they will.  There is a strong assumption that these criminals will commit suicide out of shame and guilt.  It is an effective sort of exile.</p>
    <p>Sometimes an exile will be allowed back into the flotilla when it passes through the area again.  With the vague assumption being that if they have managed to survive with the shame and guilt, and had the willpower to do so on their own, then they may have been, not innocent, but possibly justified.</p>
    <p>It’s worth noting that what they view as criminal activity skews heavily toward favoring elves.  Theft from another elf, of any variety, is a very clear crime.  Theft from someone who is not able to pass a “detect elf” spell check, isn’t really a crime at all to them.  They’ll acquiesce to the authority of any government they pass through, but will not punish crimes against non-elves themselves.</p>
    <h2>Affliction</h2>
    <p>When fighting Lycans, there is always a risk of contracting the Affliction.  Over the years of dealing with this curse, the river elves have developed a tradition for dealing with it.  Following any combat with lycanthropes anyone who has taken any kind of injury at all undergoes a round of wolfsbane treatment.  They do not try to single out specific elves for treatment because they do not want to start a wolf hunt.  Everyone takes the medicine.</p>
    <p>On the night of the first full moon after a battle, the unit gathers with their injured around a campfire and waits.  If any one of them Turns, their friends are there with silver weapons at the ready.  If none of them Turn, then the vigil becomes a celebration.  If they are not so lucky, the funeral pyre is ready.</p>
    <p>If there are too many wounded or there is not a way to hold the vigil for whatever reason, an injured river elf will be tied to the heaviest ballast available and wait underwater.  Others will watch from a safe distance with their water sense to see if they Turn, and then simply hope that the wolf drowns.</p>
    <h2>Theology</h2>
    <p>River elves see religion as a very personal and individual choice.  Their actual practices are as much formed from Family traditions as they are shaped by the cultural context.   Their organized religion is shared between all river elves on every level, like siblings in a family.  It is not something declared from a central authority on high, but something that river elves figure out for themselves with the help of their close friends and family.  The community and the laity decide the course of faith, the priesthood are merely there to help them along the way.</p>
    <p>There are, however, a few things they hold in common.  Calestros is their god, their goddess, their divine being, and while they acknowledge that other gods exist, they don’t recognize their importance.  Devout river elves believe that all things flow toward Calestros as the rivers flow to her holy sea.  She is the source and destination of life.  They also see that being an Elf is to be part of her Perfect whole that has been shattered into imperfect pieces.  And they’re a bit vague on what counts as an Elf - the more devout among them believe that anyone who recognizes the shard of Perfection within themselves is an Elf in the eyes of their god.</p>
    <p>River elf clergy, be they clerics, oracles, druids, or non-magically ordained priesthood, serve their community as therapists.  While their god is madness, that doesn’t mean they see mental illness as something to be left untreated.  They are uniquely charged with the care of the mental health of the flotilla they serve.</p>
    <h2>Holidays</h2>
    <p>There are four major holidays on the flotilla’s yearly calendar.  Three of these holidays happen in the winter months, when all river elves are hosted in the same location.  The major holidays are: Elven New Year, [Name TBD], Elfmas, and Departing’s Eve.</p>
            
    <?php include '../footer.php';
        if($_SESSION["R_META"]>=6){ $next = "6_Settlements.php"; }
        echo getarrows("3_Leadership.php",$next);
        echo goback();
    ?>
</body>
</html>
