<?php session_start(); ?>
<!DOCTYPE html>

<head>
<?php include '../../header.php'; ?>
    <title>
        Dark Elf Year 2 - Winter
    </title>
    <link rel="stylesheet" type="text/css" href="../../style.css">
    <link rel="stylesheet" type="text/css" href="../Dark.css">
</head>

<body>
    <h1>Year 2 - Winter</h1>
    <table style="width:100%">
        <tr>
            <th>Stress</th>
            <td>Economic 0/5</td>
            <td>Morale 0/5</td>
            <td>Property 0/5</td>
            <td>Military 0/5</td>
        </tr>
        <tr>
            <th>Fate Points</th>
            <td>2/3 Refresh</td>
            <td>1 Bonus</td>
        </tr>
    </table>
    <p><b>Economic</b>: As eager as everyone is to continue building, Rasputin has them put a pause on it for the moment.  They have a nice business going with the Inn currently, but trade ventures are going to become important with the river elves coming through to Crater Lake in the next couple of seasons.  Quartz and obsidian have their uses and he has no doubt they could trade some of those, but silver he knows for a fact is something that people will be wanting.  They don’t have an outpost there yet, but he figures sending a team in to mine just enough for a first time trade with the river elves would be a beneficial idea.</p>
    <p><i>Merchants</i> trapping of <b>Trade</b></p>
    <p>0 advantages, 1 success, 0 triumphs</p>
    <p><b>Political</b>: 
    <p>Yay, <i>more</i> suspicious elves that were trying to get information out of us!  Greg has the spy - Titus Skoda’s blood saved with his alchemical supplies because he apparently has potential plans for it?  No one questions it.  Shyrendora may have locked herself in her office for a while and just...screamed into a pillow, but no one can prove it.  With everything going on, she decides that it’s still best to try and keep up routine and there are now hard talks about making a division for spyhunters plus the training that it would entail.  Shyrendora is aware that Greg is working with the blood, she doesn’t know what his angle is but she has a small hope that he will come up with something useful that could be passed on to their more magically inclined researchers.  She’s also tempted to have Vahn harass him.</p>
    <p><i>Cloak and Dagger</i> trapping of <b>Spycraft</b></p>
    <p>0 advantages, 3 successes, 0 triumphs</p>
    <h3 id="jump">Story: 2.3.1: <a href="../Bonus/10_We of Like Mind.php">We of Like Mind</a></h3>
    <p><b>Military:</b> Trischal may have also locked herself in her office and screamed into the nice fluff of Fuzzy for some needed stress relief.  During this time she weighs her options of what to do next.  Training up and creating the things for a spyhunter group would take time, she knows where her people’s strengths lie and that was definitely not one of them.  Another option open to her is to try and help out the researchers by having her pathfinders scout out the area around Crater Lake.  Surface scouting would be less advantageous to the pathfinders but she is hopeful that their time on the surface would mean that they at least could find something out that might help.  It takes a few days and a couple of coin tosses where Fuzzy and others totally don’t help by trying to give her more pros and cons to each; but she finally decides to send the pathfinders out to scout around the lake.  (the square south of the Hilt’Inn and then the square east of that.)</p>
    <p><i>Pathfinder</i> trapping of <b>Reconnaissance</b></p>
    <p>2 advantages, 2 successes, 0 triumphs</p>
    <p><b>Mental:</b> Obviously going to continue to parse out an idea for a food source that can sustain so many people.  There are other ideas in the talks but those won’t happen for a little bit, one being asking the river elves for advice on fishing that...doesn’t...involve using one’s arm as the bait, while another is trade, and another is talking to the winged-elves to see if they could trade their underground scouting expertise for their academic “learn all the things” expertise.  Still, they know they need to think of something that can be in this area and not wait for the other options to come to pass.</p>
    <p><i>Research</i> trapping of <b>Academics</b> (boost die)</p>
    <p>Invoke Together in the Dark for a proficiency die</p>
    <p>1 advantage, 1 success, 0 triumphs</p>
    <p><b>Misc:</b> Greg is attempting to make notes on how to make a roundabout glyph of warding using information gleaned from blood biography.  His main idea is to try and have it so it can be set to say “people of this bloodline can gtfo.”  If he comes up with good results, he also intends to use this as his own personal “stay out of my shit” glyph for certain bloodlines/families/individuals that he doesn’t want poking into his affairs.  He has also joked about enchanting a pen with zone of truth, but with some pouting encouragement from Rasputin, that joke has turned into a promise to seriously sit down and look into it with some clerical help.</p>
    <p>Craft Alchemy - 31</p>
    <p>Spellcraft - 24</p>
    <h3>Results</h3>
    <p><b>Economic:</b> As it turns out, there is a great deal of difference in difficulty between “small team moves through many miles of deep caves and tunnels in order to map them and report their findings” and “a survey team treks through many miles of deep caves and tunnels, mines an untouched vein of silver in a wild cave with only hand tools, then returns on the same route with hundreds of pounds of raw silver ore in tow.” The good news is that dark elves are good enough at caving that they can figure this out <i>before</i> some kind of disaster strikes!</p>
    <p>The team assembled to do this is an odd bunch. Not only surveyors and miners, but also a few merchants and accountants. All protected and led by a group of veteran sappers, of course. The team sets out on their journey without any silver, and in high spirits.</p>
    <p>The team returns from their journey in low spirits, but with packs full of silver. At least all of them do actually return! The journey ended up being even harder than anticipated. It took weeks to get there, months to gather enough silver, and a solid month for them to drag it all back. There were numerous hazards, pitfalls, and mishaps, but most of all silver is <i>really damned heavy</i> and dark elves are <i>really damn tiny!</i></p>
    <p>You successfully gather enough silver for a <i>Silver Ore Shipment</i> that can be traded, but the team that you sent out returns completely exhausted. Using your Sappers directly next turn will take a <b>setback die</b>, as several of the sappers sent with the journey were ranking officers and they are still trying to get themselves together after the exhausting trip and work back into their command structure.</p>
    <p><b>Political:</b> In a small mercy, your spyhunters have a boring season. They are definitely on the ball. They gather every morning to compare notes, do headcounts, and talk each other through their night to make sure no one has any missing time. Kolya is finally well enough to return to duty, and he is given a hero’s welcome.</p>
    <p>The spyhunters operate like a well-oiled team this season. With all of the checks and balances they give each other to make sure all backs are watched and all corners checked. They are reasonably certain that there were no attempts to infiltrate the Caldera this season.</p>
    <p><b>Military:</b> This turns out to have been literally the worst possible season to send your pathfinders surface scouting in the entire time you have been in these new lands. Last year’s winter was reasonably mild, so your pathfinders and Trischal assumed that was relatively par for the course. This year, however, turned out to be worse. Far, far worse. When you are able to compare this season’s weather with previous winters, it ends up being the harshest your elves have ever seen since the end of the war.</p>
    <p>And it is in the middle of this that Trischal decides to take a hike outside. When she first sets foot outside, it’s not so bad. Cold, yes, but they have gear for that. Her pathfinder team sets out to explore the lake and hopefully find some kind of usable food source.</p>
    <p>Unfortunately, she quickly runs into frustration. The northern section of the lake, closest to the Hilt’Inn, only has the <i>Skeletal Fish</i> aspect. For both of the sectors that she has selected to survey for possible fishing, they find not a single living fish. She’s… really not sure how a skeletal fish keeps swimming, but there it is. It is also, of course, completely unusable for a food source. </p>
    <p>Up until now, her pathfinders are ahead of schedule. While they have completed their assigned squares early, the weather is slowly worsening and getting colder. Cold that is quite dangerous to a dark elf. Trischal makes a call.</p>
    <p>She elects to press on, searching further south to the southern coast of the huge lake. She is absolutely determined not to return empty handed, not when a food shortage is looming so close. She orders her pathfinders to keep moving and try to get in one more square of scouting this season.</p>
    <p>Her determination ends up well founded. Whatever horrible necromantic disaster happened at the caldera, the southern end of Crater Lake appears to have been out of range. There, they find a <i>Rebounding Fish Population</i>. They also find abandoned fishing equipment and a few fishing huts and boats. It appears there was once commercial fishing here, but whatever disaster happened it devastated the fish population.</p>
    <p>This fish population is still somewhat fragile, but far from critical. They appear to be competing with the very aggressive skeletal fish to the north, but slowly outlasting them apparently through attrition. Living fish grow and breed, undead fish don’t.</p>
    <p>It would be best to wait a couple seasons before opening any large scale fishing operations here, but running a few emergency fishing expeditions for badly needed supplies is viable with a relatively low chance of upsetting the fish population’s recovery. Trischal is feeling pretty good!</p>
    <p>Then a massive and unexpected blizzard rolls in from the north. Trischal is no longer feeling pretty good. The pathfinders make a beeline to return to the Hilt’Inn, but they’re much further out than they expected to be. The blizzard hits them full force while they’re still many miles from home.</p>
    <p>The storm envelops the team in a white out, and dumps foot after foot of snow on top of them. The winds are nearly heavy enough to drag a dark elf off their feet. If not for using Fuzzy as an anchoring point, several pathfinders may have been lost to that alone.</p>
    <p>Worst is the cold. Trischal keeps order and presses on, but dark elves have never done well in the cold and this cold is <i>lethal</i>. They are able to use the edge of the lake as a navigation guide and return to the Hilt’Inn, but this is after nearly a week of marching through the winter storm without adequate protection.</p>
    <p>Trischal and the pathfinders are in bad shape. A couple of them are literally tied to Fuzzy’s back. Trischal is barely standing. All of them have frostbite to some degree or another, many of them severe. Including Trischal. The pathfinder team is rushed to the medical caves and given immediate assistance, but even with magical healing several of them lose extremities like fingers and toes. Trischal herself is in bad shape, with blackened fingers and toes. She can’t feel them. They might heal, they might not. Only time will tell.</p>
    <p>You are unable to use the <b>Pathfinders</b> trapping next turn due to how badly injured their best team is, and Trischal is down for the count next season. She is unable to take any actions other than to rest, recover, and hope for the best.</p>
    <h3 id="jump2">Story 2.3.2: <a href="../Bonus/11_I Said Never Again.php">I Said Never Again</a></h3>
    <p><b>Mental:</b> Unfortunately, it’s more bad news. The dark elves are just so far unable to turn out a solid plan for above ground farming. Soil samples from around the edges of the Caldera  are getting more and more useless, and none of the traditional dark elf cave farming techniques are viable.</p>
    <p>Dark elf cave farming always used the heat from lava tubes and geothermal sources as something of a “power source” to fuel growth. The geothermal heat reported near the silver deposit might be enough, but by the time you could get a farm set up down there it would be well into a food shortage.</p>
    <p>Your research team warns that this long term problem is rapidly becoming a short term problem. At this point, if a solution isn’t found and implemented by the end of next turn you’re going to start running out of food and begin rationing. This is not something you want to happen.</p>
    <p>They posit that kicking the can down the road may actually be a good idea in this case. If you can come up with a short term solution next season that’ll extend your food supplies just a few months, you can last until the river elves get here. If you last until the river elves get here, you can trade with them for food. If you manage that, you should be able to buy yourself a lot more breathing room to find an actual long term solution.</p>
    <p>Whatever decision you make, you need to make it soon.</p>
    <p><b>Dilemma: </b>Now there is some good news about the refugee crisis! It’s a really, really, <i>really</i> good thing you built that refugee center when you did. The harsh blizzard, biting cold, and heavy snowfall would have been absolutely devastating to the ramshackle refugee tent city that existed there just a couple months ago. Instead, the warm, well thought out, and spacious complex that the dark elves built has more than enough warm beds to keep refugees safe, and even medical facilities for those unfortunate enough to have ended up making the trek that winter.</p>
    <p>If you hadn’t built that center when you did, many people would have died. The refugees are extremely thankful for the hospitality (and architectural skills) of the dark elves. You are seen as heroes to the new arrivals.</p>
    <p><b>Greg - Glyphs: </b>Coming up with an alchemy-only glyph of warding is kind of a no-go. It’s too innately tied to divine magic. However, that actually proves to Greg’s advantage. By alchemically modifying the blood and setting it up to act as a focus for the ward, he is able to come up with an ever so slightly modified version of the glyph spell that uses the blood as an activator. Also, because he is godsdamned brilliant, Greg figures out a way to record the exact magical frequencies needed to “code” the glyph to a particular type of blood. Once a code is discovered, that glyph can be prepared attuned to that blood type any number of times.</p>
    <p>If a Glyph of Warding is prepared attuned to a blood type, it can be set to trigger only on that specific individual, someone of that creature’s specific race and subtype, or even to close family ties if the caster is clever. This means you can now create Glyphs attuned to either Titus Skoda or to wolf elves in general. Or I guess his family, if you want to be a dick.</p>
    <p>An attuned Glyph is much harder to evade than a regular one. Not only can they immediately bypass both magical and nonmagical disguises, it also can make a caster level check using the caster’s level +4 to get through effects such as Mislead and Nondetection. Polymorph spells, however, will still bypass it as it changes the target’s blood. That may not work on Lycanthropes, though, since their blood appears to be somehow tied to their condition (as he knows from the  fact that an alchemical blood test for the affliction exists.)</p>
    <p><b>Truth Pen: </b>This is gonna be a challenging one. The most brute force way (pen with constant zone of truth activated on it) would be difficult and expensive to craft. There is also a problem: Most magic items immediately communicate their purpose to the user when applied. This would be very difficult. Greg briefly toys with the idea of creating a cursed item like a ring of truth which would work no matter what the holder wanted, but oh man there’s so many ways that could end up going horribly. It’s also even more expensive.</p>
    <p>After some thinking, Greg considers the idea that he may be thinking of this the wrong way. Even if zone of truth worked, the writer would know they were writing down something different than they wanted to and probably just stop writing before putting down anything important. Unless you went with the aforementioned curse. I mean, it’d probably work. The ethics and safety are just… dicey.</p>
    <p>What Greg might really want is a piece of parchment enchanted with discern lies. This could be stealthily activated before giving to a target. The target could write whatever they want without knowing it was active, and then after the fact the parchment could be examined. It would make it quite easy to tell if the target had knowingly written a lie, but as with Zone of Truth, it’s always possible for a target to notice or resist the magic, or be warded against such detection magic. At any rate, since it’s essentially a single use magical item that only needs to work a few minutes, these would be relatively easy to make. You wouldn’t be able to replace every single piece of paper in the Hilt’Inn, but you could probably make enough to issue them to spyhunters for use on suspicious targets.</p>
    <?php
    include '../../settarget.php'; 
    settarget("Dark",8,null,11);
    include '../footer.php';
    echo getarrows("02_2_Dark.php","02_4_Dark.php");
    setlast("Year/02_3_Dark.php");?>
</body>
